### ISSUE TITLE
SpongeVanilla 348 1.8.9 ,Build 28 of GriefPrevention. Fire will not extinguish overtime.

### ISSUE THREAD

**Issue by GOKUSSL4** [MinecraftPortCentral/GriefPrevention#101]
Fire caused by thunder will not decay/extinguish overtime.

**Comment by bloodmc** [comment]
@GOKUSSL4 Does this cause fire to spread indefinitely or does the fire remain in the same area?

**Comment by bloodmc** [comment]
This no longer occurs with latest 1.10.2 builds.
