### ISSUE TITLE
Farewell and greeting messages

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#102]
![2tgmgw](https://cloud.githubusercontent.com/assets/9058200/16791385/69864360-488c-11e6-9886-8bda2a6fb6b2.png)

Players are able to set farewell and greeting messages which can impersonate players or server messages.

Perhaps there could be a config option to disable color codes, or to force a prefix on these messages.

I could just remove the permission to set these messages, but they are convenient for the players.

**Comment by SnowBlitzz** [comment]
Good idea.

**Comment by Eufranio** [comment]
Yep, would be nice a prefix like **Entering in <playername>'s claim > [farewell here] **, and have it configurable in the messages file.

**Comment by bloodmc** [comment]
@inklit This has been fixed in upcoming build. All greeting/farewell messages will have the standard GP logo text that shows up during debug.

**Comment by inklit** [comment]
@bloodmc Thanks :)
