### ISSUE TITLE
[1.8.9] Armors on armor stand not protected

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#103]
Armors on armor stand not protected.

Interact-entity-secondary is false on both admin and basic claims and yet players are still able to take another's display armor. This has been an issue before flags were implemented, a player without trust can steal armor as well.

**Comment by bloodmc** [comment]
This is not an issue with 1.10.2

**Comment by KasperFranz** [comment]
This seem to have been reintroduced - it is currently possible in 1.10.2 to take items away from the vanilla Minecraft armor stand
