### ISSUE TITLE
[1.10 branch] Server crash when resizing a claim with subdivisions in it.

### ISSUE THREAD

**Issue by cartman-2000** [MinecraftPortCentral/GriefPrevention#106]
The server will freeze when you try to resize a claim with a subdivision in it, and all the subdivisions will also be deleted from the claim on the next server start.

This is happening  on a Windows OS.
[23:02:02] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-11a6c07
    SpongeForge: 1.10.2-2011-5.0.0-BETA-1570
    Minecraft Forge: 12.18.1.2018

ash report.
https://www.dropbox.com/s/78gumywzhbegdkc/crash-2016-07-21_22.47.50-server.txt?dl=0

**Comment by bloodmc** [comment]
@cartman-2000 Thanks for report, I have fixed this in my local workspace by rewriting how resizing claims are performed. I'll be pushing a fix later today.
