### ISSUE TITLE
Server Crash with Pistons... EventListener is being called every 2ms for some reason

### ISSUE THREAD

**Issue by hsyyid** [MinecraftPortCentral/GriefPrevention#107]
http://pastebin.com/93DNK4f7

**Comment by hsyyid** [comment]
Possibly related to https://github.com/SpongePowered/SpongeCommon/commit/b32f56d8e105a84a3e3412195d932c31e1bf4183

**Comment by bloodmc** [comment]
This was a bug in Sponge, update to latest SpongeForge.
