### ISSUE TITLE
[1.10.2] enter-claim flag

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#111]
I did `/claimflag enter-claim minecraft:player false` and then `/cfd`

First it said i wasn't allowed to enter (like it should) but then after a few seconds i got teleported to 
x0 y0 z0. I panic for a bit then died in the void.

using:
griefprevention-1.10.2-1.1.0.40
spongeforge-1.10.2-2026-5.0.0-BETA-1604
PermissionsEx-Sponge build 136

**Comment by bloodmc** [comment]
@FiveEYZ This is a sponge bug.

**Comment by bloodmc** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/859
