### ISSUE TITLE
/ignore and /separate not working

### ISSUE THREAD

**Issue by TheHimayLegend** [MinecraftPortCentral/GriefPrevention#112]
Yea so^

**Comment by inklit** [comment]
I can confirm this happens with on 1.8.9 with PermissionsEx on the latest build of Sponge and GriefPrevention.
Players are still able to see the chat messages of players that they have ignored.

**Comment by bloodmc** [comment]
Seems to be working fine in latest 1.12.2 build. Make sure you have `chat-rules-enabled` set to true in GP's config.
