### ISSUE TITLE
1.10.2 Admin Claim Dupe Bug

### ISSUE THREAD

**Issue by LucidTheStick** [MinecraftPortCentral/GriefPrevention#115]
MC: 1.10.2
Sponge: spongeforge-1.10.2-2026-5.0.0-BETA-1601.jar
GP: griefprevention-1.10.2-1.1.0.43.jar
PEX: PermissionsEx-Sponge-build136.jar

Steps:
1) Create admin claim
2) Non admin player equips any item to shield slot
3) Player right clicks in protected area
4) Primary slot is replaced by a copy of the shield slot (ex 10 diamonds in shield will cause 10 diamonds to appear in main hand/primary slot and replace whatever item was there)
5) Rinse, wash, repeat forever

**Comment by FiveEYZ** [comment]
also works in a "player made claim"
tested in my own claim using /cfd

and this issue was also reported here https://github.com/SpongePowered/SpongeCommon/issues/853

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/50467db00931cc1cafca351bdc4abf73536d194f

Update to SpongeForge 1622+

**Comment by FiveEYZ** [comment]
works great, thanks! :D
