### ISSUE TITLE
[1.10.2] Storage Drawers aren't protected

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#118]
You can just shift-left click to take items from the containers.

**Comment by bloodmc** [comment]
@Eufranio Please retest with latest SpongeForge and GP builds and let me know if it is still an issue.

**Comment by FiveEYZ** [comment]
can confirm this is still the case using spongeforge-1.10.2-2026-5.0.0-BETA-1628

will also add that "breaking" the storage drawer will make all content of the drawer duplicate

**Comment by Eufranio** [comment]
In the latest build, any protections doesn't work :|

**Comment by FiveEYZ** [comment]
Made a little video of this issue:
https://www.youtube.com/watch?v=SJ0efCBwpRU
If there is anything else u want me to test with this just tell.

Using:
griefprevention-1.10.2-2.1.0.65
spongeforge-1.10.2-2052-5.0.0-BETA-1674
forge-1.10.2-12.18.1.2065-universal
PermissionsEx-Sponge b140
StorageDrawers-1.10.2-3.2.4

**Comment by FiveEYZ** [comment]
now you can even do this https://github.com/SpongePowered/SpongeForge/issues/822

same setup as above but updated:
griefprevention-1.10.2-2.1.0.67
spongeforge-1.10.2-2052-5.0.0-BETA-1675

while /cfd is active u can break the storage drawer and pickup all its content

**Comment by bloodmc** [comment]
The following PR fixes all the issues reported in this ticket
https://github.com/jaquadro/StorageDrawers/pull/350

Once pulled, it will work fine.

**Comment by FiveEYZ** [comment]
Players are still able to extract the items from a storage drawer all other issues are fixed

it tell me "you don't have claimOwner's permission to use that" but i still get the item from the drawer in hand.

can anyone else try to confirm this?

**Comment by Eufranio** [comment]
Are the items real? I've got only fake items...

**Comment by FiveEYZ** [comment]
think i know whats going on... the version of the mod i have is to old and dont contain the PR blood made,
sorry for bringing this up :S
