### ISSUE TITLE
Combine GP greetings, farewell with commands

### ISSUE THREAD

**Issue by nguyenquyhy** [MinecraftPortCentral/GriefPrevention#120]
It would be great if we can call some commands when player is entering and leaving the claim. I hope the command can use @p to target the player too. This is quite powerful so would also need some kind of admin-level permission.

**Comment by bloodmc** [comment]
Use the BorderClaimEvent to do this

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/event/BorderClaimEvent.java
