### ISSUE TITLE
Lightning breaks item frames

### ISSUE THREAD

**Issue by OblivionNW** [MinecraftPortCentral/GriefPrevention#122]
If lightning is struck on an item frame it is dropped along with its containing item, the lightning can be
- Natural
- Spawned by command
- The move 'Thunder' on a Pixelmon

**Comment by bloodmc** [comment]
@OblivionNW I cannot reproduce this with the essentials /lightning command.

**Comment by OblivionNW** [comment]
Hi! I was using Sponge recommended build for 1.8.9

**Comment by bloodmc** [comment]
@OblivionNW I've tested in both 1.8.9 and 1.10.2 using a clean setup and cannot reproduce issue. Make sure the players running these commands are not trusted.

**Comment by OblivionNW** [comment]
I'm specifically testing it with Pixelmon, the users are simply players on my server and they don't have permission in the spawn region.

**Comment by bloodmc** [comment]
This has been fixed in SF 1.10.2 1836+ builds.
