### ISSUE TITLE
Can't do /acb in console

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#126]
06.08 23:00:55 [Server] Server thread/INFO Error occurred while executing command: net.minecraft.server.dedicated.DedicatedServer cannot be cast to org.spongepowered.api.entity.living.player.Player

This is the error I get for doing /acb SnowBlitzz 1000 world189
world189 is the name of the world, if I don't put the world parameter, I get this:

06.08 23:08:47 [Server] Server thread/INFO Error! No valid world could be found!

I'm on SF 1653 and GP 56 [1.8.9] and my character was on the server when executing those commands

**Comment by bloodmc** [comment]
@SnowBlitzz Make sure you are running the LATEST build and post the entire server log if it happens again.

**Comment by FiveEYZ** [comment]
if im doing `/acb` in-game then i dont have to specify a world, but i do need to if i run it thru the console

also using UUID wont work with `/acb`
