### ISSUE TITLE
Getting spammed by no build permissions when doing nothing

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#127]
http://i.imgur.com/SNgEJ49.png

some people get spammed by these when far out of the centerpoint even if theyre doiing nothing.

**Comment by bloodmc** [comment]
@SnowBlitzz Is this still happening in latest build?

**Comment by SnowBlitzz** [comment]
This was on build 56 and still present in 59

**Comment by bloodmc** [comment]
@SnowBlitzz Try to reproduce this. Also state the exact SF build you are using too.
