### ISSUE TITLE
Flying Pokemon able to enter claim without permission

### ISSUE THREAD

**Issue by Karagra** [MinecraftPortCentral/GriefPrevention#128]
If you mount a pokemon outside a claim that is /cf enter-claim any false you can still fly and walk into the claim while on a pokemon. You will get the no permissions spam in chat but still able to fly/walk around. Might want to add a feature that if you get that command it will tp you to a location admins can set.

**Comment by bloodmc** [comment]
This was already fixed, update to latest SpongeForge and GP.
