### ISSUE TITLE
UseBug permission for claim

### ISSUE THREAD

**Issue by Flashback083** [MinecraftPortCentral/GriefPrevention#130]
Hi ! i think we found an issue very problematic, i try to explain but im not very good :c 

In world we have this ./cf flag : 
https://gyazo.com/c96993af813cf9c95cbc6c5e652195c6

So user cant build in the world, except if he place a chest 

But when he claim, he can build in his claim (logic) and in world claim ONLY IF he is IN their claim
Did you see what i mean ?
Thanks !

**Comment by bloodmc** [comment]
I don't understand the issue.

**Comment by Flashback083** [comment]
Mhm.. how explain...
The world have build protection, you can see here : 
https://gyazo.com/c96993af813cf9c95cbc6c5e652195c6
block-break and block-place set to false okay ?

So user can place only chest to claim an area.
But the issue its the user can build in their claim (its okay for this) but he can build in world if he standing in their claim (so he can place block in 2-3 block far that the claim) 

Do you prefer video ? 
thanks

**Comment by bloodmc** [comment]
You mean the player can stand at the edge in a claim they are trusted in and build in the wilderness?

**Comment by bloodmc** [comment]
@Flashback083 OK I reproduced the issue. I'll fix soon.

**Comment by bloodmc** [comment]
@Flashback083 Please test latest build and confirm if it is fixed =)

**Comment by Flashback083** [comment]
@bloodmc  i test and its work fine for 1.8.9, thanks !
