### ISSUE TITLE
Nothing is protected, except Pressure Plates :/

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#134]
I think it's a mod incompatibility, i have a server using latest SpongeForge, Forge and GriefPrevention builds, and nothing is protected inside a claim. Other person can break/interact/open everything, except Pressure Plates.

If you want, here is the modpack that i'm using: http://www.technicpack.net/modpack/magitech-server-beta-pack.883332

There is no errors in console, i tested using /cfd command and asking a player for check if he was able to break/access things, and he was. 

Please help me, GriefPrevention is a awesome plugin and i don't want delete it from my server :/

**Comment by bloodmc** [comment]
@Eufranio You setup PEX wrong then. Did you follow the instructions on forum? Paste your permissions.json

**Comment by Eufranio** [comment]
My permissions.json: http://hastebin.com/dikokaniza.dos

**Comment by bloodmc** [comment]
@Eufranio Why did you assign the member group "griefprevention.claim": 1 ? That basically grants access to EVERYTHING under the griefprevention.claim node including flags. Remove it and fix your permissions.

**Comment by Eufranio** [comment]
I did it to not give EACH permission to the players, but if this is the problem i can remove, thank you.

**Comment by Eufranio** [comment]
Wait... I am a admin and i have all permissions in my group, but when i use /cfg, what is supposed to happen? I'm still being able to open things and interact with the claim.

**Comment by bloodmc** [comment]
Don't assign any group "permissions-default: 1". Doing this grants them access to ALL claims.
