### ISSUE TITLE
Abandonclaim issue

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#137]
Sponge 1653 to 1666 (maybe not relevant to sponge ver)
GP build 56 to 59

When the player does either /abandonclaim or /abandonallclaims, he receives errors "Error occurred while executing command: null." and "You don't have any land claims." respectively.
When right-clicking the land (with a stick) that he supposedly unclaimed it still gives the message "That block has been claimed by <PlayerName>." But here is where the weird part comes.
When I right-click the gold blocks that indicate the so-called walls of the claim I get the message "No one has claimed this block." Going inside one block of the claim gives the same note, but on the next block it says the land is claimed. This only happens on two of the sides opposite to each other.

Explained in pictures:

When right-clicking the orange stained clay it shows me that the claim is still active, but doing the same to the yellow stained clay the message changes, even though you can see the outline of the claim.
When right-clicking the orange stained clay it shows me that the claim is still active, but doing the same to the yellow stained clay the message changes, even though you can see the outline of the claim.
http://i.imgur.com/ZlhXw5b.png

The corner of the claim is really inconsistent, sometimes shows that the claim is still active, other times tells that there is no claim.
http://i.imgur.com/AHKbjsA.png
http://i.imgur.com/1FKj1mb.png

The player has all claim blocks available. Warping away from home then back did not fix, nor did relogging.

**Comment by bloodmc** [comment]
This is an issue with builds under 59. You need to reproduce it with 59+. I do not support anything under it.

**Comment by bloodmc** [comment]
Unable to reproduce this issue with builds 59+. Do NOT use anything under this build.
