### ISSUE TITLE
[1.10.2] SkeletonTrap

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#138]
How do i make these http://minecraft.gamepedia.com/Horse#Skeleton_trap unable to spawn inside a claim 

the flag entity-spawn is set to false, but they still spawn

using:
spongeforge-1.10.2-2052-5.0.0-BETA-1675
forge-1.10.2-12.18.1.2065-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b140
griefprevention-1.10.2-2.1.0.67

**Comment by bloodmc** [comment]
@FiveEYZ This sounds like a bug with sponge 1.10.2 as GP just listens for the spawn event and cancels as required.

**Comment by bloodmc** [comment]
@FiveEYZ This should be fixed in SF 1793+
