### ISSUE TITLE
[1.10.2] claimBlock are not global

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#139]
as the title say, the amount of claimBlocks a player have seems to be dimension specific.

using:
spongeforge-1.10.2-2052-5.0.0-BETA-1675
forge-1.10.2-12.18.1.2065-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b140
griefprevention-1.10.2-2.1.0.67

**Comment by inklit** [comment]
and this is an issue why exactly? I believe that this is fully intentional behavior.

**Comment by FiveEYZ** [comment]
the claimblocks i accumulate in the overworld cant be used in other dimensions, is it really supposed to be like that?
