### ISSUE TITLE
[1.10.2] Could not pass SpawnEntityEvent$Impl

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#140]
This error just came up in my console: https://gist.github.com/FiveEYZ/c46b87160c0533661d76ddd75dd37263

Using:
spongeforge-1.10.2-2052-5.0.0-BETA-1675
forge-1.10.2-12.18.1.2065-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b140
griefprevention-1.10.2-2.1.0.67

**Comment by bloodmc** [comment]
This was a sponge bug and has been fixed in latest builds.
