### ISSUE TITLE
How can I enable players to use stone_pressure_plate and wooden_button?

### ISSUE THREAD

**Issue by 5igm** [MinecraftPortCentral/GriefPrevention#146]
I have tried permissions"griefprevention.claim.flag.interact-block-secondary.minecraft.wooden_button" and "griefprevention.claim.flag.collide-block.minecraft.stone_pressure_plate", but they cannot enable players to use wooden_button and stone_pressure_plate.
The commands I issued:
```
/pex group default permission griefprevention.claim.flag.collide-block.minecraft.stone_pressure_plate true
/pex group default permission griefprevention.claim.flag.interact-block-secondary.minecraft.wooden_button true
```
spongeforge-1.10.2-2052-5.0.0-BETA-1679
griefprevention-1.10.2-2.1.0.67

**Comment by bloodmc** [comment]
@5igm For basic access use, I would recommend using '/accesstrust public'. This should give players access to anything that does not contain inventory. If you require more advanced usage then let me know so I can assist you further.
