### ISSUE TITLE
You can build in wilderness with block-place false if inside a claim

### ISSUE THREAD

**Issue by Nentify** [MinecraftPortCentral/GriefPrevention#148]
![](http://i.nentify.me/afSKbvzl.png)

In the image above, the blue circle is an admin claim. The user has permission trust (manager).

This was also tested in an admin claim where the user doesn't have permission trust. They can simply stand inside any claim and build on the wilderness when the wilderness has block-place false.

The wilderness claim has 'block-break any false' and 'block-place any false'.

While inside the claim:
- You **can** build outside the claim (should not be able to)
- You cannot build inside the claim (should be able to I believe) - Need administrators permissions

While outside the claim:
- You cannot build inside (should be able to) - Need admin perms
- You cannot build outside the claim - Need wilderness admin perms

**Comment by bloodmc** [comment]
What build are you using?

**Comment by Nentify** [comment]
Was using build 62. Works perfectly in latest builds. Thanks!
