### ISSUE TITLE
Claims should inherit wilderness/parent flags

### ISSUE THREAD

**Issue by Nentify** [MinecraftPortCentral/GriefPrevention#151]
Haven't tested with a parent claim, but entity-spawn being false on the wilderness should also affect claims in that world too.

**Comment by bloodmc** [comment]
The wilderness claim has no relation to basic/admin claims in that world. GP will generate basic/admin defaults per world that claims will inherit from. If you want to set a flag that overrides all claims then stand in the type of claim such as a basic claim and enter  '/cf entity-spawn any false override'. Read the forum topic for more info.

**Comment by bloodmc** [comment]
Re-opening in case you have suggestions to make this easier on end-users.

**Comment by Nentify** [comment]
That sounds interesting. Override may be what I want, will look into this.

**Comment by Nentify** [comment]
When in wilderness claim, running `/cf entity-spawn any false override` gives the error `Claim type WILDERNESS does not support flag overrides. Context 'override' is invalid.`.

**Comment by Nentify** [comment]
`/cf entity-spawn any false override` seems to be enough for what I need, not sure how it could be improved though. Do sub-claims inherit their parent claim's flags?

**Comment by bloodmc** [comment]
@Nentify yes and you can even block inheritance with /inherit command.
