### ISSUE TITLE
admin claim created in the overworld is in the nether too

### ISSUE THREAD

**Issue by hunter688** [MinecraftPortCentral/GriefPrevention#153]
Maybe it is related to #144

**Comment by hunter688** [comment]
with latest build which show world using /claiminfo:
first screen - in the nether, second - overworld - claim is created in the overworld and may be only in the overworld.

![2016-08-31_08 49 13](https://cloud.githubusercontent.com/assets/1410134/18118938/3be6c8ba-6f58-11e6-8f88-1ddb184e7b71.png)
![2016-08-31_08 49 34](https://cloud.githubusercontent.com/assets/1410134/18118942/42b0182c-6f58-11e6-8e90-ea33ee00f3a2.png)

**Comment by bloodmc** [comment]
Looks like you have corrupted data or something is seriously broken. Test on a clean server.

**Comment by hunter688** [comment]
maybe it is related to #159 because the end dim, wyvern dim and thaumcraft dim without this problem

**Comment by hunter688** [comment]
claim show no world in the nether, i think its gp bug, not corruption of data

claim file content:
<pre>
# 12.1.7
# # If you need help with the configuration or have any questions related to GriefPrevention,
# # join us at the IRC or drop by our forums and leave a post.
# # IRC: #spongedev @ irc.esper.net ( http://webchat.esper.net/?channel=spongedev )
# # Forums: https://forums.spongepowered.org/
#

GriefPrevention {
    accessors=[]
    builders=[
        e2ac3ce9-73dc-4fc2-a4fe-620990fdfd76,
        "4c37bc3e-3fbe-4ec6-a5d2-0ac8e2de6bc2",
        "9ad47753-0055-4cac-8312-c365be92e6fb"
    ]
    claim-name=spawn
    claim-type=ADMIN
    coowners=[]
    cuboid=false
    date-created="2016-07-16T16:17:23.955Z"
    date-last-active="2016-08-31T18:39:17.378Z"
    greater-boundary-corner="342;0;346"
    lesser-boundary-corner="-347;0;-331"
    managers=[]
    owner-uuid=fb2fe292-eec8-4daa-b7b3-d1ff848111d0
    subdivisions {
        a517a753-0265-4f07-a443-86cfc6da3f56 {
            accessors=[]
            banned-item-ids=[]
            builders=[]
            claim-name=doly
            claim-type=SUBDIVISION
            coowners=[]
            cuboid=true
            date-created="2016-08-14T07:53:22.807Z"
            date-last-active="2016-08-31T18:37:40.479Z"
            greater-boundary-corner="-25;15;64"
            lesser-boundary-corner="-43;3;46"
            managers=[]
        }
    }
    world-uuid=cc30db2a-3ff5-423b-b878-1ef132f5c0ef
}

</pre>

**Comment by hunter688** [comment]
why GP create in the pex json these entries with world "" ?

<pre>
             {
                    "contexts": {
                        "world": "",
                        "gp_claim_defaults": "ADMIN"
                    },
                    "permissions": {
                        "griefprevention.claim.flag.exit-claim": 1,
                        "griefprevention.claim.flag.projectile-impact-block": -1,
                        "griefprevention.claim.flag.item-drop": 1,
                        "griefprevention.claim.flag.projectile-impact-entity": -1,
                        "griefprevention.claim.flag.explosion-surface": -1,
                        "griefprevention.claim.flag.fire-spread": -1,
                        "griefprevention.claim.flag.command-execute-pvp": 1,
                        "griefprevention.claim.flag.item-use": -1,
                        "griefprevention.claim.flag.item-pickup": 1,
                        "griefprevention.claim.flag.interact-entity-secondary": -1,
                        "griefprevention.claim.flag.command-execute": 1,
                        "griefprevention.claim.flag.interact-entity-primary": -1,
                        "griefprevention.claim.flag.pvp": -1,
                        "griefprevention.claim.flag.entity-teleport-to": 1,
                        "griefprevention.claim.flag.interact-inventory": -1,
                        "griefprevention.claim.flag.portal-use": 1,
                        "griefprevention.claim.flag.collide-block": -1,
                        "griefprevention.claim.flag.entity-damage": 1,
                        "griefprevention.claim.flag.block-place": -1,
                        "griefprevention.claim.flag.collide-entity": -1,
                        "griefprevention.claim.flag.explosion": -1,
                        "griefprevention.claim.flag.entity-spawn": 1,
                        "griefprevention.claim.flag.interact-block-secondary": -1,
                        "griefprevention.claim.flag.entity-teleport-from": 1,
                        "griefprevention.claim.flag.interact-block-primary": -1,
                        "griefprevention.claim.flag.liquid-flow": -1,
                        "griefprevention.claim.flag.enter-claim": 1,
                        "griefprevention.claim.flag.entity-riding": 1,
                        "griefprevention.claim.flag.block-break": -1
                    }
                },
                {
                    "contexts": {
                        "world": "",
                        "gp_claim_defaults": "BASIC"
                    },
                    "permissions": {
                        "griefprevention.claim.flag.exit-claim": 1,
                        "griefprevention.claim.flag.projectile-impact-block": -1,
                        "griefprevention.claim.flag.item-drop": 1,
                        "griefprevention.claim.flag.projectile-impact-entity": -1,
                        "griefprevention.claim.flag.explosion-surface": -1,
                        "griefprevention.claim.flag.fire-spread": -1,
                        "griefprevention.claim.flag.command-execute-pvp": 1,
                        "griefprevention.claim.flag.item-use": -1,

</pre>

**Comment by hunter688** [comment]
nether have no name:

<pre>
[21:34:14] [Server thread/INFO] [FML]: Loading dimension 1 (DIM1) (DedicatedServer)
[21:34:15] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world 1
[21:34:15] [Server thread/INFO] [FML]: Loading dimension -17 (MoCWyvernLair) (DedicatedServer)
[21:34:15] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -17
[21:34:15] [Server thread/INFO] [FML]: Loading dimension -42 (The Outer Lands) (DedicatedServer)
[21:34:16] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -42
[21:34:16] [Server thread/INFO]: Preparing start region for level 0 (world)
[21:34:17] [Server thread/INFO]: Preparing spawn area: 50%
[21:34:18] [Server thread/INFO]: Preparing start region for level -1 ()
[21:34:18] [Server thread/INFO]: Preparing start region for level 1 (DIM1)
[21:34:19] [Server thread/INFO]: Preparing start region for level -17 (MoCWyvernLair)
[21:34:19] [Server thread/INFO]: Preparing start region for level -42 (The Outer Lands)

</pre>


when do /world list:

[21:34:25] [Server thread/INFO] [io.github.hsyyid.essentialcmds]: [Server] executed command world list
[21:34:25] [pool-2-thread-1/INFO]: ------------------- Showing Worlds --------------------
[21:34:25] [pool-2-thread-1/INFO]: MoCWyvernLair
[21:34:25] [pool-2-thread-1/INFO]: DIM1
[21:34:25] [pool-2-thread-1/INFO]: 
[21:34:25] [pool-2-thread-1/INFO]: world
[21:34:25] [pool-2-thread-1/INFO]: ------------------------ « » -------------------------

**Comment by hunter688** [comment]
[21:34:18] [Server thread/INFO]: Preparing start region for level -1 ()
 is problem.

wiping nether solved this issue and related too.


Thanks for help!
