### ISSUE TITLE
[1.10.2] Storage Drawers visual dupe

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#157]
Steps to reproduce:

1. Place down a Drawer:
![drawer1](https://cloud.githubusercontent.com/assets/17598280/18072509/51e45796-6e35-11e6-922c-673907c4e3e3.png)
2. Put any stackable item in the drawer, and have at least 1 on your inventory:
![drawer2](https://cloud.githubusercontent.com/assets/17598280/18072523/6ef7adba-6e35-11e6-95b7-dc829ac74ce9.png)
3. Use /cfg or ask a friend to claim the land where you are.
![drawer3](https://cloud.githubusercontent.com/assets/17598280/18072540/8a4e1afe-6e35-11e6-88b2-6bf2a52a0780.png)
4. Simply right click in the drawer with the item in your hand, you can do it multiple times. The item count in Drawer will increase, but you won't lose your hand item. 

**This is not a real dupe, if you try to extract the items from the drawer, you will retrieve only one item, but we would like if you could remove thar visual glitch**. :smile:

**Comment by bloodmc** [comment]
There is nothing I can do about this on my end, the mod author would have to fix it on client-side.
Also the following PR fixes a bunch of issues with StorageDrawers and Sponge/GP

https://github.com/jaquadro/StorageDrawers/pull/350
