### ISSUE TITLE
flags in admin claims

### ISSUE THREAD

**Issue by Jay9519** [MinecraftPortCentral/GriefPrevention#158]
I would like all players to use items in an admin claimed spawn area but not break or place blocks, i've tried /accesstrust public but that doesn't work.
with /cf command there is a flag for interact-block-primary and secondary but no idea how to make that flag true only in that claimed area, please let me know the command to do this

**Comment by Jay9519** [comment]
nobody knows how to?

**Comment by bloodmc** [comment]
Enter the following while standing in the claim
```
/cf use-item any true
```
