### ISSUE TITLE
pixelmon pokeloots

### ISSUE THREAD

**Issue by aglarcz** [MinecraftPortCentral/GriefPrevention#160]
Using suggested commands: 
/accesstrust public
/cf interact-entity-secondary pixelmon:any true
/cf block-break pixelmon:Poke_Chest true
/cf block-break pixelmon:Ultra_Chest true
/cf block-break pixelmon:Master_Chest true

Players can still duplicate items - if they are given containtertrust, they can open pokeloot chest infinetely again and again.

**Comment by ryantheleach** [comment]
Is this on 1.8.9 or 1.10? I've been using our pokeloots inside a GP admin claim just fine?

I did have it set to once per player though.

**Comment by aglarcz** [comment]
Its on 1.8.9

**Comment by OblivionNW** [comment]
I can confirm this is an issue
