### ISSUE TITLE
Pistons still broken? 

### ISSUE THREAD

**Issue by IBGnova** [MinecraftPortCentral/GriefPrevention#163]
https://gyazo.com/2f0d38ffd1d06a20d89cbb16d10d46f2

Not sure what's causing it. This is anywhere (even the wilderness).

**Comment by bloodmc** [comment]
@IBGnova Please upload your world folder so I can test.

**Comment by IBGnova** [comment]
https://www.dropbox.com/s/va7w0l949egcj26/world-20160824-070540.zip?dl=0
