### ISSUE TITLE
Can not resize Sub-Division

### ISSUE THREAD

**Issue by lightningo7** [MinecraftPortCentral/GriefPrevention#165]
I have made a somewhat large claim (5625 blocks large) and inside the claim /subdivideclaims and /cuboid and made several somewhat small subdivides. (4x4x3 dimensions)

Upon trying to resize the subdivides it tells me "Can't resize here because it would overlap another nearby claim."

This includes trying to resize in any direction.
If it helps the claims are about 10-15 blocks above one another.
If you need any other information feel free to ask.

**Comment by bloodmc** [comment]
@lightningo7 Can you upload your GP folder and give me coords?

**Comment by lightningo7** [comment]
[GriefPreventionData.zip](https://github.com/MinecraftPortCentral/GriefPrevention/files/479451/GriefPreventionData.zip)
Accidentally closed this ticket, sorry about that.

The coords are -6649 147 -7913.

**Comment by KratosKnox** [comment]
@lightningo7 OK thanks, i'll check this soon.

**Comment by bloodmc** [comment]
@lightningo7 OK thanks, I'll check this soon.

**Comment by bloodmc** [comment]
@lightningo7 I do not see any subdivisions within this claim. It also seems to appear corrupted. Can you recreate it and see if it works?
