### ISSUE TITLE
howto create claim outside GP plugin?

### ISSUE THREAD

**Issue by hunter688** [MinecraftPortCentral/GriefPrevention#167]
Please help me howto create new claim from another plugin.

Trying this:

<pre>
        World world = Sponge.getServer().getWorld("world").orElse(null);
        ClaimWorldManager cwm = GriefPrevention.instance.dataStore.getClaimWorldManager(world.getProperties());
        Location<World> lesser = new Location<World>(world, 0, 255, 0);
        Location<World> greater = new Location<World>(world, 10, 0, 10);;
        Claim cl = new Claim(lesser, greater, UUID.randomUUID(), Claim.Type.BASIC, null);
        cwm.addWorldClaim(cl);
</pre>

but get NPE :(

**Comment by bloodmc** [comment]
@hunter688 I'll add an API soon for this.

**Comment by hunter688** [comment]
Ok, thanks a lot!

**Comment by hunter688** [comment]
Still no luck with:

http://pastebin.com/nwmwAgrG

**Comment by hunter688** [comment]
Got it:

<pre>
        CreateClaimResult result = pluginInstance.dataStore.createClaim(
                world,
                0,
                10,
                0,
                255,
                0,
                10,
                UUID.randomUUID(), null, Claim.Type.BASIC, false, player);
</pre>
