### ISSUE TITLE
Waterflow Lag

### ISSUE THREAD

**Issue by KillzyazMadness** [MinecraftPortCentral/GriefPrevention#168]
Getting a large amount of lag and drop in TPS due to water flow monitoring by GriefPrevention: https://timings.aikar.co/v2/?id=430e8c0ad0334c8eb22759b90a2666b5

Was told to submit a ticket by blood in the IRC. Thanks!

**Comment by bloodmc** [comment]
@KillzyazMadness Please zip up your world and plugins so I can fix the issue.

Thanks for the report!

**Comment by bloodmc** [comment]
Closing as there hasn't been a response in over a month.
