### ISSUE TITLE
Resizing subdivisions claims outside of top level claim border/Overlapping claims

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#169]
The title is very self explanatory; it is possible to resize subdivisions outside of the top level claim border.
This causes issues as you might expect.

Version: 1.8.9 2.0.0.70

**Comment by inklit** [comment]
Actually, I've seen several cases of normal claims overlapping so I think that this issue is not just subdivisions.

**Comment by bloodmc** [comment]
@inklit OK thanks, I'll look into this soon.

**Comment by inklit** [comment]
Just thought I'd mention when claims are overlapping, it takes like 4x attempts to delete the claim before the land is actually unclaimed again.
It sort of switches between the overlapping claims about twice.

Also, there's other odd behaviour in overlapped claims, such as some(?) events not really being cancelled properly (onBlock.pre for example is not cancelled at all when a claim overlaps - tested it with ComputerCraft)

**Comment by bloodmc** [comment]
@inklit Does this still occur with latest build?

**Comment by inklit** [comment]
I'll test later today.

**Comment by inklit** [comment]
I believe that this is fixed, if it occurs again I'll create a new issue.
