### ISSUE TITLE
Putting your shovel away does not remove the client-side marker

### ISSUE THREAD

**Issue by Wolfizen** [MinecraftPortCentral/GriefPrevention#17]
Sponge: 1.8.9-1808-4.1.0-BETA-1265
GP: 12.7.1
Mods: None

Steps to reproduce:

1. Right click a block with the shovel
2. Switch items so that you are no longer holding the shovel
3. The diamond block marker still is visible

This does cancel the selection process, because when you click again elsewhere it restarts. However, the old block stays until you click again with the shovel or the stick.

**Comment by ryantheleach** [comment]
Add a timeout maybe? or alert the user that the visualization has faded due to swapping tools?
