### ISSUE TITLE
Cactus keeps growing inside gp regions.

### ISSUE THREAD

**Issue by toxxicjtag** [MinecraftPortCentral/GriefPrevention#170]
Versions: http://puu.sh/ruPk9/b00cd8250e.png
and griefprevention-1.10.2-2.1.0.72.jar

Cactus grows fine next to blocks inside of grief prevention areas.
So cactus farms dont autobreak the blocks as they grow.
Works fine when not region-ed.

**Comment by bloodmc** [comment]
@toxxicjtag Test using latest SpongeForge and GP build 77

**Comment by toxxicjtag** [comment]
Thanks, resolved.
