### ISSUE TITLE
GriefPrevention not handling ChangeBlockEvent.Modify

### ISSUE THREAD

**Issue by RysingDragon** [MinecraftPortCentral/GriefPrevention#171]
I'm the developer of a plugin called hysis which spawns a double chest ([reference](https://github.com/RysingDragon/HISYS/blob/master/src/main/java/com/rysingdragon/hisys/HISYS.java#L70)) containing the player's inventory when a player dies. I still need to handle what happens if a chest fails to be placed but due to it being a double chest it's calling ChangeBlockEvent.Modify so with GriefPrevention no matter what it will always succeed in spawning. 
This is bad in multiple ways since as a user one could just die in someone's claim repeatedly as a form of grief, also the user who lost their items won't be able to retrieve their items since they can't break/open the chest. When you get time I hope you can work on implementing a handler for this event.

**Comment by bloodmc** [comment]
@RysingDragon Creating a double chest should always fire a place event first and if that is successful then the modify will occur. Simply fire a place event first and if GP cancels it, avoid placing your chest.

**Comment by RysingDragon** [comment]
That is what I've done since using the setblock method seemed to always return successful even in claims where I should not have permission to place blocks. Everything's working out fine now since I'm firing a fake place event before setting the block.
