### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Darktilldawn** [MinecraftPortCentral/GriefPrevention#172]
http://pastebin.com/LQTL16jh

GP: 76
SF: 1775
Minecraft: 1.10.2

**Comment by hunter688** [comment]
Looks like API update of Sponge.

**Comment by hunter688** [comment]
maybe similar problem:

http://pastebin.com/aHnQRVKa

**Comment by bloodmc** [comment]
Fixed in latest build
