### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by toxxicjtag** [MinecraftPortCentral/GriefPrevention#175]
Players can place a machine anvil, have someone not in their claim break it.
This will cause whatevers inside to fall on the ground, and be auto replaced cause they don't have access.

It must be container locked for this to work.

**Comment by lambstream** [comment]
There is also a bug where if you place any item in the blood altar or many other types of single block holding things, the item would remain in your inventory and be in the storage device.

**Comment by LemADEC** [comment]
Issue is reproduced in SSP with
   TConstruct-1.10.2-2.5.3
+ spongeforge-1.10.2-2092-5.0.0-BETA-1785
+ griefprevention-1.10.2-2.1.0.77
+ PermissionsEx-Sponge-142
When having a single iron block in hand, right clicking a casting basin will fill it without 'consuming' the item in hand.
When having multiple items in hand, it'll fill the basin and place a second iron block in the world, without duping.

Issue is also reproduce with LuckPermsSponge-2.11.15

**Comment by toxxicjtag** [comment]
I'm running pixelmon with SF- 1788 and forge 2092

**Comment by bloodmc** [comment]
@LemADEC Does this occur with SF 1794?

**Comment by toxxicjtag** [comment]
Currently not doing it to me with the updated version you pushed today.

**Comment by bloodmc** [comment]
OK thanks, closing as resolved then. Update to SF 1794+ for fix.

**Comment by LemADEC** [comment]
I'm still reproducing it in SSP with:
spongeforge-1.10.2-2098-5.0.0-BETA-1794
PermissionsEx-Sponge-142
griefprevention-1.10.2-2.1.0.78

**Comment by bloodmc** [comment]
@LemADEC It's a bug in Sponge with event being cancelled. Not a GP issue.

**Comment by bloodmc** [comment]
Issue was already reported here
https://github.com/SpongePowered/SpongeForge/issues/947
