### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by OblivionNW** [MinecraftPortCentral/GriefPrevention#179]
1) Simply find a claim (you don't have permission in)
2) Get the claim owner to put a block at the very edge
3) Put a sticky piston two blocks away
4) Activate it
5) The block remains in its position and duplicates in the pistons pull back position
Example GIF: https://gyazo.com/50be337b30f54e5ee476d98ddf510dc0

Tested using latest SpongeForge for 1.8.9 (1.8.9-1890-4.2.0-BETA-1762) and the latest GriefPrevention (1.8.9-2.0.0.81).

**Comment by OblivionNW** [comment]
maybe related to #160?

**Comment by bloodmc** [comment]
@OblivionNW Does this happen with latest GP 1.10.2 or 1.11 builds?

**Comment by aglarcz** [comment]
yup, just tested on newest GP 1.10.2 and its bugged

**Comment by bloodmc** [comment]
This was fixed in 1.10.2. It will not be fixed in 1.8.9. Update to latest 1.10.2 SF and GP.
