### ISSUE TITLE
Tinker's construct bypass

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#180]
Tinker's construct provide a mining explosive named EFLN (tconstruct:throwball:1) that is bypassing claim protection.
Reproduced in SMP with:
TConstruct-1.7.10-1.8.8
griefprevention-1.10.2-2.1.0.82
spongeforge-1.10.2-2098-5.0.0-BETA-1799
forge-1.10.2-12.18.1.2095
...

**Comment by bloodmc** [comment]
@LemADEC OK I'll look into this soon.

**Comment by bloodmc** [comment]
Create a ticket in SpongeForge if this is still an issue.
