### ISSUE TITLE
GP fail to generate wilderness claimData files

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#181]
deleted my old world folder and GP only recreates the folders but no files

and because of that the console is going crazy with https://gist.github.com/FiveEYZ/c2d7f3cc7cbcd159be769e6a23cc9454

when i created a new file manually for the overworld  the spam in console stopped

using a shovel works fine

using:
spongeforge-1.10.2-2098-5.0.0-BETA-1808
forge-1.10.2-12.18.2.2107-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b142
griefprevention-1.10.2-2.1.0.83

**Comment by bloodmc** [comment]
@FiveEYZ Unable to reproduce this on my end testing with latest SF/PEX/GP. I wiped my world folder and everything was generated correctly.
