### ISSUE TITLE
[1.10.2] Could not pass SpawnEntityEvent after death in nether

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#182]
Died in the nether, when i respawned in overworld, this happen:
http://pastebin.com/raw/unz7yVUU

using:
spongeforge-1.10.2-2098-5.0.0-BETA-1808
forge-1.10.2-12.18.2.2107-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b142
griefprevention-1.10.2-2.1.0.83

**Comment by bloodmc** [comment]
You are using a bugged version of SpongeForge. Update to latest.
