### ISSUE TITLE
[1.10.2] GP stops working if a dim gets unloaded

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#183]
Teleported to nether ran around for a bit then used /home and as soon the dimension gets unloaded by sponge GP stops working:
http://pastebin.com/raw/rVZwBUZ7

all kinds of "Could not pass event" starts spamming the console

It will start working again when the dim gets loaded again, but it wont find the player claims made in overworld until server is rebooted.

using:
spongeforge-1.10.2-2098-6.0.0-BETA-1818
forge-1.10.2-12.18.2.2107-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b142
griefprevention-1.10.2-2.1.0.83

**Comment by bloodmc** [comment]
I cannot reproduce this issue using latest SpongeForge and only PEX/GP. It almost sounds like your claim files are using the wrong world UUID. Update to latest SF and test with only GP/PEX. Also try testing a fresh world.
