### ISSUE TITLE
[1.10.2] GP fails to update existing claim files

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#184]
After i manually had to create "Wilderness" claims for all dims + dims added by mods, GP gave this warning:
`01:44 Found mismatch world UUID in claim file .\world\DIM-1\GriefPreventionData\ClaimData\29b45087-4a68-44f1-bb58-9a7e9d6e6fa3. Expected 9d553e1a-430c-44b1-8901-1b555a75a1ea, found 37eaa52f-109a-468a-8450-2889ee4fa5e2. Updating file with correct UUID...`

but the files never gets updated with the new UUID
so i manually updated those files with the UUID GP tried to set, 

using:
spongeforge-1.10.2-2098-6.0.0-BETA-1818
forge-1.10.2-12.18.2.2107-universal
PermissionsEx-Sponge-2.0-SNAPSHOT-b142
griefprevention-1.10.2-2.1.0.83

**Comment by bloodmc** [comment]
@FiveEYZ Did you run a world save after? Because it will not save right away.
