### ISSUE TITLE
Mod PSI. Dupe.

### ISSUE THREAD

**Issue by Vauxite** [MinecraftPortCentral/GriefPrevention#189]
Hello

**Problem**
Protected blocks are duped when broken with a psi (break-spell). If the block is a container, items inside are duped as well.

**How to reproduce:**
1. Protect an area with griefprevention. 
2. Have another player with psi break spell.
3. Break a block inside the claim.

**Modsource:**
https://github.com/Vazkii/Psi/blob/0b3ca4fa4d5bf293ec3b0486f83858c7320e5732/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java

**Versions:**
-     FTB Presents Hermitpack 1.0.1 (Release)
-     Minecraft: 1.10.2
-     SpongeAPI: 6.0.0-SNAPSHOT-cebc736
-     SpongeForge: 1.10.2-2107-6.0.0-BETA-0
-     Minecraft Forge: 12.18.2.2107
-     Griefprevention-1.10.2-2.1.0.83

Thank you for looking into this issue.

**Comment by bloodmc** [comment]
@Vauxite Retest using SF 1836

**Comment by Vauxite** [comment]
Sorry, still a thing with the following versions:
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-cebc736
    SpongeForge: 1.10.2-2107-6.0.0-BETA-1836
    Minecraft Forge: 12.18.2.210

**Comment by bloodmc** [comment]
@Vauxite Provide a player dat file as I have no idea how to use this mod to create a spell.

**Comment by Vauxite** [comment]
Sorry for the delay. Here is a playerfile, with a casting assistant device.
https://dl.dropboxusercontent.com/u/13951379/890589be-2581-4195-b0c0-b37cb42e5dc2.dat

**Comment by bloodmc** [comment]
@Vauxite I cannot reproduce this with latest SF and GP. Retest with GP 91 and SF 1847

**Comment by leelawd** [comment]
I am still getting this same issue on all the updated versions.

Currently running:
Fresh server with these mods / versions

Psi - 1.0.41
AutoRegLib - 1.0.2 - required by psi
SpongeForge - 1.10.2-2107-6.0.0-BETA-1860
Forge - 12.18.2.2107
GriefPrevention - 1.10.2-2.1.0.109
PermissionsManager - 2.5.0 (Has the GP Support, Everything else works)
Also tried with another permissions system, just in case.
LuckPerms - 2.13.43
