### ISSUE TITLE
Startup/shutdown Error

### ISSUE THREAD

**Issue by Deathwhitch** [MinecraftPortCentral/GriefPrevention#192]
Get this weird error on start up and shut down. Think it has to do with saving. Any flags added do not persist on a server restart. 

Sponge Forge 1820
Minecraft 1.10.2
Pixelmon 5.0 Beta 10
Pex 145 (newest)

http://pastebin.com/zLJB5Sbs

**Comment by bloodmc** [comment]
@Deathwhitch Does this happen with latest SF and GP?

**Comment by Deathwhitch** [comment]
Hadn't thought of that, deleting that wont mess with anything else though will it?

**Comment by bloodmc** [comment]
This is no longer an issue in latest builds.
