### ISSUE TITLE
Handle Mana Bursts

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#194]
i Botania is a magic minecraft mod, and it adds a lot of game mechanics and stuff. It's main system is **mana**, and players are able to create Mana Bursts to grief other player's claims. Players can create Mana Bursts using Mana Blasters (this is like a gun, that fires the burst with the characteristics of the lens that the blaster is using). Screenshot:

 ![cda5481a1295428cb090c5a9b9b746d3](http://image.prntscr.com/image/d7767891c19d4a2990ca53eff69c563c.png)

You can add lenses to the Mana Blaster, that does a lot of stuff. There are lenses that break blocks, turn the blocks into falling blocks, push blocks, give damage, fire stuff, etc. By example, if you attach a bore lens in it, it will break blocks, even inside a claim:

 ![cda5481a1295428cb090c5a9b9b746d3](http://image.prntscr.com/image/508ebc58725c4215834c6b63d721317d.png)
 ![cda5481a1295428cb090c5a9b9b746d3](http://image.prntscr.com/image/34d9057968b24922b2daf0c4ef82d10e.png)

There is also a Mana Lens: Resistance, that allows the burst travel for about 250 blocks, then we can't block it near a claim. Also, Mana Bursts are fired by Mana Spreaders too (the main part of Botania), then if we block the entity inside the claim the players won't be able to use Botania in their claims. I would say to use ASM to determinate who is the owner of the burst (it gets the UUID of the shooter if it's a Mana Blaster, or null if it's a spreader) and check if the owner has permission in that claim when the Burst interact anything. But players can still create a claim near another, or even in the wilderness near another claim, and place a Mana Spreader with a Bore Lens, facing to the claim. It will grief.

Then, we need to find a way to allow only Mana Bursts coming from a spreader placed by the owner/trusted user of a claim interact with the land inside the claim, or if it is a mana blaster, check if the owner has permission...

https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntityManaBurst.java
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemManaGun.java
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/internal/IManaBurst.java

**Comment by bloodmc** [comment]
@Eufranio Can you test latest GP/SpongeForge? I wasn't able to grief with a Bore Mana Blaster. I still need to test the Mana Spreaders.

**Comment by Eufranio** [comment]
Both are fixed in the latest GP builds.

**Comment by Eufranio** [comment]
The protection of Mana Bursts is not complete. 

Using all other lenses, they works as expected, including in claims that you don't have permission. By example, I can kill mobs with Mana Lens: Damage inside a claim where I don't have permission, entity-damage is false, interact-item-primary/secondary is false, push/pull items with Mana Lens: Influence, and these lens can be used on Mana Spreaders (and also will work).
