### ISSUE TITLE
item-spawn bug

### ISSUE THREAD

**Issue by Vauxite** [MinecraftPortCentral/GriefPrevention#196]
Hello

**Problem**
- EnderIO machines are deleted when wrenched.
- RFtools machines are deleted when wrenched.
- Soulbound tinker tools are not placed inside the gravestone on death.

**How to reproduce**

Use Yeta wrench on a enderio machine in your claim with item-spawn set to false (default).

Use Smart Wrench on a RFTool machine in your claim with item-spawn set to false (default).
1. Soulbound a tinker construct tool with a netherstar
2. Die with a soulbound tinker construct tools and the tool is not placed inside the gravestone 

None of these problems/bugs are present in griefprevention-1.10.2-2.1.0.83.

**Versions**
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-cebc736
    SpongeForge: 1.10.2-2107-6.0.0-BETA-1850
    Minecraft Forge: 12.18.2.2107
    GP-version: griefprevention-1.10.2-2.1.0.95
    Modpack: FTB Prestent Hermitpack V1.2.1

**Comment by bloodmc** [comment]
@Vauxite Please confirm this has been fixed.

**Comment by Vauxite** [comment]
Wrenched machines are fixed. But soulbound tinkertools are lost upon death (not in player inventory or gravestone).

**Comment by bloodmc** [comment]
OK I'll take a look soon.

**Comment by bloodmc** [comment]
@Vauxite The soulbound bug is a SpongeForge issue which I am currently fixing. Please re-create this ticket on SpongeForge.
