### ISSUE TITLE
Psi Dupe still not fixed?

### ISSUE THREAD

**Issue by leelawd** [MinecraftPortCentral/GriefPrevention#198]
I am still getting this same issue as #189 

Currently running:
Fresh server with these mods / versions

Psi - 1.0.41
AutoRegLib - 1.0.2
SpongeForge - 1.10.2-2107-6.0.0-BETA-1860
Forge - 12.18.2.2107
GriefPrevention - 1.10.2-2.1.0.109
PermissionsManager - 2.5.0 (Has the GP Support, Everything else works)
Also tried with another permissions system, just in case.
LuckPerms - 2.13.43

I also have the Item-spawn flag set to false, this does not seem to prevent it either.

**Comment by bloodmc** [comment]
@leelawd Does it happen with SF 1866?

**Comment by leelawd** [comment]
Cannot reproduce this now with the latest 1867. Thank you.
