### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Darktilldawn** [MinecraftPortCentral/GriefPrevention#2]
- [ ]  /trapped teleports you to around 297k X

- [ ]  Piston's can be used anywhere in the world even when LimitPistonsToLandClaims: true

- [ ] Fire is unable to be placed in the entire world
Place a netherrack block and try catching it on fire
Fire should be protected inside of claims so other players can't put the fire out.

- [ ] Portals can still be created without trust(SOMETIMES)
Make a nether portal and claim around it, when a player whose not you try's to ignite the NetherPortal, it blocks the ignition on the top's of the blocks but not the sides or them.
No portal creaton should be doable by anyone but the claim owner or trust.

- [ ] 
[11:33:12] [pool-2-thread-2/FATAL] [Sponge]: stopTiming called async for org.spo
ngepowered.common.data.processor.data.entity.VehicleDataProcessor
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]: java.lang.Throwable
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at co.aikar.timings.TimingHandler.stopTiming(TimingHandl
er.java:114)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at org.spongepowered.common.data.util.DataProcessorDeleg
ate.from(DataProcessorDelegate.java:86)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at net.minecraft.entity.Entity.get(Entity.java:59)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at me.ryanhamshire.GriefPrevention.DeliverClaimBlocksTas
k.run(DeliverClaimBlocksTask.java:73)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at org.spongepowered.api.scheduler.Task$Builder.lambda$e
xecute$0(Task.java:138)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at org.spongepowered.common.scheduler.SchedulerBase.lamb
da$startTask$46(SchedulerBase.java:174)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.lang.Thread.run(Unknown Source)
(Not sure what this error is for but it's only when using ONLY the GP plugin and SpongeForge)

- [ ] When these are true in the configuration, Does not block access
        LockFenceGates=true
        LockTrapDoors=true
        LockWoodenDoors=true
            
- [ ] Animals can be spawned by other players inside your claim area.

- [ ] No way to enable allow for seige mode, the command says seige mode is not allowed.

- [ ] Spam filter does absolutely nothing when enabled in the config(Not sure you even really need this)

- [x] Turn PvP mode on for the server, mark these true in the configuration, and it should prevent PvP in the claim but it doesn't.
            ProtectPlayersInLandClaims {
            AdministrativeClaims=true
            AdministrativeSubdivisions=true
            PlayerOwnedClaims=true

- [x] No way to create admin claims when using /ac
Tried typing /ac and then placing a chest hoping it would admin claim the area, No go.

- [x] When right clicking a player inside their claim, it respond with you don't have permission to use that.

- [x] When using Essentialcmds5.9 and GP, when your inside someone else claim you CAN do /sethome
in the Configuration it's coded as CommandsRequiringAccessTrust="/sethome" So they wouldn't be able to do so. but they can still set home.

- [x] When you have a Claim Limit of let's say 100, and your chest defaults to claim an area of 15 we'll say.
It will allow the player to have a negative amount and still create the claim. So claim limit's might not be blocked.

- [x] Player can only claim ONE claim area.
When changing the config of MaximumNumberOfClaimsPerPlayer=2 it will still only allow you to create one claim, even when using the chest to auto claim.

- [x] Adding a block to config RequiresContainerTrust for a chest ID 54 doesn't protect (Same for any

**Comment by gabizou** [comment]
Don't make us download a text file to see the issue.

**Comment by Darktilldawn** [comment]
Oh my bad hold on

**Comment by Darktilldawn** [comment]
What is wrong, error log
How to reproduce this event
What the event should really be doing

- Need to add /unstuck command
- Get stuck in someones claim, and it would send a message saying use /unstuck to get out of the claim

- Adding a block to config RequiresContainerTrust for a chest ID 54 doesn't protect (Same for any block ID added to the mod string for Container/Exposive/Access trust)
- Change the configuration for BlockIdsRequiringContainerTrust
- key "- 427" may not be followed by token:'BlockIdsRequiringContainerTrust' <if you intended 'BlockIdsRequiringContainerTrust' to be part of a key or string value, try enclosing the key or value in DoubleQuotes

- Piston's can be used anywhere in the world even when LimitPistonsToLandClaims: true

- Fire is unable to be placed in the entire world
- Place a netherrack block and try catching it on fire
- Fire should be protected inside of claims so other players can't put the fire out.

- Portals can't still be created without permissions(SOMETIMES)
- Make a nether portal and claim around it, when a player whose not you try's to ignite the NetherPortal, it blocks the ignition on the top's of the blocks but not the sides or them.
- No portal creaton should be doable by anyone but the claim owner or trust.

- [11:33:12] [pool-2-thread-2/FATAL] [Sponge]: stopTiming called async for org.spo
ngepowered.common.data.processor.data.entity.VehicleDataProcessor
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]: java.lang.Throwable
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at co.aikar.timings.TimingHandler.stopTiming(TimingHandl
er.java:114)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at org.spongepowered.common.data.util.DataProcessorDeleg
ate.from(DataProcessorDelegate.java:86)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at net.minecraft.entity.Entity.get(Entity.java:59)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at me.ryanhamshire.GriefPrevention.DeliverClaimBlocksTas
k.run(DeliverClaimBlocksTask.java:73)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at org.spongepowered.api.scheduler.Task$Builder.lambda$e
xecute$0(Task.java:138)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at org.spongepowered.common.scheduler.SchedulerBase.lamb
da$startTask$46(SchedulerBase.java:174)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[11:33:12] [pool-2-thread-2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStr
eam:println:-1]:        at java.lang.Thread.run(Unknown Source)
- Not sure what this error is for but it's only when using ONLY the GP plugin and SpongeForge

- When these are true in the configuration, Does not block access
-       LockFenceGates=true
        LockTrapDoors=true
        LockWoodenDoors=true

- PvP is not prevented inside of claims.
- Turn PvP mode on for the server, mark these true in the configuration, and it should prevent PvP in the claim but it doesn't.
            ProtectPlayersInLandClaims {
            AdministrativeClaims=true
            AdministrativeSubdivisions=true
            PlayerOwnedClaims=true
            
- Animals can be spawned by other players inside your claim area.

- No way to create admin claims when using /ac
- Tried typing /ac and then placing a chest hoping it would admin claim the area, No go.

- No way to enable allow for seige mode, the command says seige mode is not allowed.

- Spam filter does absolutely nothing when enabled in the config(Not sure you even really need this)

- When right clicking a player inside their claim, it respond with you don't have permission to use that.

- When using Essentialcmds5.9 and GP, when your inside someone else claim you CAN do /sethome
- in the Configuration it's coded as CommandsRequiringAccessTrust="/sethome" So they wouldn't be able to do so.

- When you have a Claim Limit of let's say 100, and your chest defaults to claim an area of 15 we'll say.
- It will allow the player to have a negative amount and still create the claim. So claim limit's might not be blocked.

- Player can only claim ONE claim area.
- When changing the config of MaximumNumberOfClaimsPerPlayer=2 it will still only allow you to create one claim, even when using the chest to auto claim.

**Comment by bloodmc** [comment]
Please change each issue to use check boxes so we know which ones are fixed.

**Comment by Darktilldawn** [comment]
Does that look better? Sorry for the earlier messy looking issues

**Comment by ryantheleach** [comment]
- [ ] Not quite, you need to use 

```- [ ] ```

**Comment by bloodmc** [comment]
Closing as this ticket is now outdated due to many changes.
