### ISSUE TITLE
Various Thaumcraft wand foci bypasses protection

### ISSUE THREAD

**Issue by Wolfizen** [MinecraftPortCentral/GriefPrevention#20]
Sponge: 1.8.9-1808-4.1.0-BETA-1265
GP: 12.7.1
Mods: Thaumcraft 5.2.4

- [x] Equal Trade

1. Equip a wand with the Equal Trade focus
2. Start the conversion process outside someone else's claim
3. As the blocks spread out, blocks inside the claim will still be replaced

It is blocked correctly if the initial click is done inside the claim

- [ ] Nine Hells

1. Equip a wand with the Nine Hells focus
2. Click on a protected entity
3. A deny message appears, but the fire bats still attack and kill the entity

- [X] Pech's Curse

1. Equip a wand with the Pech's Curse focus
2. Click on a protected entity
3. The entity still receives the potion effects

**Comment by bloodmc** [comment]
@Wolfizen  Please retest with latest build as there were a few permission bugs that were fixed.

**Comment by Wolfizen** [comment]
The bugs involving Equal Trade and Pech's Curse have been fixed. However, the issue with Nine Hells still remains. There is now an exception thrown when the bats explode on the targeted entity: http://pastebin.com/pzDaMXn0

**Comment by bloodmc** [comment]
Fixed in SpongeCommon commit
https://github.com/SpongePowered/SpongeCommon/commit/8eca553ee8592c67a390d351dbf90306c87b92dc
