### ISSUE TITLE
[Request] Option-based Configs

### ISSUE THREAD

**Issue by Mohron** [MinecraftPortCentral/GriefPrevention#200]
I would like to have some of the config-options currently set via the config file switched over to permission-options for greater customization. I propose the following configs be switched over to options:

- initial-claim-blocks - Allow you to change a players base claim block amount by option
- max-accrued-blocks - Allow you to increase a players max claim blocks by option
- player-all-claim-expiration-days - Allow you to configure the expiry time of a player's claim by option

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/7548a7796ef9f8d543a4b5d7782648f3cb8a83c4
