### ISSUE TITLE
griefprevention-1.10.2-2.1.0.118

### ISSUE THREAD

**Issue by KumaGetsu** [MinecraftPortCentral/GriefPrevention#201]
Type /cp shows this error in-game (did not give error in console).
http://puu.sh/s6bD0/1b1c736736.png

**Comment by KumaGetsu** [comment]
Here is a console message about the error.

**Comment by bloodmc** [comment]
Fixed in commit
https://github.com/MinecraftPortCentral/GriefPrevention/commit/d985a08a7068cf7764f8897f7a3f3486f1e7b28c
