### ISSUE TITLE
/cp issue

### ISSUE THREAD

**Issue by KumaGetsu** [MinecraftPortCentral/GriefPrevention#202]
griefprevention-1.10.2-2.1.0.118

Used 'cp nucleus.home.base false' while inside of a subdivided admin claim to prevent players from using a command. The player is still able to use the command (/sethome).

**Comment by bloodmc** [comment]
@KumaGetsu Are you using PEX or LP? Because there is a bug in LP with context calculators causing /cp commands not to work. I already reported it to dev. However, PEX should work fine. If not, let me know.
