### ISSUE TITLE
Griefprevention will not use MySQL datastore

### ISSUE THREAD

**Issue by dvhaldane** [MinecraftPortCentral/GriefPrevention#205]
**Version:** griefprevention-1.10.2-2.1.0.126.jar
**Sponge Version:** 

[18:24:42] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
    SpongeForge: 1.10.2-2107-6.0.0-BETA-1873
    Minecraft Forge: 12.18.2.2120

**Config settings:**

database {
        # password
        password="griefprevention"
        # url
        url="jdbc:mysql://localhost:3306/gpdatahrm"
        # username
        username=griefprevention

**MySQL Investigation:**

mysql> use gpdatahrm;
Database changed
mysql> show tables;
Empty set (0.00 sec)

**LogFile Investigation:**

[root@192 logs]# grep "ERROR:" *
[root@192 logs]#

**Description:** Griefprevention will not use the MySQL data store regardless of configuration setting.

**Comment by bloodmc** [comment]
dupe #125

**Comment by dvhaldane** [comment]
damn.. I thought I had looked for dupes.  thank you @bloodmc
