### ISSUE TITLE
onBlockPre discrepency between 1.8.9 and 1.10.2 with ComputerCraft

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#207]
## Explanation
ComputerCraft Turtles on 1.10.2 are unable to break **any** blocks in claims, even if the claim owner was the last person to interact with or place the Turtle. 
From my understanding, isBlockProtected returns true if onBlockPre is cancelled, which prevents the Turtle from breaking blocks.

## Expected Result
The expected result is that onBlockPre is **not** cancelled for Turtles that were interacted with by a trusted player.
On 1.8.9, this functionality works perfectly and is great. When a trusted player places or interacts with a Turtle,onBlockPre event is not cancelled.

## What actually happened
On 1.10.2, onBlockPre is cancelled for Turtles even though they shouldn't be cancelled.
There is one exception to this, and that is if you trust public or set the claim flags `block-break` and `block-place` to true for any.

**Comment by bloodmc** [comment]
GP 1.8.9 and 1.10.2 Block Pre logic is identical. You need to create a ticket for SpongeCommon as this has nothing to do with GP.
