### ISSUE TITLE
Extreme lag caused by onEntityCollide check

### ISSUE THREAD

**Issue by Lemmmy** [MinecraftPortCentral/GriefPrevention#208]
A bunch of cows in a pen on 1.10.2 are causing a huge amount of lag.

![](https://slack-imgs.com/?c=1&url=http%3A%2F%2Fi.imgur.com%2FKR8ELRe.png)

**Comment by Lemmmy** [comment]
if the information is relevant, there are a lot of baby cows too

**Comment by bloodmc** [comment]
@Lemmmy Need more information.... What Sponge build? What GP build? What PEX build? What mods/plugins ? etc.  Also provide a link to a timings report.

**Comment by Lemmmy** [comment]
SpongeForge 1876
GP 129
Latest PEX (doesnt specify which version number)

**Comment by bloodmc** [comment]
@Lemmmy switch from PEX to LuckPerms and retest

https://github.com/lucko/LuckPerms

Also, delete your ./config/sponge folder so it regenerates fresh. Post a timings report with LuckPerms installed.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/391c11f8ba961784988be25c0403c2c3a5fd956c
