### ISSUE TITLE
Firespread setting is ignored

### ISSUE THREAD

**Issue by Vauxite** [MinecraftPortCentral/GriefPrevention#210]
Hello

**Problem**
Fire spread even though it's configured to false by default  (in permissionsex in file mode). Setting the flag doesn't help either.

**How to reproduce**
1. /cf fire-spread any false
2. Use a flint and steel on nearby tree or burnable material
3. See the fire spreading

**Versions**
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
    SpongeForge: 1.10.2-2123-6.0.0-BETA-1878
    Minecraft Forge: 12.18.2.2123
    Griefprevention: griefprevention-1.10.2-2.1.1.131

Additional info
The reason I'm not running 131 at the moment is because GP 135, may be causing very high load in combination with SF 1878 and DW20. Will do further testing to determine actual cause.

**Comment by SnowBlitzz** [comment]
You might need to update to the latest version and test again, both SF and GP.

**Comment by bloodmc** [comment]
@Vauxite Switch to LuckPerms https://github.com/lucko/LuckPerms as PEX hasn't been active for quite awhile and still has a few bugs that need fixing. You can also just use the doFireTick rule. Let me know if it doesn't work with LP. LP has a migrator from PEX so it should be quite easy to move.

**Comment by Vauxite** [comment]
@bloodmc  Thank you for your suggestion, I've actually been looking to moving for quite some time. 
I've temporarily solved it by gamerule firespread false.
