### ISSUE TITLE
/ic giving access to admin claims

### ISSUE THREAD

**Issue by KumaGetsu** [MinecraftPortCentral/GriefPrevention#211]
You designed /ic to function only for admins, but I need this to work for lower ranked staff who should not have permission to change admin claims.

I'd like to request a perm (griefprevention.admin.command.admin-claims) check for players who use /ic before they can change blocks in an admin claim.

If you don't want the perm check by default then I'd like a config option to enable that perm check.

**Comment by SnowBlitzz** [comment]
Or just separate the /ic command to /ignoreclaimadmin = /ica and /ignoreclaimbasic = /icb

**Comment by bloodmc** [comment]
@KumaGetsu @SnowBlitzz This has been fixed for next build. Each claim type now checks a corresponding permission.
