### ISSUE TITLE
/claimlist not working with offline players

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#212]
As of griefprevention-1.10.2-2.1.1.135.jar + PermissionsEx-Sponge-145.jar + spongeforge-1.10.2-2123-6.0.0-BETA-1878.jar, the /claimlist command won't work when checking an offline player.

**Comment by bloodmc** [comment]
This command has been rewritten with new features and support for offline players. It will be included in next build.

Here is a sneak preview
http://i.imgur.com/CVcz6db.png

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/7548a7796ef9f8d543a4b5d7782648f3cb8a83c4
