### ISSUE TITLE
Missing in-game parameters help for entity-spawn flag

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#213]
As of griefprevention-1.10.2-2.1.1.135.jar, when trying to use the entity-spawn claim flag, I can't find a proper definition in-game of the possible parameters.
Typically, when I look for it, ones type: /claimflag entity-spawn x, or /claimflag help, or /gp help.
Here, none of those provide an hint at the solution.

I've tried using /claimflag entity-spawn any false, but I'm not sure it does what I need since I can still spawn mobs and they can mate in the area.
Also, I don't know if/how to prevent mobs spawning (allowing only passive ones), without manually adding all of them.

**Comment by bloodmc** [comment]
@LemADEC I'll be working on better docs soon. The command would be as follows

/cf entity-spawn minecraft:monster false

The spawn types are animal, monster, aquatic, ambient.
You would do this for each "mod" type you want to block. I'll add a way to prevent all monster mobs soon.

Also make sure you are using the latest dev build of LuckPerms as PEX currently has some issues and hasnt been updated in awhile.

https://github.com/lucko/LuckPerms

For more help , check GP discord here https://discord.gg/jy4FQDz

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/7548a7796ef9f8d543a4b5d7782648f3cb8a83c4
