### ISSUE TITLE
issue with /abandonallclaims File issues

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#225]
User is trying to use /abandonallclaims

http://pastebin.com/RMyvS3Ck

Errorspam lags the whole server.
GP 168
SF 1928

**Comment by i9hdkill** [comment]
That palyer also has a weird player file:
http://prntscr.com/del05u

Not sure if the file caused the issue or the issue caused this file.

**Comment by ghacproductions** [comment]
Just to make sure its not the command that is displaying wrong stuff:
http://puu.sh/sBXc0/177406a4ee.png

**Comment by dezil** [comment]
same issue here 

GP 185
SF 1967

https://mega.nz/#!plt3FCrC!r4ZDnGxYX_NdUGbJG5WkVMiy2_0J9dJvm48w6kgIcMw

GP config file attached

**Comment by i9hdkill** [comment]
Got some new info:
/abandonallclaims deletes the proper amount of claim blocks if return-ratio is not 1.
But as the players can do that infinitely without the actual claims are getting deleted(because of an error), the players gets hundreds/thousands of negative claimblocks.
