### ISSUE TITLE
Animals in Claims

### ISSUE THREAD

**Issue by bigbluu722** [MinecraftPortCentral/GriefPrevention#231]
Seems passive animals in claims are unable to be accessed by anyone inside claims other than the claim owner. Trusted users get an error mentioning "this does not belong to you". Is there any known work around on this? Or is it just a bug?

**Comment by Mohron** [comment]
IMO, animal access should fall under build trust like nearly every other access does. I could see where players might want an exception for tamed pets but otherwise most players do not intend to restrict access to their animal farms from people who they `/trust`.

**Comment by bloodmc** [comment]
This isn't an issue in latest GP builds. Update to latest.
