### ISSUE TITLE
Server Stalls when upgrading to 2.0.1.169

### ISSUE THREAD

**Issue by OblivionNW** [MinecraftPortCentral/GriefPrevention#233]
When I upgraded to GriefPrevention 2.0.1.169 (MC 1.8.9) my server started stalling, no other changes were made. Stall report: http://pastebin.com/EmZqMxE4

**Comment by bloodmc** [comment]
@OblivionNW Try build 187

**Comment by bloodmc** [comment]
I cannot reproduce this issue. If you continue to have issues with PEX, try migrating to LuckPerms.
