### ISSUE TITLE
default flags are not applied correctly if true is selected

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#237]
GP 185
admin-claim example:
interact-block-secondary is set to true as default. (purple value)
claim specific (orange) is undefined
No override.

I rightclick a door or pixelmon PC.
Acess is denied.

If I set the claim specific flag (orange) to true, it works.

Same goes for item-spawn. Same setup as above, except with another flag.

Mine a block, it doesn't drop.
Use item-spawn as a claimspecific flag: it works

Flag section of our pex file:
http://pastebin.com/j7FprmFD

The issue does NOT apply to the wilderness

**Comment by bloodmc** [comment]
This a bug in PEX not properly checking transient permissions. Migrate to LP or wait for PEX to fix.
