### ISSUE TITLE
chests are connecting when placed on claim borders and the claims are next to each other

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#241]
Just a minor flaw, but this can be used to steal items, if people put a single chest on their clameborder.
Player A places a chest on his border. Player B creates a claim directly next to Player A's claim and can now place a chest next to the chest from Player A.

Player B is no able to steal items from Player A.

**Comment by bloodmc** [comment]
Is this still an issue in latest builds?

**Comment by i9hdkill** [comment]
Still an issue with SF 2844 and GP 523
