### ISSUE TITLE
Enhancement: Creative plot world creation

### ISSUE THREAD

**Issue by hugeblank** [MinecraftPortCentral/GriefPrevention#246]
So plot^2 has this feature (as you probably already know) where you type in '/plot setup' and you can create a creative plot world. Thing is, Plotsquared is very ineffective, especially with modded items. Is there any way that I could do it with the existing versions of griefprevention, or would it be a possibility to port it over?

**Comment by inklit** [comment]
Ideally you should just ask the developers of P^2 to fix their event handling.

**Comment by bloodmc** [comment]
This should be possible by using GP's API.
