### ISSUE TITLE
[Request] Cross Server Last Active for claim expiration

### ISSUE THREAD

**Issue by Mohron** [MinecraftPortCentral/GriefPrevention#248]
For us running multiple servers, we are able to offer a lot of consistency for Grief Prevention thanks to its use of permissions and options that can be shared across servers. One important item missing from this data sharing is the `Last Active` info for a player. I personally don't want a player punished for switching to a different server for a while only to come back to a deleted claim.

I would like to be able to have my players claims expire only if they have not been active on any server we run. I'm not sure if you can support this without using external storage for player/claim data but any way to accomplish this feature would be greatly appreciated.

**Comment by inklit** [comment]
Good idea, maybe it should be best to store this in permissions which can be shared.

**Comment by Mohron** [comment]
I'll just implement this myself using the GP API
