### ISSUE TITLE
[1.10.2] GP is either too protective, or not protective at all

### ISSUE THREAD

**Issue by hugeblank** [MinecraftPortCentral/GriefPrevention#249]
Hi Blood!
**THE ISSUE**
So I've been spitting issues willy nilly trying to find a non-bugged anti-grief solution. I was hesitant to use GP because the permissions seemed a little intimidating (and rightfully so, I've been trying to fix an error I was 99% sure was on my part for the past 2 days), but effective as far as mods go (thank you BTC :P). I downloaded the plugin, and booted up the server. Everything started up smoothly, no conflicts or anything... and then I went and made a claim. 
Here are my results on that:

These 2 I am hesitant on classifying as issues, for one they make sense, and for another, I probably did something wrong.
-Wilderness requires '/trust all' for players to at the very least play
-Wilderness requires that command-execute be set to true in the 'CLAIM' section of cf in order to actually execute commands 

The rest are genuine issues that I cannot fix for the life of me

EITHER:
-When a claim is created, and you trust a player and set flags enter-claim and exit-claim to true, they still cannot enter the claim. They can however access blocks within reach of their player, so If I place a chest on the edge of a claim, a containertrusted player could access it, without entering the claim. If I placed it in the middle of the claim, and out of their reach, they would not be able to.
OR:
-When a claim is created... it doesn't matter. Players can romp on up, steal your loots, break your blocks, and place phallic objects in your claim (not very fun). 

**INFORMATION**
So, I was running:
-minecraft: 1.10.2
-forge: 12.18.2.2171
-spongeforge: 2000, API 5.1, for forge 2171
-PermissionManager: 2.5.3 
and the results also occurred using
-PEX: 2.0, build 146

_Unrelated_
How do I undo a containertrust? Is there a similar command to '/containertrust' like '/containeruntrust'?

**Comment by hugeblank** [comment]
I should note that the first issue could POSSIBLY occur with having the server booted up with griefprevention, and then the second is every restart after. 

I have not done enough testing, seeing as it's a pain in the rear, and I have no time :P. Will get on it later if it isn't figured out by someone else

**Comment by bloodmc** [comment]
@hugeblank GP works perfectly fine with PEX and LuckPerms. Remove PM and retest using latest LuckPerms build

https://ci.lucko.me/job/LuckPerms/

PM is probably not handling GP permissions properly. If it works fine with LP then report the issue to PM dev as GP is already running on countless amount of servers and protecting them fine.

**Comment by hugeblank** [comment]
Oh boy... another permissions plugin to unscramble. I'll edit the results in after testing.

**Comment by hugeblank** [comment]
muahaha! So I assume you found the issue? :P
