### ISSUE TITLE
Severe lag with liquid flowing in GP claims

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#251]
**Problem**
The server will grind to a halt when you make a bunch of liquid waterfalls and then remove the source blocks inside of a GP claim.

This appears to be a tracking issue in Sponge, but since it only happens inside of GP claims I decided to open it here instead of SpongeCommon.

**Reproduction Instructions**
I tested in the End, so you probably should too but it should happen anywhere. 
1: Teleport to the End
2: Create a 10x10 platform - add edges to prevent water from flowing off.
3: Fill the platform with water.
4: Destroy the bottom of the platform (you can leave your edges)
5: Wait for the water to flow until it hits the void.
6: Claim the platform.
7: Destroy all of the source blocks for the water, so it should start flowing downwards.

Here is an image representing what it should look like while it is lagging.
http://i.imgur.com/gSpX1vw.png
The water should be flowing downards.

**Profiling/Debug**
https://timings.aikar.co/v2/?id=1b72f38c5aa0449eb6aae0fbfb69c005&section=lag
http://switchcraft.pw/misc/WarmRoast.html

**Versions**
Tested on:
`griefprevention-1.10.2-2.2.0.200.jar`
`LuckPerms-Sponge-2.16.39.jar`
`spongeforge-1.10.2-2171-5.1.0-BETA-2000.jar`
`forge-1.10.2-12.18.3.2185-universal.jar`

**Comment by i9hdkill** [comment]
Created an admin claim
Placed 20x20x1 high water.
Protected the area so no water flows into the wilderness.
Removed sourcce blocks.
Timings result:
https://timings.aikar.co/v2/?id=4f3e3f88dcf44030a384c41551cef014&start=1482421159&end=1482421297&section=all

Screenshot:
http://imgur.com/a/FRR3A

SF: 2003
