### ISSUE TITLE
No permission to use /cfr in a claim

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#253]
I have all GP permissions by the node **griefprevention** set. When using **/cfr** in wilderness it will work, when using it standing in a claim it will give the No Permission message.

![screenshot_1](https://cloud.githubusercontent.com/assets/17598280/21507949/dde34b80-cc63-11e6-836d-c84db5b2e173.png)

**Comment by bloodmc** [comment]
This has been fixed for upcoming build.
