### ISSUE TITLE
Players can edit signs before the GUI gets closed by Sponge 

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#254]
With Quark mod installed, players can edit signs by just right-clicking in it and typing. When the interact event is cancelled, Sponge automatically closes the GUI, but the player is able to write on it before the GUI get closed, and it can cause trouble in servers using sell signs. 
Vazkii stated that the edit is only completed when the player has permission to write there, as stated here: https://github.com/Vazkii/Quark/issues/189

The events are working, except by the GUI opening in the client side

**Comment by inklit** [comment]
Are you sure that the modified content gets saved server-side?

**Comment by Eufranio** [comment]
Yes, they are and it will be fixed in the next GP build
