### ISSUE TITLE
Transfer ownership on MIA owner.

### ISSUE THREAD

**Issue by ryantheleach** [MinecraftPortCentral/GriefPrevention#26]
Claims don't expire unless claim is ownerless.

Ownership is transferred to 2nd oldest, active member when the owner disappears.

Optional: Notify members on login on expiration / owner change?

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Options

You can handle expirations with options now. The /transferclaim command has been rewritten to support both offline/online users.
