### ISSUE TITLE
Duping seeds with Horn of the Wild from Botania

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#260]
I did a gif of the problem:

Horn of the Wild: https://gyazo.com/b5fa9515e798efc839fa53fcea43926c
Horn of the Canopy: https://gyazo.com/772a23e676c82fe0a80ff8d1c09208fa

The Horn of the Wild is a item from Botania mod that breaks grass. While GP/Sponge can prevent the block from being broken, it does not prevent the grass from dropping the seed. Same happens with Horn of the Canopy, that breaks leaves.

**Comment by bloodmc** [comment]
This is a sponge bug, report to SpongeForge issue tracker.
