### ISSUE TITLE
Players are able to take animals from a claim with a Golden/Cursed Lasso from ExUtils2

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#262]
1. Create a claim, deny anything you want and spawn a sheep
2. Use /cfd and click in the mob with a golden/cursed lasso from Extra Utilities 2 mod
3. Wow, you have a mob in the lasso now! And you can't put it there anymore.

**Comment by bloodmc** [comment]
Fixed in upcoming build.
