### ISSUE TITLE
[1.10.2] Player are able to break AE2 stuff

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#266]
Using a Network Tool from AE2, players are able to shift right-click a ME Cable and break it even if they are not trusted in the claim.

A message will say they "You don't have <name> permission to build here" but the ME cable still breaks.

Steps:
1. player1 make a claim
2. player1 place down ME Glass Cable(or any other AE2 block) in his claim
3. player2 have a Network Tool and shift right-click the ME Glass Cable
4. player2 see message "You don't have player1's permission to build here"

Using Prototik's patch and then i just updated it so its on par with alpha9
https://github.com/FiveEYZ/Applied-Energistics-2/tree/Sponge

griefprevention-1.10.2-2.2.0.205
spongeforge-1.10.2-2171-5.1.0-BETA-2010

**Comment by DeathVirus** [comment]
This is why a lot of servers just ban that tool. Have you tried preventing right clicking with the Network tool with a flag? Will play around that sorta thing when I get home.

**Comment by KasperFranz** [comment]
It is a problem on AE2's side.

There was a PR for a fix some time ago https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1396

but since AE2 doesn't seem to want to play with others https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2483 I am unsure if there will be a fix, but maybe blood can work his magic and get them to see the light :)

**Comment by gabizou** [comment]
I believe there is a way for me to get this to work. I'm not 100% sure about how well it will work or how much hacking around it is going to be required, but I think it will have to be on the same level of changes that I applied for explosions. @bloodmc can probably confirm at this point.

**Comment by bloodmc** [comment]
Unable to reproduce using latest SF and GP.
