### ISSUE TITLE
Claims do not prevent damage from weapons in the off-hand slot.

### ISSUE THREAD

**Issue by Rob5Underscores** [MinecraftPortCentral/GriefPrevention#270]
Stick a diamond sword in your off-hand slot. Right click on another player, that's it.

I only list the above as a sanity check as I was indeed unaware of how the off-hand slot worked myself.

Sponge: 1.10.2-2202-5.1.0-BETA-2019
GP Build: 2015

Thanks

**Comment by bloodmc** [comment]
@Rob5Underscores Diamond swords cannot be used in offhand so I have no clue what you mean by this. Only weapons that have right-click functions can be used such as a bow but that would still fall into another flag. What permissions plugin are you using?

"The main hand is also the only hand that can hit or break (left-click), even if there are no items in the main hand. This means that the off-hand cannot left-click with an item. This makes most weapons and tools unusable in the off-hand, with the exception of ones that have a right-click function."

**Comment by Rob5Underscores** [comment]
Apologies - misdiagnosed the issue.
This is down to a, currently unknown, mod in Sky Factory 3 which allows off-hand items to attack.
Is it still possible to add protection from this? If so, my permissions plugin is PermissionsEX, if it helps.

**Comment by Rob5Underscores** [comment]
Issue resolved by mod author.

Cheers
