### ISSUE TITLE
Block place/break whitelist

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#272]
Would be great to have a place and break whitelist in the claims.
Currently graves don't spawn in claims which causes the loose of items.

**Comment by bloodmc** [comment]
Uh you have multiple options.

1. Use overrides
/cf block-place gravestone true override
2. Use /cfg
/cfg group block-place gravestone true

**Comment by Sir-Will** [comment]
Hm, that doesn't seem to work for me. It only works on the claim I'm standing in but not global.

**Comment by bloodmc** [comment]
@Sir-Will you need to use override at end to make it global for the all claims of the type you are standing in.

**Comment by Sir-Will** [comment]
Oh, that explains it. I did run it on admin claim only.
Works now, thanks.
