### ISSUE TITLE
Crash Griefprevention 197

### ISSUE THREAD

**Issue by Smackzter** [MinecraftPortCentral/GriefPrevention#273]
https://hastebin.com/icijujupew.sql

Using
SpongeForge 2171 BETA 2009.
Pixelmon 5.1.0
various sponge plugins

Remade this issue as I accidentally got the griefprevention version of our 1.11 server, and not the 1.10.2 server which the crash occured on.

**Comment by Smackzter** [comment]
Trying now with build 207 and Spongeforge 2202. Will see if the problem is fixed.

**Comment by bloodmc** [comment]
Cannot reproduce this issue using latest SF and GP. If you updated to GP 207, check your subdivision data as there was a bug that messed up boundaries.
