### ISSUE TITLE
You cannot switch between admin/basic + server idles forever if trying to do so

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#275]
GP 218

Create an admin claim.
Use /claiminfo and click on "admin"
Claim is now gone(wilderness)
if you hit wilderness in /claiminfo or scroll up the chat to click admin again, server hangs forever.
fml-log during this:
https://pastebin.com/aPUieiER

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/3dd09c0afa345020bfdefffe31825cab17101b9b
