### ISSUE TITLE
[API] Allow null/unspecified owner for Admin claim creation

### ISSUE THREAD

**Issue by Mohron** [MinecraftPortCentral/GriefPrevention#276]
Admin claims do not have an owner and should not require one to be provided at creation. As for claim creator, if no owner is provided, maybe the provided cause can be used instead (the plugin is the creator after all).

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/3dd09c0afa345020bfdefffe31825cab17101b9b
