### ISSUE TITLE
Overlapping Claim coordinates on claim creation failure

### ISSUE THREAD

**Issue by Slind14** [MinecraftPortCentral/GriefPrevention#279]
It would be great for administrators and players to be informed which claims are overlapping and where they are. This is incredible helpful when dealing with huge claims.

A common case is the protection of spawn including the area around it, to avoid the outside visuals from being destroyed.

A permission which gives the additional information about the overlapping claims might be a good approach so it can be disabled in the event of PvP servers.

**Comment by Mohron** [comment]
I would say that a bonus would be to have the error output  include a link to delete any overlapping claims when attempting to make an Admin claim. Just a QoL feature.

**Comment by Slind14** [comment]
Thank you.
