### ISSUE TITLE
/gp unlockdrops not working again

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#28]
http://puu.sh/omJvk/9f88bc78da.png
/gp unlockdrops is not working again. It says you've unlocked drops after you do the commands but the message that other players cant pick it up still appears(spams it)
When drops are not unlocked yet, it spams both receiver and dropped of the item a lot. The screenshot above is from the receiver.

**Comment by bloodmc** [comment]
I cannot reproduce this issue. Remove all your plugins and test again.

**Comment by bloodmc** [comment]
Closing as this is not a GP issue.
