### ISSUE TITLE
Can't prevent people from entering in wilderness

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#283]
I want that people don't enter in wilderness. In the past, I used `enter-claim` flag which worked perfectly, but now that there's no `enter-claim´ flag, I can't prevent people from entering wilderness. Tried:

**/cf entity-teleport-to any false**
**/cfg default entity-teleport-to any false**
**/cf entity-teleport-to minecraft:player false**

All while standing in wilderness. Nothing seems to work, and players are still able to enter wilderness. If I set **exit-claim** to false, players won't be able to exit anyway, like using portals, teleports, /home /warp /spawn...

**Comment by bloodmc** [comment]
No idea what you are talking about, enter-claim was never removed.

**Comment by Eufranio** [comment]
Here, it won't show in /cf...

**Comment by bloodmc** [comment]
@Eufranio OK it seems this is only an issue with newly created installs. I'll fix it soon.
