### ISSUE TITLE
If water breaks stuff like wheat, flowers, grass, nothing will drop.

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#285]
See above.

SF 2027
GP: 226
Forge: 2202
Tested in (default) wilderness and admin claim

**Comment by bloodmc** [comment]
@i9hdkill this sounds like a Sponge bug, not GP. Test WITHOUT GP.

**Comment by i9hdkill** [comment]
Yep, SpongeForge Bug. Just confirmed. Should I report it or do you take care of that?
