### ISSUE TITLE
GriefPrevention causes server startup times in excess of 10 minutes with over 1000 claims

### ISSUE THREAD

**Issue by Rob5Underscores** [MinecraftPortCentral/GriefPrevention#294]
http://pastebin.com/Q5kC6tQu

Log above shows the timestamps of the world loading. You may notice its only taking 5 minutes, this is because on my test server modded dimensions aren't being loaded.

griefprevention-1.10.2-2.3.0.238 and spongeforge-1.10.2-2202-5.1.0-BETA-2026

Might be worth noting that the duration of time to load each dimension's claims is almost the same despite hugely varying numbers of claims (1000+ in overworld vs 1 (wilderness) in DIM1).

Thanks

**Comment by bloodmc** [comment]
I tested with over 1300 claims and the server started up instantly. You are also using the wrong SF version, Update to latest.

**Comment by Rob5Underscores** [comment]
Apologies.

Caused by PermissionsEx..

**Comment by Rob5Underscores** [comment]
After some further testing, I have found that this issue happens when both GriefPrevention and PermissionsEX are being used. Does not happen when they are running alone.

@bloodmc can you repeat?

**Comment by Rob5Underscores** [comment]
@bloodmc not fixed.

**Comment by bloodmc** [comment]
Migrate to LuckPerms.

**Comment by bloodmc** [comment]
Let me know if LP works.

**Comment by Rob5Underscores** [comment]
LP does work but it is not an ideal solution for me to switch.

**Comment by bloodmc** [comment]
@zml2008 I'm checking perms async during startup yet PEX seems to slow startup which tells me it isn't running async on your end. No issues with LP. How do you handle getPermissionValue if received off main thread?

**Comment by zml2008** [comment]
PEX should be fine dealing with async permissions checks -- could you do a ctrl+\ stack dump or (preferably) run with a profiler attached to your server? That would help determine where all this time is being spent.

My current guess is if you're setting things persistently, PEX is trying to save in between each permissions set. The Sponge permissions PR adds a method that allows performing bulk permissions operations, which might help. Optimizations in PEX to minimize redundant saves might help as well -- I'll look into that too.

**Comment by bloodmc** [comment]
@zml2008 I run the following code for player data on startup
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/GPPlayerData.java#L222

@Rob5Underscores Install warmroast and post a screenshot of where it hangs.
https://github.com/sk89q/WarmRoast

**Comment by Rob5Underscores** [comment]
https://gyazo.com/c68a69083f4fc24e3ed47d6c138d4749
https://gyazo.com/832799f0235299b5577e55afeb11b75e

Hope I expanded it far enough.

**Comment by Rob5Underscores** [comment]
@zml2008 @bloodmc 

Apologies for bugging but is this something that I can expect a quick fix for or shall I migrate to luckperms?

**Comment by lucko** [comment]
Seems that PEX is running i/o after each `#setPermission` call. I had huuge issues with this in LP.

It was solved by adding buffers. 
https://github.com/lucko/LuckPerms/blob/master/sponge/src/main/java/me/lucko/luckperms/sponge/service/persisted/PersistedSubject.java#L95
https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/utils/BufferedRequest.java

Instead of saving directly after each call, the I/O is queued to take place 1000ms later. If another save request is sent within that 1000ms cooldown, the timer is reset.

It's not my greatest code, but it seems to work ok. Perhaps you could try something similar for PEX. @zml2008 :)

**Comment by zml2008** [comment]
PEX also has a solution with the dirty flag -- that prevents redundant saves from occurring. Additionally. all operations in PEX are async anyays, so that shouldn't be holding back the server start.

**Comment by zml2008** [comment]
Also @Rob5Underscores could you provide your permissions file and GP config -- that would allow us to reproduce this locally and gather information more quickly.

**Comment by bloodmc** [comment]
@Rob5Underscores Should be fixed in latest build as I now run this async. PEX still has to work on improving it on its end but at least this should be a bandaid fix for now.

**Comment by Rob5Underscores** [comment]
@bloodmc That has reduced the loading time by a great deal!

There is still maybe ~15-20 seconds loading each world but vastly improved!

Many thanks

**Comment by bloodmc** [comment]
@Rob5Underscores did you update PEX as well? zml made an improvement to memory backend. So test that too and report back results.

**Comment by Rob5Underscores** [comment]
Just updated the PEX.

The overworld claims took about 30 seconds (longer than old build) but the DIM1 and DIM-1 were about 5 seconds each. This was just from one start up, so perhaps a false reading

**Comment by bloodmc** [comment]
@Rob5Underscores Provide another profile screenshot as it loads overworld.

**Comment by bloodmc** [comment]
Woops, I forgot to set options async. Let me do that then you can test with new GP.

**Comment by bloodmc** [comment]
Test latest GP and see if that solves it.

**Comment by Rob5Underscores** [comment]
Quite sure this is entirely resolved.

Many thanks!
