### ISSUE TITLE
API Only Library

### ISSUE THREAD

**Issue by cossacksman** [MinecraftPortCentral/GriefPrevention#295]
Can we get a jar with just the interfaces included for the API so I can package our project with the API? I wouldn't want to just pull your API package into my project every time and it would make updating a lot easier.

**Comment by bloodmc** [comment]
Minecrell fixed this with commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/94cf8b80ad7ce854ad27495c08b58af7dd39ef48
