### ISSUE TITLE
Dupe bug with creeper exploding stuff

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#296]
**Steps to reproduce:**

Create a claim
Explosions flag is false
Item-Spawn flag is false
Use /cfd
Wait a naturally creeper spawn or use /spawnmob by console
Make the creeper explode you near where a chest is

The items of the chest will be dropped, but the chest won't be broken. Dupped items. This doesn't work for players as you said earlier for me (because of the item-spawn flag), but it works for creepers that don't have a player reference.

![a](http://image.prntscr.com/image/3b87847935b24f418349962851c2eaa6.png)

**Comment by bloodmc** [comment]
This is not a GP issue but *should* be fixed in latest SF via commit

https://github.com/SpongePowered/SpongeCommon/commit/cdeebeab8e270a17209bd1e6ef65bd14f5913954
