### ISSUE TITLE
Features & Requests

### ISSUE THREAD

**Issue by Darktilldawn** [MinecraftPortCentral/GriefPrevention#3]
These are coming from my player base 

- [ ] The whole trust rework system we talked about. Players having the individual permissions to allow what untrusted players had access to. Using only /trust and /untrust commands for trust levels and everything inside the claim is protected by default. (I still think we should keep the /permission trust to allow the owner of the claim to give another player "Owner" to trust others inside the claim.

- [ ] Private chest if we are doing the trust rework. A way for the claim owner to Protect chest's from Everyone but himself and of course admins. Meaning, the Owner of the claim can /trust someone but lock a chest in his claim from players even with /trust.

- [ ] With Bukkit's version, the Subdivided claims system would have a separate trust inside the subdivided claim, but not included in the main claim. But if you trusted them in one subdivided claim, it would trust them in all of the subdivided claims inside your main claimed area. Could you make it so each subdivided has it's own separate /trust to it? Will completely help the whole trust rework.

**Comment by jsnbrown1989** [comment]
For the second suggestion above, might I suggest incorporating something similar to lockette's system using signs?

**Comment by bloodmc** [comment]
Fixed in

https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
