### ISSUE TITLE
Fire spread

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#30]
Fire spread in the config is set to false (by default)

http://puu.sh/omYIx/5a9c5567b1.jpg fire still spreads. it there was initially just one fire above the wool. it spreads VERY slow, and the spreaded fire blocks(not the main fire) spreads faster than the main

Minecraft's /gamerule doFireTick false disallows fire spread yep, but the fire also does not disappear which I would like it to

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
