### ISSUE TITLE
Flame bow bypasses projectile-impact-entity flag

### ISSUE THREAD

**Issue by DeathVirus** [MinecraftPortCentral/GriefPrevention#300]
I'm trying to prevent players from killing the animals in the spawn zone, however with the flag /cf projectile-impact.entity minecraft:animal false, the arrow bounces off the animal but still does flame damage. 
Other versions of the flag (/cf projectile-impact-entity minecraft:animal minecraft:arrow false) also failed. 
entity-damage also could not prevent fire damage. 

Upon further investigation, using a flame bow on a player while PVP is disabled still sets them on fire.

Later discovered, preventing the usage of a bow (/cp interact-item-secondary minecraft:bow false) can also be bypassed by spam shooting (instantly releasing the arrow)

**Comment by DeathVirus** [comment]
Later discovered, preventing the usage of a bow (/cp interact-item-secondary minecraft:bow false) can also be bypassed by spam shooting (instantly releasing the arrow)

**Comment by bloodmc** [comment]
I cannot reproduce this issue with a fresh claim (default flags). Please test again and provide exact steps on reproducing with a fresh setup.
