### ISSUE TITLE
TNTs doesn't explode blocks but drops the items

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#302]
1. Create a claim and use /cfd
2. Go to outside of your claim and place a TNT near the border 
3. Fire it. The blocks won't be broken but will drop the items.

**Comment by inklit** [comment]
This happens with Plethora lasers too, as long as you set item-drop flag to true.

**Comment by Eufranio** [comment]
So this is the same as https://github.com/MinecraftPortCentral/GriefPrevention/issues/296?

**Comment by inklit** [comment]
Yes it is

**Comment by bloodmc** [comment]
This is not a GP issue but *should* be fixed in latest SF via commit

https://github.com/SpongePowered/SpongeCommon/commit/cdeebeab8e270a17209bd1e6ef65bd14f5913954
