### ISSUE TITLE
Builder from RFTools can break protected areas

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#305]
The RFTools mods has a builder block, that can have a quarry upgrade, and then will mine a defined area, just like a quarry. The problem is that this builder breaks protected areas, such as GP claims (where you don't have permission). I can't attach logs here because I turned on the cause-tracker logger and the log is now 180MB, but you can reproduce it yourself:

1. Create a claim
2. Place a Builder in the border and select an area that is inside the claim with the Quarry upgrade (see [this video](https://youtu.be/sFESShtPtaA?t=5m3s) explaining how to mark the area and make the builder work)
3. Fill with energy, place an chest and turn on a redstone signal. It will start mining the area. 

You can also turn on the cause-tracker (and you may be able to read but my god it's very big)

**Comment by Time6628** [comment]
RFTools uses the [Minecraft] fake player for the builder.

**Comment by Eufranio** [comment]
It still not respecting the owner rule and breaking where it shouldn't.
