### ISSUE TITLE
Psi break block spell dupping

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#307]
When we use a [Break Block spell](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java) from Psi in a protected area, the block won't break, but will still drop it's items. Like, we break a chest, the items will drop but the chest won't be broken, dupping them.

**Comment by bloodmc** [comment]
This is a sponge bug.
