### ISSUE TITLE
GriefPrevention Subdivision Changing Y-Axis

### ISSUE THREAD

**Issue by KhaozFrost** [MinecraftPortCentral/GriefPrevention#309]
http://pastebin.com/uvzKidwp
I guess this is how to reproduce? It happens constantly but randomly..
Masterclaim is non-cuboid. but subclaims are cuboid. inheritance is off.
Server restarts or x amount of time has passed, (possibly reloads) and it changes the y-axis of the claim.
I dont exactly KNOW when the claim changes. i just happen to report a bug where claimflags keep vanishing, get told to check inheritance and when i do the chat tells me it can only be used in subdivisions. (subdivision looks as if it deletes itself but it just changes to a lower y axis (generally that of the master claim)

when i goto the coords that the subclaim should be and i start typing /inherit it says there is nothing there, when i right click with a stick i get this http://prntscr.com/e1lyyc i've tried deleting the subclaim and it says there isnt one or to stand inside it but i goto the y coord and its not there...

**Comment by bloodmc** [comment]
I cannot reproduce this with latest builds.
