### ISSUE TITLE
Add walk flag or improve the enter-claim one

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#312]
I would like a method to COMPLETELY deny entry to a claim. Many mods does teleporting in some hacky ways that aren't blocked by GP right now, because it acts like a barrier instead a blocker. Would be nice if GP checks for walking over a claim instead only check when you're entering it, so if the person is already there, he would be teleported to the border of a claim, just like GriefPreventionPlus does.

**Comment by DeathVirus** [comment]
What about the teleport related flags? I know Blood was going to do something related to ./home teleporting you to a border, rather than a point inside the claim if you aren't trusted. Might be possible to use the same system here
