### ISSUE TITLE
[Bug] Item drops being deleted on inventory close

### ISSUE THREAD

**Issue by Varijon** [MinecraftPortCentral/GriefPrevention#318]
When a player attempts to drop an item that is held by the cursor, by closing the inventory, the item gets deleted instead. This also goes for Pixelmon boss loot that does not fit in their inventory (is supposed to drop on the floor), might be related.

This only happens in admin claims, not basic or wild.
Flags on said claim:
http://i.imgur.com/06gOOF8.png
http://i.imgur.com/nIKdy4t.png

Versions:
spongeforge-1.10.2-2221-5.1.0-BETA-2109
griefprevention-1.10.2-2.3.1.251
forge-1.10.2-12.18.3.2221

**Comment by bloodmc** [comment]
@Varijon All GP does is cancel events, dupes are caused by Sponge. Create the ticket here

https://github.com/SpongePowered/SpongeCommon/issues

Also make sure you are running LATEST SF, GP or your ticket will just be ignored.

**Comment by Varijon** [comment]
Apologies for the slightly outdated versions, I hadn't taken the time to reproduce the problem locally seeing as there were no related GP changelogs.
This ticket is about the item being destroyed, similar to what forge does when the ItemTossEvent is cancelled, no item drops, but they do lose it. This while they are allowed by the claim, as seen in the flags.

A quick gif demonstration, note how 2 of the 3 dropping methods work, the other deletes.
http://i.imgur.com/B8sdh8y.gifv

We'll update everything soon and I'll report back if the problem still occurs.

**Comment by bloodmc** [comment]
@Varijon This is still a Sponge issue, report it in SpongeCommon as I mentioned.
