### ISSUE TITLE
Players cannot get removed from claims if they don't exist in usercache.json

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#322]
GP 257
SF: 2169
https://pastebin.com/JbrpFNmu

As those entries in this file have an expiry date, this happens with every user that hasn't been online for 1 month or longer.

**Comment by bloodmc** [comment]
Fixed in Sponge

https://github.com/SpongePowered/SpongeCommon/commit/3d5763880cde33f9067f1458a7d2af67ea5eef29
