### ISSUE TITLE
enderio's Staff of Traveling

### ISSUE THREAD

**Issue by meza** [MinecraftPortCentral/GriefPrevention#324]
Apparently enderio's `enderio:itermStaffTravel` does not care about either `entity-teleport-from/to` nor the `interact-item-secondary` flags, thus making escaping jail extremely easy.

Is there a way to block said item inside claims? 

`/gpdebug` tells me it's not allowed, yet I can still use the item.

![screen shot 2017-02-19 at 14 19 45](https://cloud.githubusercontent.com/assets/211977/23103279/ce03cbaa-f6b0-11e6-91ea-9578195bbc06.png)

**Comment by bloodmc** [comment]
This shouldn't be an issue with latest GP builds. Open a new ticket if problem exists.
