### ISSUE TITLE
Entity flags - Creeper explosions

### ISSUE THREAD

**Issue by Erlebsyk** [MinecraftPortCentral/GriefPrevention#329]
Problems enabling creeper explosions/grief together with luckperms. Explosions trigger (damage players and mobs) but blocks are not destroyed. All permission checks through luckperms are reading true when triggering an explosion using the "/lp verbose true" (see image).

Server system: spongevanilla-1.10.2-5.1.0-BETA-373 (others 1.10.2 tested as well)
Plugins enabled: LuckPerms-Sponge-2.17.62, griefprevention-1.10.2-2.3.1.257

[Permission checks](https://gyazo.com/9b77fa3abd6c6f56219a359d0dee6c9d)

**Comment by bloodmc** [comment]
@Erlebsyk Please test SpongeForge and let me know if the problem occurs there. Also, was this tested in wilderness?

**Comment by Erlebsyk** [comment]
This was tested in wilderness. I will see when I have time to test on forge+SpongeForge

**Comment by gigafunk** [comment]
same here...tnt explosions or egg spawned creepers same behavior.
spongeforge    version 1.10  2424
 --both forge 2281 and 2316  do it with no change so we use 2316 for todays journey map update.  
GP   1.10.2-2.3.1.297    
LP    3.2.30
surface-explosions and explosions come up as true and verbose sees whichever one it check for as true


has done this through serveral versions but just no digging into it(bigger fish to fry and all that)

I thought i just wasnt doing something correctly but then I found this.  

Let me know what elese i can do to help/test    

[fml-server-latest.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/1117460/fml-server-latest.txt)

**Comment by gigafunk** [comment]
and yes in wilderness, and the two flags are both default true and specifically set for true with the /cf interface

**Comment by gigafunk** [comment]
For me, it was a sponge setting.  It was on e of these three, but they were all false,and when set true my explosions worked.
settings are under modules but not together in the actual setting file
 modules {
        block-capturing-control=false    
         tracking=false       <-----------------I think this is the one responsible.

and under 
 block-tracking {
enabled=false

All in all I think it was the tracking=false that was stopping explosions.
