### ISSUE TITLE
[1.10.2] GraveStones not spawning in claims

### ISSUE THREAD

**Issue by YOYOK9** [MinecraftPortCentral/GriefPrevention#331]
When a players dies on my server a grave stone is supposed to spawn containing all the players loot. However if a player dies within a claim a grave doesn't spawn and all the players items are voided. Not sure of a way to fix this? Note: If a player that owns the claim dies inside his/her own claim a grave doesn't spawn. Graves do spawn outside of the claims. 

Mod: 
Gravestone mod: 1.4.9

**Comment by Eufranio** [comment]
Stand in a claim, and use `/cf block-place gravestone:any true override`, `/lp sync` and `/gpreload`, and see if that fixes your issue.

**Comment by YOYOK9** [comment]
Yeah it seemed to work thank! Now to figure out about that blasted ender staff...

**Comment by Eufranio** [comment]
?
