### ISSUE TITLE
Wrong playerdata loaded when logging into second world

### ISSUE THREAD

**Issue by ghacproductions** [MinecraftPortCentral/GriefPrevention#333]
Quite critical bug to get unlimited claims:

My blocks after creating one claim:
http://i.imgur.com/d8m1WSx.png

Relogging in another world
http://i.imgur.com/aYg0Gov.png

I can now go back to the main world and use my remaining blocks there. When I'm relogging into the main world my remaining block count goes to negative as all my claims are subtracted from my total amount and I used more claims than I had.

After creating another claim and then relogging in the main world:
http://i.imgur.com/w9FqciQ.png

This is most likely the cause for the occurence of negative claimblocks for several GP users.

**Comment by bloodmc** [comment]
OK i'll have a proper fix when I get some time. Thanks for report.
