### ISSUE TITLE
[1.10.2] AE2 Planes 

### ISSUE THREAD

**Issue by YOYOK9** [MinecraftPortCentral/GriefPrevention#335]
How do you allow the annihilation Plane from AE2 Rv4 to break blocks within a claim? I tested it outside of a claim and it works just fine.

**Comment by Eufranio** [comment]
You can use debug to see yourself. Use `/lp verbose true` and try to make it place a block inside the claim.

**Comment by YOYOK9** [comment]
They place just fine. Does the debug save anywhere? The plane is meant to break break certain blocks.

**Comment by Eufranio** [comment]
Usually it's printed in the chat.

**Comment by YOYOK9** [comment]
ah found it. However this is what i am getting:
griefprevention.flag.block-break.minecraft.source.unknown.unknown.0

**Comment by YOYOK9** [comment]
Would this possibly be something to talk to the ae2 creators about? Or is it a GP thing?

**Comment by Eufranio** [comment]
Probably a Sponge thing, report it there. AE2 devs dont support AE2 unfortunately.

**Comment by bloodmc** [comment]
Reopen if latest build still has this issue.
