### ISSUE TITLE
Enter-claim and nether portals issue

### ISSUE THREAD

**Issue by Yorkforce** [MinecraftPortCentral/GriefPrevention#337]
If a player enters a portal from the nether and it links to another portal inside someone else's claim in the overworld which has the enter-claim false flag, they get bounced out into a weird void like place, can see a chunk of overworld but can also see blazes and other nether type objects, the player will also be bouncing slightly and unable to move or perform any other actions.
Upon relogging, you end up back in the nether inside the terrain and die.

Using: griefprevention-1.10.2-2.3.1.267

**Comment by bloodmc** [comment]
Just set teleport-to flag to false.

**Comment by Yorkforce** [comment]
Just tested this with /cf entity-teleport-to any false override on all basic claims, unfortunately the player is still entering the claim and being bounced into the void type area.

**Comment by ktole1999** [comment]
when it bounced them to a void. if the disconnected and reconnect did it resolve?

**Comment by Yorkforce** [comment]
Upon relogging, you end up back in the nether inside the terrain and die.

**Comment by ktole1999** [comment]
install netherportalfix mod. issue resolved. it resolves mixed up paths of nether portals.

**Comment by Yorkforce** [comment]
Unfortunately I don't think that mod works with SpongeForge, would have been great otherwise.

**Comment by ktole1999** [comment]
I currently have it on my sponge 2202 server and works great



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Yorkforce** [comment]
Tried NetherPortalFix v4.0.1 on SpongeForge 2211 and it doesn't work, I still come out of my neighbours portal.
