### ISSUE TITLE
Autovert option

### ISSUE THREAD

**Issue by ArcasCZ** [MinecraftPortCentral/GriefPrevention#338]
Hello,

I have few features on my mind.

1) Autovert - when player makes claim, this function will automatically expands selected region from min to max Y, but it affects just main claim, sub-claims are not affected ('cause of allowing some flags in subareas)

2) Paying just for surface, not for area - usable with autovert

3) Selecting by commands - we offer on our server large areas if someone wants to make his big project, but selectin 300x300 area manually is bit nagging and difficult. I imagine this command like: /select X Y Z which will lead to select +X, -X from your position and so on.

4) More like question - has player to pay for sub-region?

I'm sorry if some of these function are in this plugin, but I'm new to this plugin and I want to make sure.

**Comment by bloodmc** [comment]
2D claims are always bedrock to sky in latest. You can use the new /claim command in latest builds with WorldEdit to claim. Use GP's API to do whatever other stuff you want.
