### ISSUE TITLE
Command Block Event Source is showing up as a player rather than command block

### ISSUE THREAD

**Issue by Earthplate** [MinecraftPortCentral/GriefPrevention#339]
https://gist.github.com/anonymous/a0deb2a484ae70c70b9910d0de59bcce

The player is placing a redstone block to activate the command block.
All actions done by a command block should show it as source in events.

**Comment by Earthplate** [comment]
Shows up as command block source in GriefPrevention 261

**Comment by bloodmc** [comment]
If this is still an issue report to Sponge as GP just uses the source passed in events.
