### ISSUE TITLE
Visual blocks

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#34]
Visual blocks only go to solid blocks, not on blocks like water or slabs. 
So for example claiming an ocean, you'll only see the visual blocks underneath on the sand.
It used to be on the higest block on the y coordinate corner, water in this case ^

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
