### ISSUE TITLE
Issue with /cfg on Multi-Server networks

### ISSUE THREAD

**Issue by DeathVirus** [MinecraftPortCentral/GriefPrevention#340]
GP Example: /cfg guardian enter-claim any true
If I do /lp user DeathVirus parent add guardian Pixelmon it won't let me enter the claim  (http://prntscr.com/efzror) 

if I do /lp user DeathVirus parent add guardian (No server argument) it will (http://prntscr.com/efzrtm)

Brought this up in the discord, Phit was able to replicate the issue.

**Comment by phit** [comment]
lp verbose when entering the claim https://gist.github.com/phit/b703a8e1065bb37f71edd64a3d2522b7
lp check returns false when inside the claim http://i.imgur.com/EAysjtR.png
