### ISSUE TITLE
Duplicating OpenComputers robots

### ISSUE THREAD

**Issue by hunter688** [MinecraftPortCentral/GriefPrevention#341]
When OC robots move, is duplicated - move to new position (OK), but also stay on previous location(WRONG). This test is inside unclaimed territory (wilderness).

Without GP no issue. With very old GP(build 135) no issue.
Tested with build 267.
SF build 2215.

Maybe some missing permission idk.

**Comment by bloodmc** [comment]
@hunter688 Test the build before 267. Let me know if it occurs there.

**Comment by hunter688** [comment]
build 265 looks ok.

**Comment by bloodmc** [comment]
@hunter688 Please test https://www.dropbox.com/s/o684l2dgp6pce5h/griefprevention-1.10.2-2.3.1-TEST1.jar?dl=0

**Comment by hunter688** [comment]
Its fixed. Many thanks!
