### ISSUE TITLE
GriefPrevention crashes on start with Sponge version 1.10.2-2254-5.2.0-BETA-2230

### ISSUE THREAD

**Issue by john01dav** [MinecraftPortCentral/GriefPrevention#346]
Hello,

I am attempting to setup GriefPrevention with Sponge version 1.10.2-2254-5.2.0-BETA-2230 on the new FTB Infinity modpack. When I do so, I get [this](http://pastebin.com/uG3wH3dZ) error and any GriefPrevention features do not work in-game as if the plugin is not installed at all. I am using Java 8.

Thank you.

(If there is any other information that is needed, please let me know)

**Comment by bloodmc** [comment]
GP requires LuckPerms. Install it and you wont get errors.

**Comment by ktole1999** [comment]
can i ask at what version did GP require luckperms?

**Comment by john01dav** [comment]
Also, why _LuckPerms_? Sponge has a [plugin-agnostic permissions api](https://docs.spongepowered.org/stable/en-GB/plugin/permissions.html).

**Comment by bloodmc** [comment]
There literally is ONLY 3 permission plugins being used in Sponge....

PermissionsEx - DEAD plugin
PermissionsManager - Did not fully implement Sponge's permissions API for quite some time and has had various issues with GP. Latest builds *may* work.
LuckPerms - Fully implements Sponge's API and is currently the best in terms of performance and features.

GP will load with the other 2 plugins but expect problems.
