### ISSUE TITLE
Containers are not protected from people that are not standing in claim

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#348]
GP 271
SF 2223
Place a chest in a playerclaim(claimborder).
Leave the claim, try to access the chest. You can open the chest and take the stuff out of it. Seems to work with all containers.
http://image.prntscr.com/image/262650961f5c49a9a4caa2855090a152.jpeg

**Comment by bloodmc** [comment]
I cannot reproduce using latest SF/GP/LP. Retest using the LATEST builds on a fresh server.

**Comment by i9hdkill** [comment]
Hm, wrong claimflag I guess.
Still, this issue is even happening on a fresh setup:
https://github.com/MinecraftPortCentral/GriefPrevention/issues/241
