### ISSUE TITLE
Setting multiple flags for the same block overrides the previous one

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#349]
hey,
not sure if I'm doing it wrong or if it is a bug.
If I first run `/cfg default block-place gravestone:gravestone true` and then `/cfg default block-break gravestone:gravestone true` it overrides the previous flag.

griefprevention-1.10.2-2.3.1.255
LuckPerms-Sponge-2.17.64

**Comment by bloodmc** [comment]
@Sir-Will Update to latest GP, SpongeForge, LuckPerms. Old builds are NOT supported.

**Comment by Sir-Will** [comment]
Same issue with:
griefprevention-1.10.2-2.3.1.272
LuckPerms-Sponge-3.0.35
spongeforge-1.10.2-2254-5.2.0-BETA-2231

**Comment by bloodmc** [comment]
Use another name other than default and paste your default luckperms data as well as fml-latest-server.log

**Comment by Sir-Will** [comment]
Logs: https://gist.github.com/Sir-Will/55656c8479bd598cd51c4983dfe9057a
Tested it with group player13 and same result.
I assume you mean the permission nodes with data:
http://i.imgur.com/NWXPhDV.jpg

**Comment by bloodmc** [comment]
@Sir-Will Test it on a clean server and provide the LuckPerms folder zipped if it occurs.

**Comment by Sir-Will** [comment]
[luckperms.zip](https://github.com/MinecraftPortCentral/GriefPrevention/files/849398/luckperms.zip)

**Comment by bloodmc** [comment]
@Sir-Will I do not see any group files. Make sure to set the LuckPerms config to json then reupload the folder.

**Comment by Sir-Will** [comment]
Looks like this issue doesn't happen with json but with mysql and h2.
I assume this is an luckperms issue then or?

**Comment by bloodmc** [comment]
This was fixed in LP build 107

https://ci.lucko.me/job/LuckPerms/107/
