### ISSUE TITLE
Name, greetings, and farewell, abandoning claim, etc

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#35]
- [ ] Greeting and farewell messages do not trigger on warping

- [ ] Greeting becomes farewell messages

- [ ] Abandoning an admin claim does not return a message telling you it was successful or whatever

- [ ] Abandoning a basic claim returns a message that I have to stand in the claim I want to delete or do /gp claims abandonall (It abandons my claim though but the message it returns is wrong)

- [ ] Stick needs to touch a block to tell if it's claimed or not, in bukkit versions it reaches far

**Comment by ryantheleach** [comment]
What version were you running?

**Comment by SnowBlitzz** [comment]
It was B8 btw I'll test B9 and see if these problem still occur
