### ISSUE TITLE
Infinitely expand your claim

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#350]
Basically if you claim the max area then use the abandonclaim command, then the AbandonAllClaims command right after it will allow for the max claim size to be infinite.

For example I have a claim size of 650 blocks. Normally after you set a claim it will tell you the you have X amount of blocks remaining. But with the bug it will continue to say 650 each time you extend the claim size.

img 1 https://s3.amazonaws.com/files.enjin.com/568951/modules/forum/attachments/2017-03-16_22.35.31_1489729751.png

img 2 https://s3.amazonaws.com/files.enjin.com/568951/modules/forum/attachments/2017-03-16_22.35.43_1489729755.png

img 3 https://s3.amazonaws.com/files.enjin.com/568951/modules/forum/attachments/2017-03-16_22.35.52_1489729760.png

**Comment by SnowBlitzz** [comment]
https://www.dropbox.com/s/76jigv0xt8w3uwr/fml-server-latest.log?dl=0

**Comment by bloodmc** [comment]
griefprevention-1.10.2-2.3.1.264.jar

Update to LATEST SF, LP, GP. Old builds will not be supported.

**Comment by SnowBlitzz** [comment]
I understand, but there was no changes in the update that addresses this issue so I'd assume it still exists.
