### ISSUE TITLE
PSI + OreExcavation in claim dupe

### ISSUE THREAD

**Issue by merjilin** [MinecraftPortCentral/GriefPrevention#354]
I've recently found out that upon updating to the newest GP around 7 hours ago, player have already managed to find and manipulate a bug. The bug allows a player to get duplicate blocks which have been mined using a PSI laser with the tick break block and OreExcavation and it only occurs in claims.
Modpack= Resonant Rise 4 version 4.1.1.1-b (Found on the ATLauncher)
Steps to reproduce:
1.hold down the key for vein miner 
2.then use the psi gun spell break block while in another players claim
(it doesnt work if your trusted)

**Comment by merjilin** [comment]
Oh and both SF and GP are the newest (I updated both at the same time 7 hours ago)

**Comment by bloodmc** [comment]
@merjilin This is actually a Sponge bug when cancelling the event. Create a ticket in SpongeForge github.
