### ISSUE TITLE
naturally spawned creeper does not destroy blocks

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#355]
Fresh setup
GP 272
SF 2241
Forge 2254
LP: 3.0.52
Enter the world, leave the spawn protection.
Look for a naturally spawned creeper. (This is important!)

Let that creeper explode.

The creeper won't destroy any blocks

What should happen:
Creeper blows stuff up.

BTW: Creeper with owner (spawned with summon or spawnegg) are working fine and are blowing stuff up.

**Comment by ktole1999** [comment]
is the player spawned creeper inside claimed area?

**Comment by i9hdkill** [comment]
No, the creeper spawns naturally in the wilderness. But guess this also applies to creepers that spawned naturally in claims.

**Comment by ktole1999** [comment]
spawning in claim may have different grief protection than wilderness. yea

**Comment by bloodmc** [comment]
@i9hdkill Does this happen with latest SF build?

**Comment by i9hdkill** [comment]
Yes, still happening with:
SF: 2262
LP: 3.0.67
and fresh lp and gp settings

**Comment by EvilCh33z** [comment]
Happening on spongevanilla 256
Fresh files and LP

Same results

**Comment by gigafunk** [comment]
#329 
related to this or duplicate? I get this with all creepers.

**Comment by gigafunk** [comment]
For me, it was a sponge setting.  It was on e of these three, but they were all false,and when set true my explosions worked.
settings are under modules but not together in the actual setting file
 modules {
        block-capturing-control=false    
         tracking=false       <-----------------I think this is the one responsible.

and under 
 block-tracking {
enabled=false

All in all I think it was the tracking=false that was stopping explosions.
