### ISSUE TITLE
[Feature] Command execution when entering/leaving a claim.

### ISSUE THREAD

**Issue by tridaak** [MinecraftPortCentral/GriefPrevention#357]
Much like there's a claim greeting and farewell, a command (or set of commands, if user uses a plugin like command kits) gets fired towards the player when a player enters a claim.

This would be good for:
-Minigames (ie: an obstacle course or maze, rewards player when they reach the end)
-Quests (ie: Reach a certain area to advance the quest)
-Achievements (ie: Reach an area in the map to get an achievement and possibly a reward)
-Track built cities/villages/etc the player has visited (ie: Store in permission plugin or database in order to allow people to teleport to previously discovered areas)

Like mentioned, another plugin can greatly add possibilities onto this feature. Command kits allows for a multitude of commands to be run, permission plugins allow for per person permissions, while a plugin like Web-API would allow admins to store information onto the website database which later can be used to display things like rewards on a person's online profile.

**Comment by bloodmc** [comment]
It makes far more sense to just add events for this EnterClaimEvent/ExitClaimEvent. You can then just create a plugin to listen to the events and do whatever you want.

**Comment by tridaak** [comment]
It does make more sense to add events and create a plugin to listen to said events.
However, Sponge is in need of a whole lot of plugins, because of that, it'd likely take a long time for someone to make such a plugin and many people would probably just need to run a single command (well, that's all I need).

In the end, it's up to you to do what you want, but I do think it would take a while for another plugin to start using the events.

**Comment by skittishtrigger** [comment]
Actually this Idea is awesome from a server admin pov.  And it could stop the need for features such as #390 and #267, as well as many others not listed.  This post seemed the most appropriate to add my own wish/need to an enhancement/feature request since it fits more than one need all in one tiny, simple, command add. 👍   Thanks for the time and I cant wait for the town.plot update!

**Comment by bloodmc** [comment]
To do what you want, use the BorderClaimEvent

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/event/BorderClaimEvent.java

**Comment by Eufranio** [comment]
https://github.com/Eufranio/ClaimTweaks
