### ISSUE TITLE
Could not pass SpawnEntityEvent$ChunkLoad$Impl to Plugin{id=griefprevention...

### ISSUE THREAD

**Issue by ziceptor** [MinecraftPortCentral/GriefPrevention#358]
1.11.2-2227-6.0.0-BETA-2249 (2251) <-- Spam in console
1.11.2-2227-6.0.0-BETA-2244 <-- Works
forge-1.11.2-13.20.0.2227-universal.jar

simon816: There was a recent change to the 'bleeding' API snapshots.

https://gist.github.com/ziceptor/03e116e590d1b74b336ceb8ead4e47f7

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/506fa189aae1512351545560a893c779d83a8a20

**Comment by ziceptor** [comment]
Thank you!
