### ISSUE TITLE
CRITICAL BUG - Access to break/place/interact when player is 2+ blocks away from claim border

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#361]
I think there's a bigger issue here. if you stand like 2-3 blocks or more away from a claim you can break, place and interact. https://gyazo.com/50ab6a6b7b0e335f715ca88481e289d5

also you can open chests if theyre near the border of the claim.
too hard to make a gif here, it lags me, but that one should suffice and give the general idea

I'm on latest SF 2259, latest GP  278, although some players already noticed it on previous versions SF 2246 GP 272

**Comment by SnowBlitzz** [comment]
I managed to fix it be regenerating my claimflags. Here are my old claim flags which do not indicate anything that would break, so im wondering?

https://pastebin.com/n7RmXuq7

**Comment by bloodmc** [comment]
@SnowBlitzz I don't see anything wrong with those flags. Try to reproduce it.

**Comment by SnowBlitzz** [comment]
Wilderness claim has block-break and block-place true by default, but I think when you manually set them with /cf, that happens.

**Comment by KingDan27** [comment]
this issue occurs on my vanilla server as well, lp verbose says the the permission is true even when the individual claim is set to false. running beta 3 spongevanilla and griefprevention-1.11.2-3.1.1.294 ill try to regenerate my claimflags config and see if that fixes it also.

**Comment by bloodmc** [comment]
This was fixed in latest GP build, update.
