### ISSUE TITLE
[SUGGESTION] Town Features 

### ISSUE THREAD

**Issue by Zachincool** [MinecraftPortCentral/GriefPrevention#362]
GriefPrevention is one of the most useful plugins I know of. It is great for protecting your private claims and adding friends, but I feel it would benefit from a town system where claims can be grouped together under the category of a 'town'. This allows players to start a community project on servers, while at the same time not having to trust strangers to their personal claims. As far as the protocol for the actual usage, my knowledge is limited, but I could see something like:

/townclaim add (townname) which would notify the founder of the town that someone wants their claim to be added to the town. Claims should be relatively close to eachother in order for this to work.

I don't think it needs to be as extensive as Polis. I just think there needs to be a basic grouping together of individual claims.

A tax or fee system would probably be a good idea, but it's probably not first priority.
Another great feature would be to allow MCClans clans to also join their claims together, or allow the clan owner to make one claim that all members of the clan automatically are trusted in.

I have other small detail ideas, but this would be the main gist. The goal would be to let players form communities in game based off of their claims without having to risk trusting strangers to their claim. It's also cool to see towns being built!

If you already have plans to add town features, then excuse this. I am not really up to date on planned features :)

**Comment by bloodmc** [comment]
This has already been discussed here

https://github.com/MinecraftPortCentral/GriefPrevention/issues/166

Add to the existing ticket instead of creating a new one.
