### ISSUE TITLE
Exposing player claim enter and exit event to API

### ISSUE THREAD

**Issue by randombyte-developer** [MinecraftPortCentral/GriefPrevention#364]
Hi!

It would be great if the API had a claim enter and exit event. Otherwise the plugin would have to check itself on every player movement if the player is currently in another claim than before.

Some places I found after a quick read where to fire the event:
- [entity on move: enter](https://github.com/MinecraftPortCentral/GriefPrevention/blob/0766a4b9ef6b6990627ac835e939cfc01bd9a2e8/src/me/ryanhamshire/griefprevention/listener/EntityEventHandler.java#L677)
- [entity on move: exit](https://github.com/MinecraftPortCentral/GriefPrevention/blob/0766a4b9ef6b6990627ac835e939cfc01bd9a2e8/src/me/ryanhamshire/griefprevention/listener/EntityEventHandler.java#L700)

**Comment by bloodmc** [comment]
Yup, already on my TODO list.

**Comment by bloodmc** [comment]
@randombyte-developer https://gist.github.com/bloodmc/84099d1ce8d0770aa1c68711fce48580
How does that look?

**Comment by randombyte-developer** [comment]
Wouldn't there be a problem for the plugin listening to both events(enter and exit): The plugin doesn't know if the player exited and entered claims on the same tick. Imagine there are two claims which are directly located next to each other. The player moves from claim A to claim B. Between A and B there is no block. Visualization of the situation(O -> no claim):

O | O | O | O
O | A | A | O
O | B | B | O
O | O | O | O

The players moves from A down to B. He is exiting and entering at the same time. I think this should be made clear in the event.

My approach:
Something like a teleport between claims event, or `ChangeClaimEvent`. It has two methods: like `getFromClaim()` and `getToClaim()`. These methods return Optionals, for the situations when a player just leaves a claim.

**Comment by bloodmc** [comment]
@randombyte-developer OK, the I'll add that.

**Comment by randombyte-developer** [comment]
I think there are two options:
1. Take the enter event from the gist and add an additional exit event
2. Just create one event(e.g. ChangeClaimEvent) as described

**Comment by bloodmc** [comment]
@randombyte-developer I don't really like the word "change" as entering/exiting a claim does not change it.

**Comment by randombyte-developer** [comment]
Yes, ok, it was just a quick suggestion. Name it what you want. But you are with me that there will be only one event for enter and exit?
`BorderCrossEvent`?

**Comment by bloodmc** [comment]
Yes for sure, hrmm how about BorderCrossClaimEvent or CrossClaimEvent?

**Comment by randombyte-developer** [comment]
I'd go for one of the first two. English is not my first language so I can't really tell what sounds better. I think both describe it well.

**Comment by bloodmc** [comment]
@randombyte-developer https://gist.github.com/bloodmc/84099d1ce8d0770aa1c68711fce48580 updated. I removed getEnter/Exit message methods as you can retrieve that from the claim itself. I also removed optional as there will ALWAYS be a claim available (wilderness if no player/admin claim).

**Comment by randombyte-developer** [comment]
I like that :+1:

**Comment by bloodmc** [comment]
@randombyte-developer OK i'll add this to GP API soon along with implementation.

**Comment by bloodmc** [comment]
@randombyte-developer There is one other issue after reviewing possible implementation. What happens if the player is denied permission to enter the claim since GP has enter/exit flags. Do you have any problem if I cancel the event in this case so you can simply check if the event is cancelled and override if needed?

**Comment by randombyte-developer** [comment]
Yes, that's good.

**Comment by Mohron** [comment]
I would second cancelling the event since the player would not have crossed a claim border.

**Comment by bloodmc** [comment]
OK i'll finish up the implementation tomorrow. It should be available by tomorrow night.

**Comment by Mohron** [comment]
If another plugin cancels this event, will it have the same effect as the enter/exit flags being set to false?

**Comment by bloodmc** [comment]
@randombyte-developer https://www.dropbox.com/s/llrn56snqly6zu0/griefprevention-1.10.2-2.3.1-TEST4.jar?dl=0

Please test that and let me know if it works fine for your needs.

**Comment by randombyte-developer** [comment]
@bloodmc Works as intended! Thanks! Do you have an ETA when this is implemented in the next release!

**Comment by bloodmc** [comment]
@randombyte-developer minecrell is helping me separate the GriefPrevention API into its own submodule. So should be soon as I will be pushing changes after this is done.
