### ISSUE TITLE
Enter 3D claim with entry denied

### ISSUE THREAD

**Issue by SirRicharalar** [MinecraftPortCentral/GriefPrevention#365]
I made a small 5x5x3 3D subdivided claim to test entry-claim. Players of MEMBER rank are able to enter that cuboid even though I set it so they can't. Here were the commands I ran:

/cfg silver enter-claim minecraft:any true
/cfg pikachu enter-claim minecraft:any false
/cfg member enter-claim minecraft:any false

This is what it spams when they try and exit the 3D cuboid area:
https://gyazo.com/868c6fafb9585e08b9552751e7af2217

LP 3.0.67
GP 2.3.1.278
SF 2262

**Comment by bloodmc** [comment]
dupe #347
