### ISSUE TITLE
deathmessages

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#37]
```
    # Cooldown period for death messages (per player) in seconds.
    death-message-cooldown=60
```

I already did /gamerule showDeathMessages false and it still shows because of gp
Option to disable? also the cooldown works, it won't show another death message if player dies within 60 seconds but it will send a blank line in chat

**Comment by bloodmc** [comment]
GP only clears the death message. If it was sending a blank line then this was a sponge bug long ago. Should no longer be an issue in latest build.
