### ISSUE TITLE
[Feature] McClans Integration

### ISSUE THREAD

**Issue by Rasgnarok** [MinecraftPortCentral/GriefPrevention#370]
A lot can be done to integrate both plugins, but basic integration, to get the ex-Polis users into GP, would be the foundation for more usability.
Here are the first ideas:
- Entering a claim owned by a clan Member would display the welcome message, but also the name of the Member and the clan he belongs to (leaving would do the same).
- Members of a clan are automatically trusted in eachother's claims (the trust level can be configurable, as well as what access it actually gives).
- Members of a clan can teleport to other Members' claims.
- Clan bonus for block counts. This is a big one; you basically give incentive to players to regroup under populous clans by applying a 'boost' (be it added claim blocks or a multiplier) the more a clan has members. Acts a bit like Towny's Resident booster. Can and should be configurable.
- Since we had chatted about the possibility of a town layer, why not take it into McClans as well? That layer can only be administered by a Clan Leader (and the ones they gave permission to, since McClans has its own perm system), and all Members of a clan have basic trust level there, plus a clan warp to it (`/clan home`). This would basically be a GP claim only clan Leaders can interact with, unless a permission level is given.
- To enlarge that communal space, Members of a clan can pay to a 'clan balance' and the Leader can convert these into Clan Claim Blocks.

Further integration can include features more PVP-oriented, like:
- Members of opposing clans cannot enter-claim into enemy territory, and vice-versa, allied clans can enter-claim into allied territory. This territory being any clan member's GP claim.
~~- Allied clans can be configured to be able to read into other clan's chat they are allied with, or even create a seperate chat for all allied clans (if there is less demand, the former is a better option).~~

Reference, https://bitbucket.org/Kippers/mcclans-core-sponge/wiki/Commands_and_Permissions

**Comment by SnowBlitzz** [comment]
`Members of a clan are automatically trusted in eachother's claims` 
This imo would be really bad. I like how the plugins are separate at the moment. If this was to be added, a default of not being automatically trusted would be fine. 

`Clan bonus for block counts. This is a big one; you basically give incentive to players to regroup under populous clans by applying a 'boost' (be it added claim blocks or a multiplier) the more a clan has members. Acts a bit like Towny's Resident booster. Can and should be configurable.` 
I like this idea. Gives players incentives to join a clan.

`Allied clans can be configured to be able to read into other clan's chat they are allied with, or even create a seperate chat for all allied clans (if there is less demand, the former is a better option).`
They can already do that

**Comment by Rasgnarok** [comment]
Updated the ticket to reflect the last point. And as for the first, that is why it would be configurable. If you've tweaked with the trust levels in GP, you'd know you can change permissions per 'level' - making it your very own version. If you don't want this at at all, then it is possible to opt out. Config options make the world go round.

To me, it is a logical step in integrating McClans into GP, it makes it much more communal.

**Comment by bloodmc** [comment]
With latest build, claim messages will now start with the claim owner's clan tag rather than [GP].
Here is commit for reference

https://github.com/MinecraftPortCentral/GriefPrevention/commit/48d662beb358e03301b71f0fdcdcad65670b4184

More features to be added soon.

**Comment by kvolkers** [comment]
Not fully thought out yet, but how about the possibility for wars between clans. Claim protection would be disabled for members between the two clans during the war. War could be triggered for example when the two sides agree to it.

**Comment by Kippers37** [comment]
Not fully thought out yet, but how about the possibility for wars between clans. Claim protection would be disabled for members between the two clans during the war. War could be triggered for example when the two sides agree to it.
