### ISSUE TITLE
Could not pass CollideEntityEvent$Impl to Plugin

### ISSUE THREAD

**Issue by EvilCh33z** [MinecraftPortCentral/GriefPrevention#372]
Using spongevanilla-1.11.2-6.0.0-BETA-243 I get this spamming console hard:

[GPERROR.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/907683/GPERROR.txt)
 Help?

**Comment by gabizou** [comment]
Update your GriefPrevention.
