### ISSUE TITLE
Trusting Groups

### ISSUE THREAD

**Issue by Cheiroso** [MinecraftPortCentral/GriefPrevention#374]
Hello.
I have an issue : I just don't know how to /trust groups. 
I tried "/trust admin" for example, and it says there is no player with this name. I tried "/trust g:lider" , "/trust Glider" and got the same error.

I use pex for groups, and got 3 groups : admin, default and lider. Sponge + forge , Minecraft 1.10.2

Thanks

**Comment by sintaxcz** [comment]
Same issue here :(
 I use luck persm for groups, and got 3 groups : admin, default and fakeplayers. Sponge + forge , Minecraft 1.10.2
