### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ziceptor** [MinecraftPortCentral/GriefPrevention#376]
https://gist.github.com/ziceptor/bbbe2f2ef6895b4b9a491901142f4fdf

forge-1.11.2-13.20.0.2227-universal.jar
spongeforge-1.11.2-2227-6.0.0-BETA-2275.jar
griefprevention-1.11.2-3.1.1.289.jar
LuckPerms-Sponge-3.1.7.jar

**Comment by bloodmc** [comment]
This shouldn't be an issue with latest builds.
