### ISSUE TITLE
Low Priority enhancement: Player argument for /ic

### ISSUE THREAD

**Issue by 10745030** [MinecraftPortCentral/GriefPrevention#378]
Usage would be:

Let's call Player 1 Jake and Player 2 Oliver

*Jake has no perms for IC*
*Oliver has perms for IC and IC.Other*
*Oliver runs the command ```/ic Jake```
*Jake now has IC enabled, allowing him to bypass claims*  

Biggest thing I hadn't figured out is determining what claims to bypass- assuming "Jake" hasn't got ic for basic or admin claims, how does Oliver determine what claim type Jake can bypass?
Maybe:
/ica Jake for admin claims
/icb Jake for basic claims?
or:
/ic Jake admin for admin
/ic Jake basic for basic

**Comment by bloodmc** [comment]
By checking if the player has the ignore claim permission.

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Permissions
