### ISSUE TITLE
Some flags are not set by default.

### ISSUE THREAD

**Issue by XakepSDK** [MinecraftPortCentral/GriefPrevention#379]
Some flags are not set by default. This can happen with any flag.
In first config generation, wilderness has no "entity-damage" flag, in second config generation - no "entity-interact-primary" flag. This is really strange.

**Comment by bloodmc** [comment]
@XakepSDK Make sure you are using the latest LuckPerms, GriefPrevention, and Sponge builds. If so, paste your fml-server-latest.log for further assistance.

**Comment by XakepSDK** [comment]
Hi! I use pex.

On Apr 20, 2017 22:11, "bloodmc" <notifications@github.com> wrote:

@XakepSDK <https://github.com/XakepSDK> Make sure you are using the latest
LuckPerms, GriefPrevention, and Sponge builds. If so, paste your
fml-server-latest.log for further assistance.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MinecraftPortCentral/GriefPrevention/issues/379#issuecomment-295795703>,
or mute the thread

**Comment by bloodmc** [comment]
@XakepSDK PEX is longer being developed and is not supported. Migrate to LuckPerms by following this guide

https://github.com/lucko/LuckPerms/wiki/Migration
