### ISSUE TITLE
[1.10.2] Fake player trusting

### ISSUE THREAD

**Issue by kaal-1** [MinecraftPortCentral/GriefPrevention#383]
Mechanical user set to right click agricraft crop, the crop goes back to the initial stage but no item drops. In 1.7.10 we were able to /trust #[FakePlayerName] but it doesn't seem to be the case anymore.

Quantum quarry is not mining anything but consuming energy, I assume it's a problem with the fake player too.

**Comment by Eufranio** [comment]
Fake Players do nothing with Sponge, so I doubt it's an problem with them, report to SpongeForge. The Quarry issue is known and there's an issue there about it, I suggest you to take a look.

**Comment by bloodmc** [comment]
This is not caused by GP. FakePlayers will also never be supported as Sponge tracks all users.

**Comment by kaal-1** [comment]
Sorry, but it is definitely caused by GP. Woot mob spawners for example (which use a fake player named [Woot]), they work fine outside claims, and do nothing inside them. I don't get why GP dropped the support to trust the fake players in 1.10, it would solve a bunch of problems since lots of mods use fake players nowadays.

**Comment by Eufranio** [comment]
Because **fake players do nothing in Sponge, since it has a built in tracker**.
