### ISSUE TITLE
[Feature] Sellable plots in Admin Claimed Areas

### ISSUE THREAD

**Issue by fatyg5** [MinecraftPortCentral/GriefPrevention#387]
Subdivision in claimed area is possible, perhaps a way to integrate these subdivisions into the economy's of servers for towns among other things. Possibly

- Subdivisions selling for money
- A tax/charge system that can be triggered daily or weekly

**Comment by bloodmc** [comment]
Latest builds support buy/selling of claims. There is also tax/bank system. Read wiki for further info.
