### ISSUE TITLE
Something is disabling teleport and more.

### ISSUE THREAD

**Issue by domretana** [MinecraftPortCentral/GriefPrevention#388]
I have follow the #rules on discord, I have updated everything and now it seems worse. LuckPerms commands are no longer working as anything I type in results in the message "[LP] Running LuckPerms v3.1.45.". I appear to have lost the access i had prior to updating the request files.

This I've noticed since installing grief/luckperms.
-Teleportation through commands or through journeymap waypoints no longer work.
-Arrows appear bugged on claimed areas belonging to others, they bounce off mobs if in claim belonging to someone else.
-Removing items from someone elses claimed itemframe causes that item to fall towards the ground and vanish.

[fml-server-latest.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/988522/fml-server-latest.txt)

Please help, this has gotten pretty frustrating. 
Thank you

**Comment by domretana** [comment]
So I reverted almost all my files, I was able to grant myself admin perms once again. I was able to run verbose, I attempt various things for teleport in and out of journey map. Everything I tried for teleport results in "you do not have permissions...". Using LP commands I was able to verify that teleport is active and that admin and moderator groups are allowed to TP. Below is my verbose output during my TP attempts. No results, please help.

Metadata
Key 	Value
Start Time 	2017-05-10 18:55:01 EDT
End Time 	2017-05-10 18:56:02 EDT
Duration 	1 minute 1 second
Count 	0 / 400
User 	Console
Filter 	tp

**Comment by domretana** [comment]
![2017-05-10_19 18 14](https://cloud.githubusercontent.com/assets/25904354/25925279/9b807cc0-35b5-11e7-82b1-88df03f98b8b.jpg)

Heres a screenshot showing that TP is set to allowed

**Comment by domretana** [comment]
Managed to get some data from verbose command, what does it mean when various things are undefined?

Verbose Checking Output
This file was automatically generated by LuckPerms v3.1.45
Metadata
Key 	Value
Start Time 	2017-05-10 23:04:27 EDT
End Time 	2017-05-10 23:05:11 EDT
Duration 	44 seconds
Count 	114 / 114
User 	DomRetana
Filter 	any
Output

Format: <checked> <permission> <value>

local:defaults/user(p) - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/user(t) - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/user - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/default(p) - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/default(t) - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
domretana - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/default(p) - griefprevention.flag.command-execute.minecraft.tp. - UNDEFINED
local:defaults/default(t) - griefprevention.flag.command-execute.minecraft.tp. - TRUE
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp. - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp - TRUE
domretana - minecraft.command.tp - UNDEFINED
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana.-115 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115 - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69 - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69.153 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69.153 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69.153 - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp - TRUE
domretana - minecraft.command.tp - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.skeleton - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.skeleton - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.animal.chicken - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana.-115 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115 - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69 - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69.153 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69.153 - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp.domretana.-115.69.153 - TRUE
domretana - griefprevention.flag.command-execute.minecraft.tp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.tp - TRUE
domretana - minecraft.command.tp - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.creeper - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.creeper - TRUE
local:defaults/user(p) - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/user(t) - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/user - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/default(p) - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/default(t) - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
domretana - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/default(p) - griefprevention.flag.command-execute.minecraft.teleport. - UNDEFINED
local:defaults/default(t) - griefprevention.flag.command-execute.minecraft.teleport. - TRUE
local:defaults/default - griefprevention.flag.command-execute.minecraft.teleport. - TRUE
local:defaults/user(p) - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/user(t) - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/user - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/default(p) - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/default(t) - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
domretana - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/default(p) - griefprevention.flag.command-execute.minecraft.teleport - UNDEFINED
local:defaults/default(t) - griefprevention.flag.command-execute.minecraft.teleport - TRUE
local:defaults/default - griefprevention.flag.command-execute.minecraft.teleport - TRUE
local:defaults/user(p) - minecraft.command.teleport - UNDEFINED
local:defaults/user(t) - minecraft.command.teleport - UNDEFINED
local:defaults/user - minecraft.command.teleport - UNDEFINED
local:defaults/default(p) - minecraft.command.teleport - UNDEFINED
local:defaults/default(t) - minecraft.command.teleport - UNDEFINED
local:defaults/default - minecraft.command.teleport - UNDEFINED
domretana - minecraft.command.teleport - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.aquatic.squid - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.aquatic.squid - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.zombie - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.zombie - TRUE
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.skeleton - UNDEFINED
local:defaults/default - griefprevention.flag.entity-spawn.minecraft.monster.skeleton - TRUE
domretana - griefprevention.flag.command-execute.luckperms.lp.verbose - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.luckperms.lp.verbose - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.luckperms.lp.verbose - TRUE
domretana - griefprevention.flag.command-execute.luckperms.lp.verbose.paste - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.luckperms.lp.verbose.paste - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.luckperms.lp.verbose.paste - TRUE
domretana - griefprevention.flag.command-execute.luckperms.lp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.luckperms.lp - UNDEFINED
local:defaults/default - griefprevention.flag.command-execute.luckperms.lp - TRUE
domretana - luckperms.verbose - TRUE

**Comment by bloodmc** [comment]
This is not a GP issue. Teleport works fine with just GP/Sponge/LP.

**Comment by ktole1999** [comment]
nucleus may have control. check config and disable as needed.
