### ISSUE TITLE
Personal claim's enter-claim flag prevents the user from leaving the claim

### ISSUE THREAD

**Issue by meza** [MinecraftPortCentral/GriefPrevention#389]
Hello

I'm using Sky Factory 3.0.8 with SpongeForge, LuckPerms, Nucleus and GP - which are at the time of this report are all up to date.

When a non admin user has the `enter-claim` flag override to false, they seem to be locked inside their own islands.

They can't leave their claim borders, they can't use the beneath teleporter and they can't use /spawn.

Weirdly enough, they _can_ use the nether portal. 

When they run /spawn, this is what I get in the logs:
`griefprevention.flag.enter-claim.minecraft.player.source.minecraft.player (FALSE)`

Spawn is obviously not protected. When I remove the enter-claim override **from the user's claim**, they can successfully go to /spawn, leave their borders or go to the beneath (although this latter is just a guess)

To reproduce, simply lock up an island like so:
![screen shot 2017-05-10 at 22 02 04](https://cloud.githubusercontent.com/assets/211977/25921155/56f6b954-35cc-11e7-9f26-707a5f5719e2.png)

Then try /spawn

[fml-server-latest.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/991205/fml-server-latest.txt)

**Comment by meza** [comment]
Apparently the `entity-teleport-to` has similar effects. It blocks the claim owner to go to /spawn for example

**Comment by bloodmc** [comment]
For now just remove the ability for users to use that flag.

**Comment by meza** [comment]
It's the admins setting that anyway, but it's the key to locking down the islands in Sky Factory 3. Is ther another way to prevent untrusted people from entering claims with the /tpisland?

**Comment by bloodmc** [comment]
@meza I'm unable to reproduce this issue with latest GP build. Reopen if it persists.
