### ISSUE TITLE
Griefprevention Wiki (Pixelmon) Issues

### ISSUE THREAD

**Issue by KhaozFrost** [MinecraftPortCentral/GriefPrevention#391]
So I'm standing in my admin claim and I run this command:
/cf projectile-impact-block pixelmon:occupiedpokeball any true in an attempt to block throwing out pokemon within the claim only. http://prntscr.com/f99wgj but I'm still able to throw out pokemon... http://prntscr.com/f99wvx the only way I can block any of these commands is if i add override to the end and doing that makes it unable to throw them out anywhere which isn't something I want.
Also this goes for things like this too:
/cf projectile-impact-block pixelmon:pokeball any true override
I need to block certain types of pokeballs but this blocks all of them and only works if i use an override. this goes for all pixelmon related commands on the wiki.

**Comment by ktole1999** [comment]
are you testing this as a player or admin?

**Comment by bloodmc** [comment]
In current builds, trust supersedes permission checks so remove all trust and just use flags only. If you want specific types of items/blocks then use meta as explained in the flag section of wiki.
