### ISSUE TITLE
Renaming items in the anvil does not work.

### ISSUE THREAD

**Issue by domretana** [MinecraftPortCentral/GriefPrevention#394]
I've encountered an issue with renaming objects in the anvil. It happens with everything but for this verbose report I was using dirt so I could create some Filler blocks for hoppers. 

When renaming, I can place the dirt in the anvil > rename > and when pulling the renamed dirt from the anvil, it reverts back to the unnamed pile in the anvil and proceeds to use my exp as if the transaction was completed.

Here's the complete verbose report, please help: https://git.io/vHJ7n

This is was I've noticed from the report but don't know how to correct this.
local:defaults/default - griefprevention.flag.block-place.minecraft.dirt.source.minecraft.sheep.0 - FALSE

**Comment by bloodmc** [comment]
Unable to reproduce with latest SF and GP. Remove all your plugins/mods except LP/GP/SF and try again with fresh perms.
