### ISSUE TITLE
Multimine overrides Block-Break=False

### ISSUE THREAD

**Issue by AtaxiaGames-GM** [MinecraftPortCentral/GriefPrevention#395]
So, I think I may be doing something wrong (using GP ver 2.3.1.295 | LP ver 3.2.4 | SF ver 2281-5.2.0-BETA-2350):  I have all three default configurations and the claim flag configured with "block-break=false"; however, it seems to be the only flag not actually working. I have other things set to false (i.e. - block-place=false, explosion=false, explosion-surface=false, fire-spread=false, interact-block-primary=false, etc, etc...), but they are all working. It's just that block-break=false doesn't seem to be. Is there something else that I have to do regarding block-break?

[FML Latest Server Log](https://www.dropbox.com/s/jjqddfv3831ndrj/fml-server-latest.log?dl=1)
[Latest Server Log](https://www.dropbox.com/s/jrzo9mfrrsj7mc8/latest.log?dl=1) which has a verbose readout of the permissions response.

I hope I've met all of the pre-stipulated rules. Thank you for your time!

**Comment by AtaxiaGames-GM** [comment]
So, I finally figured out what was happening: Apparently, multimine and GP are arguing with each other. MultiMine appears to maintain a block's progress in breaking while GP says no. Once the multimine counter reaches its max potential it allows the target block to break, overriding GP. Just thought you'd like to know my observations about it.

**Comment by AtomicStryker** [comment]
MultiMine should honor the result of ForgeHooks.onBlockBreakEvent which i hope GP uses somehow.

**Comment by bloodmc** [comment]
Sponge honors Forge' BlockBreakEvent so there should be no issue with GP. Reopen if it still happens with latest SF and GP.
