### ISSUE TITLE
Untrusted Player can break blocks inside claim when outside claim 

### ISSUE THREAD

**Issue by BobGamingHD** [MinecraftPortCentral/GriefPrevention#397]
Here is the verbose output as asked: https://gist.github.com/anonymous/60aaaba45eca23b3b8c1f87caa1ce409

**Comment by bloodmc** [comment]
Setup a test server with ONLY GP, LP, and SF. Make sure you use latest builds for each. Do not use any existing data and retest.

**Comment by BobGamingHD** [comment]
After creating the test server and copying all flags from it to my main server the issue seems to be fixed.
