### ISSUE TITLE
Possibly Player Data Corruption

### ISSUE THREAD

**Issue by Kostronor** [MinecraftPortCentral/GriefPrevention#398]
I am running into an Issue with GriefProtection at the moment.

We use SkyClaims for a SkyBlock server and when a Player dies he should respawn. 

But the player instead is seeing nothing around him and is floating in the air. After leaving is not able to join until server restart.

Removing SkyClaims does not fix this but removing GriefProtection does.

This is 100% reproduceable and we run on latest stable sponge with sponge recommended forge. 

Any Ideas what this is and how to debug it? If you need to see it in person, pm me

![image](https://cloud.githubusercontent.com/assets/644950/26560203/fb9d8004-44b4-11e7-9486-ce75b21af773.png)

**Comment by Kostronor** [comment]
Adding Logs to this issue:

Stacktrace extracted: https://gist.github.com/Kostronor/b5e8101a532497069b319303290e4e41

Server Latest: 
[fml-server-latest.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/1037329/fml-server-latest.txt)

Client latest (has the timeout and maybe other infos): 
[latest.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/1037332/latest.txt)

Txt because GitHub does not allow .log

**Comment by bloodmc** [comment]
@Kostronor The error involves a bad mapping. Could be a problem with SF 2353, try 2350 and see if that works.

**Comment by Kostronor** [comment]
@bloodmc I updated the stacktrace and log with the working version. Now the error shows.

**Comment by bloodmc** [comment]
Closing as I could never reproduce this issue.
