### ISSUE TITLE
Pixelmon - Pokeballs Will Not Throw

### ISSUE THREAD

**Issue by CKGarner** [MinecraftPortCentral/GriefPrevention#399]
I recently went through the wiki for my server in search to allow players to throw PokeBalls, I used the commands to fix shown on wiki but it still doesn't work. Can anyone further help me?

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Pixelmon

Make sure you are using LATEST GP, SpongeForge, and LuckPerms.
