### ISSUE TITLE
Mob spawning

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#40]
setting claimflag spawn-any to false, or every other claimflag involving mobs still allow mobs to spawn in spawners, spawneggs (which is okay I guess) and chicken eggs. 

Would also like to see a config option to customize what you want to be able to spawn, a blacklist? something like mobBlacklist: ["allMinecraftMobs"] or ["Pig", "Chicken"] which should disallow not just natural spawns but also spawns triggered from spawners or eggs

**Comment by hsyyid** [comment]
This would probably be best added as another list flag that would filter out specific `EntityType`s from spawning.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
