### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by PASSTHEBLEACH** [MinecraftPortCentral/GriefPrevention#403]
So, I installed the plugin and it's not even working. The config isn't showing up where it says it should be. What do I do?

**Comment by MCTyler** [comment]
Could you be any more vague? Seriously, you have absolutely no info in that report at all. No wonder I have to wait weeks to get help with REAL issues.

**Comment by bloodmc** [comment]
No response in over a week, create a new ticket if you still have issues.
