### ISSUE TITLE
Permissions/Options Issue

### ISSUE THREAD

**Issue by MCTyler** [MinecraftPortCentral/GriefPrevention#404]
Forge 2282/SpongeForge 2282/Luck Perms 3.2.11/GriefPrevention 3.1.1.294.

I am trying to use Permissions to set Max accrual blocks and accrual per hour but I cannot get the format right for luck perms. I followed the Options wiki like this /lp user/group <user|group> meta set <option> <value> [server] [world] Like this /lp group user meta set griefprevention.blocks-accrued-per-hour 60 global world and it doesn't work. Can anyone briefly explain what I'm doing wrong?

Export group: user
/luckperms group user permission set meta.griefprevention.blocks-accrued-per-hour.60 true world=world
/luckperms group user permission set meta.griefprevention.max-accrued-claim-blocks.1000 true world=world
You guys reference [this](https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Options)

**Comment by Scratchman** [comment]
As an example, let's say you have an luckperms permission group called renegadeand you want them to accrue 60 blocks per hour,

/lp group renegade meta set griefprevention.blocks-accrued-per-hour 60

that would give all players in the renegade group 60 blocks per hour on all worlds, but if you had a player named BigBob and you wanted them to max accrue 1000 blocks on a world called Alpha

/lp user BigBob meta set griefprevention.max-accrued-claim-blocks 1000 Alpha

good luck.

**Comment by MCTyler** [comment]
Thanks, I just figured it out literally 30 minutes ago! I had to leave off the optional arguments for [sever] and [world] and it worked perfectly setting the perm global for the user group!
