### ISSUE TITLE
You do not have permission to use the teleport feature in this claim.

### ISSUE THREAD

**Issue by tridaak** [MinecraftPortCentral/GriefPrevention#406]
Using latest GP and LP for Sponge Forge 1.10.2 and have all permissions, but for some reason when trying to teleport to a user's claim, I get "You do not have permission to use the teleport feature in this claim."

I can however just use the teleport command to teleport to the claim, but not through /claimlist

**Comment by bloodmc** [comment]
You must be trusted. If you are an admin, simply use /ignoreclaims to TP to non-trusted claims.
