### ISSUE TITLE
Not loading claim data 

### ISSUE THREAD

**Issue by tridaak** [MinecraftPortCentral/GriefPrevention#407]
Often, after running /claimlist <player>, waiting a bit, then running it again. The claimlist command will not return any claims, despite the user having several claim.
Running latest sponge and GP for 1.10.2

**Comment by bloodmc** [comment]
@tridaak You need to provide your fml-server-latest log.

**Comment by bloodmc** [comment]
Closing as this is not an issue with latest builds.
