### ISSUE TITLE
Flag requests

### ISSUE THREAD

**Issue by EmanYm** [MinecraftPortCentral/GriefPrevention#408]
One of my admins suggested using UniverseGuard.  I told him I like the robuse nature of GriefPrevention over the ease of use we'd get from UG.  That said, I did notice a few flags on UG that I'd like to see added, if it's possible.

`pvp` (`mobpvp` `animalpvp`) - This is different than the `command-execute-pvp` flag, as it stops players hurting another player
(This might be covered by "entity-damage")

`expdrop` `sleep` - I can't seem to find a GP equivelant.
("expdrop" might be covered by "entity-spawn" and "sleep" covered by "interact-entity-secondary")

`creeperexplosions` `endermangrief` `enderdragonblockdamage` - You can likely cover this with a single "mobgrief" flag
(The creeper might be covered by "explosion")

`vehivalplace` `vehicaldestroy` - the GP "entityriding" doesn't really seem to cover placement/breakage of carts and boats
(This could already be covered under "block-place" or "interact-entity-secondary")

`leafdecay` - We had someone asking just today about this one

`sendchat` - perhaps only the people within the same region can "hear" you?

`walldamage` `drown` `cactusdamage` - These might alreayd be covered under "entity-damage", but I'm not sure how.

`hunger` - Or even a flag that heals the player

If any of these can actually be created with specific tags, please let me know.

**Comment by Rasgnarok** [comment]
Indeed, some of these are only just clever usage of targets and existing flags. Whilst I think GP is pretty complete, with Nucleus' removal of the blacklist, some stuff could probably be added - ProtectionPerms likely interferes with GP, and I'd rather stick with the latter.

It does offer, however, item-craft and entity-breed, which I am unsure if those can be covered with existing flags.

**Comment by EmanYm** [comment]
Would breed not be covered under entity-interact-secondary since you need to right-click to feed the animal?
Item crafting can be stopped the same way, can't it?  Deny interacting with the crafting bench.

**Comment by Rasgnarok** [comment]
yeah, certain items - don't want everything, but certainly some pesky pixelmon items

**Comment by bloodmc** [comment]
These flags requests SCREAM vanilla which GP Sponge is not about. All of GP Sponge flags are generic designed for both vanilla and mods. The big difference with Sponge's version is the introduction of sources for flags. With sources, you can cover a lot more special cases such as what you asked for. Everything can be handled except hunger as it is NOT available in Sponge's API. I suggest you read the debugging section on wiki to learn what to use.
