### ISSUE TITLE
The End Flags Not Setting Correctly

### ISSUE THREAD

**Issue by DaschnerJ** [MinecraftPortCentral/GriefPrevention#409]
So I been battling with this issue for a week. I am currently running Forge-2281 with Sponge server with the grief prevention for SkyFactory3 3.0.10. However, this protection plugin is also active in all worlds which isn't an issue but an annoyance because of the said issue above. The problem is, I give my users complete access to destroy or do what ever to the end and even give them permissions, flags, set the default settings true in that dimension and world config but the plugin refuses to allow players to interact with that dimension unless I explicitly go there myself, do /trust all and allow them and then on the restart that gets reset. Even when I disable grief prevention claims for that world it still prevents players from interacting with that dimension. Only OPs can. I did a permissions debug and the only permissions getting flagged are griefprevention permissions. 

This is absolutely frustrating issue which only happens with The_end. The nether has the exact same configuration file and doesn't have this issue but no matter what test it always leads back to grief prevention. And yes, I have tested this with only grief prevention and Pex in a separate testing world and the results are the same.

**Comment by bloodmc** [comment]
PEX is a dead plugin and will never be supported. Migrate to LuckPerms to fix your problems, as suggested in the wiki.
