### ISSUE TITLE
Negative claim blocks

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#41]
A lot of players in the server are experiencing having negative claim blocks
This is a screenshot of one of the many player's claimslist and land claim info
http://prnt.sc/awbxiy
http://prnt.sc/awbyax
The land claim is 49 x 42

Now they do not get claim blocks gradually when online

**Comment by bloodmc** [comment]
@SnowBlitzz There was a cause tracking bug in recent SpongeForge builds causing claims to get claimed without a player being involved. Please update to latest SpongeForge and let me know if this issue still occurs. If it does, please try to figure out how it happens.

Thanks!

**Comment by SnowBlitzz** [comment]
The claim blocks do not add up through playtime for everyone, yes everyone. Supposed to get 100 per hour but 0.
