### ISSUE TITLE
About messages translation

### ISSUE THREAD

**Issue by EuropeJing** [MinecraftPortCentral/GriefPrevention#410]
I would like to know whether GriefPrevention can upload, change messages language (such as Chinese), if it can be even better

**Comment by bloodmc** [comment]
You can alter some messages via messages.conf file in ./config/griefprevention. Next build you will be able to alter nearly every message.

**Comment by EuropeJing** [comment]
I know this, but this is only effective for me, I want to help everyone

**Comment by bloodmc** [comment]
@EuropeJing Oh, I understand now. Sure just paste your message file to https://gist.github.com. 

Note: Next GP build will require the file to be updated again as everything has changed.

**Comment by EuropeJing** [comment]
Ok, then i create a pull requests

**Comment by bloodmc** [comment]
Closed as PR was already pulled.
