### ISSUE TITLE
List all claims in a world.

### ISSUE THREAD

**Issue by ryantheleach** [MinecraftPortCentral/GriefPrevention#411]
Would it be possible to list all claims?

Properties needed:
  owner/name, last active, location/world, size?

I'm not sure what else would be important, but having clickable texts to list additional details, clicking on loc to teleport there, with mouseover with additional details, hover owner to view all owners.

Not sure what else.

Came up in a chat with Inscrutable and Worm when discussing  Sponge Community Server.

**Comment by bloodmc** [comment]
Sure but if a server has a ton of claims, there would be too many pages to cycle through which would make it quite useless. There should still be some type of criteria to search for in order to break it down.

**Comment by ktole1999** [comment]
what about export to file?
