### ISSUE TITLE
Usage of the API

### ISSUE THREAD

**Issue by randombyte-developer** [MinecraftPortCentral/GriefPrevention#416]
Hi!

A user reported to me that GP seems to "forget" the builders of a claim. This is not due to accidentally removing them through the API.

My code(snippet):

``` kotlin
    override fun setOwners(location: Location<World>, players: List<UUID>) {
        val claim = getClaim(location)
        claim.removeAllTrusts(cause)
        claim.addTrusts(players, TrustType.BUILDER, cause)
    }
```

Where `getClaim(...)` is:
``` kotlin
    private fun getClaim(location: Location<World>): Claim {
        val claim = getClaimManager(location.extent).getClaimAt(location, false) // ignoreHeight: false
        // maybe a subdivision was targeted?
        val subdivision = claim.subdivisions.find { it.contains(location, false, false) } // ignoreHeight, excludeSubdivisions
        return subdivision ?: claim // for Kotlin foreigners: (subdivision != null) ? subdivision : claim
    }
```

Where `getClaimManager(...)` is:
``` kotlin
    private fun getClaimManager(world: World) = griefPreventionApi.getClaimManager(world)
```

Am I using the API in a wrong way? Might there any reason why GP "forgets" the trusts?

Thanks!

**Comment by Mohron** [comment]
claim.removeAllTrusts(cause)
^ You're removing everything...

**Comment by randombyte-developer** [comment]
Yeah that's right, but this is the purpose of that function: to set the specific owners, everything has to be removed first and then only add them. 

Is there some method to save the changes made to the GP storage or is this done automatically?

**Comment by bloodmc** [comment]
You need to call save()

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/data/ClaimData.java#L288

**Comment by randombyte-developer** [comment]
@bloodmc That's what I was looking for! Thanks!
