### ISSUE TITLE
IC2 machines' meta isn't reported by verbose/checked by GP

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#418]
IndustrialCraft2 machine itemstacks are simple `ic2:te:meta` items, where `meta` is the item damage that will define which machine the itemstack is representing. When you place the machine, the `block-place` flag is checked, but the checked block metadata is always 0.

How LP reports the placed block for the `block-place` flag:
![img](https://cdn.discordapp.com/attachments/215593150494801930/339113815801069569/unknown.png)

/blockinfo, from Nucleus, when looking at the block in the world:
![img](https://cdn.discordapp.com/attachments/215593150494801930/339122452858798092/unknown.png)

/iteminfo, from Nucleus, when holding the itemstack:
![img](https://image.prntscr.com/image/vdEaHBScSC2KhxEAO1Ddbg.png)

Running:
SpongeForge: 1.10.2-2281-5.2.0-BETA-2464
LuckPerms v3.2.53
GriefPrevention 1.10.2 2.3.1.302 
industrialcraft-2-2.6.245-ex110 [[link]](https://minecraft.curseforge.com/projects/industrial-craft/files/2442911)

**Comment by liach** [comment]
What's the itemstack data value?

**Comment by Eufranio** [comment]
`ic2:te:57` if that's what you mean.

**Comment by liach** [comment]
So it does not check the meta of 57?

**Comment by Eufranio** [comment]
It checks the ITEM meta for item related flags (interact-item-x) correctly. By some reason, the placed block has meta 0 instead meta 57, so block-place recognizes the placed block as `ic2:te:0`.

**Comment by liach** [comment]
Well, ic2 block metas are dependent on their block entity data.

**Comment by bloodmc** [comment]
Create a new ticket if IC2 issues occur with latest.
