### ISSUE TITLE
[1.10.2 / SpongeForge API 5] Time Out Error

### ISSUE THREAD

**Issue by Peashooter101** [MinecraftPortCentral/GriefPrevention#419]
Utilizing the server, I experience a time-out error. We have chocked down the possibilities to this plugin. This occurs on the most recent instance when we interact with a Blockling. When we changed the flags item-interact-primary and item-interact-secondary it fixed the issue. The player then attempted to shift and interact with the Blockling (which will open an inventory when you have a flower at hand) and that caused the issue next.

This has happened before on the previous modded server I was staff for but it did not have Blocklings.

There is no active error that appears on console or logs. The server enters a sort of limbo state.

**Comment by bloodmc** [comment]
I still need your fml-server-latest log so I can see what versions you are testing with. Also explain in detail step-by-step how to reproduce the issue.

**Comment by Peashooter101** [comment]
PasteBin will not accept as it is too large for pastebin. Converted to .txt since .log is not supported.
[fml-server-latest.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/1178862/fml-server-latest.txt)

Using an Administrator Region, ensure the item-interact-primary and item-interact-secondary flags are set to false.
Set down a blockling within the region and without permissions that bypass Grief Prevention, right click the Blockling with a tool to give it the item.
Server times out and everyone is forcibly disconnected for "Timed Out". The server continues to run in a "state of limbo" where it only logs the attempts to authenticate users.

We fixed the issue by setting both those flags to true. We then attempted the open inventory setting, ensuring it is false, use it in an administrator region.
Set down a blockling within the region and without permissions that bypass Grief Prevention, shift + right click the Blockling with a flower to access it's inventory.
Server times out and everyone is forcibly disconnected for "Timed Out". The server continues to run in a "state of limbo" where it only logs the attempts to authenticate users.

We did not troubleshoot this issue any further. I had work following.

The main similarities between this server and the server prior is that:

- The issue happens at seemingly random intervals, with little to no patterns noticable via logs or console.
- It does not produce a crash report and the only thing visible in logs and console is [User Authenticator] attempting to continually authenticate all users that were previously on the server, all other logs have no change.
- With a reduction of players on the original server, we noticed this issue to happen less often, but tended to happen continuously should the same players who were on prior rejoin immediately after restart.

Important Notes:

- Doing weeks of research for both servers (I was Head Administrator and had access to Console and Server Files on the first one, I own the second one) I have found nothing in regards to Sponge having a User Authentication issue.
- Noticed this issue was similar to something that happened using Essentials on a Spigot Server and tested to see if it was Nucleus caused. It was not. Not only that but the Spigot server in question ended up crashing and yielding a crash report.
- Tested via the use of Blocklings, where in the administrator region, the above stated settings caused issues. Blocklings have not caused this issue in any other way prior. This was the only specific instance that I was able to find where this issue is caused. The previous server had a lot of players, too many to track and manage for the finding of this issue. This server has just recently underwent this issue.
- Blocklings were not used in the previous server, however the previous server did have the exact same issue, so it may be caused by any mod calling certain functions regarding the flags set.
- We would consider removing this plugin if it was not integral for grief prevention on our server. Also, is the most commonly known method of grief prevention.

If you need to utilize our server for testing, we run the modpacks on both the Technic and Curse Launchers.

Curse Page: https://minecraft.curseforge.com/projects/the-official-jurassicraft-modpack-dragonpeas/files/2451736

Technic Page: https://www.technicpack.net/modpack/official-jurassicraft-modpack.1063833

The modpack contains the server IP, however it is jurassicraft.fluctis.com.

Give us a heads up prior to coming on, I am in the US Air Force and I work the Afternoon to Evening as opposed to Morning to Afternoon (I am unable 1:30 PM to 11:00 PM US Central Time (UTC-6)). I may be completely unable to contact you during working hours. The other server owners on the Discord do not fully understand this issue and cannot help. The discord we utilize is: https://discord.gg/wD9nqvs if you would like to directly contact me or a staff member at any time (I do not actively utilize gitHub enough to give consistent feedback and updates).

**Comment by bloodmc** [comment]
Thanks for the detailed report! I'll look into this issue this weekend.

**Comment by bloodmc** [comment]
@Peashooter101 This issue doesn't occur in my upcoming GP update so just wait for the new build which should be released soon.
