### ISSUE TITLE
Console error 1.12.1

### ISSUE THREAD

**Issue by Amiroslo** [MinecraftPortCentral/GriefPrevention#422]
Getting those two errors
https://pastebin.com/EpQcpZ65

Using spongeforge-1.12.1-2444-7.0.0-BETA-2500 & forge-1.12.1-14.22.0.2444-universal with latest LuckyPerm (LuckPerms-Sponge-3.2.63)

**Comment by bloodmc** [comment]
You should be using GP build 314 to support latest permission API changes.

**Comment by Amiroslo** [comment]
Would be great if I could be linked to that build. 

Thank you

**Comment by Amiroslo** [comment]
Using GP build 314, Now I have this error
https://pastebin.com/D6fUQqEx

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/a28b4a96fa8172897c72a0164ef4a2dc61399cc2
