### ISSUE TITLE
1.10 version build to wrong sponge api ?

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [MinecraftPortCentral/GriefPrevention#426]
version griefprevention-1.10.2-4.0.0.328.jar wont load because
Detected SpongeForge build 2464 but GriefPrevention requires build 2497+

The latest sponge for 1.10 is 1.10.2-2281-5.2.0-BETA-2464

Soooo 2497 is a no go ..... any fix plz ?

**Comment by fusionmc-evilscoop** [comment]
nm, have to use 6 experimental

**Comment by bloodmc** [comment]
The latest SF build is NOT 2464, it's 2497
http://files.minecraftforge.net/spongepowered

**Comment by fusionmc-evilscoop** [comment]
that diff to the one on https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2
lol
youd think they could update their own site :D
