### ISSUE TITLE
Wither won't spawn inside claimed area

### ISSUE THREAD

**Issue by kaal-1** [MinecraftPortCentral/GriefPrevention#428]
I'm using GriefPrevention with the SkyClaims plugin for spongeforge in a modded skyblock server, and I can't figure out why, but when I try to spawn a wither inside an island (claimed area with GP), the soul sand and skull simply disappear and nothing happens. Nothing is shown in the console either.

When I spawn it in the end or the nether (outside claimed areas) it spawns normally.

I looked in the wiki and couldn't find any option or flag to disable wither spawning, did I miss something?

**Comment by bloodmc** [comment]
You need to spawn the versions you are using. Paste your fml-server-latest.log file

**Comment by bloodmc** [comment]
Reopen when you provide proper information.
