### ISSUE TITLE
Water flows into claims and breaks grass

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#43]
Hi,
in 12.7.1, water can flow into claims and break grass (maybe other stuff too)

**Comment by bloodmc** [comment]
@i9hdkill This is due to a change I made in Sponge. I'll be pushing a fix shortly.

**Comment by bloodmc** [comment]
@i9hdkill update to SpongeForge 1301 to fix the issue.

**Comment by bloodmc** [comment]
Reopening as it seems I broke this recently. Will fix soon.

**Comment by i9hdkill** [comment]
Alright, thank you!

**Comment by bloodmc** [comment]
@i9hdkill Can you confirm this is fixed in latest build?

**Comment by i9hdkill** [comment]
Yes it's fixed, thanks. However the block directly near the claimborder is not updated anymore.
For example when you place a water sourceblock 2 blocks away from the border and it flows towrds the claim and you replace the source block with a block, the remaining half flowingwater block stays there.

**Comment by ghacproductions** [comment]
We made a video to demonstrate it.
Thank you for your work!
https://www.youtube.com/watch?v=GkmXuZfovrI&feature=youtu.be

**Comment by bloodmc** [comment]
Thanks, I'll keep this open until I fix this issue. It seems the blockstate of the water block still thinks its flowing when stopped by the claim border causing the logic not to run.

**Comment by bloodmc** [comment]
@i9hdkill @ghacproductions please confirm issue has been fixed.

**Comment by ghacproductions** [comment]
@bloodmc It's fixed, thank you.

**Comment by ghacproductions** [comment]
Sadly I found an other issue with water, the water is not disappearing correctly.
Again a video here:
https://www.youtube.com/watch?v=oZ1cFEic1jA&feature=youtu.be
