### ISSUE TITLE
Some Flags are not working well

### ISSUE THREAD

**Issue by runescapejon** [MinecraftPortCentral/GriefPrevention#434]
okay 
![693e6c762ba43219771d6095ca25c41c](https://user-images.githubusercontent.com/10858509/29089598-be33c6a6-7c4a-11e7-8178-dba577b6a7e7.png)
using `/cf interact-block-secondary extrautils2:creativechest false override` there a bypass by holding an vanilla block (Might be other blocks as well unsure) to bypass it
**how to reproduce the problem**
1) setup a server with GP version 1.10.2-4.0.0.328 and luckperms and install ExtraUtils mod
2) use the cmd `/cf interact-block-secondary extrautils2:creativechest false override`
3) make sure you don't have permisssion to interact with it holding nothing if you can you might want to relog it sometimes help with the luckperms weird bug or make sure you remove the perms too but yea once you can't right click it holding nothing 
4) then you can hold an stone or grass something in your hand and then you can interact with it

**Comment by bloodmc** [comment]
This was fixed in latest build, update.
