### ISSUE TITLE
Issue with /cf entity-spawn override

### ISSUE THREAD

**Issue by joserobjr** [MinecraftPortCentral/GriefPrevention#438]
I've disabled the spawn of immersiveengineering:chemthrowershot because it was damaging protected entities.

To disable I executed this command while I was in the Wilderness:
'/cf entity-spawn minecraft:player immersiveengineering:chemthrowershot false override "Item blocked: Damage protected entities"`

If I try to use the chemical thrower in the wilderness, it waste the fuel but the projectiles aren't spawned. 
No denial message is shown.

The way it works in the Wilderness is fine, however, when I get inside a claim and use the chemical thrower, the item works as if it wasn't blocked. The entity-spawn flag ignores the override.

Here is a `/lp verbose record` when I try to use it in the Wildernes:
https://gist.github.com/anonymous/574770ef00afe8f19b490a533a897c5a
`local:defaults/default - griefprevention.flag.entity-spawn.immersiveengineering.chemthrowershot.source.minecraft.player - FALSE`

And when I try to use it inside a claim:
https://gist.github.com/anonymous/0a042fb9601ce57228d495580557fef5
`local:defaults/default - griefprevention.flag.entity-spawn.immersiveengineering.chemthrowershot.source.minecraft.player - UNDEFINED`

**Comment by joserobjr** [comment]
I've got more information about it.

I managed to disable the chemthrowershot spawn by executing the command inside of every claim type.

For some reason this override flag isn't being applied automatically to all claim types as documented.

**Comment by bloodmc** [comment]
@joserobjr This would only happen if there was no user tracking on the spawn. Possible issue with tracking the mod or a bug in Sponge.

**Comment by bloodmc** [comment]
This issue no longer occurs in latest GP.
