### ISSUE TITLE
Extra utils mod being able open screen for few seconds

### ISSUE THREAD

**Issue by Tony103** [MinecraftPortCentral/GriefPrevention#442]
https://gist.github.com/anonymous/e66839ed7e5e7edba3604a756d1e0e73
i don't know if that debugging going to help but it's worth a try
so basically i did 

`/cf interact-block-secondary extrautils2:screen false`
and
`/cf interact-item-secondary extrautils2:screen false`
and they can interact with it for a few seconds and if the server lag they can interact with it even longer
weird bug but hopefully get's fix soon
- thanks

**Comment by Tony103** [comment]
i did /cf interact-item-secondary cfm:item_package override "banned" and /cf interact-block-secondary cfm:item_package override "banned"  it works and all but one problem player can still interact with it all they have to do is keep spamming it and they can interact with it 
spongeforge-1.10.2-2281-5.2.0-BETA-2569
griefprevention-1.10.2-4.0.0.354
https://gist.github.com/0756e5cc3ada728956cbcd6bd7587d02
as you can see it's cancelled but the mod it being buggy and forcing it to be open
the item it's package from MrCrayFish  Furniture Mod
and same with item called Envelope
all you have to do it keep spamming it and you'll be able to open it

**Comment by bloodmc** [comment]
@Tony103 I am unable to reproduce issues with envelope and package using SF/GP/LP and CFM. Please test using ONLY SF/GP/LP/CFM on fresh server. Make sure you are running latest 1.10.2 builds in all.

**Comment by Tony103** [comment]
weird i cannot do it only with those SF/GP/LP/CFM on a fresh testing server but i can with my main server
