### ISSUE TITLE
negative claim balance

### ISSUE THREAD

**Issue by rdalkire** [MinecraftPortCentral/GriefPrevention#443]
I have a confounded and understandably frustrated user who has been playing on my server (found in technicpack as [ape42 world 8](https://www.technicpack.net/modpack/ape42-world-8.1062008)) since I started it more than a month ago. They had made some claims, and were ready to expand but found this glitch which prevents them. They sent me a screenshot which I cropped for the relevant part, the chat window, in which you can see the user is JollyP1rate, and when they try to use the shovel they now get "You may claim up to -13.87 more chunks. (-908782 blocks)..."
[preview](https://www.dropbox.com/s/gwx1ur34komovm9/negative_claim_bal.png?dl=0) 

I have zipped up the server's files which amount to about 212 MB, compressed: [download zip](https://www.dropbox.com/s/o0fuufjfv8c3kuh/wrld08.2017-08-15.zip?dl=1)

If it helps, from the logs included in the zip above, you can see "UUID of player JollyP1rate is fe84f778-b706-4513-b584-dce5581eff09"
EDIT:  Here I just used playerinfo; here's what I get:

[01:08:59] [Server thread/INFO]: --------------------- Player Info ---------------------
[01:08:59] [Server thread/INFO]: UUID : fe84f778-b706-4513-b584-dce5581eff09
World : world
Claim Size Limits : 5000,255,5000
Initial Blocks : 25600
Accrued Blocks : 110610 (30720 per hour)
Max Accrued Blocks : 20480000
Bonus Blocks : 0
Remaining Blocks : -895982
Abandoned Return Ratio : 1.0
Total Blocks : 136210
Total Claimable Chunks : -13.67
Total Claims : 1
[01:08:59] [Server thread/INFO]: ------------------------ « » -------------------------

Also you can see that I'm using, among other things: 
- spongeforge-1.11.2-2393-6.1.0-BETA-2559.jar
- griefprevention-1.11.2-4.1.0.340.jar

Please let me know if there's any other information I can provide to help you troubleshoot the issue.

Also in the meantime if you have a really specific workaround to suggest, I'd appreciate it.

Thanks,
rdalkire (IGN goatsbuster)

**Comment by bloodmc** [comment]
Did you read the changelog and enable migration for playerdata?

**Comment by rdalkire** [comment]
Yes I read the (changelog in its sponge files page)[http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/1.11.2-4.1.0.340/griefprevention-1.11.2-4.1.0.340-changelog.txt], linked from [the ore release page](https://ore.spongepowered.org/blood/GriefPrevention/versions/1.11.2-4.1.0.340).  Here I'll copy what seems to be the relevant text for this build:

Build 340:
	bloodshot:
		* Fix child claims not saving. Fixes #427
		* Fix child claims being added twice to parents.
		* Fix some more issues with subdivision ownership.
...

I see a summary list of changes, not any special instructions for server-runner.  Would you mind copying/ linking any such instructions here?  Also will it still work to run the migration after a few hours of play, or will I need to restore to backup first?

Thanks!

**Comment by bloodmc** [comment]
I updated the main page of wiki with instructions.

**Comment by rdalkire** [comment]
I enabled migration and after restart, the players' remaining block-counts are now positive.  I think the lesson learned for me is, when you're reading changelogs it pays to scroll.  Thanks
