### ISSUE TITLE
extend-into-ground-distance not work in creating claims(Ver 4.0.0.349)

### ISSUE THREAD

**Issue by Tollainmear** [MinecraftPortCentral/GriefPrevention#444]
Thx for the GriefPrevention update,but i found something went worng when i create a new claim,
i've tested GP with the Latest version(4.0.0.349) on spongeapi5.1.0(Minecraft1.10.2),And i found Claim Manager always ignor the configuration '**extend-into-ground-distance**' in the globle.conf when creating a new claim, it just return the lesserBoundary with the Y axis where the last shovel location is,so  i try to find out the promblem：Why The '**extend-into-ground-distance**' Not Work?

Im not good at programming ,So im nor sure is the promble caused in line 9th:

 
```
1            if (!cuboid) {
2               y = lastShovelLocation.getBlockY() - activeConfig.getConfig().claim.extendIntoGroundDistance;
3                if (y > 0) {
4                    cuboid = true;
5                }
6            }
7            Vector3i lesserBoundary = new Vector3i(
8                    lastShovelLocation.getBlockX(),
9                    cuboid ? lastShovelLocation.getBlockY() : 0,
0                    lastShovelLocation.getBlockZ());
1            Vector3i greaterBoundary = new Vector3i(
2                    location.getBlockX(),
3                    playerData.getCuboidMode() ? location.getBlockY() : player.getWorld().getDimension().getBuildHeight() - 1,
4                    location.getBlockZ());
5            // try to create a new claim
```

is there should to be ：
`cuboid ?lastShovelLocation.getBlockY() - activeConfig.getConfig().claim.extendIntoGroundDistance : 0,`

By the way ： i'd like the claimming block counting method(100*100) before Gp change to chanks  counting(35.0 more chanks.(2294000blocks))

Im not good at English,Have a good day!
; )

**Comment by bloodmc** [comment]
2D claims are always 0-255 now. If you want to create a claim between bedrock and sky, you must enter 3D cuboid mode with /cuboid. The 'extendIntoGroundDistance' only remains for migration reasons.

**Comment by bloodmc** [comment]
Let me know if you need a command to easily extend 3d cuboid claims into the ground. So I can probably have something like /claimextend 5 which would extend it 5 blocks down.

**Comment by bloodmc** [comment]
I'll keep this opened until you have tested.

**Comment by Tollainmear** [comment]
maybe i have send the wrong intention,i mean when the player start claiming a new area (with cuboid mode off by default) ,the plugin should get the value in "extend-into-ground-distance",but in this mode(in default mode),claiming manager won't care the"extend-into-ground-distance"from configuration file,so,i just set the extend value to 30,the plugin will create a claim only extend to sky(256)but extend lower to bedrock with "30".

i know that cuboid mode will just define a cube area with goldshovel(by twice right click,and without extend),but i want to say what happened in default mode,it wont extend to lower even 1 more block,even i set extend value to 30.

**Comment by bloodmc** [comment]
@Tollainmear Right, as I just said this is no longer used in 4.0.0+ with 2D claims (default). 2D claims can ONLY be bedrock to sky now. If you want a specific area then you MUST use /cuboid mode.

**Comment by Tollainmear** [comment]
by the way Thx for reply

**Comment by Tollainmear** [comment]
oh....why not,its convenient for player who would dig other's claim under 13 level,But then he would be blocked by other's useless claim.....

**Comment by bloodmc** [comment]
Remember, there are 2 types of claim modes (2D and 3D). 2D is the default which always claims from bedrock to sky and 3D claims whatever you select. If you dont want anyone under a person's claim then use 2D which will auto extend to bedrock always.

**Comment by bloodmc** [comment]
For further discussion, check our discord https://discord.gg/jy4FQDz

**Comment by Tollainmear** [comment]
anyway,the smarter function will be cut with the extend function was abandoned,and then,claimming method is going unflexible.
but its really useful for some survival server before the extend function was cut.

**Comment by bloodmc** [comment]
Its not unflexible at all, have your users get used to /cuboid and they can construct whatever claims they want.
