### ISSUE TITLE
Foxguard integration

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#45]
Hi,
from far as I know, worldguard is no longer being developed for sponge so I was looking for an alternative.
We were using both, worldguard and griefprevention before on 1.7.

Now we moved to Foxguard and I was wondering if there is the possibility to check if there is a FoxGuard region before creating a claim and deny claiming if a region is found at that place. 
(Like the worldguard integration in Griefprevention)
https://github.com/FoxDenStudio/FoxGuard

**Comment by bloodmc** [comment]
@i9hdkill Sure I could add support for this.

**Comment by bloodmc** [comment]
@i9hdkill Latest build provides a brand new flag system which is better than Worldguard's.

**Comment by bloodmc** [comment]
Oops, hit close by accident. Leaving this ticket open until I can add support for foxguard.

**Comment by i9hdkill** [comment]
Great, it's likely that we don't need Foxguard anymore with these GP changes. We will see if we pick up developing and building our server.

**Comment by bloodmc** [comment]
Closing as Foxguard still has no API to hook into.
