### ISSUE TITLE
/cf barely works.....

### ISSUE THREAD

**Issue by codydbgt** [MinecraftPortCentral/GriefPrevention#453]
/cf interact-block-secondary minecraft:crafting_table true override is the command i typed

output: 
https://i.gyazo.com/9ab6d2e8e1c7190f956387e49374365d.png

and this still will not allow players to use a table in a admin claim 

you should consider testing this command more

**Comment by bloodmc** [comment]
I'll leave this ticket open until I fix output of command to be more clear.

**Comment by codydbgt** [comment]
i just downloaded the latest files for every thing lp works fine and other people are complaining about this command i was just stating the obvious and i love to test

**Comment by bloodmc** [comment]
No problem. I'll push a fix soon so it shows output properly.
