### ISSUE TITLE
Grief if block-place = true

### ISSUE THREAD

**Issue by iLefty** [MinecraftPortCentral/GriefPrevention#456]
Everyone can open any container, if in the region there is a block-place = true.
https://youtu.be/BCCObf-9GNc

Logs:
http://tinyurl.com/y9tpwrc9
https://git.io/v5T2J

**Comment by iLefty** [comment]
Of course, this is not the latest versions, but installing the latter, nothing has changed.

**Comment by bloodmc** [comment]
Unable to reproduce with latest builds.
