### ISSUE TITLE
Surface explosions 

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#46]
# Whether players can detonate explosives above sea level.
        # 
        surface-explosions=false

Explosions above sea level still happen (tested on extreme hills)

**Comment by bloodmc** [comment]
@SnowBlitzz OK I'll fix this soon.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
