### ISSUE TITLE
The plugin incorrectly counts the size of cuboid

### ISSUE THREAD

**Issue by Zimon4eR** [MinecraftPortCentral/GriefPrevention#462]
If select highest point of region with shovel when creating admin/3d region first, and lowest second - plugin count rg size wrong..
if lowest first - all works fine.
Steps to reproduce:
1. Create 10x5x10 cuboid.
2. Make selection 3d via /cuboid
3. Select via shovel highest point and then lowest of the cuboid.

Here i've selected cuboid 15x6x20 and got error :/
http://i.imgur.com/kaydvm2.png

**Comment by bloodmc** [comment]
Thanks, this will be fixed in next update.
