### ISSUE TITLE
Bug with stick

### ISSUE THREAD

**Issue by iLefty** [MinecraftPortCentral/GriefPrevention#470]
Hi! I found new bug/grief. Now with stick. 
https://youtu.be/kl5RZl63TLI

https://gist.github.com/anonymous/2f91c516f284fcf003c80b7641f5e35c
https://gist.github.com/anonymous/1fffa9f07d8e3ea589a49549377715e7

For that small period of time, when the chest opens, with the help of InvTveaks you can pull out all items.

**Comment by bloodmc** [comment]
Does this only happen with stick? I'm unable to reproduce this on my end.

**Comment by iLefty** [comment]
earlier it was with roasted meat, but after updating it was fixed. Now I noticed only a stick, maybe something else is capable.

**Comment by bloodmc** [comment]
I can't reproduce this with latest build. Sounds like network issues.

**Comment by ryantheleach** [comment]
Is Inventory Tweaks installed on the server? if so this might be a SpongeCommon or Inventory Tweaks bug.

**Comment by iLefty** [comment]
InventoryTweaks instaleed in minecraft client, not on server.
