### ISSUE TITLE
rftools screen protection

### ISSUE THREAD

**Issue by Magi1053** [MinecraftPortCentral/GriefPrevention#472]
The Screen tile entity from RF Tools doesn't respect claims. When I right click on any button on the screen, I get the message in chat `You don't have permission to interact with the block rftools:screen.`but it didn't prevent the interaction, the button still got pressed.

**Comment by bloodmc** [comment]
Because some mods open it client side and ignore server. GP sends a close screen packet to workaround this issue. Log a ticket with the mod if that isn't good enough.
