### ISSUE TITLE
Command /claim does nothing when using WorldEdit 6.1.8 / GP for 1.12.1

### ISSUE THREAD

**Issue by Dockter** [MinecraftPortCentral/GriefPrevention#474]
Hello,

Versions:  
* Forge: 1.12.1-14.22.1.2481
* Sponge: 1.12.1-2480-7.0.0-Beta-2640
* GP: 1.12.1-4.2.0.418
* WorldEdit (Forge): 1.12-6.1.8

Issue:  

Proceeded to create an area using //pos1 and //pos2, typed /claim, nothing happened, no stacktrace server or client side.

Please advise.

**Comment by bloodmc** [comment]
You are using an outdated build of WorldEdit. Try latest http://builds.enginehub.org/job/worldedit and see how it works.

**Comment by mcsnetworks** [comment]
blood, I updated to worldedit-forge-mc1.12.1-6.1.9-SNAPSHOT-dist, no change.  /claim still does nothing, no feedback at client or server.

**Comment by Dockter** [comment]
This seems to be working in the latest version I tested which is:  *450.
