### ISSUE TITLE
Negative claim blocks

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#48]
People can make more claims than they should and expand their claims forever, their claim blocks will just be negative

**Comment by i9hdkill** [comment]
same issue

**Comment by SnowBlitzz** [comment]
I'm unable to reproduce it however. It just seems to only work for certain players which is weird. I am still unsure

**Comment by bloodmc** [comment]
@SnowBlitzz @i9hdkill I will need a test world with GP and player data that can reproduce this issue. Zip up a test case for me so I can resolve the issue.
