### ISSUE TITLE
Issue preventing Mekanism (Digital Miner) from functioning?

### ISSUE THREAD

**Issue by Lytearro** [MinecraftPortCentral/GriefPrevention#481]
Grief Prevention is preventing Digital Miner via Mekanism from mining blocks anywhere when placed by non OP'd player. Version of Mekanism doesn't matter as it's a consistent issue across multiple versions.  Does not innately allow use of miner, or there is no clear way to specific allow just the Digital Miner to work. 

Placing miner as regular non-OP player, it doesn't work, but uses energy as if mining blocks, the blocks just don't break. Placing as OP player, any sequential player can edit filter, stop, and start the Digital Miner, and it will still pick up blocks. The person who crafts the item does not matter, only who places it. 

Claim/Unclaimed doesn't seem to be a factor, even in Aroma mining world, this issue persists.

Referencing to previous issue in Mekanism git that explains why it fails in prevention plugins. https://github.com/aidancbrady/Mekanism/issues/3029 if this is the same issue in here, I hope there is a fix for it that I can use to implement on a multiplayer server.

**Comment by xAlicatt** [comment]
I'm not sure what you all did to fix this, but as soon as I updated Sponge this issue returned.
