### ISSUE TITLE
[API] Claim#removeUserTrust TrustType.NONE does not remove all Trust Types

### ISSUE THREAD

**Issue by Mohron** [MinecraftPortCentral/GriefPrevention#484]
`Claim#removeUserTrust` `TrustType.NONE` does not remove all Trust Types like we previously discussed on Discord.

`Claim#removeUserTrust`
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaim.java#L2112-L2122

Goes to `Claim#getUserTrustList`
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaim.java#L2265-L2276

Which doesn't handle `TrustType.NONE`.

**Comment by SubtypeZero** [comment]
This issue currently makes it impossible to revoke building permissions with SkyClaims via `/is kick`. Currently, the only workaround is to have admins remove players from islands using `/untrust`, since that command is disabled for players.

**Comment by ShadowKitten** [comment]
This is an issue we are having and is rather annoying! A fix for all GP builds would be very helpful.
