### ISSUE TITLE
fire spread does not stop the fire [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [MinecraftPortCentral/GriefPrevention#485]
**Hello!**
I am configuring the fire propagation within my protection, I have used the "/cf" command and changing the **fire-spread: false** but the fire continues to spread.

griefprevention-1.10.2-4.0.1.474.jar
SkyClaims-0.26.0-S5.1-BETA.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2691.jar

![screenshot_5](https://user-images.githubusercontent.com/13698597/31469142-540cb59c-aea6-11e7-9a37-9cec8a24dc19.png)

**Comment by Rasgnarok** [comment]
On a fresh install of GP, running: 
![image](https://user-images.githubusercontent.com/18584380/33520027-d6792896-d780-11e7-83d6-a5d13c6dbf97.png)
1) Create a basic claim
2) Deny `fire-spread` on CLAIM
3) Light up grass/wood -> fire spreads regardless.
![image](https://user-images.githubusercontent.com/18584380/33520040-21ae6d44-d781-11e7-8f02-f107bcf5b838.png)

**Comment by bloodmc** [comment]
Fixed in Sponge.

https://github.com/SpongePowered/SpongeCommon/commit/725494f085ed2ca405b899729bfeaeb5b07682f2
