### ISSUE TITLE
GP / Sponge event exception when teleporting from the end via winning portal block

### ISSUE THREAD

**Issue by Dockter** [MinecraftPortCentral/GriefPrevention#487]
Error:  https://gist.github.com/Dockter/53010c76b791fca9eb3c88285fac0be2

Was generated when I beat the dragon and teleported out.  Once I pressed ESC at the client this error was displayed at the server.

**Comment by Eufranio** [comment]
That doesn't happen for me, with:
```
[GP] Running GriefPrevention 1.10.2-4.0.1.507
[GP] Running SpongeForge 1.10.2-2477-5.2.0-BETA-2731
[GP] Running luckperms 4.0.35
```
Can you update GriefPrevention, SpongeForge and LuckPerms and try again?

**Comment by bloodmc** [comment]
This is no longer an issue in latest SF/GP builds.
