### ISSUE TITLE
[Bug] GriefPrevention Seems to eat command on certain usages of command-execute flag

### ISSUE THREAD

**Issue by MastaC729** [MinecraftPortCentral/GriefPrevention#488]
Version of GriefPrevention: 4.0.1.477
Version of Forge: 12.18.3.2254
Version of Sponge: 5.2.0.2691

Note: I am also running Pokemon Dark 4.2 with some addon mods.

When I tried to create a command-execute claim flag on an admin claim, depending on the command being blocked GriefPrevention will just eat the command with no output of success or fail from both the console and the user's chat window. It worked just fine with Nucleus commands, but not any from Wondertrade or Pixelextras. Any help would be much appreciated. Let me know if you need any additional information.

**Comment by Rasgnarok** [comment]
A fml server latest log would be appreciated, if you can still reproduce this with latest LP, GP and SF.

**Comment by bloodmc** [comment]
This was fixed. Update to latest GP.
