### ISSUE TITLE
Trust Data Reset on Restart?

### ISSUE THREAD

**Issue by Muzixs** [MinecraftPortCentral/GriefPrevention#490]
Server Version: 1.10.2
Sponge: 2477-5.2.0-BETA-2691
GP: 4.0.1.477
Sky Claims: 0.26.0-S5.1-BETA

I have a Sky factory 3 server with various claims and some of those claims have their trusties reset(i think, or not saved) when the server restarts. Theres a slight pattern with the players it effects but have yet to see this a fact. I know Sky Claims hooks into GP's API but as far as I can tell, it does not handle any of the claim data, only reads from it. I'm at a lose and would appreciate any input.

![2017-10-17_2332](https://user-images.githubusercontent.com/1609506/31699947-0e0d0b76-b394-11e7-8a5b-0c38978cfa0e.png)

**Comment by Mohron** [comment]
There may be an undocumented requirement to have the ClaimData saved manually after updating Trusts.

**API Method SkyClaims Uses:**
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/claim/Claim.java#L335-L342

**API Method Implementation**
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaim.java#L2109-L2123

***Trust Command Implementation*
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/command/CommandHelper.java#L959-L1036
**Specifically**
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/command/CommandHelper.java#L1025-L1027
