### ISSUE TITLE
edit sign

### ISSUE THREAD

**Issue by christo666** [MinecraftPortCentral/GriefPrevention#492]
Can anyone please let me know how to deny a group to right-click on a wall_mounted sign? I'm trying to avoid players to edit signs on the "COMMANDS" area on the server Spawn.
I've tried with no success with flags like interact-block-secondary on minecraft:wall_sign.

My server is using:
forge-1.10.2-12.18.3.2477
spongeforge-1.10.2-2477-5.2.0-BETA-2698
griefprevention-1.10.2-4.0.1.481
LuckPerms-Sponge-3.4.38

Thanks!

**Comment by KasperFranz** [comment]
Can you for future reference describe what you did to fix it @christo666 ?
