### ISSUE TITLE
Players can still deal damage to other players with ModernWarfareMod weapons

### ISSUE THREAD

**Issue by prodkid** [MinecraftPortCentral/GriefPrevention#493]
Using GP 4.3.0.480 and MW Mod 1.11.4 BETA mc1.11.2

Players can use weapons to damage other players in pvp safezone

**Comment by hunter688** [comment]
I think its due mod missing projectiles owner (player) like vanilla arrows.

**Comment by Rasgnarok** [comment]
Provide a full fml server latest, a LP verbose output and update your versions, before letting us know this is still an issue.
