### ISSUE TITLE
Cannot load on Sponge 1.12.1

### ISSUE THREAD

**Issue by Denyol** [MinecraftPortCentral/GriefPrevention#494]
Start log: https://hastebin.com/nanawaniye.sql

GriefPrevention version 4.3.0 doesn't start on a sponge vanilla instilation running out of an IntelliJ run configuration.

**Comment by bloodmc** [comment]
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/EventContextKey

You need to use LATEST SpongeVanilla for 1.12.2
