### ISSUE TITLE
flags for pixemon

### ISSUE THREAD

**Issue by afghan007** [MinecraftPortCentral/GriefPrevention#499]
Hello i need help pls help me im a server owner im useing GriefPrevention for my server i claimed the spawn players can't battle npc trainers and can't battle wild pokemon at spawn claim
used difrent flags didn't worked pls help me

**Comment by KasperFranz** [comment]
have you checked this guide: https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Pixelmon

**Comment by bloodmc** [comment]
As KasperFranz stated, read the wiki.
