### ISSUE TITLE
deleteclaim and transferclaim not working

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#50]
both /deleclaim and /transferclaim commands (there might be more that I don't know of) give "Error occurred while executing command: null" but if i keep walking around the claim and spam the command it will work suddenly

**Comment by bloodmc** [comment]
@SnowBlitzz I wasn't able to find any issues with /deleteclaim but I did fix /transferclaim.

**Comment by SnowBlitzz** [comment]
I was just standing on another player's claim and did /deleteclaim, for some reason sometimes it works and sometimes it doesn't. I've had cases wherein another player claimed a part of their house so they requested me to remove it, and sometimes I get "Error occurred while executing command: null" and othertimes it runs successfully. Strange behavior
