### ISSUE TITLE
The End portal does not work [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [MinecraftPortCentral/GriefPrevention#503]
Hello, I have a portal to the end in the spawn of the server, that area is protected as Administrator, but users can not enter the portal, they are not teleported.
The Nether portal works normally for all users and is in the same protection.
The "portal-use" flag is activated

LuckPerms-Sponge-3.4.20
SkyClaims-0.26.0-S5.1-BETA
spongeforge-1.10.2-2477-5.2.0-BETA-2698
griefprevention-1.10.2-4.0.1.474

**Comment by Rasgnarok** [comment]
We cannot be sure this is a bug until you test on latest versions and provide a LP verbose output showing your permissions and flags were done correctly. Update your LP and GP, and run a verbose test.

**Comment by bloodmc** [comment]
@HeberonYT Please provide exact steps on how to test this. So list what claims to create and what flags to set so I can reproduce.

**Comment by MJRLegends** [comment]
You need to allow collide-block for the end portal to work @HeberonYT

**Comment by bloodmc** [comment]
Unable to reproduce with clean setup. Use /gpdebug to troubleshoot what is causing the issue.

**Comment by HeberonYT** [comment]
@MJRLegens Thank you very much, it was just that. It would be a good idea to place that info somewhere because I never found it during the entire time I searched for it.
