### ISSUE TITLE
Dupe issue with GriefPrevention

### ISSUE THREAD

**Issue by runescapejon** [MinecraftPortCentral/GriefPrevention#504]
Hello! 
Here are the version i am currently on
griefprevention-1.12.1-4.3.0.483.jar
spongeforge-1.12.2-2503-7.0.0-BETA-2711
forge-1.12.2-14.23.0.2515

here is how the Dupe glitch works
you will need 2 people for this
1 person make a claim
then place a block near the claim that you want to dupe with example place a diamond block on the border of your claim
the second person that not trusted in your claim place down Block breaker from
Industrial Foregoing mod and power it if you don't know how it works then it would be easier to use Extra Utilities 2 Creative Energy Source block next the block breaker and it start duping check inside of the block breaker and you will get dupe items
here a GIF on how to do this

https://gyazo.com/a5a1e344f77af9484b5c579155908d48
as you he place a block breaker next to my diamond block and it start to dupe
you can use any source of power to power block breaker i just use Creative energy source because it was faster to show you

**Comment by bloodmc** [comment]
All GP does is cancel events, this is a SpongeForge issue. Create a ticket there.

**Comment by JoeSGT** [comment]
@bloodmc it seem SpongeForge said basically said it's the mod issue
and it's been reported but he is unable to fix it 
can you see if you can do anything?
here is the ticket of the information on what he said 
https://github.com/Buuz135/Industrial-Foregoing/issues/87
