### ISSUE TITLE
Trust command does not work [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [MinecraftPortCentral/GriefPrevention#507]
The command /untrust <player> is not allowed to use it.
I have Administrator and User permission and even then it is not possible to remove a player from the list.
The message that appears is the following:
![screenshot_3](https://user-images.githubusercontent.com/13698597/32401825-8db1ac2e-c0dc-11e7-911c-2ef0b8574b0b.png)

![screenshot_4](https://user-images.githubusercontent.com/13698597/32401846-32a8410c-c0dd-11e7-97ec-b195857eea6d.png)

griefprevention-1.10.2-4.0.1.474.jar
LuckPerms-Sponge-3.4.20.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2698.jar
SkyClaims-0.26.0-S5.1-BETA.jar

**Comment by bloodmc** [comment]
SkyClaims blocks it, not as GP issue.
