### ISSUE TITLE
What is the exact command to set the starting claim blocks?

### ISSUE THREAD

**Issue by SweggyDucks** [MinecraftPortCentral/GriefPrevention#508]
I am trying to set the starting claim blocks of my server to 500. A day or two ago you referenced me to this: https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Options , which shows me the permission, but where do I input the value for the permission? (so like could you for example show me the permission you would type to make starting claim blocks 500).

**Comment by bloodmc** [comment]
It is at bottom of options page.

```
/lp user/group <user|group> meta set <option> <value> [server] [world]
```
