### ISSUE TITLE
Setting up any type of trust for groups causes a null pointer exception

### ISSUE THREAD

**Issue by FireflyHM** [MinecraftPortCentral/GriefPrevention#514]
Sponge Vanilla 1.12.2-7.0.0-BETA-351
LuckPerms 3.4.54
GriefPrevention 1.12.1-4.3.0.483
Nucleus 1.2.0-PR3-S7.0-MC1.12.2

When I try to set up trust of any type to users, gp works as intended.
When I try to set up trust of any type to groups, gp throws a null pointer exception.

[stacktrace](https://gist.github.com/FireflyHM/0351cc4f2d24b1de00f4fc97ca056581)

**Comment by Rasgnarok** [comment]
To be sure that this is not a simple fix, please update to the latest LP (4.0.4) and SV (352).

**Comment by FireflyHM** [comment]
Updated to LP 4.0.4, SV 352. Problem persist.

[stacktrace](https://gist.github.com/FireflyHM/250a8c199dd70ea4f787b2af97b47ebc)
