### ISSUE TITLE
[Suggestion] Hide coordinates on /claimlist <player>

### ISSUE THREAD

**Issue by xion87** [MinecraftPortCentral/GriefPrevention#516]
In my server i got some players that being anoyed if somesone know where their claim are, many have request to hide the coordinates on /claimlist <player> or just show it to people that have permission. Is possible? thank you.

**Comment by bloodmc** [comment]
Users should only see claims they are trusted to. If you don't want them seeing the claim then remove the trust. Make sure you are running latest GP/SF/LP as well.
