### ISSUE TITLE
Disable crop trampling

### ISSUE THREAD

**Issue by NeumimTo** [MinecraftPortCentral/GriefPrevention#525]
There seems to be no flag which could be used when an entity or a player jumps & lands on a crop-block, by default the crop block will be destroyed and block beneath the crop will become dirt block.

Old GP for bukkit seems to had this feature https://github.com/MinecraftPortCentral/GriefPrevention/search?q=crop+trampling&type=Commits&utf8=%E2%9C%93 

GP debug only shows the standart block-break flag 
https://gist.github.com/anonymous/079750c1d35709cfcdae2ceae0f8f929

**Comment by bloodmc** [comment]
Create a ticket requesting context for this in Sponge as it doesn't exist so it's impossible to include in GP until that happens.
