### ISSUE TITLE
Could not pass ClientConnectionEvent$Disconnect$Impl... 

### ISSUE THREAD

**Issue by ziceptor** [MinecraftPortCentral/GriefPrevention#526]
On stopping server https://gist.github.com/ziceptor/27e0996191bdcfc78ad2dc5cf62059fb

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2742.jar
griefprevention-1.12.1-4.3.0.503.jar
LuckPerms-Sponge-4.0.16.jar

**Comment by Eufranio** [comment]
This doesn't seem to be an GriefPrevention error, looks like WorldEdit is at fault here.

**Comment by ziceptor** [comment]
I don't remember what led to this error. It was only once.
