### ISSUE TITLE
3D first claim limit

### ISSUE THREAD

**Issue by Horusor** [MinecraftPortCentral/GriefPrevention#527]
Hi ! You can see this issue [on Sponge forum](https://forums.spongepowered.org/t/griefprevention-official-thread-1-10-1-11-1-12-town-wecui-support/1123/1328?u=encu_lator)

**Comment by Rasgnarok** [comment]
You have outdated plugins, and something already isn't right if you have negative claim blocks. Please first submit information concerning your issue and update, otherwise we cannot help.

**Comment by Horusor** [comment]
I updated. I use now the last 1.10.2 version : griefprevention-1.10.2-4.0.1.507
And the issue is the same : I'm not stuck when I enlarge a cuboid claim. The plugin write I have a negative block account insted of blocking me. It does (blocking) in basic 2D mode.

**Comment by Horusor** [comment]
I use last versions for plugins of the day...
Last Grief Prevention : griefprevention-1.10.2-4.0.1.507
Last Sponge for 1.10.2 : spongeforge-1.10.2-2477-5.2.0-BETA-2777
Last LuckPermsSponge : LuckPerms-Sponge-4.0.49

Last Project Core/Inventories/Portals/Worlds/

And it is not fixed :'(

**Comment by bloodmc** [comment]
Fixed in GP 688+

https://github.com/MinecraftPortCentral/GriefPrevention/commit/1c2e28f70691c8447ef89d59e1d8b9d736f2c079
