### ISSUE TITLE
2 claim modes for 2 worlds

### ISSUE THREAD

**Issue by Horusor** [MinecraftPortCentral/GriefPrevention#528]
Hi !

You can see this issue [on Sponge forum](https://forums.spongepowered.org/t/griefprevention-official-thread-1-10-1-11-1-12-town-wecui-support/1123/1335?u=encu_lator).

**Comment by Rasgnarok** [comment]
This is an incomplete ticket. Please provide versions as well as logs/steps so we can reproduce this issue. It is also outdated, so please update LP/Sponge/GP to latest before testing again.

**Comment by bloodmc** [comment]
As Rasgnarok stated, you need to include information in the ticket. Do NOT link to another thread.
