### ISSUE TITLE
disabling griefprevention on specific worlds doesn't work

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#53]
Using
claims-mode=0
config-enabled=true
in a Griefprevention/worlds/overworld/mine/world.conf
Using Griefprevention built from source today.

You can still claim areas.

**Comment by bloodmc** [comment]
@i9hdkill Did you restart the server after making the change? I haven't added a proper reload yet.

**Comment by i9hdkill** [comment]
Sry, I just looked for the setting that I knew from bukkit. Didn't kknow that there is another one.

Claims are disabled now, but I think some of your functions are tied to your own, now removed setting.
http://pastebin.com/ARcP8Wwy
Getting this errors only when I am on a world with claims-mode=0

**Comment by bloodmc** [comment]
@i9hdkill Please test latest commit and let me know if it fixes this issue.

**Comment by i9hdkill** [comment]
Thanks, works!
