### ISSUE TITLE
The block-break flag on an admin claim does not work [Minecraft 1.12.2_SpongeForge]

### ISSUE THREAD

**Issue by SeanOMik** [MinecraftPortCentral/GriefPrevention#532]
I made an admin claim to protect my servers spawn and applied the block-break flag to claim and set it to false. How ever, other players can break blocks in the claim. I'm using Luckperms as my permission manager. I've probably spent like 2-3 hours on this, so any help would be appreciated.

**Comment by Rasgnarok** [comment]
Please provide more relevant information, such as version numbers (for LP, GP, Forge, Sponge). Your `fml-junk` log would also serve greatly here. Lastly, a `/gpdebug` output of the current issue will be necessary.

**Comment by bloodmc** [comment]
It works fine....You also failed to provide any relevant information. Setup a clean server which will work fine then figure out what you did wrong.
