### ISSUE TITLE
[Sponge 1.12.2] Item pick-up cause error - ChangeInventoryEvent$Pickup

### ISSUE THREAD

**Issue by Krosta8** [MinecraftPortCentral/GriefPrevention#534]
Hello,
I'm getting an error, when someone pick-up something in Wilderness.
Here is a setting of wilderness https://ctrlv.cz/FDL8
And here is an error https://pastebin.com/5CLV4D2z

GriefPrevention 1.12.1-4.3.0.503
SpongeForge 1.12.2-2529-7.0.0-BETA-2746
Luckperms 4.0.25

**Comment by rob5251** [comment]
Probably related to this recent change from SpongForge, just guessing though, I'm no programmer.
https://github.com/SpongePowered/SpongeForge/commit/bb2dc11ec7b7764c7f72d498ebab241a9c4a804f

**Comment by Whazaaaaa** [comment]
Having the same issue. It even goes to the point of kicking people when trying to pickup items.
griefprevention-1.12.1-4.3.0.503
1.12.2-2529-7.0.0-BETA-2746
(Running AllTheMods3)
https://pastebin.com/GNAL7m4h

**Comment by ziceptor** [comment]
+
forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2747.jar
griefprevention-1.12.1-4.3.0.503.jar
LuckPerms-Sponge-4.0.28.jar

**Comment by Yorkforce** [comment]
Also having the same issue
spongeforge-1.12.2-2529-7.0.0-BETA-2746.jar

It kicks players off the server with an Internal Server Error, and prevent them logging back on, bit of a headache tbh.

**Comment by rob5251** [comment]
#536 Should have closed this.

**Comment by rob5251** [comment]
#536 should close this.
