### ISSUE TITLE
coal and pixelmon ores are dropping xp even if you can't break them

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#54]
Using Forge 1902
Griefprevention from today
SpongeForge 1890 Build 1330

Grab a pickaxe, disable /IgnoreClaims and try to break coal-ore. (On an area where you don't have permission to break blocks).
You will get xp. This way you can get unlimited xp. This xp will stay even after a relogg.

Similiar issue with mod Items like Pokechests. Players can infitely click on them, get items out of it and they don't disappear. Seems like Pixelmon gets the click event but pixelmon can't react on it? I don't know.

**Comment by bloodmc** [comment]
@i9hdkill I cannot reproduce this. Remove all plugins except GriefPrevention and see if it still occurs.

**Comment by i9hdkill** [comment]
Reproduced this with a fresh spongeForge setup with just griefprevention and claims set to mode "2"
You need to be in survival gamemode and a pickaxe.

**Comment by bloodmc** [comment]
OK this will involve a bit of work now that I see what mode 2 should be doing. I'll have a fix soon.

**Comment by SnowBlitzz** [comment]
What do you mean by mode 2 btw o.o

**Comment by bloodmc** [comment]
@i9hdkill Turns out this was a SpongeForge bug which I just fixed. However I may need to fine tune mode 2 checks so I'll keep this open for a bit.

**Comment by i9hdkill** [comment]
Thanks, the latest sponge build fixed the dropping exp issue!
Though there are still some issues with mode 2.
Mode 2 doesn't protect chests right now, which is good in my opinion..
However this leads to problems with modded chests like pixelmon lootchests.
The cooldown isn't triggered and the chest does not diseappear.
There are different pokeloot chest modes. 
Mode 1: You are getting an item and the chest disappers if you click it. 
Mode 2: Every player can access it once. 
Mode 3: you can open it infinitely, but you get a cooldown
When griefprevention mode 2 is active, nothing of this happens.
Is there a way to change that on your side or it's a design flaw in pixelmon?

**Comment by bloodmc** [comment]
This issue is now moot as the newest build adds a Wilderness claim to manage flags in.

commit for reference
https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
