### ISSUE TITLE
Override/ban messages are broken

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#540]
Reproducible on a fresh install of GriefPrevention + LuckPerms + SpongeForge. Override/ban messages are broken, they aren't being displayed to the user.

Reproducing:
1. Fresh install of GP. Create an claim, use `/cf block-place minecraft:dirt false override test` and try to place an dirt. The dirt won't be placed and you won't receive any messages.
2. Other flags aren't working with override messages as well.

```
[GP] Running GriefPrevention 1.10.2-4.0.1.507
[GP] Running SpongeForge 1.10.2-2477-5.2.0-BETA-2731
[GP] Running luckperms 4.0.35
```

**Comment by Rasgnarok** [comment]
Seems to be fine on the 1.12.2 branch;
![image](https://user-images.githubusercontent.com/18584380/33519925-b3f59608-d77e-11e7-99c5-80bcb9a1554d.png)

**Comment by bloodmc** [comment]
As confirmed by Rasgnarok. This is a non-issue with master branch.
