### ISSUE TITLE
[Config] Typo in Logging

### ISSUE THREAD

**Issue by Rasgnarok** [MinecraftPortCentral/GriefPrevention#541]
![image](https://user-images.githubusercontent.com/18584380/33520923-335dca7e-d792-11e7-861f-e2a1f6c7e907.png)
Using: 
![image](https://user-images.githubusercontent.com/18584380/33520927-4565b254-d792-11e7-8751-d667b4b183a7.png)

**Comment by bloodmc** [comment]
This was fixed in PR #559
