### ISSUE TITLE
Duplication Dragon egg with Claim's

### ISSUE THREAD

**Issue by JoeSGT** [MinecraftPortCentral/GriefPrevention#542]
My version are 
spongeforge-1.12.2-2555-7.0.0-BETA-2758
LuckPerms-Sponge-4.0.36
griefprevention-1.12.2-4.3.0.505

I have no mods installed just the plugins i listed above

Here how i do it i first get a ender dragon egg (vanilla)
and i make a large claim then go into survival 
place the 1 egg in your claim. Then Left Click it but do not right click it
you most likely have to do that 2 time's then you will see the Egg on top and bottom essentally  2 eggs
within the same location but just 1 on top and 2nd on bottom 

EDIT: also this don't happen without doing it on claims. and i made a fresh test server with all default config

**Comment by bloodmc** [comment]
This is a sponge bug when cancelling interact event. Report it to SpongeCommon.
