### ISSUE TITLE
Hoppers wont feed into chests

### ISSUE THREAD

**Issue by frustrationnn** [MinecraftPortCentral/GriefPrevention#543]
I have tried a thousand combinations of moving hoppers but no matter what I do they will allow items through

**Comment by frustrationnn** [comment]
1.12.2)

**Comment by Rasgnarok** [comment]
There's no information here. What are your flags? Where is your `gpdebug` output? There is no way here to know if it is an issue with your flags, your versions or an actual bug. Give us information and the steps to reproduce it.

**Comment by bloodmc** [comment]
Not enough information.
