### ISSUE TITLE
OpenComputers

### ISSUE THREAD

**Issue by SolaoBajiuik** [MinecraftPortCentral/GriefPrevention#544]
Is there a way to get OpenComputers items.

Robot, Drones, and Transposers

To work properly and not violate the Claims of GriefPrevention?

**Comment by Eufranio** [comment]
Are they bypassing GP?

**Comment by SolaoBajiuik** [comment]
Yes.

**Comment by SolaoBajiuik** [comment]
They do have a FakePlayer configured in the configuration file:

    # The name to use for the global fake player needed for some mod
    # interactions.
    fakePlayerName="[OpenComputers]"

    # The UUID to use for the global fake player needed for some mod
    # interactions.
    fakePlayerUuid="7e506b5d-2ccb-4ac4-a249-5624925b0c67"

**Comment by Eufranio** [comment]
Then report it to SpongeForge, GP is doing what it should.

**Comment by bloodmc** [comment]
Update to latest GP/SF and use source instead of the fakeplayer.
