### ISSUE TITLE
[1.12.2] Flooding error to console for time to time

### ISSUE THREAD

**Issue by LiskoSlayer63** [MinecraftPortCentral/GriefPrevention#546]
The console is flooded by Sponge's crash messages about `java.lang.NoSuchMethodError` caused by GriefPrevention. This isn't crashing the whole server but it's annoying.

**GriefPrevention version:** 4.3.0.470
**SpongeForge version:** 2555-7.0.0-BETA-2764
**Forge version:** 14.23.1.2561
**Minecraft version:** 1.12.2

I uploaded the full crash message [here](https://pastebin.com/vLtaMQfN).

**Comment by Eufranio** [comment]
Update GriefPrevention.
