### ISSUE TITLE
Dupe Glitch with Claim's and there border of it

### ISSUE THREAD

**Issue by JoeSGT** [MinecraftPortCentral/GriefPrevention#547]
Here are my versions
forge-1.12.2-14.23.1.2565
spongeforge-1.12.2-2555-7.0.0-BETA-2774
LuckPerms-Sponge-4.0.47
griefprevention-1.12.2-4.3.0.505

okay here how the dupe glitch work get a friend to make a claim
then make sure you do not have access to the claim
make a wall on the border of there claim
get inside of the claim *(make sure you do not have permission to break/place in the claim)*
and then get a diamond block *( example i want to dupe with)*
then place the diamond block on the border wall you made an boom you duping
the item does not delete out of your hand and it's placing on the wall

i made a GIF to show you it work
https://gyazo.com/7b7c71972eed7ff9944d48a837790eb7

the glowstone is the border of the claim and the stone is the border wall you can make outside of there claim

I did this without no mods just the version's i mention above

**Comment by DumbSlayer** [comment]
OMG IT WORKS Ima Use it on all the servers I know Thx Bud!

**Comment by bloodmc** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1638

This does NOT occur in older 1.12.2 SpongeForge builds. It was broken recently.
