### ISSUE TITLE
[Addon Request] Ability to disable Pumpkin/Glowstown border when using WECUI

### ISSUE THREAD

**Issue by Dockter** [MinecraftPortCentral/GriefPrevention#548]
Hello,

We use WECUI with GP and was wondering if you could add a configuration to disable the Pumpkin/Glowstone border visuals since WECUI serves this purpose.

**Comment by Eufranio** [comment]
@Dockter try using the latest GP build, I added a config option for that.

**Comment by bloodmc** [comment]
Closing as this has been resolved with a config option.
