### ISSUE TITLE
java.util.NoSuchElementException: No value present when interacting with Pixelmon

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#55]
When rightclicking a pokemon, it gives an exception.
World with claimmode 2
Pixelmon 4.2.5
Latest griefprevention built from source
http://pastebin.com/Ai88DJ7W

**Comment by bloodmc** [comment]
@i9hdkill Should entity interaction only be allowed in claims as well?

**Comment by bloodmc** [comment]
Also, your stack trace doesn't line up with latest source. In the stack trace, it complains about an optional on line 1228 but line 1228 in master is the following 

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/event/PlayerEventHandler.java#L1228

Please rebuild your source (wipe out build folder) and test again.

**Comment by i9hdkill** [comment]
Yeah, blocks are enough. Pixelmon/entities should be accessible.
Thanks will try that

**Comment by i9hdkill** [comment]
@bloodmc Sry about that. Now it's definetely a fresh build:
http://pastebin.com/jqgdQutC

**Comment by i9hdkill** [comment]
Just found this:
http://pixelmonmod.com/tracker.php?p=2&t=8498
Error when a pixelmon spawns. I think it's not a bug in griefprevention.
