### ISSUE TITLE
IC2 Explosion

### ISSUE THREAD

**Issue by FilipK-CZ** [MinecraftPortCentral/GriefPrevention#550]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2760
- Forge version: forge-1.12.2-14.23.1.2555-universal
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
- Operating System: Ubuntu 14.04.5 LTS

Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, InstantRespawn, LuckPerms, Nucleus, ProjectCore, ProjectWorlds, SkinsRestorer, Web-API, Web-API API

GriefPrevention don't protect Explosion by Mining Laser near claim (explosion interact with blocks in claim) and Dynamite dropped in claim (or near)

**Comment by Dockter** [comment]
GP doesn't seem to be protecting against explosions in "Wilderness" from creepers either.

**Comment by Dockter** [comment]
I would recommend trying Sponge Build 2797 or newer.  I was having a similar issue and I resolved mine with the newest build.

**Comment by bloodmc** [comment]
Sponge issue, update to latest.
