### ISSUE TITLE
[Sponge 1.12.2] Inventories Vanishing

### ISSUE THREAD

**Issue by kreezxil** [MinecraftPortCentral/GriefPrevention#552]
My players are reporting that the inventories of chests, furnaces, and other tile entities that have inventories are vanishing when they come back to them after the chunk that the inventories were in unload.

I am also getting the following server error about every 15 seconds https://pastebin.com/wBpMtB6c

**Comment by bloodmc** [comment]
1.12.1-4.3.0.470

Using an outdated GP build

Grab latest from 

http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention

**Comment by kreezxil** [comment]
thanks. I had gotten the one I reported from https://ore.spongepowered.org

**Comment by kreezxil** [comment]
that fixed the inventories, thanks again.
