### ISSUE TITLE
[4.3.0.509] Item Frames issues

### ISSUE THREAD

**Issue by kreezxil** [MinecraftPortCentral/GriefPrevention#553]
First you can't place item frames or paintings unless you use /ignoreclaims command, I would've thought that block-place being set to true would allow item_frame and painting placing.

Secondly, when you reboot the server the item_frames and paintings all pop off.

All item frames and paintings outside of the claims stayed where they were placed and did not pop off.

fml-server-latest.log: https://gist.github.com/e19ad22ab479827d7bb01ff977416571

**Comment by bloodmc** [comment]
Item frames are entities NOT blocks. Learn how to use the /gpdebug command which is explained in wiki and test in a CLEAN server with default flags and fresh claims.
