### ISSUE TITLE
The portal-use flag  does not work correctly.

### ISSUE THREAD

**Issue by Mr-Krab** [MinecraftPortCentral/GriefPrevention#554]
This flag only affects the portal to the nether world and only in the private territory.
I would like to block the use of portals by players everywhere except private spawn.

Tested on:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-c9dfe2a
SpongeForge: 1.12.2-2555-7.0.0-BETA-2798
Minecraft Forge: 14.23.1.2555
GriefPrevention 1.12.2-4.3.0.509

I apologize for my english, I used google translator.

**Comment by bloodmc** [comment]
Set the flag in the wilderness using override which will affect all claims. Read wiki for more information.

**Comment by Mr-Krab** [comment]
Can these screenshots convince you? No matter how I changed the parameters of the flag, it did not act properly. As soon as I entered the / accesstrust command in the region all portals became available to the players. The flag only affects the portal to the nether world.

![2018-01-09_14 26 30](https://user-images.githubusercontent.com/29023558/34719846-6bc4dd8e-f54d-11e7-93d8-ab666c4f9361.png)
![2018-01-09_14 26 42](https://user-images.githubusercontent.com/29023558/34719847-6c16897c-f54d-11e7-8c75-8f502bc1d50d.png)
![2018-01-09_14 26 50](https://user-images.githubusercontent.com/29023558/34719848-6c38f00c-f54d-11e7-962e-dce39318d8de.png)
![2018-01-09_14 27 10](https://user-images.githubusercontent.com/29023558/34719850-6c7a12da-f54d-11e7-8b1b-3f272fbbfa2b.png)
![2018-01-09_14 27 20](https://user-images.githubusercontent.com/29023558/34719852-6c9bffd0-f54d-11e7-9769-f2fdc4d2e29d.png)
![2018-01-09_14 27 38](https://user-images.githubusercontent.com/29023558/34719853-6cbf03b8-f54d-11e7-9edc-2b8ed0f83810.png)



![2018-01-09_14 27 04](https://user-images.githubusercontent.com/29023558/34719849-6c597b4c-f54d-11e7-8031-7d5cde4c5be4.png)
