### ISSUE TITLE
Console filled with errors

### ISSUE THREAD

**Issue by zachdoug24** [MinecraftPortCentral/GriefPrevention#555]
**Currently Running**
- Forge-1.10.2-12.18.3.2511
- SpongeForge-1.10.2-2477-5.2.0-BETA-2793
- GriefPrevention-1.10.2-4.0.1.507    
        
         
**Rundown of Issue**
So, I initially thought this was an issue with LuckPerms, but was told otherwise.    
    
I'm running the latest version of Grief Prevention for 1.10.2, and the list of my mods can be seen: 
    
**Full List of Server Mods**
![](https://i.imgur.com/rjrKuVS.png)

    
**Files Appropriate to Case**

`server-latest.log` is https://gist.github.com/zachdoug24/c5cea059a10cdd2b9813b617a7de6171    
    
Since the `fml-server-latest.log` is far too big to upload, here's the file: https://transfer.sh/Nei0/fml-server-latest.log
        
  
What Lucko pointed out that was GriefPrevention related was: https://paste.lucko.me/y7PGLQrugT

**Comment by Dockter** [comment]
Why do you have SpongeAPI jar and a SpongeForge jar?  Also, why do you have two GP jar's?

**Comment by Rutes** [comment]
my console has also recently become filled with errors with the latest sponge - running 1.12.2 with only server-side mods - I'll post a new issue if someone hasn't already

**Comment by bloodmc** [comment]
As Docter stated, you are throwing jars into your mods folder that shouldn't be there. You should only have 1 GP jar and spongeforge jar. The GP API is INCLUDED in GP and its not needed in the mods folder. You also are using UniverseGuard which will conflict with GP. Start with a clean server and add ONLY GP/SF/LP then add mods slowly until you find the culprit.
