### ISSUE TITLE
java.lang.NoSuchMethodError with SpongeForge

### ISSUE THREAD

**Issue by Rutes** [MinecraftPortCentral/GriefPrevention#556]
I recently updated forge and sponge on my 1.12.2 server - running only server-side mods. Now I'm getting some console errors anytime someone picks up a block (so, a lot). This could be a forge or sponge issue (I admit I wouldn't know how to tell), but I wanted to check here first since GriefPrevention is mentioned in the error. The errors are being logged to fml-junk-earlystartup.log.

> [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Pickup$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.1-4.3.0.470, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/opt/minecraft/van/mods/griefprevention-1.12.1-4.3.0.470.jar}
> java.lang.NoSuchMethodError: org.spongepowered.api.event.item.inventory.ChangeInventoryEvent$Pickup.getTargetEntity()Lorg/spongepowered/api/entity/Item;
> 	at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerPickupItem(PlayerEventHandler.java:1564) ~[PlayerEventHandler.class:1.12.1-4.3.0.470]
> 	at org.spongepowered.common.event.listener.PickupListener_PlayerEventHandler_onPlayerPickupItem139.handle(Unknown Source) ~[?:?]
> 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2821]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2821]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2821]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:355) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2821]
> 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:197) [SpongeImpl.class:1.12.2-2555-7.1.0-BETA-2821]
> 	at org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeInventoryPickupEvent(SpongeCommonEventFactory.java:212) [SpongeCommonEventFactory.class:1.12.2-2555-7.1.0-BETA-2821]
> 	at net.minecraft.entity.item.EntityItem.redirect$onAddItemStackToInventory$zfj000(EntityItem.java:774) [acl.class:?]
> 	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:399) [acl.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$zgh000(EntityPlayer.java:3726) [aed.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600) [aed.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571) [aed.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167) [vp.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zif000(NetHandlerPlayServer.java:2029) [pa.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by bloodmc** [comment]
Update to latest GP here
http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention
