### ISSUE TITLE
Could not pass ChangeInventoryEvent$Pickup$Pre$Impl Latest Every thing. ( sponge vanilla )

### ISSUE THREAD

**Issue by RustyDagger** [MinecraftPortCentral/GriefPrevention#557]
Just setting up GP on a new server, Fresh install on just about every thing. 

Running:
spongevanilla-1.12.2-7.1.0-BETA-5
https://image.prntscr.com/image/0vvwAV01TdO4LN33NHjNhw.png

Cause: Picking up or Dropping any item.

Log file: https://pastebin.com/qxwxM6RM

**Comment by KasperFranz** [comment]
As far as I can see it is appening because of this change from @gabizou 
https://github.com/SpongePowered/SpongeCommon/compare/541e9cbb69a06adf27a2e364b6ef9975ad38cae5...7d3a19bf5eadaf65ac2ffd5764b42cdd2418886d#diff-1f64809fa1159cc535d01923f106d01d

**Comment by ryantheleach** [comment]
@KasperFranz No, it's because GP bypasses the API here:

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaim.java#L916

But yeah, same difference.

**Comment by ryantheleach** [comment]
[griefprevention-1.12.2-4.3.1.0.zip](https://github.com/MinecraftPortCentral/GriefPrevention/files/1611685/griefprevention-1.12.2-4.3.1.0.zip)
