### ISSUE TITLE
/claimlist shows the amount of free claimblocks, but not the list of claims

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#56]
See title.
Usually there should be a list with your own claims with coordinates and used claimblocks per claim.

**Comment by SnowBlitzz** [comment]
Yes, this is another strange behavior I've been getting similar to /deleteclaim, sometimes it works and sometimes it doesn't.

Try doing /claimlist on random times. Sometimes you'll see it will list all your claims and sometimes it will just show your amount of blocks. Really odd behavior

**Comment by bloodmc** [comment]
@i9hdkill @SnowBlitzz This will be fixed after I finish up teleport/portal support in Sponge so I can generate claimlist properly.
