### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by RaresKool** [MinecraftPortCentral/GriefPrevention#561]
If one takes a bucket and attempts to pick up a fluid from within a claim in which he is not trusted, the user will be given a bucket filled with that fluid and still be left with his original bucket. This way a user could gain infinite fluids of sorts, and also an infinite amounts of buckets.

**Comment by bloodmc** [comment]
Unable to reproduce with latest SF/LP/GP. Create a new ticket if you can reproduce with a CLEAN environment and make sure to provide actual logs.
