### ISSUE TITLE
Exception thrown which Could not pass InteractBlockEvent$Secondary$MainHand$Impl

### ISSUE THREAD

**Issue by Tollainmear** [MinecraftPortCentral/GriefPrevention#563]
using:
SpongeForge
 Minecraft: 1.10.2
 SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2477-5.2.0-BETA-2637
Minecraft Forge: 12.18.3.2511
griefprevention : v-4.0.1.507

gist about this exceptions is [here](https://gist.github.com/Tollainmear/1f1cfb135b221aa221580e3fd7b1ff8d)

**Comment by Tollainmear** [comment]
sorry to say that the suspect of making server out of memory is not GP (So ignore the previous title)

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/1cf213ec0024b7e5930b688bc874416c7ac306a5
