### ISSUE TITLE
[1.12.2, GP-509] "minecraft:armor_stand" not protected from taking armor

### ISSUE THREAD

**Issue by Zimon4eR** [MinecraftPortCentral/GriefPrevention#565]
Players can take armor from "minecraft:armor_stand" block...

GriefPrevention 1.12.2-4.3.0.509
SpongeForge 1.12.2-2555-7.0.0-BETA-2800
luckperms 4.0.85

**Comment by i9hdkill** [comment]
Make sure you disable interact-entity-secondary for armor_stands + projectile-impact for armor_stands

**Comment by Zimon4eR** [comment]
Why its not disabled by default? And how do I update >100 basic regions with new flags?

**Comment by bloodmc** [comment]
Armor stands are NOT blocks. Entity interaction has never been disabled by default, if you want to change defaults then edit the global config. Read the wiki on how to make use of the override argument with flags. And start using /gpdebug
