### ISSUE TITLE
[1.12.2] Claim blocks not transferring properly

### ISSUE THREAD

**Issue by yepidoodles** [MinecraftPortCentral/GriefPrevention#567]
What happened:

1. Using my normal account, I created an Admin claim.
2. Using my alt, I changed that Admin claim into a Town claim - This seemed to put the claim in that name.
3. I log back in on my normal account after a day, the claim was now back in my name, with my remaining claim blocks at -49k
4. I transferred the claim using /claim transfer to the alt account
5. Claim is now in the alt's name, but claim blocks did not transfer

Changing the claim back to an Admin claim made no difference.

End Result Screenshots:
My player info:
[![Screenshot from Gyazo](https://gyazo.com/d208a70c13698f40cc6bb02b3b08f04f/raw)](https://gyazo.com/d208a70c13698f40cc6bb02b3b08f04f)
My Alt's player info:
[![Screenshot from Gyazo](https://gyazo.com/25efb48cea86899578107548bed7a70c/raw)](https://gyazo.com/25efb48cea86899578107548bed7a70c)
Claim's Info:
[![Screenshot from Gyazo](https://gyazo.com/c9afc7232582a253819da29c9299bb09/raw)](https://gyazo.com/c9afc7232582a253819da29c9299bb09)

**Comment by bloodmc** [comment]
@yepidoodles Please reproduce this issue on a clean server with only GP/LP/SF. List exact steps you took so I can test to confirm.

**Comment by bloodmc** [comment]
Assuming this is no longer an issue in latest builds.
