### ISSUE TITLE
Going thru Nether Portal throws exceptions

### ISSUE THREAD

**Issue by smmmadden** [MinecraftPortCentral/GriefPrevention#568]
I originally thought this was a LuckPerms issue but he's saying it is a GP issue given the repeated exceptions.

https://github.com/lucko/LuckPerms/issues/685

**Comment by bloodmc** [comment]
Unable to reproduce this error on a clean install. Setup a fresh server with ONLY GP/LP/SF and reproduce the error.

**Comment by smmmadden** [comment]
All I have done was to add the GP mod to my Pokecube Revival Server which runs fine without it. When I log in as an admin, I have the griefprevention.admin permission and I'm OP'd on the server.  I've also added all 26 meta's for each option to my UUID in LuckPerms and griefprevention.flag.entity-spawn.minecraft set to true.

**Comment by bloodmc** [comment]
Again, reproduce this on a CLEAN server then slowly add whatever you are testing until it breaks. If you are not willing to put in the time to do proper testing then this issue will be closed.

**Comment by smmmadden** [comment]
that's what I have been doing is "testing".  :-)  I have no problem testing out changes to environments and its the same process I follow for adding any new Mod or Plugin to one of my servers.  You'll never hear me complain about testing.

I've copied a production server back to my test region, added GP and I get exceptions going thru the portal.  

Without GP mod, I can go thru a nether portal and come back without exceptions being thrown.  With GP added, I can still go thru and back, but all the GP exceptions are thrown.  

With that said, I just went on a hunch and tested this again, this time by copying the GP mod back to my client mods folder too.  Now there are no more exceptions.  As I'm fairly new to the Sponge/Forge mod world (been doing Spigot servers for years), how does one figure out when the server mod has to be also on the client?  Some sites say server only, many others say nothing at all.  I was thinking this should be server only given what it does, but guess I'm wrong on that count. :-(  Thanks for your time, I do appreciate it. -Steve

**Comment by bloodmc** [comment]
This is the last time I'm going to say this. Create a clean server with ONLY GP/LP/SF, the issue should NOT occur. Slowly add whatever changes you did on your server until it breaks then list the steps you took to reproduce it.

**Comment by smmmadden** [comment]
there is no need to be nasty or rude here @bloodmc .  I certainly was not and am not being rude, so that is uncalled for.

As I clearly stated in my last post, I resolved the issue by copying the mod to the client mods folder.  If you don't want to answer the question posted, that's fine, I'll just close this myself.  Thanks.
