### ISSUE TITLE
Could not pass ServerChatEvent //at me.ryanhamshire.griefprevention.DataStore.getPlayerData

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#57]
We are using a custom chat plugin.
Sometimes when chatting, we are getting these errors:
http://pastebin.com/EnXEuW5A

and this seems to be random: (Not sure if it's related)
http://pastebin.com/G9zrpEcK
Might be something with delivering claimblocks, but it fails?.

Btw: Thanks for your hard work on Sponge and of course Griefprevention!

**Comment by bloodmc** [comment]
@i9hdkill Please send me your skype info when you get a chance.

**Comment by i9hdkill** [comment]
jonnni239
