### ISSUE TITLE
[API] canBreak/canBuild functions

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#570]
hey,

I always used `GriefPreventionPlugin.instance.allowBreak()` to check if the player does have the permission to break a block at a specific location.
This is no longer available in the latest GP versions and I also couldn't find a good alternative.
Would be great to have something like this in the API.

**Comment by bloodmc** [comment]
Uh what? that was internal which was never supported. You should be using the flag methods in Claim.

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/claim/Claim.java#L823
