### ISSUE TITLE
item-drop prevent using Q but not Draging

### ISSUE THREAD

**Issue by Lorrainrm** [MinecraftPortCentral/GriefPrevention#573]
spongeforge-1.12.2-2555-7.1.0-BETA-2842
LuckPerms-Sponge-4.0.85
griefprevention-1.12.2-4.3.0.511
 forge-1.12.2-14.23.1.2600-universal.jar

item-drop false in wilderness, players can drop dragin the item, but not using Q.

will elaborate more tomorrow, heading to bed now

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/e4b5aecb0ab84cba3e0ea6897679a31d042978e5
