### ISSUE TITLE
Interact-inventory requires interact-block-secondary to work

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#576]
Interact-inventory requires interact-block-secondary to work.
For example i want people to access an enderchest, which is classified as an inventory at spawn (admin claim), allowing interact-inventory ender_chest isn't enough, i still have to give interact-block-secondary ender_chest for them to be able to actually open it.

**Comment by bloodmc** [comment]
These are 2 completely different interactions as mods may have actions for both. Working as intended.
