### ISSUE TITLE
[Feature] Allow defining what happens to claims with unpaid taxes

### ISSUE THREAD

**Issue by BrainStone** [MinecraftPortCentral/GriefPrevention#580]
I'd like to be able to configure what happens when the tax of a claim is not paid. For example that the claim gets abandoned if the taxes aren't paid.

If not already implemented it would be useful to list all claims that owe taxes, so that at least admins can remove them.

**Comment by bloodmc** [comment]
I plan on adding tax events to allow admins to make any changes they wish.

**Comment by bloodmc** [comment]
You can handle everything using below

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/data/EconomyData.java

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/event/TaxClaimEvent.java

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/permission/GPOptions.java#L59
