### ISSUE TITLE
Throwing pokeballs checking for item-spawn

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#583]
https://gist.github.com/anonymous/6fc928c55e0502645cea571efe6b609a

Pokeballs (in this testing case, safari balls), pass through the ground when thrown into the floor. In the debug, it was checking for item-spawn for some reason, which it isn't supposed to check, or didn't check for before.

Tested this on 2 other claims: 1 with item-spawn false and another with item-spawn true. The one with item-spawn false will always have the pokeballs pass through the ground, and the one with item-spawn true will make the pokeball hit the ground and drop (normal behavior).

So I conclude that it's checking for item-spawn wrongly. iirc it didn't work this way before.

`also, I noticeed that it keeps spamming the gravel in the debug even though he isn't placing or breaking any.`

Nvm, I just saw the update Build 528:
	bloodshot:
		Allow entity targets to be used with item-spawn flag.
		The 'item-spawn' flag represents entity items so entities need to be 
		supported as targets.
This probably fixes what I reported here, I'll have to test.

**Comment by bloodmc** [comment]
Update to latest build and allow it with item-spawn.
