### ISSUE TITLE
[Suggestion] Add a setting for the near-claim limit

### ISSUE THREAD

**Issue by Lemmmy** [MinecraftPortCentral/GriefPrevention#589]
I understand that the 1-block place-near-claim limit exists to prevent siphoning from chests, however players are able to break blocks in this limit without being able to place them back. They have to get an admin to worldedit the blocks back in. I believe there should at least be a config option or permissions flag to disable this 1-block limit, with the obvious consequence of edge chests being vulnerable.

**Comment by Ale32bit** [comment]
It's really annoying not being able to place blocks in your own claim because of your innocent neighbour.
