### ISSUE TITLE
[1.12.2] Duplication of buckets

### ISSUE THREAD

**Issue by Krosta8** [MinecraftPortCentral/GriefPrevention#590]
Hello,
I found an issue with latest version of Sponge and GP.
If the player has more than one bucket in a stack and doesn't have permission for block-break, the player get message, that he doesn't have permission to build there and get water bucket.
This issue is with everything, that can be filled to bucket (water, lava...).
Here is debug: https://gist.github.com/anonymous/694773c7081bb80816c8c3e4a68f8008

Versions:
GriefPrevention 1.12.2-4.3.0.533
SpongeForge 1.12.2-2586-7.1.0-BETA-2887
luckperms 4.0.124

**Comment by bloodmc** [comment]
This is a sponge bug, not GP. For now just stop the interact from occuring.

**Comment by Krosta8** [comment]
Should I post this bug on SpongeForge then?
And how do you mean stop the interact? I tried to disable interact with bucket, but it doesn't help too.

**Comment by Tollainmear** [comment]
Hi @bloodmc , Excuse me, this problem still appears in the latest version of GP 4.3.0.630, running on SpongeForge 3206. How can we avoid this problem? or if this is a problem with Sponge, what kind of information should we provide to them?
