### ISSUE TITLE
[Bug] Claims don't get frozen after tax aren't paid

### ISSUE THREAD

**Issue by BrainStone** [MinecraftPortCentral/GriefPrevention#596]
When a player couldn't pay their taxes they still can build on their claims.

I've set `griefprevention.tax-expiration-basic` to 0 and `griefprevention.claim-expiration-basic` to 14.  
As far as I understand it the two options I set mean that a claim freezes instantly without any leeway but they have a time period of 14 days to pay (while the taxes still apply) before the claim gets deleted, amm I right?

**Comment by bloodmc** [comment]
This has been fixed and will be released with the GP 4.4.0 update.

**Comment by Shybella** [comment]
I can confirm on 655 this does not work
