### ISSUE TITLE
Conflict with MoCreatures?

### ISSUE THREAD

**Issue by Dockter** [MinecraftPortCentral/GriefPrevention#597]
Using GP with MoCreatures.  The FireOgre the one that destroys blocks, GP is blocking the destroy but its creating itemStacks of the items that were prevented from being broke.

ItemStacks are real its not a de-sync with the client.

Using:  
* SF: 2908
* GP, latest as of 2/3/2018
* LP: 126.

**Comment by bloodmc** [comment]
Not a GP bug. Fixed in Sponge.
