### ISSUE TITLE
Builder can break but not place items on the edge of subclaims

### ISSUE THREAD

**Issue by RaresKool** [MinecraftPortCentral/GriefPrevention#598]
Upon trying to implement some shop plots for players, I have discovered that once they are given the builder permission to the subclaim they can break the edge of the claim, but not build. (The yellow blocks in the [picture ](https://i.imgur.com/xdqCFnW.jpg) are the edge I am referring to)

https://i.imgur.com/xdqCFnW.jpg

_spongeforge-1.12.2-2586-7.1.0-BETA-2882_. | _griefprevention-1.12.2-4.3.0.536_
_also tested with sponge 2900 and 2914_

**Comment by i9hdkill** [comment]
This is a feature, but not implemented the right way. Usually it should stop placing containers, if there is a another container directly near it. (The chest would connect and you could steal items from other chests that way).
However, it just checks if the player can build in the claim near by. But it should only disallow placing of containers and only if there is an actual container right next to the block that you are trying to place

**Comment by bloodmc** [comment]
Fixed in latest build. Use /ignoreclaims to bypass this check.

**Comment by bloodmc** [comment]
Actually this is not fixed. I'll have a claim option soon for this.
