### ISSUE TITLE
Players losing claim

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#60]
I feel like the last time you've fixed it there's something missed. Some players (who are active) lost their claims recently. I'm using B17 which this is supposed to be fixed. 

Auto chest unclaim days is default 7
Claim inactivity expiration I've set to 60 days

I thought it would follow the 60 days

**Comment by bloodmc** [comment]
@SnowBlitzz You need to paste your entire world config.

**Comment by SnowBlitzz** [comment]
http://pastebin.com/Nx8k2n8V

Just in case

**Comment by bloodmc** [comment]
@SnowBlitzz I don't see any issues with the code I have. Did GriefPrevention log a message when this claim disappeared? Whenever the cleanup task runs, a message is always logged.

**Comment by SnowBlitzz** [comment]
Hmm haven't heard any of this lately. I believe it is fixed and that my issue of world not saving properly is causing this

**Comment by bloodmc** [comment]
OK closing this. Create another ticket if it occurs and make sure to include log.
