### ISSUE TITLE
entity-spawn flag prevents entities from loading

### ISSUE THREAD

**Issue by BrainStone** [MinecraftPortCentral/GriefPrevention#600]
When I place down lets say an item frame and set the flag `entity-spawn` to false, then restart the server the item frame is gone.  
While I'm aware that it technically counts as spawning I think it should never be canceled.

Alternatively I tried setting `entity-spawn` to true for item frames and then they didn't get deleted, though now players can place them down. Denying `item-use` for the item frame did not fix it.

Any suggestions?

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging

Use /gpdebug to determine what you need to use.

As for entity-spawn denying chunk spawns, i'll be moving this to a new flag 'chunk-spawn'

**Comment by bloodmc** [comment]
https://www.dropbox.com/s/gbhbx150r9a18so/griefprevention-1.12.2-4.3.0-TEST1.jar

The new 'chunk-spawn' flag needs to be tested in this build. Once confirmed it works properly, ill push changes to master.
