### ISSUE TITLE
Plugin permissions on the issue

### ISSUE THREAD

**Issue by MoeShimaKaze** [MinecraftPortCentral/GriefPrevention#601]
Hello, my plugin is being used on my server
After I added griefprevention.user to the player
The player can not destroy the box, so I added griefprevention.flag to the player
Players can destroy the box, but also can enter the protected area broken and bad protection area of the box
How do I add permissions, so that players can normally damage the box outside the protected area, but also can not destroy the territory of the box
Thanks in advance for your help

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging

Never give any user griefprevention.flag
