### ISSUE TITLE
[More Info Needed] Claimflag events checking wrong player

### ISSUE THREAD

**Issue by Lemmmy** [MinecraftPortCentral/GriefPrevention#602]
A server is having a strange issue where events will get attributed to a completely different player about 20% of the time (this rate seems to increase when TPS is lower). This has been going on for about a week now, since at least Sponge 2900, and GriefPrevention 536.

This may be something to do with Sponge's new cause tracker.

## Broken blocks not dropping items
https://gist.github.com/anonymous/3b0f15fced1b9d827af498bf43b02684
https://gist.github.com/anonymous/a0d4b1e9bc8d6e784ce7eec06dfd9277
https://gist.github.com/anonymous/ddc0eefda73166186f217b665a845124

These three gists show `apemanzilla` breaking an anvil. Near the end, it shows that `rtlsdr` (a user who was **not online**) broke the anvil instead. As this occured in a claim, and rtlsdr was not trusted, this caused the anvil to not drop an item, meaning the block was completely lost.

The user that events get randomly attributed to seem to be different every day, possibly different every restart.

## ~Turtles completely duping (including their inventories)~ (FIXED)
https://gist.github.com/anonymous/0c6b917edb64f0df193ebc7a5be60068

~This gist shows a turtle that was placed by `CrazedProgrammer` attempting to move. Every time it moves, it tries to break the old turtle in its place, however the event got reattributed to `3d6` (again, **not online**, and she **did not place the turtle**). This caused the turtle to completely dupe, including its inventory.~

![](https://i.crzd.me/3UcNnCH9.png)
~This was one turtle, duped into a few hundred.~

## Mod versions
- Minecraft 1.12.2
- forge-1.12.2-14.23.2.2611-universal
- griefprevention-1.12.2-4.3.0.542
- LuckPerms-Sponge-4.0.131
- spongeforge-1.12.2-2611-7.1.0-BETA-2916

## Other mods
- ActiveTime-s7.1-v1.3.2
- AutoRegLib-1.3-15
- Baubles-1.12-1.5.2
- BiblioCraft[v2.4.3][MC1.12.0]
- cc-tweaked-1.80pr1.4-slightly-less-awful-02
- Chisel-MC1.12-0.1.1.26
- Computronics-1.12.2-1.6.6.182-better-multiperiphs
- ironchest-1.12.2-7.0.34.820
- jei_1.12.2-4.8.5.147
- kristpay-1.0-SNAPSHOT-all
- MinimalPeripherals-lite-1.12.2-1.3
- Nucleus-1.2.2-S7.0-MC1.12.2-plugin
- OpenComputers-MC1.12.1-1.7.1.43
- plethora-1.12.2-1.1.10
- Quark-r1.4-122
- sampler-1.73
- spongeprometheusexporter-1.3.1-plugin
- TabManager-1.0.4
- weirdinggadget-1.12.2-2.0.5-universal
- worldedit-forge-mc1.12-6.1.8-dist

**Comment by bloodmc** [comment]
GP has nothing to do with what gets tracked. Turn on causetracker debugging in sponge's config to see if the server is spamming errors causing the tracker to blow up.

**Comment by Lemmmy** [comment]
With these settings:
```
    cause-tracker {
        capture-async-spawning-entities=true
        generate-stacktrace-per-phase=false
        maximum-printed-runaway-counts=3
        report-different-world-changes=false
        verbose=true
        verbose-errors=true
    }
```
I'm seeing no errors in console at all for both the block drop issue and the turtle dupe.

**Comment by bloodmc** [comment]
@Lemmmy See if you can reproduce the issue with only Sponge/GP/LP and CC. Do this test in a fresh environment. Upload test world if reproduced.

**Comment by Lemmmy** [comment]
Haven't been able to reproduce it yet - will let you know if I'm able to.

**Comment by bloodmc** [comment]
Are you able to reproduce with an exact copy of your server?

**Comment by bloodmc** [comment]
This should all be fixed in latest SpongeForge and GP.

**Comment by Lemmmy** [comment]
Hi there - it seems that [reverting this](https://github.com/MinecraftPortCentral/GriefPrevention/commit/a6739061ece8c553ab414f6f9cf53963512ca6d7) caused the turtle dupe bug to start happening again.

![](https://shitty.download/Cy6N.png)
