### ISSUE TITLE
Players Attacking from across Claims

### ISSUE THREAD

**Issue by frostdaye** [MinecraftPortCentral/GriefPrevention#606]
Players can sit on the edge of the claim with a sword while another player runs out into the PvP zone, the first player can hit the second from the safety of the non-PvP zone to make him invincible from all attacks because he is in the zone that is safe to all damage.

This allows players to just sit in one claims and punch out into another without worry of damage. 

Is there a way to fix this? And/or is this an issue that is already going to be fixed?

**Comment by bloodmc** [comment]
@frostdaye You need to specify what version of GP you are using along with LuckPerms and Sponge. Easiest way is to simply post your server logs.

**Comment by frostdaye** [comment]
griefprevention-1.12.2-4.3.0.511

LuckPerms-Sponge-4.0.134

Sponge - 1.12.2-7.1.0-BETA 22

**Comment by bloodmc** [comment]
@frostdaye you are using completely outdated builds. Update to latest GP, SF, and SF then try again.
