### ISSUE TITLE
GP not detecting entities entering/exiting claims

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftPortCentral/GriefPrevention#608]
GP appears to ignore entities entering/exiting claims.

Tested by leading a creeper through the claim,

**GpDebug** https://gist.github.com/anonymous/57bccdf16f2c14ea03d40c7c48dd3830

**fml-junk-earlystartup** https://gist.github.com/DrZoddiak/8828db9d65a0f957fc6f36a180159d5c

![capture](https://user-images.githubusercontent.com/9203727/36617924-e5282300-18ae-11e8-9d90-26d3f831eb53.PNG)
![capture2](https://user-images.githubusercontent.com/9203727/36617934-ea57b8ae-18ae-11e8-9d71-b1ab71da1e92.PNG)

**Comment by kencinder** [comment]
I too tried specifying the same as above, as well as setting the claim from 'undefined' to 'false' which kept me out, but mobs could still be led through the claim.
I also tried a specific monster, a spider using `/cf enter-claim minecraft:spider false` and was able to lead the spider through the claim.
Entity spawns with defaults are showing (TRUE) in debug, but `enter-claim` aren't showing at all in the debug.

https://gist.github.com/anonymous/d9062decd9b0501a4572534a1dea4d22
