### ISSUE TITLE
Simple Chunk Claiming Mode

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#609]
I would like to see a simple mode of claiming offered, where a user right clicks inside a chunk and claims the entire chunk. Preferably an "All or nothing" option in the config as well, where it can be set as the only mode.

Most of my users are family, and young children, and the current system is rather imposing and difficult for them to use. Much easier to allow them to claim an entire chunk for themselves.

**Comment by bloodmc** [comment]
Make sure your users are all using WECUI with liteloader. More information can be found here

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/WECUI-(Improved-Visuals)

There is also the '/claim' command which will claim the region selected from WE mode. If this is still not good enough, I can think about a new option that can be set on players to force "chunk claiming" mode. First click would probably select the chunk and second click would probably claim it.

**Comment by kencinder** [comment]
Even using WECUI is a bit beyond the grasp of 4-6 year olds, and a simple ability for them and even others to just click on and claim a chunk, would be much easier.
