### ISSUE TITLE
Some turtle events being fired as wrong user

### ISSUE THREAD

**Issue by Lemmmy** [MinecraftPortCentral/GriefPrevention#610]
This issue may be related to #602. On this server, turtles have a 100% chance of duping (+ their inventories) if they are moving up and a player is jumping on top of them. We have been able to reproduce the underlying issue on a fresh server this time.

# Production server - MC 1.12.2, SpongeForge [(mod list)](https://gist.github.com/Lemmmy/7568dcabfc9658539b44bc2ae55d1637)
We made a claim as Lemmmy (non-admin) and placed a turtle. Lemmmy ran [this code](https://gist.github.com/Lemmmy/18fb37954d7feef37d312590231155a2) on it. Yemmel (admin user, respecting claims, not trusted in the claim) jumped on the turtle as it was moving upwards. The turtle fully duped twice. We reproduced this multiple times, there was a 100% chance of dupe.

# Reproduction on test server - MC 1.12.2, SpongeForge

[**This video demonstrates the dupe**](https://shitty.download/t4dK.mp4)

- Run [forge 2611 installer](https://files.minecraftforge.net/)
- Added mods:
  - [cc-tweaked-1.80pr1.4](https://minecraft.curseforge.com/projects/cc-tweaked/files)
  - [griefprevention-1.12.2-4.3.0.555](http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/)
  - [LuckPerms-Sponge-4.1.15.jar](https://ci.lucko.me/job/LuckPerms/)
  - [spongeforge-1.12.2-2611-7.1.0-BETA-2944](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2)
- /lp creategroup admin
- /lp group admin parent set default
- /lp group admin permission set griefprevention.admin
- /lp group default permission set griefprevention.user
- /lp user ADMIN_USER group set admin
- Claim an area of land as TEST_USER
- **Do not /ignoreclaims as ADMIN_USER**
- Place a turtle as TEST_USER
- Place a block of coal in the turtle's inventory
- Run `edit dupe`
- Insert the code:

```lua
turtle.refuel()
while true do
    for i = 1, 5 do turtle.up() end
    for i = 1, 5 do turtle.down() end
end
```

- Ctrl, enter to save
- Ctrl, right arrow twice, enter to exit
- Run `dupe`, the turtle should begin vertically oscillating
- Run `/gpdebug on` as ADMIN_USER
- As ADMIN_USER, jump on top of the turtle. When it is moving upwards, start jumping.
- ChangeBlockEvent.Break will be triggered as ADMIN_USER instead of TEST_USER. Turtle will either stop moving, or completely dupe. If it stops moving, restart the server and try again.

![](https://shitty.download/tyd2.png)

**Comment by JamesMC100** [comment]
OMG XD going to abuse the SHIT out of servers xDDD
Thanks for NOT fixing :D 💃

**Comment by bloodmc** [comment]
@Lemmmy First GP cannot cause dupes. It literally just cancels events which causes Sponge to restore the blocks. As for the user, it is technically not wrong as Sponge will always use the notifier over the block owner. However, there probably could be a check to make sure the block actually has physic logic before updating it. In any case, this ticket needs to be placed in SpongeForge as it is not a GP issue.

**Comment by Lemmmy** [comment]
Thanks blood. I was able to reproduce this on latest SpongeForge (2951) and latest GriefPrevention (559). As such, I have moved the issue to [SpongeForge#2034)(https://github.com/SpongePowered/SpongeForge/issues/2034).
