### ISSUE TITLE
abandonallclaims wont delete basic claims inside of admin claims

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftPortCentral/GriefPrevention#615]
![capture](https://user-images.githubusercontent.com/9203727/36940280-9aa2f10e-1f05-11e8-8d06-1329b7248441.PNG)

https://gist.github.com/DrZoddiak/5cd31910b267ed448796742bc7e635f1

As title says when using /abandonallclaims basic claims inside of admin claims wont delete
Town claims will be deleted if there in admin claims though

**Comment by bloodmc** [comment]
Please paste your GP global config.

**Comment by DrZoddiak** [comment]
https://gist.github.com/DrZoddiak/a5105df962564f87e48caa99a62fdb54

It should mostly be default, I believe the only modification I made was the auto-claim
