### ISSUE TITLE
Blocking entities from entering a claim causes pathing noise spam

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#617]
Using `enter-claim false` to block entities, particularly monsters, causes them to get stuck at claim borders but still attempting to move into it. This causes a lot of noise to be generated from their attempted movement that does not succeed, in rapid succession.

It would be preferable if an option to despawn them on enter-claim was available, as they also tend to pile up at claim borders, which aside from the noise leaves many item drops around the border when they die on sunrise.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/0016b4f600abac9cbe8930eeae8a19cb5848f9d2
