### ISSUE TITLE
Claims being removed once offline

### ISSUE THREAD

**Issue by ItzAntony** [MinecraftPortCentral/GriefPrevention#618]
For some reason when a user claims an area and then logs off their claim is removed and other users can edit/take items from that claim. Can this please be fixed ASAP. I seen this was an issue reported in 2016 but you couldn't reproduce it. It is still an issue. The version of sponge that we are on is 1.10.2

**Comment by bloodmc** [comment]
Zero information given and 1.10.2 is no longer supported.
