### ISSUE TITLE
Crash on region load

### ISSUE THREAD

**Issue by evernife** [MinecraftPortCentral/GriefPrevention#620]
When a player load an area specific area, the server crash.

Don't know if is griefprevention fault, i am just creating here because it's mentioned on the crash report.

Crash Report: https://hastebin.com/ajudamepub.scala

Also, i have already asked on LuckPerms https://github.com/lucko/LuckPerms/issues/836

**Comment by bloodmc** [comment]
1.10.2 is no longer supported. Upgrade to 1.12.2

**Comment by evernife** [comment]
🤦‍♂️

**Comment by KasperFranz** [comment]
It seems like a LP issue - have you tried updating it?

**Comment by evernife** [comment]
Yes, when the crash started i updated both plugin to the latest version:

> LuckPerms-Sponge-4.1.31.jar
> griefprevention-1.10.2-4.0.1.558.ja
