### ISSUE TITLE
Console permission issue

### ISSUE THREAD

**Issue by Witchcrafter1** [MinecraftPortCentral/GriefPrevention#630]
[fml-server-latest.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/1857893/fml-server-latest.log)
[latest.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/1857894/latest.log)
![2018-03-28_23 44 57](https://user-images.githubusercontent.com/37211601/38058263-89eaf3ac-32e2-11e8-9b61-569e7008b59e.png)
[fml-junk-earlystartup.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/1857895/fml-junk-earlystartup.log)

There is an issue with (admin-)claims, flags, and commands from the console.

The issue:
I have an admin claim (Spawn), where no mobs should spawn.
--> cf entity-spawn is false

But I want that the console is able to summon a mob inside this claim.
The problem is that the console isn't able to summon this mob inside the claim.

How to reproduce:

Create an admin claim
cf entity-spawn to false

use in the console `summon minecraft:zombie -355 78 157 {NoAI:1b}`
(with the correct coords inside the claim)

in the console should be the message:
"Object successfully summoned"

But on the block is no mob
------
use as admin the same command
--> now there will spawn a mob at the exact coords

simple solution (that I don't want):
cf entity-spawn minecraft:zombie true
but then they spawn regularly at night

GPdebug line for this command:
entity-spawn    none    minecraft:zombie    (-355, 78, 157)    default    FALSE

__________

the same thing happens with `minecraft:kill @e[type=minecraft:zombie,x=-356,y=77,z=156,dx=5,dy=6,dz=5]`
and the flag entity-damage

the admin is able to execute the command

**Comment by bloodmc** [comment]
OK, the solution to this issue would be to make sure the source is coming up as ConsoleSource then you can simply turn on spawning ONLY if the source is from console. I'll fix it when I get some time.
