### ISSUE TITLE
Unable to delete admin claim with 0 blocks

### ISSUE THREAD

**Issue by hugeblank** [MinecraftPortCentral/GriefPrevention#631]
Minecraft version: 1.12.2
Spongeforge version: 1.12.2-2611-7.1.0-BETA-2955
Forge version: 14.23.2.2624
GP version: 4.3.0.562
LP Version: 4.1.38

Don't ask me how I managed to do it but I made a 0 block area admin claim on my server.

![2018-03-28_17 33 18](https://user-images.githubusercontent.com/16393543/38063512-74dfe910-32ae-11e8-8aec-bf7d34b51458.png)
The outline that GP provides of this odd claim

![2018-03-28_17 33 53](https://user-images.githubusercontent.com/16393543/38063513-74facf46-32ae-11e8-8998-6116a59cff74.png)
Because I can't exactly stand inside the claim, seeing as it's 0 blocks (and slamming the blocks around it with a stick tell me that there isn't a claim there) I'll have to tp to its exact location and then delete it like that.

![2018-03-28_17 34 16](https://user-images.githubusercontent.com/16393543/38063514-75164028-32ae-11e8-8edb-f30fddd318e3.png)
/claiminfo says its wilderness... ok then, I guess it's sticking around for a while.

I attempted to reload GP, and restart the server, but it didn't get deleted by either of those methods either. I don't know if this is classified as a bug report or a feature request, but I need that claim removed and there's no way to do it (that I can blatantly see). If there was a way for an admin to have that ability, that would be great.

EDIT: Just thought I'd add to this that I have another admin claim that has a -182 block area, and has the same problem as the claim that has a 0 block area.

**Comment by bloodmc** [comment]
Delete the bugged claim from storage. You can find all claim data in ./config/griefprevention/worlds. If you manage to reproduce how this bug occurs then I'll reopen this ticket.
