### ISSUE TITLE
[Suggestion] claimlist and related commands default to the world you are in

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#632]
I know you can do /claimlist [\<player> [world]] but it can get confusing when you're in a world, and /claiminfo is pulling up claims from overworld.

Is it possible to have this work off the world you are in, when not specifying a world?

**Comment by bloodmc** [comment]
It's done like this so players can easily TP to claims between worlds without specifying world. I'll add the world to the list so it is less confusing.
