### ISSUE TITLE
"modid:any" not working with block-break and block-place using "default"

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#633]
```
GriefPrevention 1.12.2-4.3.0.569
SpongeForge 1.12.2-2611-7.1.0-BETA-2990
luckperms 4.1.44
```
Trying to allow villagers to break crops etc in admin claimed villages.

 `/cf block-break minecraft:villager minecraft:any true default` appear to work when issued, but the results do not and a gpdebug only shows the standard block-break/block-place flags returning false.
Specifying a specific block, such as `/cf block-break minecraft:villager minecraft:wheat true default` works.

Using no context works fine when using  `/cf block-break minecraft:villager minecraft:any true`, as does using override, but neither are desired results.

**Comment by bloodmc** [comment]
As stated in the wiki when using both source and target `Note: If you specify a source you cannot use any and a modid MUST be specified.` 

I don't plan on improving the functionality any time soon as it isn't a simple process. I'll leave this ticket open as a future enhancement.

**Comment by kencinder** [comment]
So modid:any won't work either using "default"? It works ok using no context or override.

**Comment by bloodmc** [comment]
Again, any AND modid:any is NOT supported due to how permissions are laid out currently.
