### ISSUE TITLE
Clicking claim in /claimlist doesn't show claiminfo

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftPortCentral/GriefPrevention#634]
As you can see I am inside the claim, and it shows up in the list
![claim](https://user-images.githubusercontent.com/9203727/38176601-8aa5a7ba-35b7-11e8-997b-1a791c3eb813.PNG)
This is the info for the claim when using `/claiminfo`
![claiminfo](https://user-images.githubusercontent.com/9203727/38176606-9f6a89ae-35b7-11e8-9e2b-b350c0b71cc8.PNG)
However when clicking the claim in `/claimlist`
![capture](https://user-images.githubusercontent.com/9203727/38176612-b5e8afda-35b7-11e8-911a-c5e98b257677.PNG)

![version](https://user-images.githubusercontent.com/9203727/38176627-f9e3e25e-35b7-11e8-87e2-c6ad5056eac2.PNG)

**Comment by bloodmc** [comment]
I see a basic claim within a basic claim which shouldn't be possible. Figure out how you got the basic within a basic then post steps here.

**Comment by DrZoddiak** [comment]
You are incorrect in that visual, you see a basic in a town off to the right, and a singular 2d basic claim that I am in.

**Comment by bloodmc** [comment]
Just recreate the basic claim then figure out how to reproduce the bug.

**Comment by bloodmc** [comment]
Oh nevermind, I see the bug is ONLY when you click Basic in chat. OK, I'll fix soon.
