### ISSUE TITLE
GP claim flags random issues ?

### ISSUE THREAD

**Issue by wowjudo** [MinecraftPortCentral/GriefPrevention#640]
Hello

After confirming this issue with few other servers owners in the GP discord i thought i'd open a ticket

Basicly at any given time the plugin can bug out which results lava to stop flowing, pixelmons not being able to be sent out, piston bug and other weird issues inside claims. in the wilderness it's fine

Server restart fixes this

Using sponge 1.12.2.2990 , GP 1.12.2-574 and 1.12.2-4.1.63 LP

**Comment by bloodmc** [comment]
You need to provide logs as this tells me nothing. Include ALL server logs and make sure to provide gpdebug logs as well.

**Comment by wowjudo** [comment]
During claim glitches where players are unable to throw Pokemon, battle in-side claims or where block updates don't occur, a player can add public trusts to fix it for a time.

/accesstrust public gives players the ability to throw pokemon out with r, then battle pokemon on claims during glitches.
/trust public will allow block updates to happen.

**Comment by wowjudo** [comment]
i will try to get the logs and gpdebug but last time i tried to debug the site had 404 error

**Comment by wowjudo** [comment]
https://griefprevention.github.io/debug/?3DN03Mf9wR

**Comment by wowjudo** [comment]
another example

https://griefprevention.github.io/debug/?NetYuV2nCq

**Comment by bloodmc** [comment]
This sounds like the OLD pixelmon bug which was fixed ages ago. What pixelmon version are you using? Include ALL server logs (fml-server-latest.log, fml-junk log etc..)

**Comment by wowjudo** [comment]
im running the latest pixelmon reforged version (6.2.3)

also it's not just pixelmon stuff that is bugged, it's also minecraft stuff (lava, pistons, water etc)

there's nothing in the logs, no error but i can send them to you via discord

**Comment by bloodmc** [comment]
No pixelmon servers are reporting this issue with latest builds. Update to latest.
