### ISSUE TITLE
PermissionHandler high CPU usage

### ISSUE THREAD

**Issue by XakepSDK** [MinecraftPortCentral/GriefPrevention#641]
Yourkit CPU profiling
https://puu.sh/A8iM0/02de65ace1.png
https://puu.sh/A8iQm/3b056a0aa9.png
https://puu.sh/A8iRz/bdcdf535e4.png

This causes tps drop.

**Comment by XakepSDK** [comment]
Luckpems issue link: https://github.com/lucko/LuckPerms/issues/929

**Comment by LemADEC** [comment]
Please provide more context to your issue: versions involved, mods & plugins involved, activity done by players and such

**Comment by XakepSDK** [comment]
Minecraft 1.12.2
GP 4.3.0.574 , SpongeForge 2990, Forge 2611, Pixelmon 6.2.3

**Comment by LemADEC** [comment]
How do you reproduce it?

**Comment by XakepSDK** [comment]
There is more than 70 active players on the server, i don't know, how to repro.

**Comment by bloodmc** [comment]
Unable to reproduce this in latest builds.
