### ISSUE TITLE
/Claimlist command isn't showing newly created Admin claims

### ISSUE THREAD

**Issue by Dockter** [MinecraftPortCentral/GriefPrevention#643]
Hello,  using the build compiled as of 4/20/2018.  I created an admin claim, I then typed /claimlist.  The newly created claim doesn't appear in the list.

**Comment by kencinder** [comment]
Did you click to filter by "ADMIN" as by default it only shows you your own claims. Also it will only show you claims in the overworld without a world specified.

**Comment by Dockter** [comment]
Yes, I clicked on that and other various ones to try and get the list to populate, it didn't.

**Comment by bloodmc** [comment]
Admin claims are not owned by a single player which is why they will not show up in "OWN" tab. Click on the "ALL" tab and it will show up fine.
