### ISSUE TITLE
GriefPrevention ignores maximum number of claims

### ISSUE THREAD

**Issue by EscolarProgramming** [MinecraftPortCentral/GriefPrevention#647]
I've recognized the problem that GriefPrevention ignores the metadata which regulates the maximum of basic claims a player can create. Maybe there's the same issue with the town and subdivision claims, but because I don't use them I haven't tested it. 

How to reproduce:
1. Set the metadata "griefprevention.create-claim-limit-basic" to a number bigger than 20 (20 is default)
2. Try to create more than 20 claims - you'll get an error that you have reached your limit of land claims

Running versions:
forge-1.12.2-14.23.3.2655
spongeforge-1.12.2-2655-7.1.0-BETA-3063
LuckPerms-Sponge-4.1.81
griefprevention-1.12.2-4.3.0.574

**Comment by bloodmc** [comment]
@EscolarProgramming Did you run /gpreload AFTER changing the limit?

**Comment by EscolarProgramming** [comment]
Yes, I did

**Comment by i9hdkill** [comment]
This goes for some other options aswell. At least this is known for claim-expiry.

**Comment by bloodmc** [comment]
Confirmed bug related to admin limits that need to be reworked =)
