### ISSUE TITLE
[Suggestion]To supporting WE_CUI Forge edition

### ISSUE THREAD

**Issue by Tollainmear** [MinecraftPortCentral/GriefPrevention#657]
Hi~This is not a bug, may I suggest to making GP support WE-CUI ForgeEdition? liteLoader edition was quite stable until the VanilliaFix mod has to added to the client side. there is a conflict between two mod, then I could found CUI ForgeEdition was not supported by GP.
I means if there were similar interface, Will GP support that in the future?

**Comment by bloodmc** [comment]
No, there will be no support for the forge edition as it is the "unofficial" version and a complete hack. If you have an issue with the liteloader version then create a ticket as that is how you get issues resolved.

https://github.com/Mumfrey/WorldEditCUI/issues
