### ISSUE TITLE
Inconsistent wilderness protection

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#658]
After updating from 12.2-4.3.0.579 to 1.12.2-4.3.0.583 the wilderness protection is no longer working correctly.
In `griefprevention/worlds/minecraft/overworld/world/world.conf` the default-wilderness flag `block-break` and `block-place` is set to false.

Sometimes after a server restart players can break blocks but can't place them while it doesn't show any message when trying to place blocks in the wilderness. If the server restarts again then it's working correctly again.
I assume this is caused by the blacklist addition as this is the main thing which was changed in GP.

I also noticed that there are multiple wilderness files in `griefprevention/worlds/minecraft/overworld/world/ClaimData/wilderness` while in the old 1.10 versions of GP there was always one, not sure if this is intended.

The /cf command shows the flags correctly:
![](https://i.imgur.com/t5JlWc5.jpg)

**Comment by bloodmc** [comment]
Unable to reproduce this issue on a clean server. If there are multiple wilderness files then you loaded multiple overworlds at one point or the UUID of your world changed. There have been bugs in LuckPerms in the past where permissions wouldn't always load properly. Try an older LuckPerms version 4.1.x and see if it solves your issue.

**Comment by Sir-Will** [comment]
All the wilderness files have the same world-uuid. I'm running LuckPerms-Sponge-4.2.12 atm.

**Comment by bloodmc** [comment]
Reproduce it with clean server and provide all server logs when you do.

**Comment by Sir-Will** [comment]
I couldn't reproduce the issue on a clean server yet but what causes the wilderness files to be created if the world uuid is the same for all of them?

**Comment by bloodmc** [comment]
Not sure, which is why I asked for it to be reproduced on a clean server. For now, just delete all the extra files and leave 1 that has the proper data inside.

**Comment by Sir-Will** [comment]
If I copy this claim into the clean server it creates a new wilderness file on every restart.

2d15fe0d-2ad7-461f-a79e-1b450a818af9
```
GriefPrevention {
    accessor-groups=[]
    accessors=[]
    builder-groups=[]
    builders=[]
    claim-expiration=true
    claim-type=ADMIN
    container-groups=[]
    containers=[]
    cuboid=false
    date-created="2018-05-15T02:15:04.093Z"
    date-last-active="2018-05-15T02:15:04.093Z"
    deny-messages=true
    economyData {
        bankTransactionLog=[]
        for-sale=false
        sale-price=0.0
        tax-balance=0.0
    }
    flag-overrides=true
    greater-boundary-corner="180;255;180"
    inherit-parent=true
    isExpired=false
    lesser-boundary-corner="-180;0;-180"
    manager-groups=[]
    managers=[]
    owner-uuid="31ba06e2-5738-4e4e-af31-da504cd16fbd"
    pvp=UNDEFINED
    requires-claim-blocks=true
    resizable=true
    sizeRestrictions=false
    subdivisions {}
    world-uuid=cde52faa-4a3f-4194-8172-c3fe705a2528
}
```

The world uuid is cde52faa-4a3f-4194-8172-c3fe705a2528 which are in both claim files and nucleus shows the same uuid.

**Comment by Sir-Will** [comment]
Unfortunately the main issue (blocks being breakable sometimes) is still there. Any way to track this down?

**Comment by bloodmc** [comment]
Do what I said and test with LP 4.1.X

**Comment by bloodmc** [comment]
Try this build https://www.dropbox.com/s/0rmoby3idiizyr1/LuckPerms-Sponge-4.1.83.jar

**Comment by Sir-Will** [comment]
I will have to check if I can get it running on the live server as a lot of plugins require LP 4.2

**Comment by bloodmc** [comment]
I don't see how a plugin would "require" LP 4.2 unless an event was added recently that they are using directly.
