### ISSUE TITLE
Pixelmon won't spawn in the wild or in certain places.

### ISSUE THREAD

**Issue by Corcustos** [MinecraftPortCentral/GriefPrevention#661]
For some reason, pixelmon simply will not spawn in the wild. There is only one place on the server that pixelmon are choosing to spawn, and that's spawn, which is admin claimed. There is only one place on the server that pixelmon are choosing to spawn, and that's spawn which is admin claimed. However, other admin claims which share the same default flags, will not spawn pokemon, nor will they spawn in user claims. Pixelmon from spawners won't even spawn, and I cannot spawn any from my pokeball or using /pokespawn. They simply pop out for a brief moment, flash, and then go away.

I've had to rewrite the above paragraph multiple times because they keep deciding to not spawn in spawn, only spawning in the wild, or simply not at all. It's very confusing, so I just left this instead. I was able to find parts of the wilderness using /rtp where pokemon would spawn, and other places where they would not.

I even used "/cf entity-spawn pixelmon:any true override" to enable them. I am not using "griefprevention.*" or "*" for any permissions. I also used /pokekill to kill all pokes, just to see if that would work, but the same situation happens even when there are no preexisting pokemon on the server. This still happens after a GP reload or server restart.

I am using the following versions:
GP 4.3.0 578. I've tried both prior and later version, but still encounter the issue.
SP 3105
Forge 2655

Video showing what is going on: https://youtu.be/-UckAHKiRiM

Logs:
[latest.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/2033737/latest.log)
[debug.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/2033739/debug.log)
[fml-junk-earlystartup.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/2033740/fml-junk-earlystartup.log)

Completely unrelated issue, but pistons keep disappearing and leaving ghost blocks, which are still there even upon relog. Only happens in claims. Not a priority, but some insight would be helpful.

**Comment by bloodmc** [comment]
You need to provide a gpdebug. Run the command `/gpdebug record` then `/gpdebug paste` and provide the result.

**Comment by bloodmc** [comment]
Please retest on a clean server with only Pixelmon/GP/LP/SF (Latest) and provide all logs.

**Comment by Corcustos** [comment]
I figured out the issue, it was a user mistake. You can go ahead and close this. Apparently being vanished prevents pokemon from spawning near you, so it had nothing to do with griefprevention even though it seems like it at first.
