### ISSUE TITLE
/at and /ct now giving players block-break access

### ISSUE THREAD

**Issue by Corcustos** [MinecraftPortCentral/GriefPrevention#663]
As the title says, if I do ./ct or ./at in any claims to allow users to use pixelmon PCs, doors, etc, it allows them to block-break, but they still cannot block-place. The claimflag for block-break is false, and I even set an override for admin claims to no avail. There's not really much other information to give. I do ./at all OR /ct all, and they can break blocks now. Remove it, and they cannot. This isn't so much of an issue for admin claims because all I need enabled is interact-block-secondary, but this also happens in user claims.

Note: Turns out the interact-block-primary flag specifically allows people to break blocks. It did not in 578. interact-block-secondary doesn't allow people to place blocks though, so I'm really confused.

I am using the following versions:
GP 4.3.0.587
SF 3105 - Forge 2655
LP 4.2.13

Nobody has the "griefprevention.*", or "*" commands. Additionally, when I first upgraded GP from 578, this issue did not occur. It was only after a restart that this started happening.

GPDebug: https://griefprevention.github.io/debug/?ELxduy1ICn
Not sure if this helps, but I had a user break blocks with ./at and ./ct on. Their user is Syco_KN. I also broke some blocks as well.
[latest.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/2041065/latest.log)
[fml-junk-earlystartup.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/2041066/fml-junk-earlystartup.log)

(I can't upload a debug.log because it's too large for both here and gist)

**Comment by bloodmc** [comment]
Unable to reproduce this on clean server. Also I see this in your gpdebug.

`block-break | minecraft:player | minecraft:sandstone | (-417, 98, 115) | Syco_KN | FALSE`

block-break is being denied

If you can reproduce this on a CLEAN server with only GP/LP/SF then i'll reopen.

**Comment by Corcustos** [comment]
Sorry to reopen the ticket like this, but I am unable to access a fresh server at the moment. However, I was able to make a video showing how I can recreate it. Even though block-break is being denied, players are still able to break blocks. Here is a video showcasing the issue I'm having: [https://youtu.be/kv-z-sKCVZ0](https://youtu.be/kv-z-sKCVZ0)

If I am unable to recreate this issue on a fresh server, am I exempt from receiving help here?

**Comment by bloodmc** [comment]
Do this, create a new claim and test with a user that ONLY has griefprevention.user permission. Only set /containertrust OR /accesstrust for the same user. If problem persists, take a screenshot of your overrides.

**Comment by Corcustos** [comment]
Problem persists: http://prntscr.com/jmr089

**Comment by bloodmc** [comment]
Screenshot output of `/lp user <username> permission info`. Also make sure the claim you are creating is NOT a child of another as it will inherit from parent by default. Last, provide a gpdebug of just the user by using `/gpdebug user username`

**Comment by Corcustos** [comment]
http://prntscr.com/jmr5pf <- Permissions
gpdebug: https://griefprevention.github.io/debug/?iCVNe5Sd2j

It still says block-break is false, but as you can see from the video above, blocks are still broken.

**Comment by bloodmc** [comment]
Your sponge log is filled with errors from the plugin de.randombyte.commandutils. Remove that plugin and try again. If it still does not work then you need to do what I asked and reproduce on a clean server as there is clearly something on your end breaking it. GPDebug reports false so the issue is not on my end.

**Comment by Corcustos** [comment]
Both problems seem to have subsided for now, not entirely sure why an alias mod would cause something like this, but hopefully it's fixed permanently. If the problem arises again, and I cannot recreate it on a clean server, what do you suggest I try?

**Comment by bloodmc** [comment]
Again, if GPDebug reports results properly then it is not my issue. Your issue was caused by using an incompatible sponge plugin. Report to author if you need to use plugin as it must be updated to support latest Sponge.

**Comment by Corcustos** [comment]
The issue is back, CommandUtils is gone, attempting to get a test server up to no avail, although pistons seem to be completely fine. It's just the interact-block-primary causing people to be able to break. Did something change from GP 578 to 587 that might conflict with other mods? This issue never happened in 578. GPDebug isn't even showing block-break anymore, just trust.accessor. Unfortunately, I am unable to get a test server up and working at the moment. What do you suggest I do from this point on with the given information in mind?

**Comment by Corcustos** [comment]
@bloodmc Just wanted to let you know that I was finally able to solve the issue. Downgrading back to griefprevention 571 completely eliminated all of my problems with pistons and block-breaking when interact-block-primary was on. Thank you for your help.
