### ISSUE TITLE
claim option

### ISSUE THREAD

**Issue by ziceptor** [MinecraftPortCentral/GriefPrevention#665]
Does not work for me command  /co min-claim-size-basic-z 2
In the wasteland it is reported that I have no rights to install options. The claims say that you need to change the administrator options.

no error in log

forge-1.12.2-14.23.4.2703-universal.jar
spongeforge-1.12.2-2703-7.1.0-BETA-3119.jar
LuckPerms-Sponge-4.2.14.jar
griefprevention-1.12.2-4.3.0.587.jar

**Comment by yepidoodles** [comment]
Hey I was wondering the progress on the fix for this? My current shop plots at spawn are 7x7, if there's no progress on this within a couple weeks, I'm going to have to re-build my entire spawn shop area to accommodate larger plots. Rather not do that, as you can imagine.

**Comment by bloodmc** [comment]
This will be fixed after GP 5.0.0 is released which should be soon. You can work around it by manually applying the option to sponge's default user in luckperms. For example, if you want to set the minimum claim size to 2 for basic then the default user must have an option set for 2 or lower.

**Comment by yepidoodles** [comment]
That is what I did and that didn't work...
