### ISSUE TITLE
Towntag token for chat managers

### ISSUE THREAD

**Issue by Shybella** [MinecraftPortCentral/GriefPrevention#667]
requesting for a Towntag token to be displayed in chat managers as a prefix. (nucleus)

**Comment by bloodmc** [comment]
@dualspiral Would you be able to provide some insight on how I can handle this request? Not familiar with how nucleus handles chat. Thanks!

**Comment by dualspiral** [comment]
I'll see what I can do and perhaps PR that in as the short term fix.

Are there any other tokens that would be of use (at least for now?)

**Comment by bloodmc** [comment]
Sounds good thanks. Nope, town tag is the only thing currently being used.

**Comment by bloodmc** [comment]
Thanks! I'll provide user with a jar so they can test soon.

**Comment by Shybella** [comment]
I'm available to test this at any time
