### ISSUE TITLE
Minimum basic claim size not working

### ISSUE THREAD

**Issue by yepidoodles** [MinecraftPortCentral/GriefPrevention#669]
Hello, I posted this on Discord first but as far as I saw, I never got a response, so I'm posting it here.
[![Screenshot from Gyazo](https://gyazo.com/15bbae7bd356d94f5e12f911a4fcaf7b/raw)](https://gyazo.com/15bbae7bd356d94f5e12f911a4fcaf7b)

I've updated SF to 2705-3135 and GP to 4.3.0.593 since then, which are the current latest, and re-tested to no avail.

Nucleus info for mod/plugin list: https://gist.github.com/yepidoodles/5b369de63a5036f47ff497be589bab4e

Many thanks for any assistance, let me know if you need any further information. 

~ Alice

**Comment by bloodmc** [comment]
dupe #665
