### ISSUE TITLE
wilderness is not checking for block-break + other flags seem to work but no messages on deny

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#671]
GP 597
Sponge 3105
Forge 2655

https://luckperms.github.io/verbose/?xqrj731ulV/
(user sucessfully breaks a grass block)
/claiminfo
http://prntscr.com/jq2g7f

Flags:
http://prntscr.com/jq2hs5
There is only one wilderness file with the file name that matches the world uuid and uuid in /claiminfo. So that should be ok.

Placing is denied, but without a message:
https://luckperms.github.io/verbose/?xLPCFcXlwP

Block-break handling in basic and admins claims is working.

**Comment by kencinder** [comment]
Can confirm broken here too

SpongeForge 1.12.2-2705-7.1.0-BETA-3136
GP 4.3.0.597
LuckPerms 4.2.20

GPDebug done with Block-Break default set FALSE in Wilderness, and ClaimFlagDebug ON

https://griefprevention.github.io/debug/?bIBjBTlAPJ
