### ISSUE TITLE
Catalytic Lens duplication bug when used next to a claim.

### ISSUE THREAD

**Issue by RaresKool** [MinecraftPortCentral/GriefPrevention#675]
If a Catalytic Lens from Project E is used on a block adjacent to any claim, it will cause the blocks in the range of the Catalytic Lens to drop, but the blocks will still be present.

This way, players can place down items next to a claim they do not own, then use the Catalytic Lens on said blocks and therefore duplicate them.

If used horizontally on the block next to someone's claim, this could be used to duplicate the items owned by other players.

**Comment by bloodmc** [comment]
Supply `debug.log` and all version info.
