### ISSUE TITLE
CarryOn Dupe Bug

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#676]
the CarryOn mod allows to pickup tiles in claims which keeps the tile in the claim but also adds it to the player hands.

I tried to fix this issue myself but I'm unable to as the GP api doesn't provide a way to check if the claim is set to break deny or allow.

griefprevention-1.12.2-4.3.0.603
CarryOn MC1.12.2 v1.8

**Comment by bloodmc** [comment]
The mod should be firing Forge's `BlockEvent.Break` before attempting to pickup a tile. The issue is on the mod end as it ignores protection mods/plugins entirely.

Create a ticket on the tracker here

https://github.com/Tschipp/CarryOn/issues
