### ISSUE TITLE
/delete claim error

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#68]
http://puu.sh/pnVCW/d858351bf1.jpg

**Comment by ghacproductions** [comment]
Have you checked the log for errors?

**Comment by SnowBlitzz** [comment]
Nothing on console

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
