### ISSUE TITLE
Able to take and place liquids from adminclaims

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#682]
Anyone is able to take and place water or lava from adminclaims. This is fixed if you disable item-use on buckets, water buckets, and lava buckets but this shouldn't be a necessary action.

With this bug, you're essentially also able to create obsidian and cobblestone from the water and lava you place, which can grief any adminclaim you have.

SpongeForge 3171. GP 614.

**Comment by bloodmc** [comment]
Sponge bug, update to latest SF.
