### ISSUE TITLE
annoying givepet o.o

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#69]
hmm ok so pixelmon chatting npcs (placed by me, or anyone) inside and outside claims can't be accessed anymore since it tells the player I need to /givepet to them. 

right clicking a player also tells them they need to /givepet but this doesn't really matter much than the first one.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
