### ISSUE TITLE
buying and selling claim blocks is disabled

### ISSUE THREAD

**Issue by illysia** [MinecraftPortCentral/GriefPrevention#691]
i set a buy and sell price for buying and selling blocks and reloaded the plugin
it still tells me buying and selling blocks is disabled when i do /buyclaimblocks
i looked everywhere in the config and i have no idea how else to enable it

i have the newest version of vault if that has anything to do with it

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Global-Config#economy

Make sure you also have an economy plugin installed.
