### ISSUE TITLE
dupe 

### ISSUE THREAD

**Issue by ImagePrototype** [MinecraftPortCentral/GriefPrevention#693]
https://youtu.be/djdmlV4wlmM
not working in global region, region to which there is access, as well as in the regions where the '/ct all' flag is set.

**Comment by ImagePrototype** [comment]
[GP] Running GriefPrevention 1.12.2-4.3.0.576
[GP] Running SpongeForge 1.12.2-2611-7.1.0-BETA-3016
[GP] Running luckperms 4.1.91

**Comment by bloodmc** [comment]
Upgrade to latest GP, SF, and LP. Outdated versions are not supported.
