### ISSUE TITLE
[Feature Request] Show claim boundary using WE CUI

### ISSUE THREAD

**Issue by fsgmhoward** [MinecraftPortCentral/GriefPrevention#694]
With the help of WE CUI, we can see the boundary of the claim land when we try to claim it. However, is it possible to show it again whenever we use the command `/claiminfo` (or add it as a button in the claiminfo menu) so it is much easier for us to check the boundary of an existing claimland?

I found this feature useful when I use residence in 1.7.10. It will be nice if GP have something similar. Thanks.

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/WECUI-(Improved-Visuals)

Are you using WECUI + Liteloader?

**Comment by fsgmhoward** [comment]
@bloodmc I am using forge + WECUI... I somehow missed that docs but I tried today it does not seem to be working (the glowstone and gold blocks did show up but the WECUI grid didn't)

Local plugins:
WE: `worldedit-forge-mc1.12-6.1.8-dist`
WECUI: `WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12-14.21.1.2387`

Server plugins:
Sponge `3206`
Forge `2705`
WE: `worldedit-forge-mc1.12-6.1.8-dist`
GP: `4.3.0.628`

**Comment by bloodmc** [comment]
You must use WECUI with liteloader. Forge edition is NOT supported.
