### ISSUE TITLE
Option griefprevention.min-claim-size-basic-x/y/z not working

### ISSUE THREAD

**Issue by fsgmhoward** [MinecraftPortCentral/GriefPrevention#696]
GP version: `4.3.0.628`
LP version: `4.2.17`
Forge version: `2705`
Sponge version: `3206`

I have set the meta of my group's parent group according to the docs. When I execute command `/lp user <my user name> info`, I can see the following meta data are registered:
```
[10:31:39] [pool-4-thread-1/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [LP] -    Meta: 
(griefprevention.blocks-accrued-per-hour=0) 
(griefprevention.claim-expiration-town=100000)
(griefprevention.min-claim-size-basic-z=3) 
(griefprevention.claim-expiration-subdivision=100000)
(griefprevention.min-claim-size-basic-x=3)
(griefprevention.create-claim-limit-basic=0)
(griefprevention.min-claim-size-basic-y=3)
(griefprevention.claim-expiration-basic=100000) 
(griefprevention.claim-create-mode=1)
```

I also did `/gpreload` and even restarted my server. However, when I try to create a 3x3x3 basic claim, it told me that length on x-axis of 3 is less than the minimum 10 and the minimum size is still 10x5x10 (default values).

Since `griefprevention.blocks-accrued-per-hour` does come into effect, I think I should have set the options in a correct way.

Moreover, `griefprevention.claim-create-mode` does not change the mode of auto-claimed claims which is still 2D after the option is set.

**Comment by bloodmc** [comment]
Read commit message on how to solve this

https://github.com/MinecraftPortCentral/GriefPrevention/commit/0df8e2dc03186868f2520c9174764e978ce802eb
