### ISSUE TITLE
Feature Request:  flags to contain events to the protection area

### ISSUE THREAD

**Issue by DatenThielt** [MinecraftPortCentral/GriefPrevention#698]
Not sure how Feasible it is,  But the ability for example to set a flag to allow explosions/effects that are generated within a claim,  to not effect anything outside a claim. 

This would allow servers to keep explosions on for various items (Mostly reactors, draconian Chaos, IC2) and keep them dangerous, without risking world ending consequences

**Comment by bloodmc** [comment]
You can already handle this by denying explosions in wilderness. Any area not claimed by a player is the "wilderness". Just stand in wilderness and set whatever flags you want.

**Comment by DatenThielt** [comment]
I will close this and after some testings if we notice something that does not work as expected we will let you know,  thank you bloodmc!
