### ISSUE TITLE
Feature Request - Cap on all claim blocks

### ISSUE THREAD

**Issue by Zachincool** [MinecraftPortCentral/GriefPrevention#70]
Hello.
I am requesting a feature for your plugin.
A global cap on all claim blocks for all players. Please note - this is not the "max-accrued-blocks" option in the config. You can bypass that if you purchase blocks or admins give you bonus blocks. I am talking about a full cap that can not be bypassed no matter what. Currently, it is possible for players to have an infinite amount of claim blocks - as long as they can afford it!

Thanks!

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
