### ISSUE TITLE
Use IC2's laser gun in the server to brush items in the territory.

### ISSUE THREAD

**Issue by umbrella22** [MinecraftPortCentral/GriefPrevention#701]
**Impact version**
MC version :1.12.2
MOD version：4.3.0.663
forge version：14.23.4.2725
**How to reproduce**
**After the use of the territory, if someone uses a IC2 laser mining gun outside the territory, using an explosion or rapid fire mode, it will destroy the territory and will bring out the objects in the field in the form of falling. This is a very severe BUG, hoping to be repaired.**

**Comment by bloodmc** [comment]
This is exactly what `item-spawn` flag is for. Make sure the module is turned on and that it is enabled in the claim.

**Comment by bloodmc** [comment]
Closing as this should be resolved with `item-spawn`.

**Comment by umbrella22** [comment]
**[22:31:38] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Running GriefPrevention 1.12.2-4.3.0.633
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3242
[GP] Running luckperms 4.2.40**
![qq 20180630223220](https://user-images.githubusercontent.com/19886152/42126147-856c41a6-7cb5-11e8-8d96-039e9052d2af.jpg)
![qq 20180630225006](https://user-images.githubusercontent.com/19886152/42126268-fbdcaffe-7cb7-11e8-9818-167354af7a8c.png)
[22:46:16] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Event: ChangeBlockEvent.Pre
**[GP] Target: minecraft:flowing_water.0
[GP] Permission: griefprevention.flag.liquid-flow.minecraft.flowing_water.source.minecraft.flowing_water.0.0
[GP] Location: (-20, 73, 399) User: gtofian

[22:46:16] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Event: ChangeBlockEvent.Pre
[GP] Target: minecraft:stone.0
[GP] Permission: griefprevention.flag.liquid-flow.minecraft.stone.source.minecraft.flowing_water.0.0
[GP] Location: (-20, 72, 399) User: gtofian

[22:46:16] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Event: ChangeBlockEvent.Pre
[GP] Target: minecraft:flowing_water.2
[GP] Permission: griefprevention.flag.liquid-flow.minecraft.flowing_water.source.minecraft.flowing_water.2.2
[GP] Location: (-15, 25, 443) User: gtofian

[22:46:16] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Event: ChangeBlockEvent.Pre
[GP] Target: minecraft:water.10
[GP] Permission: griefprevention.flag.liquid-flow.minecraft.water.source.minecraft.flowing_water.2.10
[GP] Location: (-15, 24, 443) User: gtofian

[22:46:18] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Event: SpawnEntityEvent.ChunkLoad
[GP] Target: forestry:butterflyge
[GP] Permission: griefprevention.flag.entity-chunk-spawn.forestry.butterflyge
[GP] Location: (-115, 90, 357) User: gtofian

[22:46:18] [Server thread/INFO] [minecraft/DedicatedServer]: [GP] Event: SpawnEntityEvent.ChunkLoad
[GP] Target: forestry:butterflyge
[GP] Permission: griefprevention.flag.entity-chunk-spawn.forestry.butterflyge
[GP] Location: (-105, 94, 363) User: gtofian**
@bloodmc 
Is that the right way to open it, please? But it still appears like screenshots, and logs are on top.

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging

**Comment by bloodmc** [comment]
@umbrella22 I'm still waiting for a proper debug using `/gpdebug record` and `/gpdebug paste`
