### ISSUE TITLE
Some Botania rituals failing in claimed areas

### ISSUE THREAD

**Issue by DragaoNimhe** [MinecraftPortCentral/GriefPrevention#703]
As stated in the title, some Botania rituals are not working within claimed areas: So far we have tested throwing a carrot into a full pool of mana to change it into a beetroot, which produced a beetroot visibly for a fraction of a second, then vanished. This happened every time, when repeated. We have also tried this with beetroot seeds, which should produce melon seeds; yet each time it produces the item, which instantly vanishes. It functions fine outside of player-claimed areas.

**Comment by bloodmc** [comment]
Please post a gpdebug of output when you test this action. Follow the wiki here to debug

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging

Also post an output of `/gpversion`

**Comment by DragaoNimhe** [comment]
Apologies for my delayed reply. Was hoping to have time to get that for you tonight but sadly I did not. I'll shoot it your way first thing when I get up tomorrow.

**Comment by DragaoNimhe** [comment]
We have solved the issue, it was related to a slightly outdated version of GP conflicting with sponge. Apologies for wasting your time.
