### ISSUE TITLE
Taintseeds can't spread taint fibre

### ISSUE THREAD

**Issue by iamtpage** [MinecraftPortCentral/GriefPrevention#704]
Hi,

Taint seeds are unable to place taint fibre from TC BETA16:
![2018-07-02_00 50 36](https://user-images.githubusercontent.com/8901422/42147176-1da2508c-7d92-11e8-8eb4-f36405f42719.png)
![image](https://user-images.githubusercontent.com/8901422/42147192-3629e8c2-7d92-11e8-83b0-e5076d14e429.png)
![image](https://user-images.githubusercontent.com/8901422/42147199-3ebbc726-7d92-11e8-93d1-9af5e0e5948d.png)

I've allowed them and even captured gpdebug logs showing that the permissions evaluate to true, but the taint_fibre block is never placed

**Comment by bloodmc** [comment]
@iamtpage does this work without GP? Have you tested with only GP/SF/LP ? Anything blocked by GP will always show up in gpdebug so something else seems to be causing the problem.

**Comment by iamtpage** [comment]
I'll test and report back

**Comment by bloodmc** [comment]
Assuming resolved as there has been no response in 2 weeks.
