### ISSUE TITLE
ComputerCraft Turtle Dupe Bug

### ISSUE THREAD

**Issue by JavaProphet** [MinecraftPortCentral/GriefPrevention#71]
The ComputerCraft guys said it isn't their fault. If you have a turtle in a protected zone, and it breaks a block, it gets the drop without breaking the block.
We are using ComputerCraft v1.79, Forge 11.15.1.1890, Sponge spongeforge-1.8.9-1890-4.2.0-BETA-1471, and GriefProtection 1.8.9-0.1-4.

**Comment by bloodmc** [comment]
@JavaProphet They are correct, i'll look into this after I finish next build.

**Comment by inklit** [comment]
Can confirm this is a bug. Also has serious issues with placing blocks, and moving inside claims.
Passing claim borders does not work unless it is leaving the claim.

OpenComputers has a very similar problem but it duplicates the entire Robot when it tries to move into a claim.

**Comment by bloodmc** [comment]
After looking into the issue, the problem lies in Sponge. The turtle calls isBlockProtected which is currently not tracked by sponge. Open a ticket in SpongeCommon so we can fix it there.
