### ISSUE TITLE
Enter-Claim False Bug

### ISSUE THREAD

**Issue by shinzoop1** [MinecraftPortCentral/GriefPrevention#710]
So doing /cf and clicking "enter-claim" to false will make it so when a player runs into the region it turns them invisible and they also cannot teleport by /spawn, /home, /warp. relogging fixes the issue of teleporting and can be repeated without fail on our server.

**Comment by bloodmc** [comment]
Provide /gpversion output

**Comment by bloodmc** [comment]
No response in days, closing.
