### ISSUE TITLE
Wiki clarification

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#713]
As of now, the Wiki commands list says that '/claimlist' command is supposed to list claimblocks for the player, while in fact it's the '/playerinfo' command doing that. This is different from the legacy GF bukkit command.
I propose to change the commands wiki page to be more explicit on both commands so we can look it up more easily.

**Comment by LemADEC** [comment]
Also, /claimbook isn't implemented in Sponge according to Mohron, so we might wanna mark it as such in the wiki.

**Comment by DrZoddiak** [comment]
The wiki is editable by anyone. The changes have been made, but there's not really a need to submit an issue in the future, as again anyone is able to edit it.
