### ISSUE TITLE
Subdivisions are taking into account the claim-limit when they shouldn't

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#716]
so yeah, subdivisions are taking into account the claim-limit when they shouldn't. If you set a max claim limit of 5 and the player has 1 giant claim, they can only subdivide that claim 4 times. I don't think subdivisions should be checked for the claim limit since they're just claims within a claim.

**Comment by bloodmc** [comment]
As this is a user option, just set it to a very high number until GP 4.4.0 is released.

**Comment by SnowBlitzz** [comment]
But we also want to limit their number basic claims.

**Comment by bloodmc** [comment]
What does that have to do with the subdivision limit? Basic create limit has no relation to subdivision limit.

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Advanced-Options

**Comment by SnowBlitzz** [comment]
Hmm wait sorry. I think I've had a misunderstanding. Got a report that someone wasn't able to set more than 4 subdivisions so I thought it had something to do with the basic claim limit. I'll close this for now.

**Comment by SnowBlitzz** [comment]
Ok I think we had a misunderstanding. My main report still stands. 

Subdivisions are taking into account the BASIC claim-limit when they shouldn't. If you set a max BASIC claim limit of 10 and the player has 1 BASIC claim, they can only subdivide that claim 9 times (totaling to 10 overall claims, 1 BASIC and 9 SUBDIVIDES). 

These are my settings: https://i.imgur.com/D2nqr4o.png
As you can see, claim limit subdivision is set to infinite while claim limit basic is set to 10.
