### ISSUE TITLE
Fire spread does not stop the fire 1.12.2

### ISSUE THREAD

**Issue by ResponsibleBear** [MinecraftPortCentral/GriefPrevention#718]
Hi! Fire spread flag does not work.
What am I doing. 
I ignite the block on the border, and the fire begins to spread further.
Thanks for the help.

Versions:
griefprevention-1.12.2-4.3.0.644.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3310.jar

![2018-07-17_00-21-13](https://user-images.githubusercontent.com/7941838/42778809-bf5850ae-8957-11e8-9a71-8ea1321625c6.png)
![2018-07-17_00-24-53](https://user-images.githubusercontent.com/7941838/42778836-dcb9496e-8957-11e8-8af2-819dd92a5878.png)
![2018-07-17_00-26-50](https://user-images.githubusercontent.com/7941838/42778919-22a94b04-8958-11e8-8f7a-ec79bc3dc63a.png)
![2018-07-17_00-26-37](https://user-images.githubusercontent.com/7941838/42778920-22cd59fe-8958-11e8-83b4-96e671254f0e.png)

**Comment by bloodmc** [comment]
Unable to reproduce and you are using a completely outdated SF build. Also Fire Spread will always work for owners in claims they own, if you want it completely disabled set the gamerule to false.

**Comment by bloodmc** [comment]
Oh I see 3310 was around the date this was posted. Just update SF and you should be fine.

**Comment by sapphirepixelmon** [comment]
Hi @bloodmc ,

I have the same problem. Fire spreads while fire spread is disabled. I have:
spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar
griefprevention-1.12.2-4.3.0.646.jar
installed.
