### ISSUE TITLE
Subdivisions lose all access when the server restarts

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#72]
When my server restarts, subdivision claims lose all of their access, including from the creator themselves.

The creator must abandon the toplevel claim and then redo the subdivisions to fix it.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/624fa61e165e903768e5288e613207dad28451be
