### ISSUE TITLE
[Request] Hide flags users do not have permission to use in /cf

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#721]
When performing /cf users see flags they do not have permission to edit in their own claim as per `user-claim-flags` in the config.
Would be nice if entries not present in this list, were not even displayed to the user. They can't edit defaults or the value in their own claim anyway.

**Comment by bloodmc** [comment]
This was already fixed for GP 4.4.0 which will be released soon.

**Comment by bloodmc** [comment]
This was fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/87f7971f2f7040629e0edf54a198dc16116f3bfc

Flags won't be hidden but will show text on hover stating they need permission to access.
