### ISSUE TITLE
Enter-claim false bug

### ISSUE THREAD

**Issue by ResponsibleBear** [MinecraftPortCentral/GriefPrevention#722]
Hello!
If the region has the enter-claim false flag after the player attempts to enter it, it can not use commands or break blocks. Teleportation is canceled, blocks do not break. 
Sorry for the bad english.

Versions:
griefprevention-1.12.2-4.3.0.644.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3310.jar

![2018-07-18_00-15-00](https://user-images.githubusercontent.com/7941838/42840352-feb41fe4-8a1f-11e8-8b82-9adad74093f3.png)

**Comment by bloodmc** [comment]
You are running outdated SF which was bugged. Update SF.
