### ISSUE TITLE
Cannot trust group or public

### ISSUE THREAD

**Issue by Yukimir** [MinecraftPortCentral/GriefPrevention#724]
GP Version: 1.12.2-4.3.0.640
LE Version: 4.2.17
Sponge Version: 1.12.2-2705-7.1.0-BETA-3270

Issue:
Cannot trust group or public by `/trust`  `/ct`  `/at`
`/trust [player]` is ok

**Comment by bloodmc** [comment]
Running outdated SF/GP build and have provided no logs. Provide complete information or your tickets will be closed.
