### ISSUE TITLE
Player's Cant Open Chest

### ISSUE THREAD

**Issue by PrimeBomb** [MinecraftPortCentral/GriefPrevention#725]
GP Version: 1.10.2-4.0.1.566
LE Version: LuckPerms-Sponge-4.2.51.jar
Sponge Version: 1.10.2-2477-5.2.0-BETA-2793

Issue: Players can't open chests when they have claimed a region, and Small Storage Crates (the ones from actually additions) any player can open them.

**Comment by bloodmc** [comment]
1.10.2 is not supported. Update to 1.12.2
