### ISSUE TITLE
Issue abandoning claim

### ISSUE THREAD

**Issue by Shybella** [MinecraftPortCentral/GriefPrevention#727]
It's a rare event that happens. Not all the time.

When a user tries to abandon a claim it notifies that the claim has been abandoned but does not.

video: https://gyazo.com/681aa611df6ec37dd97259540d086a54

GP: 644 SF: 3323

**Comment by kencinder** [comment]
What is luckperms version? This sounds a lot like sync issues in the past...

**Comment by Shybella** [comment]
4.2.41 I am using a build from July 1st. I should update and test it
latest is 4.2.51. 

Luckperms on Ore probably needs a update unless those are RBs only it's at 4.2.17.

**Comment by bloodmc** [comment]
Create a new ticket if this occurs with latest GP.

**Comment by Shybella** [comment]
Yeah, will do. Thanks again blood.
