### ISSUE TITLE
Subdivision claims can get sold, but doesn't appear in /claimbuy list.

### ISSUE THREAD

**Issue by anghenfil** [MinecraftPortCentral/GriefPrevention#729]
- GriefPrevention Version 4.3.0.644

If you create a "Subdivision Claim" with /claimsubdivide you can sell the claim with /claimsell, but the claim won't appear in the /claimbuy list.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/e58db9094828b59ef8e08ff5e508fc8e21e1924c
