### ISSUE TITLE
Improve claim visuals

### ISSUE THREAD

**Issue by bloodmc** [MinecraftPortCentral/GriefPrevention#73]
This is an open ticket to discuss how we can improve claim visuals.

First off, claims are cuboids and the area is persisted by storing the location of the lesser/greater corner of the cuboid. Players are given the ability to use an investigation tool to view their claim area. 

Here is an example showing how a visual looks in a 30x30 block claim
http://i.imgur.com/gV0BwHv.jpg

As it stands now, visuals can consume a bit of resources based on how they are currently handled.
As you can see in picture, every 10 blocks a visual block is shown. 10 blocks is the current limit of how many blocks can be skipped before a visual is needed. The type of visual is determined by the claim type. Currently there are 3 types of claims which are the following 
1.  BASIC
   The default visuals block types for this claim type are Glowstone and Gold. Each of the 4 corners are set with a visual Glowstone block surrounded by 2 gold blocks. Then depending on how large the claim is, up to 10 blocks a visual gold block is shown as seen in the picture above.
2. ADMIN
   Admin claims use visual block types Glowstone and Pumpkin. Same visual logic as BASIC
3. SUBDIVISION
   Subdivisions use visual iron block types and wool. Same visual logic as BASIC

https://postimg.org/image/dn2iwic7l/

The second image shows a visual from the side of the same 30x30 area basic claim. As you can see in this picture, there are no visuals except on the top. This is one area where we can improve on to allow a player get a better glimpse of the cuboid size that his/her claim fills.

Things to improve
1. Rewrite Visualization logic for adding claim elements as shown here
   https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/Visualization.java#L148
2. Add more visuals based on the player view to make the second visual posted above better. Visuals should be shown on the side blocks(since player is looking at the side) rather than just the top.
3. Allow visual block types to be configurable.
4. Improve performance during visuals.

pinging @DDoS for help =)

**Comment by Zidane** [comment]
Here is a thought @bloodmc 

Maybe WorldBorder could be utilized? So if you right click with the shovel, you are shown a WorldBorder that shows your claim. You could cancel the damage part of it and only show it for that player. Would be a good way to outline the claim well.

**Comment by ryantheleach** [comment]
If world borders don't appear to be feasible, you could trace a line perpendicular to the closest wall of the claim, and render some particles at the players eye height.

**Comment by ryantheleach** [comment]
Hey blood, just got a chance to help a server admin set stuff up today, running 2.0.0 on 1.8.9 I was having a lot of difficulty creating an admin claim around the whole spawn, the visuals were either underground or hard to see, when I traveled larger distances to cover the spawn, even when using the stick to attempt to see what was claimed.
