### ISSUE TITLE
SpongeServer - GriefPrevention commands not works

### ISSUE THREAD

**Issue by marekvac** [MinecraftPortCentral/GriefPrevention#731]
Hey, i have a sponge server 1.10.2 with this plugins:
- GriefPrevention 1.10.2-4.0.1.507
- LuckyPerms 4.2.17
- Nucleus 0.20.0-S5.1-1.10.2
- FlexibleLogin 0.17.4
- TotalEconomy 1.6.0
- UniverseGuard 1.0.5
- WorldEdit 1.10.2-6.1.5-SNAPSHOT

**Other mods:**
AppleCore, AppleSkin, AutoRegLib, BiblioCraft, Blocklings, CodeChickenLib, CoFH core, CTM, CustomMobSpawner, MoCreatures, DungeonTactics, ElevatorMod, FastLeafDecay, Hats, Chisel, iChuntil, ironchest, IvToolkit, JurassiCraft, library, LootBags, MagmaMonsters, maliscore, malisdoors, Mantle, mowziesmobs, Pams HarvestCraft, RecurrentComplex, ropebridge, TConstruct, ThermalEx, ThermalFoundation, ViesCraft

I can claim area. But any command from griefpreventions like /trust not works. It send me "Unkown command". No error send to console. But when my server starts sponge sends [this error](https://pastebin.com/D4Esaiw4).

- Sponge version: 1.10.2-2477-5.2.0-BETA-2793
- Operating system: Windows 7
- Java: Java 8
- Forge version: 1.10.2-12.18.3.2477

**EDIT: When i disable Nucleus, command workings.**

**Comment by bloodmc** [comment]
`1.10.2` is not supported. Update to `1.12.2`
