### ISSUE TITLE
Minor issue related to permission

### ISSUE THREAD

**Issue by wysohn** [MinecraftPortCentral/GriefPrevention#732]
Hi, I have a small compatibility issue that is out of my hand.

So before explain it, please take a look at this piece of code:

https://github.com/wysohn/TriggerReactor/blob/dd8295bf97ea0811f225a1dc0a0157ef6586ab42/src/main/java/io/github/wysohn/triggerreactor/sponge/manager/ExecutorManager.java#L120

I'm working on granting one time permission which can override other permission plugins. So when a player use command through the above code, the player object is wrapped with the class called  TemporarilyPrivilegedPlayer which is a child class of Player class. All it does is delegate every functionality of player instance, except the permission part. 

What I realized is that in GriefPrevention, I found the code below trying to cast Player instance to net.minecraft.entity.Entity.

https://github.com/MinecraftPortCentral/GriefPrevention/blob/e57001576db82aa12801316f7f10ec60159a1a05/src/main/java/me/ryanhamshire/griefprevention/permission/GPPermissionHandler.java#L532

But for my case, the TemporarilyPrivilegedPlayer is nothing more than a pure child class of Player (of Sponge API), so casting to net.minecraft.entity.Entity does not work even though Player class is in fact child class of org.spongepowered.api.entity.Entity. 

Please address this issue if possible.

Thank you!

**Comment by bloodmc** [comment]
OK thanks for report. I'll push a fix when I get some free time.
