### ISSUE TITLE
explosion spawns loot of block, that wasn't destroyed

### ISSUE THREAD

**Issue by VoGGi312** [MinecraftPortCentral/GriefPrevention#733]
GP Version | 1.12.2-4.3.0.645
Sponge Version | 1.12.2-2705-7.1.0-BETA-3341

Hi all, i have this problem
https://github.com/SpongePowered/SpongeForge/issues/1811

my config
https://pastebin.com/AGrXxT1u

pgdebug with appliedenergistics2:tiny_tnt
https://griefprevention.github.io/debug/?8PGUV0yaRX

pgdebug with ic2:mining_laser
https://griefprevention.github.io/debug/?kTMHq95dn9

https://i.imgur.com/FQpdWgg.jpg
Territory in private and not in private remained intact, but dropped blocks.

**Comment by bloodmc** [comment]
Set the flag `item-spawn` to false to workaround issue.
