### ISSUE TITLE
Toggle Claim Tool

### ISSUE THREAD

**Issue by JadenDevon** [MinecraftPortCentral/GriefPrevention#734]
Is there any way to toggle the claim tool so that you can use it as the regular item? Currently you are unable to do things such as put the item on a pedestal in modded servers because griefprevention overrides the ability to place the item. Rather than having to change the tool every time someone needs to use it in a mod, I think that it would be good for the player to be able to toggle it off and on as needed.

**Comment by bloodmc** [comment]
No that would be too confusing. If the golden shovel has uses with other mods then change the tool in config.
