### ISSUE TITLE
server crash, when user don`t have griefprevention.admin and use //set in region

### ISSUE THREAD

**Issue by VoGGi312** [MinecraftPortCentral/GriefPrevention#735]
GP645
SF3341

crash log
https://drive.google.com/open?id=1D68NE0b6CtqM_KIzwmkd1lE6ktv_hIPK

gamelog
https://drive.google.com/open?id=1A9AqHjV3Wvb0zybR1O1u_tkksFJrUtH2

**Comment by VoGGi312** [comment]
2146 sting in gamelog.
In the radius of the team was privat, and the person did not have the right to access private.

**Comment by bloodmc** [comment]
Reproduce it on a clean server and list steps as I requested.

**Comment by bloodmc** [comment]
Closing as I still cannot reproduce this.
