### ISSUE TITLE
Could not pass ChangeBlockEvent$Pre$Impl

### ISSUE THREAD

**Issue by ResponsibleBear** [MinecraftPortCentral/GriefPrevention#736]
Hello. Log is here

https://gist.github.com/ResponsibleBear/0b5171fe8de8f44115627895a450b507

[GP] Running GriefPrevention 1.12.2-4.3.0.646
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3353 
[GP] Running luckperms 4.2.51

**Comment by LemADEC** [comment]
I've not tried another versions between 3333 and 3353. From the change logs, it seems related to spongeforge build 3334.
Also, think again before downvoting someone helping you

**Comment by LemADEC** [comment]
Issue isn't reprodued with spongeforge-1.12.2-2705-7.1.0-BETA-3350.
According to kencinder, it probably came with 3351.

**Comment by bloodmc** [comment]
Fixed in latest SF

https://github.com/SpongePowered/SpongeCommon/commit/12224db5e9894a4bdd5196e05f279566002f8a52
