### ISSUE TITLE
Set the largest size of the territory

### ISSUE THREAD

**Issue by juzhijian** [MinecraftPortCentral/GriefPrevention#737]
![qq 20180726231413](https://user-images.githubusercontent.com/14793250/43271260-a3f9162a-9129-11e8-965f-5e91c841921d.png)
![qq 20180726231418](https://user-images.githubusercontent.com/14793250/43271265-a737b242-9129-11e8-95e7-cb0ab28a9a7e.png)
Setting is not effective

**Comment by bloodmc** [comment]
This will be improved in GP 4.4.0. For now you need to adjust the min/max using the following command

`/co option value default`

**Comment by juzhijian** [comment]
You don't have permission to assign an option to a group.

Added griefprevention.admin

**Comment by juzhijian** [comment]
I added griefprevention.admin，But it still hints that there is no authority。
