### ISSUE TITLE
Liquid is placable in claims

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#74]
https://www.youtube.com/watch?v=KLxuhlUbiaU
It seems that when the block isn't highlighted, you are able to place buckets in claims.
Not really easy to explain it, so here is a video.
The liquid is able to be placed in claims.

This has been used to grief several claims on my server, and is quite easy to do.
I consider this a "critical bug".

**Comment by bloodmc** [comment]
@inklit Is this resolved with latest build?

**Comment by inklit** [comment]
See issue #78

**Comment by SnowBlitzz** [comment]
I'm not having this issue on GP B10 and SF1509, however, the 'no permission to place water' message is a bit off.. http://prnt.sc/bmfiwm

**Comment by bloodmc** [comment]
@SnowBlitzz should be fixed in B10.

**Comment by SnowBlitzz** [comment]
You mean B11? since I was on B10 with that screenshot.
