### ISSUE TITLE
Throwing [morb] on protected region makes it just disappear (Thermal Expansion)

### ISSUE THREAD

**Issue by wysohn** [MinecraftPortCentral/GriefPrevention#742]
Version:
![image](https://user-images.githubusercontent.com/8789836/43390717-be2eea3e-93a3-11e8-9d12-af1bc345211d.png)
---
You don't have permission shows up, but the item consumes however.

It contains a mob inside this item (the morb can take a mob in it), so it disappears if this happens

**Comment by bloodmc** [comment]
Use `/gpdebug record`, throw item then `/gpdebug paste` and provide result here.

**Comment by wysohn** [comment]
https://griefprevention.github.io/debug/?OPNPbUstQc

I threw three [morb]s

---

And also, a player reported that he was playing in the protected region (not owned by him) killing zombies, and he lost his tools at some point.

Not sure if that's related to GP though

**Comment by bloodmc** [comment]
You are allowing item use here

`interact-item-secondary | minecraft:player | thermalexpansion:morb | (9893, 68, -11422) | wysohn | TRUE`

But you deny the block interact

`interact-block-secondary | thermalexpansion:morb.0 | minecraft:tallgrass.1 | (9893, 68, -11422) | wysohn | FALSE`

Just deny the `interact-item-secondary` to fix your issue.
