### ISSUE TITLE
Admin dont have permissions

### ISSUE THREAD

**Issue by astetyn** [MinecraftPortCentral/GriefPrevention#744]
Hello,

Admins cant do anything in basic claims created by other players. They have got permission griefprevention.admin and server have been restarted many times after that. Where can be problem?

**Comment by Lemmmy** [comment]
Have the admins tried running `/ignoreclaims`?

**Comment by astetyn** [comment]
Yes, with /ignoreclaims its working well. Thanks. But this only possiblity for that? Or is there something similar but permanent?

**Comment by Lemmmy** [comment]
Not to my knowledge, each admin will have to run `/ignoreclaims` (alias `/ic`) once after each time the server starts.

**Comment by astetyn** [comment]
Thank you very much. `/ic` is enough for me.
