### ISSUE TITLE
liquids and buckets dupe

### ISSUE THREAD

**Issue by ResponsibleBear** [MinecraftPortCentral/GriefPrevention#746]
Hello, here is video. 
https://youtu.be/T7bECqkE9ag

[GP] Running GriefPrevention 1.12.2-4.3.0.646
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3374
[GP] Running luckperms 4.2.51

**Comment by Zimon4eR** [comment]
![](https://i.imgur.com/CCEBiNq.png)

**Comment by bloodmc** [comment]
Deny `interact-item-secondary` and it shouldn't dupe. If it does, log a proper ticket in Sponge.
