### ISSUE TITLE
Assigning  Claim Blocks Accrued Per Hour for different groups.

### ISSUE THREAD

**Issue by makssymm** [MinecraftPortCentral/GriefPrevention#747]
I was wondering if there was a permission node or something I can do in the config to be able to set different variables for different groups.

For example the default Claim Blocks Accrued Per Hour is 100.
If someone donates for a rank I want that number to increase 
So for the donor rank I want to set it to;  Claim Blocks Accrued Per Hour: 250
For the next; Claim Blocks Accrued Per Hour: 350. and so on.

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Advanced-Options
