### ISSUE TITLE
Containertrust allows people to place blocks

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#75]
/containertrust allows players to place blocks, although they are unable to destroy them.

Not related to #74

**Comment by bloodmc** [comment]
@inklit Is this still an issue in latest build?

**Comment by inklit** [comment]
See issue #78

**Comment by SnowBlitzz** [comment]
This is not an issue on my server running latest SF and GP

**Comment by bloodmc** [comment]
@SnowBlitzz thanks, closing then.
