### ISSUE TITLE
Naturally spawning and used egg to spawn

### ISSUE THREAD

**Issue by lichenglin19901123** [MinecraftPortCentral/GriefPrevention#750]
Can you set up a monster or animal that cannot be naturally generated in the territory? But you can use eggs to create monsters or animals. I set the entity-spawn to false, which will make monster eggs and animal eggs too useable. I don't want this. Is there any special command that can be done? It is forbidden to produce creatures naturally in the territory, allowing the use of eggs to spawn.

**Comment by bloodmc** [comment]
Use /gpdebug and deny what shows up.
