### ISSUE TITLE
Block-place with water source being ignored when Interact-item-secondary being true

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftPortCentral/GriefPrevention#751]
If the claim has interact-item-secondary set to TRUE then block-place is checked, but ignored for water blocks being placed with a bucket.
https://griefprevention.github.io/debug/?YDV9K94n49

If the claim has interact-item-secondary set to false then the water is not placed (as expected)

https://griefprevention.github.io/debug/?wBeu5o2rop

![capture](https://user-images.githubusercontent.com/9203727/44005699-3bf96e78-9e3d-11e8-9701-c1d8c97fa465.PNG)

**Comment by bloodmc** [comment]
Please retest in GP 684+

**Comment by bloodmc** [comment]
Should be fixed in SF 3616 and GP 687+.
