### ISSUE TITLE
You can still change type of spawners even if interact-block-secondary is set to false

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#754]
Verbose:
https://luckperms.github.io/verbose/?A7m8PfINKx

This is false, but the spawner still changes to another type:
griefprevention.flag.interact-block-secondary.minecraft.mob_spawner.source.minecraft.spawn_egg.0.0

GP 646
SpongeForge 3371

**Comment by bloodmc** [comment]
Reopen if this occurs with GP 684+
