### ISSUE TITLE
Spawning of mobs through spawners is not tracked

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#755]
Place a mob_spawner in your world and set it to zombie (I think other types work too)

Use /lb verbose true

You won't see any mob spawner checks. Outcome: You can't block spawning though spawners.

Might be a Sponge issue though

GP 646
SpongeForge 3371

**Comment by bloodmc** [comment]
It is tracked, you are most likely testing as an admin or an owner of claim which will go through trust instead of permissions.

**Comment by i9hdkill** [comment]
Yes, I was testing as an admin. But setting the spawning to false as override should stop the spawner regardless of any admin stuff. How should blocking spawns work else?

**Comment by bloodmc** [comment]
```
entity-spawn | minecraft:mob_spawner.0 | minecraft:pig | (-363, 91, 145) | default | FALSE
entity-spawn | minecraft:mob_spawner.0 | minecraft:pig | (-363, 91, 147) | default | FALSE
entity-spawn | minecraft:mob_spawner.0 | minecraft:pig | (-361, 91, 149) | default | FALSE
```

Works for me. Test on a clean server.

**Comment by i9hdkill** [comment]
Updated to latest SF. Yeah it kinda works.
Do the following. Place a spawner on another players basic claim using /ic. Block entity.spawn pig.
Pigs are still spawning. Do /ic again. Pigs spawning is blocked as you lost permissions on this claim. But I want to block spawning at all times. Even if you own the claim where the spawner is in. Or in other words, blocking spawning from entity types globally.

**Comment by bloodmc** [comment]
Next time try to state exactly what is occuring =). The issue was simply override not being checked when trusted. Should be fixed in next build.

**Comment by i9hdkill** [comment]
I tried:D Thanks for fixing!
