### ISSUE TITLE
/givepet not working (1.13)

### ISSUE THREAD

**Issue by DesignedbyTom** [MinecraftPortCentral/GriefPrevention#756]
When you preform the command /givepet (username) it tell you too right click the pet, but when you right click it only sits/stands/interacts with the pet. And no message appears confirming the transfer, and it does not transfer.

**Comment by DrZoddiak** [comment]
Sponge GP has not been made to be API8 compatible since Sponge for API8 is not released.

**Comment by DesignedbyTom** [comment]
I am not using sponge, I am using the latest release of Spigot/Bukkit 1.13

**Comment by bloodmc** [comment]
This repo is for Sponge only. Create a ticket here for Spigot/Bukkit
https://github.com/TechFortress/GriefPrevention
