### ISSUE TITLE
items lost on death due to invalid flag & target?

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#758]
As of spongeforge-1.12.2-2705-7.1.0-BETA-3409.jar + griefprevention-1.12.2-4.3.0.652.jar, when a player die in a claim with item-spawn = false, keepInventory = false, all his inventory gets deleted with no item dropped.
This also happens if said player is the owner of the claim.

According to gpdebug:
- when a player dies, we have Flag = item-spawn, Target = minecraft:custom
- when a player drops, we have Flag = item-drop, Target = minecraft:player

I think we've 2 issues here, not sure if they're in GriefPrevention or SpongeCommons:
1- when dying, Flag should be item-drop with Target being the player
2- when item-spawn is cancelled, items should be returned to player's inventory, this might be a consequence of the invalid flag?

Issue is reproduced with no mods (only a bunch of plugins).
Issue is reproduced with spongeforge-1.12.2-2705-7.1.0-BETA-3355.jar.
Issue is reproduced with griefprevention-1.12.2-4.3.0.646.jar.
I didn't try other versions.

**Comment by bloodmc** [comment]
In latest GP, `item-spawn` no longer affects living entities so this should no longer be an issue.
