### ISSUE TITLE
False Portal Use Message

### ISSUE THREAD

**Issue by xChristopher210** [MinecraftPortCentral/GriefPrevention#76]
My players keep getting spammed by a message thats saying they cant use a portal in my claim even though that are standing around. They are not going into a portal at all.

![36c0ddeee3276ae57af20ce1a179c57f3d882cdba88d36dab7 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13145453/16432774/4ac8c9d4-3d4c-11e6-8032-1ed055fe5178.jpg)

Running:
SpongeForge Version: 1508 (API 4.2.0)
Forge Version: 1890 (1.8.9)
Pixelmon Version: 4.2.7 (1.8.9)
GriefPrevention 1.0-8 (1.8.9)

**Comment by bloodmc** [comment]
Fixed in commit 
https://github.com/MinecraftPortCentral/GriefPrevention/commit/c69eb480089c369670a4f752ddc9ccc0b436ea6f
