### ISSUE TITLE
Can't set clam flag for Forestry fluids

### ISSUE THREAD

**Issue by braunly** [MinecraftPortCentral/GriefPrevention#760]
`/cf liquid-flow forestry:fluid.biomass false override`
![2018-08-22 13_32_05-minecraft 1 12 2](https://user-images.githubusercontent.com/8600722/44458774-ef0b1000-a60f-11e8-81d1-d0fb0b876e97.png)
`/gpversion`
![2018-08-22 13_33_28-minecraft 1 12 2](https://user-images.githubusercontent.com/8600722/44458812-0a761b00-a610-11e8-8b8e-9895e755e502.png)

**Comment by bloodmc** [comment]
Unfortunately GP 4.3.0 sources require targets. The next update improves sources but has not been released yet.

**Comment by braunly** [comment]
Thank you
But, i have another issue with liquid-flow
