### ISSUE TITLE
Block-Inventories doesn't drop their items

### ISSUE THREAD

**Issue by EscolarProgramming** [MinecraftPortCentral/GriefPrevention#761]
Hello everybody,
there's an error related to GP 4.3.0.652 and SF 3406:
If you break a chest (or another block with an inventory, e.g. a dispenser) the items inside will not be dropped. It doesn't occure in wilderness but in basic and admin claims.
I think the problem is related to the permissions because it will not drop if you have `griefprevention.basic` or `griefprevention.admin` but it will work with the permission `griefprevention.*` and to the fired events.
Here's a debug log with normal permissions: https://pastebin.com/WqiFuVyy
And here with the wirldcard: https://pastebin.com/vEbxM6Jt
So you can see in the second debug log the `DropItemEvent.Destruct` event is fired for the items too but in the first log it's only fired for the chest itself.

**Comment by MorbiusStorm** [comment]
Same here. GP 652, SF 3413. Cant farm items. They don't spawn in when you right click. But with griefprevention.* permission it works. Looking like this might affect a lot of things.
