### ISSUE TITLE
Wrench on signs working in admin claim area

### ISSUE THREAD

**Issue by ehmitchell3** [MinecraftPortCentral/GriefPrevention#767]
Hello all.

I've set up an admin claim, but any of the wrenches (IC2, Thermal, Ender, AE2) seem to still manipulate the signs.

Things I've done:
* Use standard admin claiming
* Set specific "**item-use**" flag for each wrench
* Set the flag "/cf **interact-item-primary** ic2:wrench minecraft:sign false" and "/cf **interact-item-secondary** ic2:wrench minecraft:sign false".

**Edit**: In addition, satchels (Thermal Series:Tools) bypass chests on claims (can place in, but not take out) when using right click.

I can provide a list of mods, but we're on 1.12.2. 

Thanks!

**Comment by ehmitchell3** [comment]
Any update? Thanks!

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/b5cae67239f09654f8c5aeb0945db92f6463c23a

Update to GP 684+
