### ISSUE TITLE
Softmute settings

### ISSUE THREAD

**Issue by xion87** [MinecraftPortCentral/GriefPrevention#769]
I upgraded griefprevention and now player are getting random softmuted with no expire when they flood a little the chat, there is no setting and configurable option, but i would like to add a toggle config... 
GFP 4.3.0.654
MC 1.12.2
Forge 2705
Spongeforge 1.12.2-2705-7.1.0-BETA-3361

**Comment by bloodmc** [comment]
Disable chat protection if you don't want to use it. It's in GP's chat section of config.

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/configuration/category/GeneralCategory.java#L59
