### ISSUE TITLE
Disabling PvP

### ISSUE THREAD

**Issue by xChristopher210** [MinecraftPortCentral/GriefPrevention#77]
Trying to disable PvP in multiple ways but it doesn't work at all. People still beat each other rather then them not being able to do it at all which i intend.

I'm doing the command:
`/cf interact-entity-primary minecraft:player false`
(Since PvP flag is not working yet)

![44d684ce1086f214ccfd499a30c16172f0cee34414bdc38af4 tfile_urlpv](https://cloud.githubusercontent.com/assets/13145453/16432856/d478e880-3d4c-11e6-8cd7-e947b458e1c8.png)

Running:
SpongeForge Version: 1508 (API 4.2.0)
Forge Version: 1890 (1.8.9)
Pixelmon Version: 4.2.7 (1.8.9)
GriefPrevention 1.0-8 (1.8.9)

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/c69eb480089c369670a4f752ddc9ccc0b436ea6f
