### ISSUE TITLE
Players losing permission in their claims. GP: 655

### ISSUE THREAD

**Issue by Shybella** [MinecraftPortCentral/GriefPrevention#771]
http://prntscr.com/kvv1bl

Players are losing permissions inside their own claims. They are fixing it by abandoning their claim and recreating the claim.

Rolling back to 646 resolves the problem.

If you need any additional information I am able to assist.

**Comment by bloodmc** [comment]
Provide GP configs and GP debug logs.

**Comment by Shybella** [comment]
This was caused by a bug in Sponges cause tracker.
