### ISSUE TITLE
Ghost claims

### ISSUE THREAD

**Issue by EscolarProgramming** [MinecraftPortCentral/GriefPrevention#775]
We have a problem with "ghost claims" (claims that don't exist but prevent to create a new claim or expand an existing one).
The two red marked blocks in the first screen are such ghost claims. All blocks on the right side of the leaves are part of a real claim. But if you want to expant that claim it will be blocked ("Your selection would overlap another claim - No claims found in world", see second screen).
If I shift-rightklick with a stick to show all existing claims it says that there are two claims, but only one of them (the unbuggy one) is listed.

![claimbug](https://user-images.githubusercontent.com/6965961/45921084-d1e78c80-beae-11e8-829e-4cb09db31b17.jpg)

![java_2018-09-22_21-30-40](https://user-images.githubusercontent.com/6965961/45921087-de6be500-beae-11e8-912e-6c3b8766c656.png)

I'm running on GP 1.12.2-4.3.0.653 and SF 1.12.2-2705-7.1.0-BETA-3406

**Comment by bloodmc** [comment]
Please zip your griefprevention folder and provide the location in world where this issue happens.

**Comment by EscolarProgramming** [comment]
Okay, I've found the solution:
There was an old subdivision claim of a claim which no more exist (It was stored in /world/ClaimData/subdivision and not in /world/ClaimData/basic/subdivision). So the subclaim still exists but the parent claim is deleted. It won't be shown in the list because it's only a children claim but you are not able to delete it because the original one doesn't exist (I hope you can understand what I mean :D)

**Comment by EscolarProgramming** [comment]
It wasn't enough, it's still buggy :( The both affected blocks are at x2070/z3038 and x2071/z3038.
Here's a link to the griefprevention-folder: 
[griefprevention.zip](https://github.com/MinecraftPortCentral/GriefPrevention/files/2416781/griefprevention.zip)
