### ISSUE TITLE
Interactive chat are blocked by Litebans mute anti-bypass

### ISSUE THREAD

**Issue by xion87** [MinecraftPortCentral/GriefPrevention#779]
I noticed if i use Litebans in bungeecord that got this option
 If enabled, muted players cannot use commands containing ":", for example: "/minecraft:me".
  prevent_bypass: true

And player for example do /claimlist and click anything on interactive chat, these command will be all blocked by that litebans setting, (i think because these click thing will redirect to command like "griefprevention:claim tp" like.
Is fixable?

**Comment by bloodmc** [comment]
Test with GP 684, SF3616 and state exact steps to replicate.

**Comment by xion87** [comment]
is safe to use these on product server with pixelmon?

**Comment by xion87** [comment]
tried, same thing, litebans is on bungee side

**Comment by bloodmc** [comment]
LiteBans is not open source so I have no clue what they are doing. Open a ticket with LiteBans as it is cancelling the event when a user uses a command using `:`.
