### ISSUE TITLE
Explosions occasionally don't respect claims

### ISSUE THREAD

**Issue by Brycey92** [MinecraftPortCentral/GriefPrevention#780]
Sometimes, when a mob explodes or an untrusted player sets off TNT in/around your claim, the explosion is allowed despite the `explosion` and `explosion surface` flags being set to false in the claim. The effect is very noticeable if a player creates a large ball of TNT outside your claim and sets it off.

I'm running SF 1.12.2-2705-7.1.0-BETA-3361 and GP 1.12.2-4.3.0.653.

**Comment by Brycey92** [comment]
I created a wall of logs at the edge of a claim and a dense ball of TNT which I lit off. Most of the logs weren't affected, but a large chunk at the bottom of the wall was.
https://griefprevention.github.io/debug/?vVexqVJu4B

I still need to test this having an untrusted non-admin player set off the TNT, though.

**Comment by bloodmc** [comment]
Please retest with GP 677+ and latest SF.

**Comment by bloodmc** [comment]
Unable to reproduce with GP 677+ and latest SF.

**Comment by Brycey92** [comment]
Thanks for testing this!
