### ISSUE TITLE
There is a hardcoded minimum claim size of 10

### ISSUE THREAD

**Issue by Brycey92** [MinecraftPortCentral/GriefPrevention#782]
setting the permission `meta.griefprevention\\.min-claim-size-basic-x.5` in LP results in the min claim X size being 10, but setting it to 50 results in it being 50 correctly. The same happens with the Z coordinate and its permission node.

I'm running SF 1.12.2-2705-7.1.0-BETA-3361 and GP 1.12.2-4.3.0.653.

**Comment by Brycey92** [comment]
Evidently a duplicate of #696, and there's a workaround in 0df8e2d. I'll leave this open in anticipation of no workaround being required in GP 4.4.0, unless blood prefers to close it.

**Comment by bloodmc** [comment]
As my commit message states, you must also update the default value as it acts as an admin limit. This will change in next major version but it is working as intended currently.
