### ISSUE TITLE
It should be possible to specify any mod ID in entity flags

### ISSUE THREAD

**Issue by Brycey92** [MinecraftPortCentral/GriefPrevention#786]
This is a feature request to allow specifying any:hostile, any:aquatic, etc. instead of having to specify one flag for every mod. With a large number of mods, this can become tedious fast, and it's easy to forget to setup flags in GP for new mods that are added.

I'm running SF 1.12.2-2705-7.1.0-BETA-3361 and GP 1.12.2-4.3.0.653.

**Comment by bloodmc** [comment]
A mod id is required based on how permissions are setup for flags.

`minecraft:animal` would use permission `griefprevention.flag.entity-spawn.minecraft.animal`

If any were used, it would use permission `griefprevention.flag.entity-spawn.animal`.

This would cause a problem as all entities will have modid, type, and name in their permission checks. The only way to handle `any` would be to do another check always. I really try to avoid adding additional permission checks as it can lead to performance issues. GP already has too many which is what I've been cleaning up for next major update.
