### ISSUE TITLE
Spamming diamond chisel and ichisel bypasses claims

### ISSUE THREAD

**Issue by Brycey92** [MinecraftPortCentral/GriefPrevention#787]
When left-clicking normally on chiselable blocks in someone else's claim with either a diamond chisel or ichisel, protection works normally. When left-clicking very quickly, some clicks are not caught, and the blocks are chiseled. This is confirmed not to be client-side only, as a relog does not return the blocks to their original state.

I'm running SF 1.12.2-2705-7.1.0-BETA-3361 and GP 1.12.2-4.3.0.653.

**Comment by kencinder** [comment]
Tested this using claimflagdebug in an Admin claim, on a stone block with a diamond chisel.

Was able to reproduce by spamming left-click and the block is changed, if single left-clicking at a normal pace, the block is unchanged.

Block state changes very rapidly when spamming left-click, possibly why it's not being caught?

spongeforge-1.12.2-2705-7.1.0-BETA-3481
GriefPrevention-4.3.0.662

**Comment by bloodmc** [comment]
This was fixed in later SF build that fixed various interaction event issues. Update to SF 7.1.5+
