### ISSUE TITLE
Permission 'griefprevention.claim.command.trust.remove' is wrong

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#79]
Using GriefPrevention (build 8), PermissionsEx, Forge 1890, and Sponge 1509.

Not sure if this was changed or not, but the actual permission node is 'griefprevention.claim.trust.command.remove' according to PermissionsEx debug mode, which is not the same one that shows in https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/GPPermissions.java 

I think this might be helpful for some people to know.

**Comment by bloodmc** [comment]
@inklit This was already fixed, read the commits or changelog. Use Build 11.
