### ISSUE TITLE
Players can place and pick up fluids

### ISSUE THREAD

**Issue by Brycey92** [MinecraftPortCentral/GriefPrevention#790]
In a claim they're not trusted to, players can spam empty or full buckets and place/pick up fluids.

https://griefprevention.github.io/debug/?ZxGcFuJwy3

I'm running SF 1.12.2-2705-7.1.0-BETA-3361 and GP 1.12.2-4.3.0.653.

**Comment by bloodmc** [comment]
This is not a GP bug and was already fixed in Sponge. Update SF.

**Comment by Brycey92** [comment]
Thanks for the notice! I haven't had enough free time lately to update yet, but I will soon.

**Comment by Brycey92** [comment]
This is not fixed in SF 3477, and that's the latest version of SF. Please reopen this.
