### ISSUE TITLE
duplicating dragon egg

### ISSUE THREAD

**Issue by theumbreonl0rd** [MinecraftPortCentral/GriefPrevention#791]
When dragon eggs are clicked by someone who doesn't have perms in the admin claim it teleports a copy of the egg while keeping the original leading to lots of people getting dragon eggs.

**Comment by kencinder** [comment]
Tested with placed egg in an admin claim, egg would teleport normally for player with permission, for player without permission the egg did absolutely nothing and stayed where it was, and no duplicates were created.

spongeforge-1.12.2-2705-7.1.0-BETA-3481
GriefPrevention-4.3.0.662

**Comment by bloodmc** [comment]
Unable to reproduce on latest SF/GP.
