### ISSUE TITLE
Duplicating certain items

### ISSUE THREAD

**Issue by theumbreonl0rd** [MinecraftPortCentral/GriefPrevention#792]
Some items can be duped if the person isn't trusted in the admin claim if the object does not take up the whole space that a block would. For example skulls, torches and even some modded items that do not fill up a whole blocks hitbox.

**Comment by kencinder** [comment]
Tested spamming placement of a skeleton skull and torch in an admin claim, and could not reproduce any duplication.

spongeforge-1.12.2-2705-7.1.0-BETA-3481
GriefPrevention-4.3.0.662

**Comment by bloodmc** [comment]
Create a new ticket if this occurs with GP 677+ and latest SF.
