### ISSUE TITLE
/cf command-execute nucleus.tpahere returns error

### ISSUE THREAD

**Issue by Shiunin** [MinecraftPortCentral/GriefPrevention#793]
Hello,

I am using 'griefprevention-1.12.2-4.3.0.646.' and am trying to restrict nucleus tpahere command, with this command:

`/cf command-execute nucleus.tpahere false`

and I encountered this error:

> "Error occurred while executing command: Missing required argument in TextTemplate "type".

**Comment by kencinder** [comment]
Incorrect formatting for the flag, according to the in-game info.

Should be `/cf command-execute nucleus:tpahere false`
