### ISSUE TITLE
Missing change logs

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#796]
Since end of August, version 4.3.0.654 and up, the change logs are empty on the download website.
Is there a new place to get those?

**Comment by Zimon4eR** [comment]
![](https://i.imgur.com/a7IzyCl.png)
https://github.com/MinecraftPortCentral/GriefPrevention/commits/master

**Comment by DrZoddiak** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/commits/master

**Comment by bloodmc** [comment]
Downloads and changelogs are now on ore.
