### ISSUE TITLE
OpenBlock block breaker can't be used inside claims

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#797]
As of griefprevention-1.12.2-4.3.0.662.jar + spongeforge-1.12.2-2768-7.1.2-RC3493.jar, we can't use OpenBlock block breaker inside claims.

When using /gpdebug, the report says:

Flag/Trust | Source | Target | Location | User | Result
-- | -- | -- | -- | -- | --
block-break | fakeplayer:openmodsfakethis-001 | minecraft:cobblestone | (768, 97, 769) | OpenModsFakethis-001 | FALSE

It appears the cause tracker didn't detect the player and remains with a fake player source.

When trying to update flags with said fake players it fails:
`/cf block-break fakeplayer:openmodsfakethis-001 minecraft:cobblestone true override` says there's too many arguments
`/cf block-break minecraft:player minecraft:cobblestone true override` works fine
`/trust OpenModsFakethis-001` and `/trust fakeplayer:openmodsfakethis-001` are both failling

To work around this issue, I've tried to give a blanket permission with `/cf block-break minecraft:cobblestone true override`, but the block breaker is still denied according to gpdebug:

Flag/Trust | Source | Target | Location | User | Result
-- | -- | -- | -- | -- | --
entity-spawn | none | minecraft:zombie | (1246, 134, 768) | default | TRUE
trust.ignore | none | minecraft:zombie | (1246, 134, 768) | LemADEC | TRUE
block-break | fakeplayer:openmodsfakethis-001 | minecraft:cobblestone | (768, 97, 769) | OpenModsFakethis-001 | FALSE
block-break | fakeplayer:openmodsfakethis-001 | minecraft:cobblestone | (768, 97, 769) | OpenModsFakethis-001 | FALSE
block-break | fakeplayer:openmodsfakethis-001 | minecraft:cobblestone | (768, 97, 769) | OpenModsFakethis-001 | FALSE
block-break | fakeplayer:openmodsfakethis-001 | minecraft:cobblestone | (768, 97, 769) | OpenModsFakethis-001 | FALSE
block-break | fakeplayer:openmodsfakethis-001 | minecraft:cobblestone | (768, 97, 769) | OpenModsFakethis-001 | FALSE

**Comment by bloodmc** [comment]
@LemADEC Is this still an issue with GP 677+ ?

**Comment by LemADEC** [comment]
OpenBlocks block breaker still fails to break blocks inside claims: https://griefprevention.github.io/debug/?EzWovRL0MF

Flag | Trust | Source | Target | Location | User | Result
-- | -- | -- | -- | -- | -- | --
interact-block-secondary | accessor | minecraft:grass.0 | minecraft:lever.5 | (1049, 65, 589) | LemADEC | TRUE
block-break | none | openmods:fakeplayer_openmodsfakethis001 | minecraft:grass | (1050, 64, 589) | default | FALSE

It does work outside claim.
I didn't try any flags.
Sponge did report issues in the console during the test, maybe from placing the block? https://gist.github.com/LemADEC/0c9e467fd69dd72faec105dba76e79d8

Tested on FTB Continuum 1.6.0, including OpenBlocks-1.12.2-1.8,
 with spongeforge-1.12.2-2768-7.1.6-RC3596 and griefprevention-1.12.2-4.3.0.677.

**Comment by bloodmc** [comment]
This will be resolved soon =) Requires changes to both SpongeForge and GP.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/2995ef7f13a1839c9a56ebc0c778ed1e5d204826

https://github.com/SpongePowered/SpongeCommon/commit/6f51d6471d0f26832f297528e033ef32ed449482
