### ISSUE TITLE
Spam Filter Not Detecting IPs

### ISSUE THREAD

**Issue by xChristopher210** [MinecraftPortCentral/GriefPrevention#80]
I recently had a person come on my server and advertised. However GP did not pick up the IP and did not censor the IP. The person did not do anything to work his/her way around to make the ip not be censored, he did infact paste the IP in my chat perfectly without any workarounds make to it.

This is the exact message of the player that constantly spammed this message over and over until GP kicked him and I banned him straight afterwards.

`29.06 18:22:01 [Server] Server thread/INFO [Trainer]Playername ➟ Hey guys, I got a new server at play.server.com Would LOVE if you joined! You start with a m-ball`
_I replaced his name and his ip_

Builds Running Currently:
SpongeForge Version: 1509 (API 4.2.0)
Forge Version: 1890 (1.8.9)
Pixelmon Version: 4.2.7 (1.8.9)
GriefPrevention: Build 11 (1.8.9)

**Comment by SnowBlitzz** [comment]
Don't think it had an IP filter before but would be nice to have.

**Comment by ryantheleach** [comment]
ALso they didn't post an "IP" they posted a url. unless you censored everything that looked like a link you wouldn't be able to nicely automate this.

**Comment by bloodmc** [comment]
Spam filter should be working properly in latest builds.
