### ISSUE TITLE
"Too many arguments" from RFTools builder as source

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#800]
Seems the source for the RFTools builder is in a format that GP can't handle, and you get "Too many arguments" when trying to use it.

`rftools:rftools:builder`

https://griefprevention.github.io/debug/?hZxjtjkxx8

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/ec09c5190f78e85c38e17202369d943d2ce725c9
