### ISSUE TITLE
Request - ClaimCreatedFullyEvent

### ISSUE THREAD

**Issue by TerminatorNL** [MinecraftPortCentral/GriefPrevention#802]
Hey there, is it possible to fire another non-cancellable event where claims that have successfully created are exposed?

Right now, claims inside `me.ryanhamshire.griefprevention.api.event.CreateClaimEvent` are not fully initialized. All activities between line [2835](https://github.com/MinecraftPortCentral/GriefPrevention/blob/e829946b81c0a167e2ffda637cedc7596f7ea36e/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaim.java#L2835) and line [2860](https://github.com/MinecraftPortCentral/GriefPrevention/blob/e829946b81c0a167e2ffda637cedc7596f7ea36e/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaim.java#L2860) are missing.

My suggestion would be to create an event containing `me.ryanhamshire.griefprevention.claim.GPClaimResult`.

I am currently using a workaround where I wait for the next server tick so I know that a claim has been created for sure, which is not very elegant.

Thank you for your attention.

**Comment by bloodmc** [comment]
I'll just add a Pre/Post sub interface to the event which will solve your issue.

**Comment by TerminatorNL** [comment]
Thank you very much.
