### ISSUE TITLE
Players can place rails even when block-place=false

### ISSUE THREAD

**Issue by Shmeeb** [MinecraftPortCentral/GriefPrevention#816]
SpongeAPI: 7.1.0-6eb292fd
Sponge: 1.12.2-7.1.5-SNAPSHOT
SpongeForge: 1.12.2-2768-7.1.5-RC3512
Minecraft Forge: 14.23.5.2768
GP: griefprevention-1.12.2-4.3.0.662

It also doesn't take the rail out of their inventory when they place it

GPDebug: https://i.gyazo.com/08b1a37736703e7a2a3be41adf9eb173.png

Lead to this, lol: https://cdn.discordapp.com/attachments/513968670091771938/520686094577303562/2018-12-07_11.33.17.png

**Comment by bloodmc** [comment]
Unable to reproduce with latest SF and clean GP server. Please test with a clean server and reproduce.

**Comment by bloodmc** [comment]
Please reopen if this issue occurs on GP 677 with latest SF.
