### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Meta-Win** [MinecraftPortCentral/GriefPrevention#817]
(Sponge + Tech Reborn + Grief Prevention)
When a player have /accesstrust or /containertrust on a claim, he can use wrenchs to dupe and steal machines.
When right-click a machine with a wrench, it will drop the machine, but it don't will be removed from the claim. After some attempts, the user will finally steal the machine from the claim(with 6+ identical machines).

**Comment by Meta-Win** [comment]
I have a new problem now, when you keep trying to remove the machine with a wrench without permission on the claim, the machine disappears.

**Comment by LemADEC** [comment]
Is only a specific wrench from a specific mod?

**Comment by bloodmc** [comment]
Create a new ticket if you are having another issue.
