### ISSUE TITLE
PVP Override in claim settings doesnt override sponge dimension config as it should

### ISSUE THREAD

**Issue by xReckless** [MinecraftPortCentral/GriefPrevention#819]
pvp is set to true in server.properties and in the global sponge config turned it off in the overworld config but still cant damage players with the override set to true
Running SpongeForge 1.12.2-2768-7.1.2-RC3493
Running GriefPrevention 1.12.2-4.3.0.662

**Comment by bloodmc** [comment]
PVP must be enabled in Sponge or it will never work. This is not a GP issue as you are doing it the wrong way. Enable PVP in Sponge then disable/enable PVP in GP claims.

**Comment by xReckless** [comment]
Might want to update the wiki then
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Claiminfo

**Comment by kencinder** [comment]
Looking at this more, it is an issue, at the very least the wording of the wiki. The wiki behaviour appears that GP can override Sponge's settings.

In the situation that the server owner wants PVP off everywhere except a specific claim, having PVP true in Sponge config means that /claiminfo PVP option of FALSE does work. But this also means that you have to set this to FALSE in every claim, as there doesn't appear to be a way to set the option as a default for all claims.

In the case Sponge's PVP setting is false, then ALL GP PVP options = FALSE, making the entire option fairly pointless as a result as you cannot set any claim TRUE.

If GP can in fact override Sponge's config for this, it should. Multiple users have asked for this behaviour in Discord.

**Comment by bloodmc** [comment]
@xReckless @kencinder This issue has been addressed in latest SpongeForge RC3518+. It will also require latest GP build which can be found on Sponge's Ore.
