### ISSUE TITLE
Piston timeout

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#82]
Piston moving pistons can timeout a server inside a claim

**Comment by bloodmc** [comment]
@SnowBlitzz you need to provide the crash report and/or server logs.

**Comment by SnowBlitzz** [comment]
I don't think there's anything on the server logs. When the lever is flicked, everyone gets timedout and nobody can join the server until it is restarted. Blacklisted pistons for now and will start testing on a test server as soon as I can. I'll update you with more info soon.

**Comment by SnowBlitzz** [comment]
Yep just tested this twice. Nothing shows up on the server console. The server doesn't really 'crash' so there's no crash log either. It just kicks me out with the message "Timed out" and whenever I try to join back I get the same message (so nobody can join, but the server still displays x amount of people online when there are none) until I restart the server.

**Comment by SnowBlitzz** [comment]
[2016-07-02-1.log.gz](https://github.com/MinecraftPortCentral/GriefPrevention/files/344791/2016-07-02-1.log.gz)
This is the log for when I tested the item frames with someone. At the very end of the log where pioavenger leaves, I flicked the lever of the contraption. That's all in the log btw nothing shows after...

**Comment by bloodmc** [comment]
@SnowBlitzz That is not the log I need. You need to send me the FML server log which can be found within the logs folder.

**Comment by SnowBlitzz** [comment]
For some reason I couldn't upload the zip or rar here so uhhh, here https://www.dropbox.com/s/atesib1gfmlp6kt/FMLlogs.rar?dl=0

**Comment by inklit** [comment]
I experience a similar bug with complex piston machines on my server, although it leaves piston heads behind with no piston base. The piston heads are very hard for players to remove themselves.

**Comment by cartman-2000** [comment]
This also fixes a block duplication bug with falling blocks.

**Comment by inklit** [comment]
It also fixes a duplication glitch with ComputerCraft turtles (although now they can just plow through claims instead of sitting there duplicating blocks)
