### ISSUE TITLE
command-execute default set false behaves as an override would

### ISSUE THREAD

**Issue by kencinder** [MinecraftPortCentral/GriefPrevention#823]
Doing `/cf` and clicking on the default setting for `command-execute` and setting it false in a basic claim, winds up causing the flag to affect even the claim owner, leaving you with no recourse to fix it unless you edit the flag in `/luckperms/sponge-data/defaults/default.json` and restart the server.

I did not test this in an Admin claim, very short on time at the time, but the behavior may extend to it and possibly the wilderness.

**Comment by kencinder** [comment]
I had some more time to test this just now, the behavior is present in BASIC and ADMIN claims, but not in the wilderness.
Moving to a different claim type or wilderness and doing `/ic` allows you to move back and change the flag back.

**Comment by bloodmc** [comment]
I added a workaround for admins, i'll add a fix for owners soon.
