### ISSUE TITLE
invisible walls / getting stuck in claim

### ISSUE THREAD

**Issue by demonte4509ui** [MinecraftPortCentral/GriefPrevention#824]
so I have been having a recurring issue players will claim things and then suddenly they get stuck and whenever they get stuck they go invisible to even admins, they cant tp out or go back to their claim. when I remove the mod it fixes everything but when I put It back in it returns, the only way I was to fix it the first time was to make a new world but I don't have that option now as I have too many players and I don't know what to do to fix it.

**Comment by bloodmc** [comment]
What GP version? What Sponge version? Paste logs.

**Comment by bloodmc** [comment]
Closing as there is no information at all.
