### ISSUE TITLE
Levers Don't work w/ AccessTrust Public

### ISSUE THREAD

**Issue by system-operator** [MinecraftPortCentral/GriefPrevention#826]
forge-1.12.2-14.23.5.2807-universal
Spongeforge-1.12.2-2768-7.1.5-RC3515
griefprevention-1.12.2-4.3.0.673
LuckPerms-Sponge-4.3.79

Levers aren't working with latest build + accesstrust public. 

Have also specifically added the perms to no avail. Bug?

**Comment by system-operator** [comment]
Tested with Build 673, still broken.

**Comment by system-operator** [comment]
Was server.properties spawn protection, please close!

**Comment by kencinder** [comment]
You are able to close your own tickets
