### ISSUE TITLE
Sticky Piston Dupe

### ISSUE THREAD

**Issue by Monokuma1** [MinecraftPortCentral/GriefPrevention#827]
After updating GP to 673, the sticky-piston-pushes-block dupe still exists on my server. 

Using the following
 griefprevention-1.12.2-4.3.0.673.jar
LuckPerms-Sponge-4.3.79.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3392

Note: I did try the latest recommended version of SF but that didn't help either.

**Comment by bloodmc** [comment]
Provide a test world that can reproduce the issue. Make sure to list where test setup is located.

**Comment by Monokuma1** [comment]
I am unable to reproduce the duping on the test world as I am on my live server

**Comment by bloodmc** [comment]
Then copy the chunk where the issue is to the test world to reproduce. If it still cannot be reproduced then replace all the pistons to see if that solves it.

**Comment by Monokuma1** [comment]
I resolved it by deleting the worlds folder in the config and letting it reload. Sorry for the inconvenience.
