### ISSUE TITLE
Block Position Resets

### ISSUE THREAD

**Issue by system-operator** [MinecraftPortCentral/GriefPrevention#828]
forge-1.12.2-14.23.5.2807-universal
Spongeforge-1.12.2-2768-7.1.5-RC3515
griefprevention-1.12.2-4.3.0.673
LuckPerms-Sponge-4.3.79

When a player doesn't have permission, and breaks modded blocks from Thermal, Immersive mods, the blockstate/position is reset. (Ducting, Breakers, Servos, so much more...)

**Comment by bloodmc** [comment]
Provide exact steps on how to reproduce issue.

**Comment by kencinder** [comment]
This is just a visual glitch, logging out and back in, or leaving the area and coming back corrects it.

**Comment by bloodmc** [comment]
Unable to reproduce on latest SF/GP. Update to SF 3614+ and GP 681+
