### ISSUE TITLE
Players do not take fall damage

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#83]
Admins can take fall damage, but players can't.
This happens in all claims, including the wilderness.

Using build 11.

**Comment by SnowBlitzz** [comment]
My players could take damage. In fact a lot has died from falling lately.

**Comment by inklit** [comment]
It seems players can only take fall damage inside of claims that they are trusted in.

**Comment by SnowBlitzz** [comment]
Hmmm yeah. ^
