### ISSUE TITLE
Notenoughwands bypass

### ISSUE THREAD

**Issue by Shybella** [MinecraftPortCentral/GriefPrevention#830]
The moving wand from Notenoughwands bypasses GriefPrevention claims once again.

Mod: notenoughwands-1.12-1.7.1
SF: RC3549
Debug: https://griefprevention.github.io/debug/?409bFS0e76

Can move blocks inside claims even though debug catches it as false.

**Comment by bloodmc** [comment]
Issue is with mod, i spoke to dev and he will fix it soon.

https://github.com/romelo333/notenoughwands1.8.8/issues/30
