### ISSUE TITLE
Random Things | Block Breaker, allowing source (block's id) doesn't work.

### ISSUE THREAD

**Issue by BitCrack** [MinecraftPortCentral/GriefPrevention#831]
I noticed Block Breaker from Random Things working on singleplayer but not on my server.
I allowed `block-break` for everything using command:
`/cf block-break 1`
and it worked!

But I didn't want every block to break any block so I tried allowing Block Breaker from Random Things to break blocks using command:
`/cf block-break randomthings:blockbreaker 1`
and that didn't work. I also tried using:
`/cf block-break randomthings:any 1`
but that didn't work as well.

I use GP 4.3.0.662

Same thing happens for Block Breaker from OpenBlocks.

Please help ASAP as this is only issue on my server so far.

**Comment by DrZoddiak** [comment]
As Aiidoneus said, please produce a gpdebug report with the latest GP.
Knowing the Sponge and LP version you are on will also be helpful.

**Comment by BitCrack** [comment]
I use
SpongeForge - 1.12.2-2768-7.1.4
LP - 4.3.76

This is what I got from debug: https://griefprevention.github.io/debug/?jLO8aVJpHW
I can be sure this is a fakeplayer, but is there any way to stop it doing so?

**Comment by kencinder** [comment]
Update SpongeForge to 1.12.2-2768-7.1.5 and GP to latest, numerous changes since what you're running, including changes IIRC that would have your block work as the user that placed it, solving your issue.

**Comment by BitCrack** [comment]
Unfortunately I couldn't find a newer version at https://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/
I downloaded SpongeForge 1.12.2-2768-7.1.5

I rerun all commands I wrote in the description,
I also tried running, guessing from the debug:
`/cf block-break fakeplayer:rtblockbreaker 1 override`

I tried debugging again but it shows basically the same thing:
https://griefprevention.github.io/debug/?9Yx9seqxdG

**Comment by kencinder** [comment]
662 doesn't work properly on SF 7.1.5

https://ore.spongepowered.org/blood/GriefPrevention/versions/1.12.2-4.3.0.674

**Comment by BitCrack** [comment]
Ah! I see, download link in the description of this repo is a lil' outdated I guess.
I'll try the newer version and tell if anything happened.

**Comment by BitCrack** [comment]
So, I debugged again, https://griefprevention.github.io/debug/?UjtVBaDWaL and,
`fakeplayer:rtblockbreaker`
changed to:
`forge:fakeplayer.rtblockbreaker`

I tried rerunning command like so:
`/cf block-break forge:fakeplayer.rtblockbreaker 1 override`
without any effect, again.

**Comment by kencinder** [comment]
Flag should be `/cf block-break forge:fakeplayer.rtblockbreaker true` adding override only if you want it to be able to break blocks in any claim of that type.

**Comment by BitCrack** [comment]
um, I copied this exact command and nothing's happening, no errors, no output anything.
If I do it without any block (so flag should be set for all blocks) it works but not with that.

**Comment by kencinder** [comment]
Sorry been a bit, but that's specifying it as a target. As per the wiki for target "Note: If you specify a source you cannot use any and a modid MUST be specified."
I'm not sure if this is still an issue...if not you can try: `/cf block-break forge:fakeplayer.rtblockbreaker any true`
Else you have to specify a target such as `/cf block-break forge:fakeplayer.rtblockbreaker minecraft:dirt true`

**Comment by BitCrack** [comment]
Doing
`/cf block-break forge:fakeplayer.rtblockbreaker any true`
showed an error: `Too many arguments!`

`/cf block-break forge:fakeplayer.rtblockbreaker minecraft:dirt true` did the same.

**Comment by kencinder** [comment]
I have a feeling that the `.` in the name causes those issues. Along the same lines as an issue I posted https://github.com/MinecraftPortCentral/GriefPrevention/issues/800

**Comment by BitCrack** [comment]
Hm... I'll try blacklisting it in `global.conf`
It might work but I'm not sure.

**Comment by kencinder** [comment]
Bear in mind that will mean GP ignores that, and won't stop players from using it to break blocks anywhere they can place/use it.

**Comment by BitCrack** [comment]
I know that,
but on this server, I am having this issue on is skyblock so everyone and everywhere should be able to do that. Well, of course, correct me if I'm wrong and I don't understand how this blacklist works exactly.

**Comment by kencinder** [comment]
The blacklist works by not checking that block for permission, GP outright ignores it. So say User A has a claim, User B could place it at the edge of their claim and have it break blocks in that claim.

I had a quick look at what it is, it seems it only breaks 1 block in front of it...so not an issue like a quarry would be, but if it's blacklisted, GP will not check anything it does.

**Comment by BitCrack** [comment]
Huh, seems like it could just check where the block was destroyed if it was outside the allowed claim then just block it... But it's just my suggestion, I don't really know how it works internally.
Nonetheless `Too many arguments!` error seems like a bigger deal than that right now.
I can't do practically anything with that block now.

Also, just a side question, does blood read these issues? I haven't seen him reply on other issues.

**Comment by BitCrack** [comment]
Nope, putting it in `blacklist.conf` didn't fix it.
