### ISSUE TITLE
Use API to check chest access

### ISSUE THREAD

**Issue by mfnalex** [MinecraftPortCentral/GriefPrevention#832]
Is it possible to use the API to check if a player has access/can open a chest at a given location?
I could not find any information about the API except this: https://github.com/MinecraftPortCentral/GriefPrevention/wiki/API
That doesn't help me very much because I don't want to create claims.

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/claim/ClaimManager.java#L56

Once you have the claim, you can check permissions 

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/claim/Claim.java#L834

However, I see you are currently using Spigot. My spigot version is not ready yet so you should be checking the GriefPrevention classic at https://github.com/TechFortress/GriefPrevention
