### ISSUE TITLE
Building Gadgets Leaves Ghost Blocks on Undo

### ISSUE THREAD

**Issue by MstrTaffy** [MinecraftPortCentral/GriefPrevention#833]
Issue:
When using Building Gadgets on a claim, if you build and then undo the build, it leaves behind ghost blocks.

Steps to reproduce:
Set Building Gadgets to Vertical wall
Stand in any claim (that you can build in)
Place 3x3 wall
Undo
Ghost blocks are left.

GPDebug:
https://griefprevention.github.io/debug/?y8QOwmU9rt

Versions:
griefprevention-1.12.2-4.3.0.676
spongeforge-1.12.2-2768-7.1.6-RC3568
LuckPerms-Sponge-4.3.80
BuildingGadgets-2.4.6

**Comment by kencinder** [comment]
Confirmed, I could reproduce this on Building Gadgets 2.4.6 as well as 2.6.3, on latest SF/LP/GP as of writing this reply.

Using the gadget to make a wall in the wilderness, and then using the Undo key resulted in no ghost blocks.
Doing the same in a claim resulted in ghost blocks that had to be broken by hand.

**Comment by kencinder** [comment]
What I found odd though, was I went to record things so I could show it happening, and I stopped being able to reproduce it.

**Comment by kencinder** [comment]
After more testing, for some reason the tool is coming across as no user in debug sometimes, and others as my user. The mod only works in creative mode, so setting the following flag in the wilderness should work.

`/cf block-break buildinggadgets:lasergunentity true override`

**Comment by MstrTaffy** [comment]
The mod works in survival too? As long as you have the blocks on your person that you are trying to build with

**Comment by kencinder** [comment]
That flag should still be safe to use in that case anyway, as the only way for that source to be doing block-break, is by the user using the Undo key. I can't see any way it could be abused.

**Comment by MstrTaffy** [comment]
I get this when trying the suggested command
![image](https://user-images.githubusercontent.com/30232425/52700780-e0088780-2fcc-11e9-826a-daa93b78825b.png)

**Comment by bloodmc** [comment]
Update to latest SF/GP.
