### ISSUE TITLE
Problem with placing strings

### ISSUE THREAD

**Issue by Balgros** [MinecraftPortCentral/GriefPrevention#834]
I got a Problem on my Server

It's possible to place strings in claimed areas.  the Player gets a notification but the string will be placed anyway. And he wont lose his item.

Greetings.

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging

Make sure you are running latest GP build as well
https://ore.spongepowered.org/blood/GriefPrevention/versions
