### ISSUE TITLE
Wrench griefing

### ISSUE THREAD

**Issue by SSKirillSS** [MinecraftPortCentral/GriefPrevention#838]
Sorry if such an issue has already been and I did not notice.

If I try to use the AE2 or TE wrenches on AE2 cables or drive(and other machines) - they break and do not dropped. Maybe I incorrectly configured the flags. Help please understand the situation, I'm need to prevent interact with wrenches at other players regions.
Debug: https://griefprevention.github.io/debug/?PCAaqWloW0
Versions and other information have at that's link ^

**Comment by bloodmc** [comment]
Update to GP 677 and try again

**Comment by SSKirillSS** [comment]
Did not help.

![image](https://user-images.githubusercontent.com/38190325/53274998-709c4180-370a-11e9-871a-67748aa53fb3.png)

**Comment by SSKirillSS** [comment]
Now tested on a completely clean server with AE2. This problem is not observed.
Recently, for some reason, players may break the frames in regions, although the flags have not changed. 
In addition, on the other server does not always drop the wood from trees(DynamicTrees mod), although initially it worked fine.
I don’t know what to associate with, but such problems occur too often.

**Comment by SSKirillSS** [comment]
After full reset flags in world and configs it's work correctly. But how did this happen if nobody changed the flags and after the restart they remained the same?

**Comment by bloodmc** [comment]
Not sure, no recent updates have messed with flag data in LuckPerms. If you discover what caused it, update ticket.
