### ISSUE TITLE
trust keeps deleting itself

### ISSUE THREAD

**Issue by Coolrooswag** [MinecraftPortCentral/GriefPrevention#839]
The trust command keeps deleting itself?

Version:griefprevention-1.12.2-4.3.0.677

https://gyazo.com/2b61bfa945f8df30254f53032ed8e4ad

**Comment by bloodmc** [comment]
You did not specify any player or group.

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Commands#trust

**Comment by Coolrooswag** [comment]
It says the command does not exist, untrust exists but trust does not
