### ISSUE TITLE
Adding a new flag.

### ISSUE THREAD

**Issue by IBGnova** [MinecraftPortCentral/GriefPrevention#84]
Hello,
I would like to request a flag. This flag would be something like item-drop-on-death or something of the sort, it would be a flag that would allow items to drop when a player dies even if the gamerule keepInventory is on. This flag would be used for servers that want to have a peaceful world where their items don't drop, but that also want to have a pvp arena where players can fight each other for loot.

**Comment by SnowBlitzz** [comment]
there's already something like this in B11's config, though I don't think it bypasses gamerule keepInventory.

**Comment by IBGnova** [comment]
Yeah I am trying to only set item drops on death for a specific area not the full map.

**Comment by bloodmc** [comment]
This should be handled with a custom plugin using Sponge events.
