### ISSUE TITLE
Griefprevention /trust command keeps deleting itself!

### ISSUE THREAD

**Issue by Coolrooswag** [MinecraftPortCentral/GriefPrevention#840]
Alright in this GIF I will execute /trust and then /untrust, /trust will come up as does not exist and /untrust will come up as existing

https://gyazo.com/6f51ef45fcaf631ef025378ed2af697c

As you can see the /trust command comes up as not a command and /untrust comes up as a command

the only solution to this is reinstalling the JAR 

sponge version:spongeforge-1.12.2-2768-7.1.5
GP version:griefprevention-1.12.2-4.3.0.662

**Comment by bloodmc** [comment]
You are using outdated SpongeForge/GP builds. Update to GP 679 and SpongeForge 3611.
