### ISSUE TITLE
Able to bypass claim flags

### ISSUE THREAD

**Issue by Kingrc16** [MinecraftPortCentral/GriefPrevention#843]
So here are the issues: Players can place almost any block in a claim even with the flag that doesn't let them like boats and they can break lily pads with boats also they can place string and some normal blocks as well in a public mine i have. Here is a debug i ran with the string issue: https://griefprevention.github.io/debug/?utXf3B44x0

**Comment by bloodmc** [comment]
Using unsupported SF version 1.12.2-2768-7.1.5

Update to latest SF and GP 681
