### ISSUE TITLE
How to get claims to also use y axis.

### ISSUE THREAD

**Issue by Solarmender** [MinecraftPortCentral/GriefPrevention#845]
Hello. I used to play on a modded server that used grief prevention. To claim you would use claim blocks but it would also scale in the y axis. For example if you had a tower that was 150 blocks tall and 20 by 20 it would cost 60000 claim blocks to claim. Is it possible to enable a system like this? Thank you

**Comment by DrZoddiak** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Commands#cuboid

There's also a config option if you want 3d claims to be available in wilderness, which sounds more like what you're looking for.

**Comment by Solarmender** [comment]
Where is this config?

**Comment by DrZoddiak** [comment]
Location : `/config/griefprevention/worlds`

Config snippit: 
 playerdata {
        # Determines which claim block system to use for claims. (Default: AREA)
        # If set to VOLUME, claim blocks will use the chunk count system to balance 3d claiming.
        # If set to AREA, the standard 2d block count system will be used.
        
claim-block-system=AREA


You'll want to set to volume

**Comment by Solarmender** [comment]
I set it to volume to try already but then t used this weird 0.2 chunk system

**Comment by bloodmc** [comment]
This issue has been answered, if you dont like the setting then use AREA.
