### ISSUE TITLE
Thermal Expansion Crescent Hammer

### ISSUE THREAD

**Issue by Shybella** [MinecraftPortCentral/GriefPrevention#850]
After update 680/681 Thermal Expansion Crescent Hammers have a issue with permissions inside the owners claim. 

GIF of the problem: https://gyazo.com/e21adfbdae9e37a611ee7db1faf688e9

GPDebug: https://griefprevention.github.io/debug/?SxXxsb9ifZ

SF: 3616/3614
GP: 681
ThermalExpansion/COFHCORE:  CoFHCore-1.12.2-4.6.1.22-universal/ThermalExpansion-1.12.2-5.5.2.39-universal

**Comment by Shybella** [comment]
https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/item/tool/ItemHammerCore.java

**Comment by bloodmc** [comment]
Unable to reproduce on clean server.

**Comment by kencinder** [comment]
I can reproduce, I was able to take players machines with a crescent hammer exactly like in the OP.

Only difference in my setup, is SF 3616

**Comment by kencinder** [comment]
Ok the problem actually seems to be with `interact-block-secondary` being TRUE. It is FALSE by default, but I had changed it TRUE for us.
Even if `item-use` or `interact-item-secondary` are FALSE it allows the wrench to work anyway.

I also noticed if `item-spawn` is TRUE, you can duplicate machines and ducts when `interact-block-secondary` is FALSE.

**Comment by henkekalmar** [comment]
I did what @kencinder suggested, but putting `item-spawn` to `FALSE` caused other mod mechanics to break, mainly what I've been able to find was Fluix Cystal production and machines that "drop" the end result on the ground. Such as the Metal Former from Immersive Engineering

**Comment by bloodmc** [comment]
Still unable to reproduce on clean server with all interact flags set to true. Reproduce this on a CLEAN server and provide exact steps.

**Comment by kencinder** [comment]
It's not possible to reproduce this on a test server by yourself using `claimflagdebug`, the claim has to belong to another user.
I tried on a clean test server and wasn't able to reproduce anything either by using `claimflagdebug`

All the following done in a claim owned by another user, using either DEFAULT or CLAIM flags.

- Set `interact-block-secondary` TRUE, `interact-item-secondary` FALSE and `item-spawn` FALSE
Crouch+Right-Click with a crescent hammer and you can remove the machines+itemducts AND they disappear...gone without a trace.

- Set `interact-block-secondary` FALSE, `interact-item-secondary` TRUE and `item-spawn` TRUE.
Crouch+Right-Click with a crescent hammer and you can duplicate machines+ducts.

- Set `interact-block-secondary` TRUE, `interact-item-secondary` FALSE and `item-spawn` TRUE.
Crouch+Right-Click with a crescent hammer and you can remove the machines+itemducts. They however do not duplicate or disappear.

One would expect `interact-item-secondary` FALSE to disallow the wrench itself being used on anything, but it's not being stopped and resulting in the above behaviours.

SF 3616
GP 683
LP 4.3.108
