### ISSUE TITLE
bStats crash

### ISSUE THREAD

**Issue by ffantasy33** [MinecraftPortCentral/GriefPrevention#852]
hello, when i try to start my server it crashes, here is the crash report  https://pastebin.com/X3N69FKe
could you help me?

**Comment by bloodmc** [comment]
Update SF to 3616 and GP 682.

**Comment by ffantasy33** [comment]
still doing the same error  log: https://pastebin.com/5swVKaFC
crash report: https://pastebin.com/eT8TDQcQ
