### ISSUE TITLE
Vps changing

### ISSUE THREAD

**Issue by ffantasy33** [MinecraftPortCentral/GriefPrevention#853]
Hello recently I have changed the host of my vps, so I moved the files but on this vps griefprevention doesn't work, here is the log. Already tried to update SP and GP  log: https://pastebin.com/5swVKaFC
crash report: https://pastebin.com/eT8TDQcQ

**Comment by bloodmc** [comment]
`griefprevention        | 1.12.2-4.3.0.682         | griefprevention-1.12.2-4.3.0.682.jar `
Update to GP 686
