### ISSUE TITLE
Vps Changing pt.2

### ISSUE THREAD

**Issue by ffantasy33** [MinecraftPortCentral/GriefPrevention#854]
Hello recently I have changed the host of my vps, so I moved the files but on this vps griefprevention doesn't work, here is the log. Already tried to update SP and GP to 686
crash-report: https://pastebin.com/M3rjPikP

**Comment by bloodmc** [comment]
Another plugin is most likely causing the crash, remove plugins until it works. Let me know which one is the culprit.

**Comment by ffantasy33** [comment]
Hey, I don't think is the plugin because on the first vps it works, in the second it doesn't, but I will try tomorrow.

**Comment by bloodmc** [comment]
The error does not happen with GP/SF/LP on a clean server. If it happens again, another plugin did not setup metrics properly which is causing the issue.
