### ISSUE TITLE
Pixelmon Reforged UltraWorld

### ISSUE THREAD

**Issue by xion87** [MinecraftPortCentral/GriefPrevention#855]
I noticed Using Pixelmon reforget 7.0.3 GP, will launch a exception when a "ultra world" will unload
https://gist.github.com/xion87/1ab757e3ae82056fe317b5828016c5bd
Using:
griefprevention-1.12.2-4.3.0.686
spongeforge-1.12.2-2768-7.1.6-RC3616
Pixelmon reforged 7.0.3

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/claim/GPClaimManager.java#L435

Update to latest GP 687.
