### ISSUE TITLE
claimlist autocompletion issue

### ISSUE THREAD

**Issue by xion87** [MinecraftPortCentral/GriefPrevention#856]
I noticed this error when somesone trying to use /claimlist with tab with invalid values
https://gist.github.com/xion87/f6d82f61df82ffbcdab5c3257aee50d6
Using:
griefprevention-1.12.2-4.3.0.686
spongeforge-1.12.2-2768-7.1.6-RC3616

**Comment by bloodmc** [comment]
This is a sponge bug with the user command element. Report it on SpongeCommon.
