### ISSUE TITLE
Admin claim ownership

### ISSUE THREAD

**Issue by XakepSDK** [MinecraftPortCentral/GriefPrevention#857]
1. Create admin claim
2. Revoke admin rights
3. Creator can modify that claim

**Comment by bloodmc** [comment]
You need to run `/gpreload` to refresh permission cache.

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Permissions

`If you alter any admin permissions while in-game, make sure you run /gpreload as GP caches various permissions for performance gains.`

**Comment by XakepSDK** [comment]
Cache isn't rebuild even on restart?
