### ISSUE TITLE
Admin claim type change permission issue

### ISSUE THREAD

**Issue by XakepSDK** [MinecraftPortCentral/GriefPrevention#858]
1. Someone creates admin claim
2. Have `griefprevention.admin`
3. Write `/claminfo`
4. Click on `basic`
5. Can't change back to `admin`

**Comment by bloodmc** [comment]
Unable to reproduce. Test on a CLEAN server with fresh luckperms/config and provide new steps to reproduce.

**Comment by bloodmc** [comment]
Closing as there has been no response.
