### ISSUE TITLE
no action advanced option

### ISSUE THREAD

**Issue by playfrite** [MinecraftPortCentral/GriefPrevention#860]
Hi,

when I add the options via the commands, they are not taken into account. Is this normal?

I did / lp group peasant meta set griefprevention.create-claim-limit-basic 1
but when I test, I can still create multiple claims

thank you

**Comment by bloodmc** [comment]
You need to run `/gpreload` as stated in wiki.

**Comment by playfrite** [comment]
I executed the command and I even restarted the server but the options do not apply
