### ISSUE TITLE
setting minecraft:air in the blacklist does not stop it from being checked 

### ISSUE THREAD

**Issue by dezil** [MinecraftPortCentral/GriefPrevention#862]
GP Version | 1.12.2-4.3.0.687
Sponge Version | 1.12.2-2768-7.1.6-RC3616
LuckPerms Version | 4.3.17

**Comment by bloodmc** [comment]
AIR is ignored in GP by default, as other ticket states please provide exact steps on how to get AIR to show up in gpdebug result.
