### ISSUE TITLE
TNT explosion

### ISSUE THREAD

**Issue by SSKirillSS** [MinecraftPortCentral/GriefPrevention#863]
Hey. After upgrading to the latest version, Spongeforge and GP TNT started blasting blocks, although any types of explosions are disabled in the flags.

https://griefprevention.github.io/debug/?swCKZnG0Oc

![image](https://user-images.githubusercontent.com/38190325/54827519-3dc27a80-4cc3-11e9-8f32-cca8c959f615.png)
![image](https://user-images.githubusercontent.com/38190325/54827527-40bd6b00-4cc3-11e9-9c8a-af078faaa480.png)

**Comment by bloodmc** [comment]
latest SF is bugged, downgrade to 3616.
