### ISSUE TITLE
No action option

### ISSUE THREAD

**Issue by playfrite** [MinecraftPortCentral/GriefPrevention#864]
Hi,
when I add the options via the commands, they are not taken into account. Is this normal?
I did / lp group peasant meta set griefprevention.create-claim-limit-basic 1
but when I test, I can still create multiple claims
 And
 
I executed the command and I even restarted the server but the options do not apply

**Comment by bloodmc** [comment]
Provide gpdebug and lp verbose output.

**Comment by bloodmc** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/9477958766c20af9f8e1ed46401bf74778fdf229
