### ISSUE TITLE
Console spamming errors

### ISSUE THREAD

**Issue by Explosivee** [MinecraftPortCentral/GriefPrevention#866]
Minecraft Version: 1.12.2
Sponge Version: 1.12.2-2768-7.1.5
Forge Version: 14.23.5.2815
Plugin Version: 1.12.2-4.3.0.688

Issue: I made a server in my Windows10 pc to test out some plugins and after i join the server console started spaming this errors:
![image](https://user-images.githubusercontent.com/35429381/54885478-89288480-4e8d-11e9-9bf5-3d5b318a83ff.png)

If you wanna see the log file: 
[latest.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/3000833/latest.log)
(I couldn't upload it to pastebin or ftb paste cuz file is too big, sorry)

**Comment by deadman96385** [comment]
Did you figure out a fix for this? I am having the same issue
