### ISSUE TITLE
Arrows break item frames

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#87]
Reopening of #85 as it does not appear to have been fixed in the latest build (12).

**Comment by bloodmc** [comment]
@inklit how are you testing? Are you attacking a claim you own?

**Comment by inklit** [comment]
No, I'm testing by using standing in an admin claim, and then shooting an arrow at an item frame inside of a claim directly perpendicular of the claim I'm standing in.

What is the command to set projectile-impact-entity to false for all stuff?
It is missing a target value, though I'm not neccesarily sure as to what the target should be.

**Comment by bloodmc** [comment]
It should be 'any'

**Comment by inklit** [comment]
Thanks, this works.
