### ISSUE TITLE
Throwable items not stopped in claimed land

### ISSUE THREAD

**Issue by Kingrc16** [MinecraftPortCentral/GriefPrevention#871]
So I want to have items frames in my claim but players can use throwable items like snowballs and knock the items out of a item frame and the claim doesn't stop it or if they click fast enough one will still toss and make the item drop from the frame.

**Comment by bloodmc** [comment]
GP protects spawned items fine. Make sure you are using SpongeForge 3616 and GP 688. Use gpdebug to determine what flags to use.

See https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging
