### ISSUE TITLE
you cannot create a basic claim in this dimension / help

### ISSUE THREAD

**Issue by SlendyOff** [MinecraftPortCentral/GriefPrevention#874]
hello, i have a problem when a user try to claim an area. i don't know what i need to config or put please someone help me.

![2019-03-30_19 29 13](https://user-images.githubusercontent.com/49005896/55280828-fc505180-52f8-11e9-8ee2-ff97d2409361.png)

**Comment by bloodmc** [comment]
This is not a GP message. Most likely SkyClaims.
