### ISSUE TITLE
cant get api

### ISSUE THREAD

**Issue by Perzan** [MinecraftPortCentral/GriefPrevention#879]
for some reason "GriefPrevention.getApi();" isn't defined, and I'm using eclipse and I am using the plugin jar as a resource

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/API

If it is still undefined, you do not have the library attached in eclipse properly.

**Comment by Perzan** [comment]
will this work with spigot? i want to access the gp API on a spigot server

**Comment by Perzan** [comment]
im just trying to make my plugin check if a player can break a certain block... i dont know anything about gradle either :(

is there a maven dependency for gp?
