### ISSUE TITLE
Crashing upon preparing a world's spawn

### ISSUE THREAD

**Issue by N1ghthauq** [MinecraftPortCentral/GriefPrevention#882]
Using griefprevention-1.12.2-4.3.0.689 with project worlds. The issue im having with this is that when the multiple worlds start preparing their spawn gp freaks out for some reason.

[EDIT] I forgot to include a paste of console. https://pastebin.com/jCCFn7dn

**Comment by kencinder** [comment]
GP 4.3.0.679+ requires Spongeforge 1.12.2-2768-7.1.6-RC3610+

Recommended Spongeforge to use is 1.12.2-2768-7.1.6-RC3616 at this time.
