### ISSUE TITLE
Dropped items from destroyed blocks are invisible

### ISSUE THREAD

**Issue by i9hdkill** [MinecraftPortCentral/GriefPrevention#885]
Using GP 689 and SpongeForge 7.1.6-RC3671

- Create a basic claim with a user
- Break a block for example a chest or pixelmon PC
- You won't see the dropped item
- Walk over the place where the item should be
- You can pickup the invisible item

Replacing SpongeForge 3671 with 3616 "fixes" the problem.

Removing GP when SpongeForge 3671 is installed fixes the issue aswell.

That's why it's probably a GP bug

**Comment by runescapejon** [comment]
might be fix on this commit https://github.com/SpongePowered/SpongeForge/commit/de8763c585f110e50bfc537059302b00692f7c72
update sponge and check again

**Comment by i9hdkill** [comment]
3671 already includes this commit

**Comment by bloodmc** [comment]
This isn't a GP problem as all GP does is cancel the event. The bug is on Sponge side.
