### ISSUE TITLE
Furnace drop item when lit but consume one charcoal.

### ISSUE THREAD

**Issue by Kazer67** [MinecraftPortCentral/GriefPrevention#886]
Using GP 689 and SpongeVanilla 1.12.2-7.1.6-RC165

* Put a furnace on the ground
* Put some ore in it
* Put coal or charcoal

Result : items will be ejected when the furnace is lit except one coal/charcoal who's consume. If you put back ore and coal/charcoal when the furnace is already lit, everything work fine.

When I remove GP, the issue is not on the server anymore. That's why I think it's GP related.

**Comment by runescapejon** [comment]
I'm having the same issue my versions are 
GP: 1.12.2-4.3.0.689
LP: 4.4.4
SF: 1.12.2-2768-7.1.6-RC3681

**Comment by kencinder** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2725

Sponge isssue, not GP
