### ISSUE TITLE
Error while running claim command

### ISSUE THREAD

**Issue by NeoEka** [MinecraftPortCentral/GriefPrevention#887]
Sponge versions tested: 
7.15
7.16

GP version: 1.12.2-4.3.0.689

Error message from console

27.04 12:11:22 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'claim' for source EntityPlayerMP['Sakata'/21, l='world', x=-25986.45, y=145.99, z=10834.87]: null
27.04 12:11:22 [Server] INFO java.lang.NullPointerException: null
27.04 12:11:22 [Server] INFO at me.ryanhamshire.griefprevention.command.CommandClaimWorldEdit.execute(CommandClaimWorldEdit.java:78) ~[CommandClaimWorldEdit.class:1.12.2-4.3.0.689]
27.04 12:11:22 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5]
27.04 12:11:22 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5]
27.04 12:11:22 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5]
27.04 12:11:22 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
27.04 12:11:22 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
27.04 12:11:22 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
27.04 12:11:22 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
27.04 12:11:22 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
27.04 12:11:22 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
27.04 12:11:22 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
27.04 12:11:22 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
27.04 12:11:22 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
27.04 12:11:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
27.04 12:11:24 [Server] Server thread/ERROR [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.689, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/./mods/plugins/griefprevention-1.12.2-4.3.0.689.jar}
27.04 12:11:24 [Server] INFO java.lang.NoSuchFieldError: BLOCK_EVENT_PROCESS
27.04 12:11:24 [Server] INFO at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPlace(BlockEventHandler.java:765) ~[BlockEventHandler.class:1.12.2-4.3.0.689]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.listener.PlaceListener_BlockEventHandler_onBlockPlace304.handle(Unknown Source) ~[?:?]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) ~[SpongeEventManager.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) ~[SpongeImpl.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:598) ~[TrackingUtil.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:491) ~[TrackingUtil.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:446) ~[TrackingUtil.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$unwind$0(BlockTickPhaseState.java:69) ~[BlockTickPhaseState.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.context.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:72) [CapturedSupplier.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.unwind(BlockTickPhaseState.java:69) [BlockTickPhaseState.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.unwind(BlockTickPhaseState.java:46) [BlockTickPhaseState.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:268) [PhaseTracker.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:581) [PhaseContext.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:304) [TrackingUtil.class:1.12.2-2768-7.1.5]
27.04 12:11:24 [Server] INFO at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2158) [oo.class:?]
27.04 12:11:24 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) [oo.class:?]
27.04 12:11:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
27.04 12:11:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
27.04 12:11:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
27.04 12:11:24 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
27.04 12:11:24 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by kencinder** [comment]
GP 4.3.0679+ requires SpongeForge 7.1.6 RC3610+(Or SpongeVanilla 7.1.6-RC156+). As of this post, SpongeForge 7.1.6 RC3616( Or SpongeVanilla 7.1.6-RC156) is what we recommend using, and like always the latest GP version available.

**Comment by bloodmc** [comment]
Update to latest SF and GP 690
