### ISSUE TITLE
All Claims lost after Reboot server every time.

### ISSUE THREAD

**Issue by Possemaster** [MinecraftPortCentral/GriefPrevention#895]
MC Version: 1.12.2 (MODPACK Towncraft)
Forge Version: forge-1.12.2-14.23.5.2836-universal.jar
SpongeForge Version: spongeforge-1.12.2-2825-7.1.6-RC3693.jar
GriefPrevention Version: griefprevention-1.12.2-4.3.0.689.jar

The claim files are in the config folder and I can read them fine, but every reboot the land becomes unclaimed. I can reclaim the same land and the plugin creates a second file with exact the same data except the time it was created. It seems the claims are not loaded on reboot.

I also notice that after I created for example 1 Admin claim and 1 Basic claim and I run /claimlist, the TP location often has a wrong Y level set at 0 and spawns you under ground, by panning back and forth between the TABS it fixes itself but also sometimes comes back. Very unreliable.

**Comment by Possemaster** [comment]
Example Basic claims attached. One initial claim, after reboot claim was gone and recreated the same claim. After reboot also second claim was gone. This happens also with Admin claims, Town claims etc...

[files.zip](https://github.com/MinecraftPortCentral/GriefPrevention/files/3151519/files.zip)

**Comment by bloodmc** [comment]
GP 689 has not been tested on later SF builds and is known to cause issues. Wait for a new build that supports latest SF.
