### ISSUE TITLE
 fire spreads when being placed on the side of a claim

### ISSUE THREAD

**Issue by Gaabrx** [MinecraftPortCentral/GriefPrevention#899]
I am using sponge 7.1.0 and using the griffin prevention plugin, however when putting lava on the side of a claim the lava comes in and spreads fire 1.12.2-4.30.689 the plugin version

**Comment by kencinder** [comment]
GP 4.3.0.679+ requires SpongeForge 7.1.6 RC3610+(Or SpongeVanilla 7.1.6-RC156+). As of this post, SpongeForge 7.1.6 RC3616(Or SpongeVanilla 7.1.6-RC156) is what we recommend using, and like always the latest GP version available.
