### ISSUE TITLE
Greeting and farewell not showing up

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#900]
The greeting and farewell messages no longer show up when entering or leaving a claim.

griefprevention-1.12.2-4.3.0.689

![](https://i.imgur.com/dOLcFr3.jpg)

**Comment by bloodmc** [comment]
Reproduce on a clean server with SF 3616 + GP + LP and include logs.

**Comment by Sir-Will** [comment]
Seems to be no longer an issue.
