### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by M3TTA** [MinecraftPortCentral/GriefPrevention#901]
Server comes to a crawl then crashes once i start it.
Minecraft: 1.12.2
Sponge: 7.1.5
GriefPrevention: 4.3.0.689

Crash log here https://pastebin.com/s6AG6tzd

**Comment by kencinder** [comment]
GP 4.3.0.679+ requires SpongeForge 7.1.6 RC3610+(Or SpongeVanilla 7.1.6-RC156+). As of this post, SpongeForge 7.1.6 RC3616(Or SpongeVanilla 7.1.6-RC156) is what we recommend using, and like always the latest GP version available.
