### ISSUE TITLE
Compact Machines - Ghost Block issue

### ISSUE THREAD

**Issue by Yorkforce** [MinecraftPortCentral/GriefPrevention#902]
SpongeForge: 3716
Compact Machines: b267
Grief Prevention: 662

I originally thought this might be a spongeforge issue but after testing further it only seems occur inside griefprevention claim areas

Essentially a ghost block is being left behind when trying to use the compact machine projectors to create blocks.

Full details are listed here:
https://github.com/SpongePowered/SpongeForge/issues/2762

**Comment by Zerotiger** [comment]
This was annoying me too, but I managed to make it work.
The fieldprojectors has to be able to break the blocks used for the recipes.
When it's crafting a "crafting hologram" block is placed for rendering the crafting animation. This block should break after the animation is done, though.
So, you have to add both of those tot he blacklist.

block-break="compactmachines3:tileentityfieldprojector","compactmachines3:tileentitycraftinghologram"]

**Comment by kencinder** [comment]
GP 4.3.0.679+ requires SpongeForge 7.1.6 RC3610+(Or SpongeVanilla 7.1.6-RC156+). As of this post, SpongeForge 7.1.6 RC3616(Or SpongeVanilla 7.1.6-RC156) is what we recommend using, and like always the latest GP version available.

You are 27 builds behind on GP, and the version of GP you are using does not work correctly on newer Spongeforge builds.

**Comment by Yorkforce** [comment]
@kencinder Apologies, seems i had an old http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/ link bookmarked, i'll try version 689
