### ISSUE TITLE
[Request] Chest Auto-claim limit

### ISSUE THREAD

**Issue by anxic** [MinecraftPortCentral/GriefPrevention#905]
Hi,

Thank you for this plugin which is very useful. I would like to suggest a permission concerning the chest auto claim.

Currently with this method is only one claim per user, it would be great if we can put a limit of claim per user group. (That's why it's better to use permissions instead of options on the config file)

What I like with the auto-claim it's the possibility to define exactly the zone radius. 

Other remarks, currently when we try to claim when we exceed the limit, can we put back automatically the chest on the inventory ? 

Thank you

Kind regards,

**Comment by bloodmc** [comment]
See https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Advanced-Options

**Comment by kencinder** [comment]
The options do only cover expiration and taxes. They're asking if auto-claims could have an option for more than one.
