### ISSUE TITLE
Sweet berry bushes stealing on claims

### ISSUE THREAD

**Issue by LoneDev6** [MinecraftPortCentral/GriefPrevention#906]
If you have sweet berry bushes in your claim other people can steal your berry rightclicking on the plant, idk if it's fixable since I didn't find any event regarding this behaviour on spigot docs

**Comment by LoneDev6** [comment]
This could work I think
![image](https://user-images.githubusercontent.com/27242001/59501715-6ad69180-8e9c-11e9-8ee7-6ea05f9e86fc.png)

**Comment by kencinder** [comment]
This repository is for Sponge GP, not Spigot.

**Comment by bloodmc** [comment]
Please report to https://github.com/TechFortress/GriefPrevention/issues

**Comment by LoneDev6** [comment]
Thanks, done https://github.com/TechFortress/GriefPrevention/issues/556
