### ISSUE TITLE
[IMPORTANT] A huge mistake in the claim system

### ISSUE THREAD

**Issue by Beshelmek** [MinecraftPortCentral/GriefPrevention#908]
I run GriefPrevention 1.12.2 **4.3.0.689** on Sponge . 
I can create claims in other player's claims that do not belong to me. Even in the admin.
Just select a region with **WE** (//pos1, //pos2, etc..) in someone else's claim and use /claim command. **And my private BASIC created inside another**! I can break block and other actions.

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-672794fe
    Sponge: 1.12.2-7.1.6-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.6-RC3616
    Minecraft Forge: 14.23.5.2838 

P.S - Sorry for my bad English :(

**Comment by noremac09** [comment]
Can reproduce.

```
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-672794fe
    Sponge: 1.12.2-7.1.6-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.6-RC3616
    Minecraft Forge: 14.23.5.2809
```
