### ISSUE TITLE
Right clicking on non-hostile mobs inside claims returns "null"

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#91]
In chat, it shows a red "null" when you right click on non-hostile mobs inside of claims.
This only happens if you are trusted in the claim, and you are not the owner of the claim.

No errors in the console.

**Comment by bloodmc** [comment]
I'm not able to reproduce this issue with B20. Please state the EXACT entity you are trying to interact with as well as the type of trust you gave to other player.

**Comment by inklit** [comment]
Sheep and cows, interacting with a block in the hand.
Full trust.

**Comment by inklit** [comment]
Leaded cows that were spawned naturally, and then lead into a claim, when attempting to interact with them holding wheat this happens as described above.
![cows](https://cloud.githubusercontent.com/assets/9058200/16728354/d5315104-4733-11e6-99dd-e34502bad204.png)
