### ISSUE TITLE
Console spam whenever players are online

### ISSUE THREAD

**Issue by KidBrine** [MinecraftPortCentral/GriefPrevention#911]
Basically, the console keeps getting spammed whenever a player is online.
using the latest sponge and GriefPrevention
[loggos.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/3316085/loggos.log)
before you mark this as a clone, none of the other solutions I have seen have worked!

**Comment by yepidoodles** [comment]
I'm having this issue too once I updated to a latest version of Sponge, I'm backporting version by version at the moment. 

"before you mark this as a clone, none of the other solutions I have seen have worked!"

What were you referring to here? I couldn't find any other issues on this.

**Comment by bloodmc** [comment]
689 does NOT support latest SF builds. Try the following

https://www.dropbox.com/s/lihpedotgn3p8wm/griefprevention-1.12.2-4.3.0.0.jar

or build latest master.

**Comment by LemADEC** [comment]
> 689 does NOT support latest SF builds. Try the following
> 
> https://www.dropbox.com/s/lihpedotgn3p8wm/griefprevention-1.12.2-4.3.0.0.jar
> 
> or build latest master.

that version is spamming console with `java.lang.NoSuchMethodError: org.spongepowered.common.bridge.world.DimensionTypeBridge.getModId()Ljava/lang/String;`
on mods/spongeforge-1.12.2-2838-7.1.7-RC3830.
