### ISSUE TITLE
/dc alias not working

### ISSUE THREAD

**Issue by Ewallee** [MinecraftPortCentral/GriefPrevention#912]
alias does not working: /dc "unknown command"
griefprevention 1.12.2-4.3.0.689
spongeforge 1.12.2-2825-7.1.6
LuckPerms-Sponge-4.3.75
forge-1.12.2-14.23.5.2823

**Comment by kencinder** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/commit/cfc6ad421002c658908c58d202187502dc75b859
