### ISSUE TITLE
Could not pass the event SpawnEntityEvent$ChunkLoad$Impl to an Event Listener! 

### ISSUE THREAD

**Issue by Wissi** [MinecraftPortCentral/GriefPrevention#913]
We love your plugin it's awesome and we use it a lot, but we found this bug and it's spamming too much and causing lag on server.
Console spam on server.  Full server log [here](https://gist.github.com/Wissi/3452a1bd9d62fe646b9d37967dae2481)
```
[14:39:19] [Server thread/WARN] [Sponge]: /* Since the event can be modified during the event's listener,
 there could be adverse side effects of the exception occuring
such that duplications or other game breaking issues could exist.
Due to the nature of the exception, this is not likely an exception
that is covered by SpongeForge or Forge itself, and therefor should
be reported to the mod/plugin author first prior to reporting to
Sponge or Forge. */
[14:39:19] [Server thread/WARN] [Sponge]: /* Owning Mod/Plugin: griefprevention
```
Sponge: spongeforge-1.12.2-2838-7.1.7-RC3807.jar and spongeforge-1.12.2-2825-7.1.6-RC3713.jar
Griefprevention: griefprevention-1.12.2-4.3.0.662.jar and griefprevention-1.12.2-4.3.0.689.jar

Thanks for all your hard work.

**Comment by bloodmc** [comment]
689 does NOT support latest SF builds. Try the following

https://www.dropbox.com/s/lihpedotgn3p8wm/griefprevention-1.12.2-4.3.0.0.jar

or build latest master.

**Comment by tenten8401** [comment]
Latest master doesn't seem to make a difference for me, having this exact issue as well.
