### ISSUE TITLE
Events Console Spam on spongeforge 2838 (GP: 4.3.0.690)

### ISSUE THREAD

**Issue by Skyine918** [MinecraftPortCentral/GriefPrevention#921]
There is a problem on newest SF and GP
- Forge: forge-1.12.2-14.23.5.2838
- SpongeForge: spongeforge-1.12.2-2838-7.1.7-RC3836
- Griefprevention: 1.12.2-4.3.0.690
Mods/Plugins:
- Advent Of Ascension 3.1.1
- CatClearLag-0.9.0
- LuckPerms-Sponge-4.4.26
- Nucleus-1.12.1-S7.1-MC1.12.2-plugin
- TotalEconomy-1.7.1-API_7
Server starts successfully, but when player do something, there is a console spam. Also, when player pick up an item, server disconnects him (there is an example in latest.log)
[latest.log](https://github.com/MinecraftPortCentral/GriefPrevention/files/3351198/latest.log)

**Comment by TheRealDadbeard** [comment]
Same for me

**Comment by Salty-Cheese** [comment]
I'm having this same CollideBlockEvent$Impl spam whenever a player does anything.

**Comment by Skyine918** [comment]
Everything is ok when I use SpongeForge RC3832: [1.12.2-2838-7.1.7-RC3832](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2). Most likely because changes in something called 'bridges' in next versions of SF

**Comment by LemADEC** [comment]
I could use the PlayerInventory fix from Sponge RC3838 for a new modpack coming up next week.

**Comment by LemADEC** [comment]
For those interested, the fix is already in the repository, you just need to compile it locally:

![image](https://user-images.githubusercontent.com/4776032/60757155-3c655580-a007-11e9-8fe8-ca0572b587a8.png)

**Comment by bloodmc** [comment]
Use GP 692
