### ISSUE TITLE
Error occurred while executing command /adminclaims

### ISSUE THREAD

**Issue by ColonelCheru** [MinecraftPortCentral/GriefPrevention#922]
Hello, I just installed GriefPrevention on my server. I run it with spongeforge-1.12.2-2768 and LuckPerms. (unsure if these are worth noting). I added all the permissions to the admin permission role, with the other "default" ones to the default permission.
I just ran the command /adminclaims and I get the error message shown in the image.
"Error occurred while executing command: org/spongepowered/common/bridge/world/DimensionTypeBridge"
![image](https://user-images.githubusercontent.com/52555992/60696781-38292300-9eb5-11e9-8ea1-cd03f6bf3bf7.png)

I have absolutely no idea what to do.
What do I do to fix this? Thanks!

**Comment by runescapejon** [comment]
Update sponge
