### ISSUE TITLE
[Feature Request] ClaimBalanceUpdateEvent

### ISSUE THREAD

**Issue by alexstaeding** [MinecraftPortCentral/GriefPrevention#923]
We have a modded server network running Velocity that has each world on a different server (spawn, nether, wild, etc..). Players gain claim blocks through voting and on an hourly basis. We're trying to set it up so that the players experience it as a single server while maintaining the advantage of multithreading by having each world on a different server.

After a short conversation with your discord mods it's clear you can't/won't be adding database support in this version due to the release of GD.

However, a `ClaimBalanceUpdateEvent` would really help us write our own plugin to support the claiming system in a multi-server environment.

Thank you for your time

**Comment by bloodmc** [comment]
No new features will be added to GP Sponge as GriefDefender will be taking over. If you have an API request, create a ticket here
https://github.com/bloodmc/GriefDefenderAPI
