### ISSUE TITLE
[1.10 branch] Infinite fire spread.

### ISSUE THREAD

**Issue by cartman-2000** [MinecraftPortCentral/GriefPrevention#93]
The plugin doesn't block fire from spreading, and the fire that does spread doesn't decay at all, so if something in forest catches fire, the whole forest can potentially burn.

This fire was started by a thunderstorm on the server.  The wilderness flags for fire-spread are false here.
https://www.dropbox.com/s/9wzag06vlz4et29/Screenshot%202016-07-05%2017.30.27.png?dl=0

 [19:17:10] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-05d0adc
    SpongeForge: 1.10.2-2002-5.0.0-BETA-1539
    Minecraft Forge: 12.18.0.2005

**Comment by cartman-2000** [comment]
The past few updates to sponge and this mod have fixed the infinite spread of the fire, but it would appear that the flag for fire spread is still being ignored when it's set to false on the wilderness claim.

**Comment by GOKUSSL4** [comment]
the same is occuring in the 1.8.9 build as well.

**Comment by bloodmc** [comment]
This no longer happens with latest 1.10.2 builds.
