### ISSUE TITLE
Could not pass the SpawnEntityEvent$ChunkLoad$Impl to Event Listener

### ISSUE THREAD

**Issue by HackuJacku** [MinecraftPortCentral/GriefPrevention#953]
Hello.

After updating Forge, SpongeForge, Nucleus, LuckPerms and GP to the recommended versions by the Pixelmon Reforged team, I was unable to start my server up. My console kept spamming this error.

**Error:** https://pastebin.com/raw/r1yeAyMX

**Versions:**
Forge: 2838
SpongeForge: 3825
GriefPrevention: 692 
LuckPerms: 4.4.29
Nucleus: 1.13.2

**Comment by Rasgnarok** [comment]
Bumping down to 689 for now will do, until blood releases GriefDefender. GP will not be updatded anymore, and GD will have special versions that target safe builds of SF.

**Comment by i9hdkill** [comment]
Not a bug. You are using the wrong GP version. Use GP 689. This is also listed on the download page.
