### ISSUE TITLE
No cactus damage

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#96]
There is no cactus damage in claims you are not trusted in, as well as the wilderness.

**Comment by cartman-2000** [comment]
This is somewhat buggy for me, sometimes it can take 2-3 seconds of touching one before it starts to damage you, and other times there's no issue with it damaging you.

**Comment by bloodmc** [comment]
Simply add an override for 'collide-block minecraft:cactus' and set to true to force collisions on it.
