### ISSUE TITLE
Sponge Forge 3844. LuckPerms Latest. GP latest. Gp commands not going through.

### ISSUE THREAD

**Issue by TheParsley** [MinecraftPortCentral/GriefPrevention#964]
I have Sponge forge 3844 because the server will not start with anything else. I try GP commands but they just say unknown commands. My console gets spammed with this when I use Build 689: https://prnt.sc/pvhqbw

**Comment by kencinder** [comment]
1: Unknown command = No permission. This was changed in more recent Sponge builds. Update to SF 7.1.7 recommended build.

2: GP 689 won't work on that build or newer, use 692.
