### ISSUE TITLE
odd liquid behavior 

### ISSUE THREAD

**Issue by FiveEYZ** [MinecraftPortCentral/GriefPrevention#99]
~~for some reason players in survival mode are unable to use water/lava bucket in wilderness or~~ ~~claim~~
~~in creative however place can~~
this also happen whitout gp

griefprevention-1.10.2-1.0-0
spongeforge-1.10.2-2002-5.0.0-BETA-1550

removing the source block makes the liquid behave funky
![liquids](http://i.imgur.com/oHcYWOC.png)
relogging or restart the server wont help

also tested on a 1.10.2 server with only 
gp, sponge and pex installed

**Comment by inklit** [comment]
I have this same issue, about the source block behaving funky.
My players are able to place liquids in survival with no problem, though.

**Comment by bloodmc** [comment]
This is a sponge bug, nothing to do with GP.

**Comment by FiveEYZ** [comment]
i dont understand, then how can it only happen with only GP installed?

**Comment by bloodmc** [comment]
@FiveEYZ You need to test in 1.8.9 SpongeForge as 1.10.2 sponge is still in bleeding and is VERY buggy still.

**Comment by FiveEYZ** [comment]
alright thanks, will test it

**Comment by bloodmc** [comment]
@FiveEYZ did it work correctly in 1.8.9?

**Comment by FiveEYZ** [comment]
yes sorry, everything works flawlessly on 1.8.9 :/ 
I just have to wait until sponge gets more stable and hopefully it will be fixed along the way :)

**Comment by bloodmc** [comment]
@FiveEYZ 
Create a ticket for 1.10 here
https://github.com/SpongePowered/SpongeCommon/issues

Make sure to explain how it works in 1.8.9 and what breaks in 1.10
